### ISSUE TITLE
Fail to add integration

### ISSUE THREAD

**Issue by KoekieWaus** [hacs/integration#1004]
Hey if got a problem,

I'm using Hacs 0.23.2, 
HassOS 0.106.6 original img from website

System: HassOS 3.12 (amd64 / qemux86-64)
Home Assistant Core: 0.106.6
Home Assistant Supervisor: 209

<details>
<summary>server info</summary>

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Amsterdam
version | 0.106.6
virtualenv | false

</details>

on a virtual machine on a qnap nas, 

 i followed the entire tutorial how to install, i see it in integrations -> add -> HACS, when i click it its loading and jumps back to add integrations., i cant find any thing in the issue page what helps me

in the log is only find this:
## Debug log

<details>
  <summary>Logs</summary>

```2020-03-13 12:51:39 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 62, in post
    handler, context={"source": config_entries.SOURCE_USER}
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 100, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 500, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 290, in async_process_deps_reqs
    hass, integration.domain
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 55, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 44, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3138, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

</details>

**Comment by xboxtreme** [comment]
It happens to me exactly the same

**Comment by ludeeus** [comment]
Update to HA 107, and try again.
HACS can not install it's own dependencies, it is HA that does that.

**Comment by KoekieWaus** [comment]
> Update to HA 107, and try again.
> HACS can not install it's own dependencies, it is HA that does that.

Totaly for got to say that this can be closed...

What the error is i dont know..

But when 0.107 came out and i did the update hacs installed right away.

So this can be closed
