### ISSUE TITLE
HACS doesn't check integrations before removal

### ISSUE THREAD

**Issue by andriej** [hacs/integration#1031]
## Version of HACS

Integration wersja: | 0.23.2
-- | --
Frontend wersja: | 20200309184730
Repozytoria: | 518

## Describe the bug

HACS doesn't chack if integration I want to remove is used by HA or not.
Found it on example: fontawesome integration.

Steps to reproduce (every time):

1. Install (in HACS) "fontawesome" integration.
2. Restart HA
3. Add (in HA) Integrations -> fontawesome
4. Restart HA (or not, doesn't matter)
5. In HACS remove "fontawesome" integration, HACS doesn't prompt (maybe it should) that integration is still active
6. Restart HA
7. After restart, HA prints error in log:
![image](https://user-images.githubusercontent.com/6303489/78016682-6c017e00-734b-11ea-90e4-dc66dc2bfac0.png)

if you go to HA -> Integrations, you will see:
![image](https://user-images.githubusercontent.com/6303489/78016723-7d4a8a80-734b-11ea-8e18-5d59c77de140.png)
which is integration without any devices and cannot be removed by HA UI/configflow.
Even after 'delete' prompt, nothing happens.

to revert, I had to reinstall fontawesome, restart and then were able to remove integration.

Smaller issue: after installing fontawesome it doesn't say what config flow has succeded adding:
![image](https://user-images.githubusercontent.com/6303489/78016552-41afc080-734b-11ea-9ca3-5bf2e17fd1e3.png)

## Debug log

<details>
  <summary>Logs</summary>

```text
Szczegóły loga (ERROR)
Logger: aiohttp.server
Source: loader.py:341
First occurred: 12:31:14 (1 occurrences)
Last logged: 12:31:14

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 106, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_remove
    unload_success = await self.async_unload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 704, in async_unload
    return await entry.async_unload(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 270, in async_unload
    integration = await loader.async_get_integration(hass, self.domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 341, in async_get_integration
    raise IntegrationNotFound(domain)
homeassistant.loader.IntegrationNotFound: Integration 'fontawesome' not found.
```

</details>

**Comment by ludeeus** [comment]
This is not a bug, this is by design.
HACS does not know if you are using an integration or not.

**Comment by andriej** [comment]
Why wouldn't it check then? It has an access to config flow...

**Comment by andriej** [comment]
@ludeeus or at least for the ones that use config flow it could check, right?

**Comment by ludeeus** [comment]
No it can not, I tried to implement but in the past, but the info is not there for HACS to use.
