### ISSUE TITLE
Can not install dependencies (TypeError: expected string or bytes-like object)

### ISSUE THREAD

**Issue by SebastianPietschner** [hacs/integration#1059]
## Version of HACS

0.32.2

## Describe the bug
HACS appears in integrations menu but when clicked menu refreshes and scroll progress is cleared.

## Debug log

<details>
  <summary>Logs</summary>

```text
2020-04-12 09:53:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 62, in post
    handler, context={"source": config_entries.SOURCE_USER}
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 100, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 501, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 291, in async_process_deps_reqs
    hass, integration.domain
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 55, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 44, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3145, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

</details>

**Comment by ludeeus** [comment]
Try _any_ other custom component

**Comment by SebastianPietschner** [comment]
Other integration custom components work fine and I'm able to launch their configuration menu flow.

**Comment by ludeeus** [comment]
Which one is working?
The error is network/premission (not related to HACS)

**Comment by SebastianPietschner** [comment]
I've just removed the `base_url` line from my config. I am still unable to launch the flow locally or remotely.

**Comment by SebastianPietschner** [comment]
The integration I tried was the Samsung Smart integration

**Comment by ludeeus** [comment]
It does not have any dependencies, that's why it worked <https://github.com/ollo69/ha-samsungtv-smart/blob/master/custom_components/samsungtv_smart/manifest.json#L9>

Your HA installation can not install dependencies needed by HACS.
There is not a single line of code I can change in HACS to make it work since this is done _before_ HACS is started.

**Comment by SebastianPietschner** [comment]
How would I get HACS to install the dependencies? My network connection is not at fault and I've tried reinstalling the HACS custom_component.

**Comment by ludeeus** [comment]
> How would I get HACS to install the dependencies?

You can't, since HACS does not install those, Home Assistant does.
If you run docker, do not use a different user/group for the container.
if you have a deps dir in your config dir, delete it.
Other than that I have no more tips for you.
