### ISSUE TITLE
Missing HACS Community Sore in Left Panel

### ISSUE THREAD

**Issue by cap10tim** [hacs/integration#1070]
This is my first time ever submitting an issue. 

After discovering I could no longer access the store, I tried to check the integrations page. It seemed okay, but the entities page shows a problem.

I checked the log and it said there was an issue... But didn't copy before restarting. HACS still wouldn't load. Downloaded new hacs.zip and copied everything over customcomponents/hacs. (Suspecting corruption.)

Getting an exception issue in the log.

-->

## Version of HACS

Home Assistant 0.108.6

Unsure of version, since I cannot access HACS at all. 

## Describe the bug
I do not see HACS starting, and is wholly unavailable.

## Debug log

Config entry for roku not ready yet. Retrying in 20 seconds.
4:31:23 PM – config_entries.py (WARNING) - message first occurred at 4:19:02 PM and shows up 24 times
http://192.168.10.254:8123/config/areas/dashboard:0:0 ResizeObserver loop limit exceeded
4:31:19 PM – components/system_log/__init__.py (ERROR)
Updating skybell binary_sensor took longer than the scheduled update interval 0:00:05
4:19:28 PM – Binary sensor (WARNING)
Setup of sensor platform alexa_media is taking over 10 seconds.
4:19:20 PM – Sensor (WARNING)
Setup of switch platform alexa_media is taking over 10 seconds.
4:19:20 PM – Switch (WARNING)
Error setting up integration hacs - received exception
4:19:14 PM – util/package.py (ERROR)
Failed to initialize notification service webostv
4:19:05 PM – Notify (ERROR)
You are using a custom integration for weatheralerts which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
4:18:54 PM – loader.py (WARNING)

-----------------

Logger: homeassistant.bootstrap
Source: util/package.py:44
First occurred: 4:19:14 PM (1 occurrences)
Last logged: 4:19:14 PM

Error setting up integration hacs - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 50, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 129, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 291, in async_process_deps_reqs
    hass, integration.domain
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 55, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 44, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3145, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

</details>

**Comment by lbouriez** [comment]
I had a similar issue today, HACS was not working anymore
```
Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:104
First occurred: 11:35:05 PM (2 occurrences)
Last logged: 11:35:05 PM

Setup failed for hacs: Integration not found.
Setup failed for alexa_media: Integration not found.
```
The reason was that the hacs folder in the custom_components was totally empty... probably due to a fail update :/
I just had to re-download it.
