### ISSUE TITLE
Error doing job: Task was destroyed but it is pending!

### ISSUE THREAD

**Issue by CyanoFresh** [hacs/integration#1096]
## Version of HACS

cannot open ui

## Describe the bug
HA stopped responding while process is active.
I was redirected from https://github.com/home-assistant/core/issues/34738 so more information and logs there.
Looks like error was not handled properly

## Debug log

<details>
  <summary>Logs</summary>

homeassistant_daemon.log:
```txt
[32m2020-04-21 19:10:33 INFO (MainThread) [hacs] Loading known repositories[0m
[31m2020-04-21 19:10:33 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved[0m
Traceback (most recent call last):
  File "/home/hass/homeassistant/custom_components/hacs/helpers/information.py", line 40, in get_repository
    repository = await github.get_repo(repository_full_name)
  File "/srv/homeassistant/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 51, in get_repo
    await self.get_ratelimit()
  File "/srv/homeassistant/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 148, in get_ratelimit
    raise AIOGitHubException(f"GitHub returned {response.status} for {url}")
aiogithubapi.exceptions.AIOGitHubException: GitHub returned 502 for https://api.github.com/rate_limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hass/homeassistant/custom_components/hacs/hacsbase/__init__.py", line 319, in recuring_tasks_all
    await self.load_known_repositories()
  File "/home/hass/homeassistant/custom_components/hacs/hacsbase/__init__.py", line 366, in load_known_repositories
    repositories = await self.get_repositories()
  File "/home/hass/homeassistant/custom_components/hacs/hacsbase/__init__.py", line 351, in get_repositories
    self.session, self.configuration.token, category
  File "/home/hass/homeassistant/custom_components/hacs/helpers/get_defaults.py", line 37, in get_default_repos_lists
    repo = await get_repository(session, token, "hacs/default")
  File "/home/hass/homeassistant/custom_components/hacs/helpers/information.py", line 43, in get_repository
    raise HacsException(exception)
custom_components.hacs.hacsbase.exceptions.HacsException: GitHub returned 502 for https://api.github.com/rate_limit[0m
[32m2020-04-21 19:11:25 INFO (MainThread) [homeassistant.components.esphome] Can't connect to ESPHome API for 192.168.1.120: Timeout while connecting to ('192.168.1.120', 6053)[0m
[32m2020-04-21 19:11:25 INFO (MainThread) [homeassistant.components.esphome] Trying to reconnect in 60 seconds[0m
[32m2020-04-21 19:11:29 INFO (MainThread) [aioesphomeapi.connection] 192.168.1.123: Unexpected error while reading incoming messages: [0m
[32m2020-04-21 19:11:29 INFO (MainThread) [homeassistant.components.esphome] Disconnected from ESPHome API for 192.168.1.123[0m
[32m2020-04-21 19:11:29 INFO (MainThread) [aioesphomeapi.connection] 192.168.1.122: Unexpected error while reading incoming messages: [0m
[32m2020-04-21 19:11:29 INFO (MainThread) [homeassistant.components.esphome] Disconnected from ESPHome API for 192.168.1.122[0m
[32m2020-04-21 19:11:29 INFO (MainThread) [aioesphomeapi.connection] 192.168.1.121: Unexpected error while reading incoming messages: [0m
[32m2020-04-21 19:11:29 INFO (MainThread) [homeassistant.components.esphome] Disconnected from ESPHome API for 192.168.1.121[0m
[32m2020-04-21 19:11:29 INFO (MainThread) [homeassistant.components.esphome] Successfully connected to 192.168.1.121[0m
[32m2020-04-21 19:11:29 INFO (MainThread) [homeassistant.components.esphome] Successfully connected to 192.168.1.123[0m
[32m2020-04-21 19:11:29 INFO (MainThread) [homeassistant.components.esphome] Successfully connected to 192.168.1.122[0m
Traceback (most recent call last):
  File "/srv/homeassistant/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/__main__.py", line 342, in main
    exit_code = asyncio.run(setup_and_run_hass(config_dir, args))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 538, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1782, in _run_once
    handle._run()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/hass/homeassistant/custom_components/hacs/hacsbase/__init__.py", line 273, in prosess_queue
    can_update = await get_fetch_updates_for(self.github)
  File "/home/hass/homeassistant/custom_components/hacs/helpers/remaining_github_calls.py", line 19, in get_fetch_updates_for
    limit = await remaining(github)
  File "/home/hass/homeassistant/custom_components/hacs/helpers/remaining_github_calls.py", line 8, in remaining
    ratelimits = await github.get_ratelimit()
  File "/srv/homeassistant/lib/python3.7/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiogithubapi/aiogithub.py", line 148, in get_ratelimit
    raise AIOGitHubException(f"GitHub returned {response.status} for {url}")
aiogithubapi.exceptions.AIOGitHubException: GitHub returned 500 for https://api.github.com/rate_limit
[31m2020-04-21 19:11:57 ERROR (updater) [homeassistant.core] Error doing job: Task was destroyed but it is pending![0m
[31m2020-04-21 19:11:57 ERROR (updater) [homeassistant.core] Error doing job: Task was destroyed but it is pending![0m
[31m2020-04-21 19:11:57 ERROR (updater) [homeassistant.core] Error doing job: Task was destroyed but it is pending![0m
```
home-assistant.log:
```
2020-04-21 19:11:57 ERROR (updater) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2020-04-21 19:11:57 ERROR (updater) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
2020-04-21 19:11:57 ERROR (updater) [homeassistant.core] Error doing job: Task was destroyed but it is pending!
```

</details>

**Comment by ludeeus** [comment]
This was fixed with 0.24.2
