### ISSUE TITLE
HACS not showing up in UI

### ISSUE THREAD

**Issue by kiwipaulrob** [hacs/integration#1121]
HACS running in latest version of HA on a RP Rasparian.

Cant see the version etc as not showing up in UI.

Here is the log.

Logger: homeassistant.bootstrap
Source: util/package.py:44
First occurred: 9:33:59 AM (1 occurrences)
Last logged: 9:33:59 AM

Error setting up integration hacs - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 50, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 129, in _async_setup_component
    await async_process_deps_reqs(hass, config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 294, in async_process_deps_reqs
    hass, integration.domain
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 78, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 124, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 44, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3145, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
Connection lost. Reconnecting…

**Comment by kiwipaulrob** [comment]
Thanks for your prompt response (and all your hard work) . I will investigate

**Comment by kiwipaulrob** [comment]
Deleting the `dep`s directory from the `config `directory fixed the problem.
