### ISSUE TITLE
TypeError: 'AIOGithubRepositoryContent' object is not iterable

### ISSUE THREAD

**Issue by konikvranik** [hacs/integration#1130]
## Version of HACS
0.21.6

## Describe the bug
On HACS page in Home Assistant there is never ending progressbar.
Install buttons are disabled saying that there is a background process.

## Debug log

```text
2020-05-08 13:34:08 INFO (MainThread) [hacs.repository.integration.atymic.project_three_zero_ha] Registration complete
2020-05-08 13:34:10 DEBUG (MainThread) [hacs.repository.appdaemon.UbhiTS.ad-autointernetrebooter] Checking repository.
2020-05-08 13:34:10 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/__init__.py", line 197, in startup_tasks
    await self.load_known_repositories()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/__init__.py", line 386, in load_known_repositories
    await self.factory.execute()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/task_factory.py", line 30, in execute
    await asyncio.gather(*self.tasks)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/task_factory.py", line 66, in safe_register
    await hacs.register_repository(repo, category)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/__init__.py", line 157, in register_repository
    await repository.registration()
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/appdaemon.py", line 60, in registration
    if not await self.validate_repository():
  File "/home/homeassistant/.homeassistant/custom_components/hacs/repositories/appdaemon.py", line 48, in validate_repository
    for filename in self.content.objects:
TypeError: 'AIOGithubRepositoryContent' object is not iterable
2020-05-08 13:34:11 INFO (MainThread) [hacs.repository.plugin.Sian-Lee-SA.honeycomb-menu] Registration complete
2020-05-08 13:34:11 INFO (MainThread) [hacs.repository.plugin.fineemb.lovelace-cn-map-card] Registration complete
2020-05-08 13:34:11 INFO (MainThread) [hacs.repository.appdaemon.Mohlsson.ReplayLightsHistory] Registration complete
2020-05-08 13:34:11 INFO (MainThread) [hacs.repository.plugin.Voxxie.lovelace-jumbo-card] Registration complete
2020-05-08 13:34:13 DEBUG (MainThread) [hacs] 4885
2020-05-08 13:34:13 DEBUG (MainThread) [hacs] 2020-05-08 12:32:41
2020-05-08 13:34:13 ERROR (MainThread) [hacs] Validation for custom-components/sensor.wifi-scanner failed with GitHub returned 404 for https://api.github.com/repos/custom-components/sensor.wifi-scanner/contents/cu
2020-05-08 13:34:17 INFO (MainThread) [hacs.repository.integration.rkoebrugge.hacs-youless-component] Registration complete
2020-05-08 13:34:18 INFO (MainThread) [hacs.repository.integration.Bouni.drkblutspende] Registration complete
2020-05-08 13:34:19 INFO (MainThread) [hacs.repository.integration.r-renato.ha-climacell-weather] Registration complete
2020-05-08 13:34:19 INFO (MainThread) [hacs.repository.integration.robbinjanssen.home-assistant-omnik-inverter] Registration complete
2020-05-08 13:34:19 INFO (MainThread) [hacs.repository.integration.peternijssen.home-assistant-jumbo] Registration complete
```
```
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving button-card/button-card.js from /home/homeassistant/.homeassistant/www/community/button-card/button-card.js.gz
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving lovelace-thermostat-card/main.js from /home/homeassistant/.homeassistant/www/community/lovelace-thermostat-card/main.js.gz
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving ha-card-waze-travel-time/ha-card-waze-travel-time.js from /home/homeassistant/.homeassistant/www/community/ha-card-waze-travel-time/ha-card-waze-travel-time.js
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving button-entity-row/button-entity-row.js from /home/homeassistant/.homeassistant/www/community/button-entity-row/button-entity-row.js.gz
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving lovelace-light-with-profiles/light-with-profiles.js from /home/homeassistant/.homeassistant/www/community/lovelace-light-with-profiles/light-with-profiles.js.g
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving lovelace-multiple-entity-row/multiple-entity-row.js from /home/homeassistant/.homeassistant/www/community/lovelace-multiple-entity-row/multiple-entity-row.js.g
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving radial-menu/radial-menu.js from /home/homeassistant/.homeassistant/www/community/radial-menu/radial-menu.js.gz
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving secondaryinfo-entity-row/secondaryinfo-entity-row.js from /home/homeassistant/.homeassistant/www/community/secondaryinfo-entity-row/secondaryinfo-entity-row.js
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving spotify-card/spotify-card.js from /home/homeassistant/.homeassistant/www/community/spotify-card/spotify-card.js.gz
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving lovelace-card-mod/card-mod.js from /home/homeassistant/.homeassistant/www/community/lovelace-card-mod/card-mod.js.gz
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving lovelace-auto-entities/auto-entities.js from /home/homeassistant/.homeassistant/www/community/lovelace-auto-entities/auto-entities.js.gz
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving weather-card/weather-card.js from /home/homeassistant/.homeassistant/www/community/weather-card/weather-card.js.gz
2020-05-08 13:35:25 DEBUG (MainThread) [hacs] Serving lovelace-more-info-card/more-info-card.js from /home/homeassistant/.homeassistant/www/community/lovelace-more-info-card/more-info-card.js.gz
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving lovelace-layout-card/layout-card.js from /home/homeassistant/.homeassistant/www/community/lovelace-layout-card/layout-card.js.gz
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving lovelace-template-entity-row/template-entity-row.js from /home/homeassistant/.homeassistant/www/community/lovelace-template-entity-row/template-entity-row.js.g
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving lovelace-thermostat-card/styles.js from /home/homeassistant/.homeassistant/www/community/lovelace-thermostat-card/styles.js.gz
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving lovelace-thermostat-card/thermostat_card.lib.js from /home/homeassistant/.homeassistant/www/community/lovelace-thermostat-card/thermostat_card.lib.js.gz
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving air-visual-card/air-visual-card.js from /home/homeassistant/.homeassistant/www/community/air-visual-card/air-visual-card.js.gz
2020-05-08 13:35:26 DEBUG (SyncWorker_3) [custom_components.logbook_cache] Storing 2020-05-08 07:30:00+00:00
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving dual-gauge-card/dual-gauge-card.js from /home/homeassistant/.homeassistant/www/community/dual-gauge-card/dual-gauge-card.js.gz
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving rgb-light-card/card.js from /home/homeassistant/.homeassistant/www/community/rgb-light-card/card.js.gz
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving tracking-number-card/tracking-number-card.js from /home/homeassistant/.homeassistant/www/community/tracking-number-card/tracking-number-card.js.gz
2020-05-08 13:35:26 DEBUG (MainThread) [hacs] Serving travel-time-card/travel-time-card.js from /home/homeassistant/.homeassistant/www/community/travel-time-card/travel-time-card.js.gz
```

**Comment by ludeeus** [comment]
1) `1.0a1` is **not**  a HACS version.
2) Issue containes no debug logs...

**Comment by konikvranik** [comment]
How do I find hacs version? pip says `Requirement already up-to-date: hacs in /srv/homeassistant/lib/python3.7/site-packages (1.0a1)`

**Comment by konikvranik** [comment]
I fiound that HACS has to be updated manually. After update it works.
