### ISSUE TITLE
HACS not loading after update to 1.0.1 - Restore Failed

### ISSUE THREAD

**Issue by HITChris** [hacs/integration#1221]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.0.1
| Home Assistant version     | 0.110.1
| Installation method for HA | Supervised

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the backend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS upgrades as expected and asks to restart Home Assistant.
Upon restart HACS is present in Integrations and can be configured/modified but is not available on the Sidebar or via direct URL.

Log (see below) report that a restore failed because [Not a directory: '/config/.storage/hacs/120370503.hacs']

### Steps to reproduce

1. 1. 1. Upgrade from 24.5 to 1.0.1 (upgrade using HACS) and restart HA

## Debug logs

<details>
  <summary>2020-05-22 11:07:31 DEBUG (MainThread) [hacs] Configuration type: flow
2020-05-22 11:07:31 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.0.1
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-05-22 11:07:31 DEBUG (MainThread) [hacs] Can update 489 repositories
2020-05-22 11:07:31 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Checking repository.
2020-05-22 11:07:40 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Running checks against 1.0.1
2020-05-22 11:07:42 INFO (MainThread) [hacs.repository.integration.hacs.integration] Registration complete
2020-05-22 11:07:44 INFO (MainThread) [hacs.data] Restore started
2020-05-22 11:07:44 ERROR (SyncWorker_30) [homeassistant.util.json] JSON file reading failed: /config/.storage/hacs/120370503.hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'
2020-05-22 11:07:44 CRITICAL (MainThread) [hacs.data] [[Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'] Restore Failed!
2020-05-22 11:07:44 INFO (MainThread) [hacs] Disabling HACS
2020-05-22 11:07:44 INFO (MainThread) [hacs] Removing recuring tasks
2020-05-22 11:07:44 INFO (MainThread) [hacs] Removing sensor
2020-05-22 11:07:44 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry HACS for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 296, in async_unload
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 64, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 180, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2020-05-22 11:07:44 INFO (MainThread) [hacs] Removing sidepanel
2020-05-22 11:07:44 INFO (MainThread) [hacs] HACS is now disabled</summary>

```text

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
It looks like your permissions / FS is bugged.
Delete this directory and restart HA `/config/.storage/hacs`

**Comment by HITChris** [comment]
That's not reassuring, but it does resolve my issue. Thanks.
