### ISSUE TITLE
When the github ratelimit is hit a forward entry unload is done for sensor but it was never loaded.

### ISSUE THREAD

**Issue by bdraco** [hacs/integration#1244]
## Describe the issue

When the github ratelimit is hit, the config entry is unloaded
`await hass.config_entries.async_forward_entry_unload(config_entry, "sensor")` is called but since it failed to load in the first place the below error is logged.

```
2020-05-24 15:19:26 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.0.2
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-05-24 15:19:26 INFO (MainThread) [hacs] HACS is ratelimited, repository updates will resume in 1h.
2020-05-24 15:19:26 CRITICAL (MainThread) [hacs] [GitHub Ratelimit error] - Could not load HACS!
2020-05-24 15:19:26 INFO (MainThread) [hacs] Disabling HACS
2020-05-24 15:19:26 INFO (MainThread) [hacs] Removing recuring tasks
2020-05-24 15:19:26 INFO (MainThread) [hacs] Removing sensor
2020-05-24 15:19:26 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 296, in async_unload
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 64, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 180, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2020-05-24 15:19:26 INFO (MainThread) [hacs] Removing sidepanel
2020-05-24 15:19:26 INFO (MainThread) [hacs] HACS is now disabled
```

**Comment by bdraco** [comment]
@ludeeus Nice work on a quick fix 🥇
