### ISSUE TITLE
Not working after HA 0.110 Update

### ISSUE THREAD

**Issue by DoubleAmperSand** [hacs/integration#1250]
After recent HA update to : 0.110 HACS fails to reload. 
I get the below errors in the log ive tried fully uninstalling HACS and reinstalling but get the same error.

2020-05-25 06:45:10 ERROR (SyncWorker_0) [homeassistant.util.json] JSON file reading failed: /config/.storage/hacs/120370503.hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'
2020-05-25 06:45:10 CRITICAL (MainThread) [hacs.data] [[Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'] Restore Failed!
2020-05-25 06:45:10 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 5 seconds.
2020-05-25 06:45:16 WARNING (MainThread) [homeassistant.setup] Setup of updater is taking over 10 seconds.
2020-05-25 06:45:22 ERROR (MainThread) [homeassistant.components.updater] Timeout fetching Home Assistant update data
2020-05-25 06:45:23 ERROR (SyncWorker_18) [homeassistant.util.json] JSON file reading failed: /config/.storage/hacs/120370503.hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'
2020-05-25 06:45:23 CRITICAL (MainThread) [hacs.data] [[Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'] Restore Failed!
2020-05-25 06:45:23 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 10 seconds.
2020-05-25 06:45:34 ERROR (SyncWorker_18) [homeassistant.util.json] JSON file reading failed: /config/.storage/hacs/120370503.hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'
2020-05-25 06:45:34 CRITICAL (MainThread) [hacs.data] [[Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'] Restore Failed!
2020-05-25 06:45:34 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 20 seconds.
2020-05-25 06:45:55 ERROR (SyncWorker_9) [homeassistant.util.json] JSON file reading failed: /config/.storage/hacs/120370503.hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'
2020-05-25 06:45:55 CRITICAL (MainThread) [hacs.data] [[Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'] Restore Failed!
2020-05-25 06:45:55 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 40 seconds.
2020-05-25 06:46:36 ERROR (SyncWorker_16) [homeassistant.util.json] JSON file reading failed: /config/.storage/hacs/120370503.hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'
2020-05-25 06:46:36 CRITICAL (MainThread) [hacs.data] [[Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'] Restore Failed!
2020-05-25 06:46:36 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 80 seconds.

**Comment by ludeeus** [comment]
Remove this file `/config/.storage/hacs`

**Comment by akerrichardt** [comment]
ludeeus I know you gave up on me but this solved my problem also.

**Comment by Talk2Giuseppe** [comment]
> Remove this file `/config/.storage/hacs`

Just to be clear...  Is this all files, as in /config/.storage/hacs.*
  - hacs.repositories
  - hacs.hacs
  - hacs.critical

or is it the hacs folder in /config/.storage/

Thanks!

**Comment by bsmith76s** [comment]
> > Remove this file `/config/.storage/hacs`
> 
> Just to be clear... Is this all files, as in /config/.storage/hacs.*
> 
> * hacs.repositories
> * hacs.hacs
> * hacs.critical
> 
> or is it the hacs folder in /config/.storage/
> 
> Thanks!

Was this answered? I'm not sure to delete files or folder

**Comment by DoubleAmperSand** [comment]
I just deleted the files and restarted HA and this solved the problem.

**Comment by lmatter** [comment]
> > > Remove this file `/config/.storage/hacs`
> > 
> > 
> > Just to be clear... Is this all files, as in /config/.storage/hacs.*
> > 
> > * hacs.repositories
> > * hacs.hacs
> > * hacs.critical
> > 
> > or is it the hacs folder in /config/.storage/
> > Thanks!
> 
> Was this answered? I'm not sure to delete files or folder

I moved the hacs folder to "oldhacs" (just to have a backup), restarted, and the HACS sidebar returned
