### ISSUE TITLE
Stuck running background tasks

### ISSUE THREAD

**Issue by OrganicKobze** [hacs/integration#1255]
| Description                | Value |
| -------------------------- | ----- |
| HACS version               |
0.21.1
| Home Assistant version     |
0.110.2
| Installation method for HA |
Virtual Machine (Linux)
| Web browser                |
Any
| Web browser version        |
N/A
## Checklist

- [ ] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read https://hacs.xyz/docs/issues
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS frontend is stuck 'running background tasks'. I have waited a long while and also tried multiple server reboots.

### Steps to reproduce

N/A

1. 1. 1.

### Screenshots

N/A

## Javascript logs from your browser console

Log Details (ERROR)
Logger: homeassistant.core
Source: custom_components/hacs/repositories/appdaemon.py:48
First occurred: 13:34:55 (1 occurrences)
Last logged: 13:34:55

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 197, in startup_tasks
    await self.load_known_repositories()
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 386, in load_known_repositories
    await self.factory.execute()
  File "/config/custom_components/hacs/hacsbase/task_factory.py", line 30, in execute
    await asyncio.gather(*self.tasks)
  File "/config/custom_components/hacs/hacsbase/task_factory.py", line 66, in safe_register
    await hacs.register_repository(repo, category)
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 157, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/appdaemon.py", line 60, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/appdaemon.py", line 48, in validate_repository
    for filename in self.content.objects:
TypeError: 'AIOGithubRepositoryContent' object is not iterable

**Comment by ludeeus** [comment]
Update HACS manually, that was fixed a long time ago.
<https://hacs.xyz/docs/installation/manual>
or <https://hacs.xyz/docs/installation/manual_cli>
