### ISSUE TITLE
Requires 0.110.0 or newer

### ISSUE THREAD

**Issue by ramondunker** [hacs/integration#1288]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | latest
| Home Assistant version     | 0.110.4
| Installation method for HA | venv
| Web browser                | Chrome
| Web browser version        | latest

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I can install hacs, but it gets disabled right away. The logs show that it requires 0.110.0 or newer. I'm using home assistant 0.110.4.

### Steps to reproduce

1. Install hacs (folowed this guide: https://hacs.xyz/docs/installation/prerequisites)
2. Restart home assistant

1. 1. 1.

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

2020-06-02 15:15:18 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel hacs
2020-06-02 15:15:18 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel hacs
2020-06-02 15:15:18 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel hacs
2020-06-02 15:15:19 CRITICAL (SyncWorker_16) [hacs] You need HA version 0.110.0 or newer to use this integration.
2020-06-02 15:15:19 CRITICAL (SyncWorker_11) [hacs] You need HA version 0.110.0 or newer to use this integration.
2020-06-02 15:15:19 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel hacs
2020-06-02 15:15:19 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 219, in reload_hacs
    await async_setup_entry(hass, config_entry)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 77, in async_setup_entry
    raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady
2020-06-02 15:15:19 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel hacs
2020-06-02 15:15:19 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 219, in reload_hacs
    await async_setup_entry(hass, config_entry)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 77, in async_setup_entry
    raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady
2020-06-02 15:15:19 CRITICAL (SyncWorker_3) [hacs] You need HA version 0.110.0 or newer to use this integration.
2020-06-02 15:15:19 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel hacs
2020-06-02 15:15:19 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 219, in reload_hacs
    await async_setup_entry(hass, config_entry)
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 77, in async_setup_entry
    raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady
2020-06-02 15:15:22 CRITICAL (SyncWorker_0) [hacs] You need HA version 0.110.0 or newer to use this integration.
2020-06-02 15:15:22 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel hacs
2020-06-02 15:15:22 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 40 seconds.

```

</details>

**Comment by ludeeus** [comment]
Then you are not running the version of HA you think you are.

**Comment by ramondunker** [comment]
pi@raspberrypi:/home/homeassistant/.homeassistant $ pip3 show homeassistant
Name: homeassistant
Version: 0.110.4
Summary: Open-source home automation platform running on Python 3.
Home-page: https://www.home-assistant.io/
Author: The Home Assistant Authors
Author-email: hello@home-assistant.io
License: Apache License 2.0
Location: /home/pi/.local/lib/python3.7/site-packages
Requires: pytz, attrs, certifi, voluptuous, ciso8601, PyJWT, voluptuous-serialize, pip, cryptography, ruamel.yaml, pyyaml, async-timeout, astral, aiohttp, python-slugify, requests, importlib-metadata, bcrypt, jinja2
Required-by:

> Then you are not running the version of HA you think you are.

**Comment by ludeeus** [comment]
yeah... your `pi` user is running `0.110.4`, your `homeassistant` user is not

**Comment by ramondunker** [comment]
It does...:

homeassistant@raspberrypi:~ $ pip3 show homeassistant
Name: homeassistant
Version: 0.110.4
Summary: Open-source home automation platform running on Python 3.
Home-page: https://www.home-assistant.io/
Author: The Home Assistant Authors
Author-email: hello@home-assistant.io
License: Apache License 2.0
Location: /usr/local/lib/python3.7/dist-packages
Requires: astral, ruamel.yaml, async-timeout, jinja2, PyJWT, certifi, python-slugify, pyyaml, bcrypt, attrs, pytz, voluptuous-serialize, requests, ciso8601, aiohttp, voluptuous, importlib-metadata, pip, cryptography
Required-by:

**Comment by ludeeus** [comment]
aaaaaaand once more when you activate your venv

**Comment by ramondunker** [comment]
Wow... Thank you :)
