### ISSUE TITLE
SIde panel Icon is missing after update

### ISSUE THREAD

**Issue by Madman833** [hacs/integration#1302]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.0.3
| Home Assistant version     |0.110.4
| Installation method for HA | venv

## Checklist

- [ x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [ x] I have enabled debug logging for my installation.
- [ x] I have filled out the issue template to the best of my ability.
- [ x] I have read https://hacs.xyz/docs/issues
- [ x] This issue is related to the backend of HACS.
- [ x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.
I have updated the my hassio to the latest OS ,to the latest HASSIO version and than to the latest HACS. The side panel icon is appers for a sec after restart the hassion then disappears and cannot start.

### Steps to reproduce

I cannot fully reproduce, if I load back an earlier snapshoot HACS still not active on the sidebar. After updating HA,  HACS icon appers for a sec and disappering again.

1. 1. 1.

## Debug logs

<details>
  <summary>Logs</summary>

```text

2020-06-05 16:17:02 DEBUG (MainThread) [hacs] Configuration type: flow
2020-06-05 16:17:02 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 0.24.3
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-06-05 16:17:02 INFO (SyncWorker_10) [googleapiclient.discovery] URL being requested: GET https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest
2020-06-05 16:17:03 INFO (SyncWorker_10) [googleapiclient.discovery] URL being requested: GET https://www.googleapis.com/calendar/v3/calendars/hu.swedish%23holiday%40group.v.calendar.google.com/events?orderBy=startTime&maxResults=15&singleEvents=true&timeMin=2020-06-05T16%3A17%3A03.241082%2B02%3A00&alt=json
2020-06-05 16:17:03 INFO (MainThread) [hacs] HACS is ratelimited, repository updates will resume in 1h.
2020-06-05 16:17:03 INFO (SyncWorker_6) [googleapiclient.discovery] URL being requested: GET https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest
2020-06-05 16:17:03 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Checking repository.
2020-06-05 16:17:03 CRITICAL (MainThread) [hacs] [GitHub returned 401 for https://api.github.com/rate_limit] - Could not load HACS!
2020-06-05 16:17:03 INFO (MainThread) [hacs] Disabling HACS
2020-06-05 16:17:03 INFO (MainThread) [hacs] Removing recuring tasks
2020-06-05 16:17:03 INFO (MainThread) [hacs] Removing sensor
2020-06-05 16:17:03 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 296, in async_unload
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 64, in async_unload_entry
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 180, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2020-06-05 16:17:03 INFO (MainThread) [hacs] Removing sidepanel
2020-06-05 16:17:03 INFO (MainThread) [hacs] HACS is now disabled

```

</details>

**Comment by Madman833** [comment]
I solved the issue my self. Previously I use the UI to set HACS up. Nothing was added into the YAML. I have added now all the config into YAML and HACS started to work again. The olny differences that I lost all of my settings from before.

**Comment by Madman833** [comment]
Solved as well. Deleted the integration set it up again with a new token.
