### ISSUE TITLE
HACS unavailable to update, no sidebar - causing issues, cannot remove or renew

### ISSUE THREAD

**Issue by baldfox** [hacs/integration#1340]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.03
| Home Assistant version     | 0.113
| Installation method for HA | hassio
| Web browser                | Chrome or safari
| Web browser version        | Chrome Version 83.0.4103.97 

## Checklist

- [x] I'm running the newest version of HACS https://github.com/hacs/integration/releases/latest
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read https://hacs.xyz/docs/issues
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I updated my home-assistant installation to 0.111 and OS 4.10. Since then the HACS options has been missing from the side bar. I originally had it entered manually in yaml under configuration.yaml but I removed that in its entirety and added hacs in under integrations. Nothing worked. The screen continued to reload every 30-40 seconds or so, and for a split second I would see Hacs appear and then disappear. I played with all the options in the integration including daemon etc but nothing would make it appear stable or around long enough for me to click on the link. I am unable to update HACS to the latest as I cannot access it. 

I am also getting these errors:

### Steps to reproduce

I have since removed the integration and tried to revert back to the original coding in yaml which was working previously, but that doesn't work either. I do not see HACS at all.

I have searched for a way to update hacs manually but have failed in my attempts.

### Screenshots

![image](https://user-images.githubusercontent.com/32448665/84754211-dee0d380-afe1-11ea-85a8-e1e1a63d5e00.png)

![image](https://user-images.githubusercontent.com/32448665/84754255-ee601c80-afe1-11ea-8ed2-b51c6d4e2b5f.png)

![image](https://user-images.githubusercontent.com/32448665/84754300-020b8300-afe2-11ea-911d-c0ccb4b64529.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

2020-06-16 14:10:34 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {'installation_type': 'Home Assistant', 'version': '0.111.3', 'dev': False, 'hassio': True, 'virtualenv': False, 'python_version': '3.7.7', 'docker': True, 'arch': 'x86_64', 'timezone': 'Asia/Almaty', 'os_name': 'Linux', 'os_version': '3.11.6', 'supervisor': '227', 'host_os': 'HassOS 4.10', 'chassis': 'embedded', 'docker_version': '19.03.8', 'distribution': 'alpine', 'huuid': 'db4bfce31ec94fad923e12befbd5dfc0'}
2020-06-16 14:10:34 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2020-06-16 14:10:34 INFO (MainThread) [homeassistant.components.notify] Setting up notify.webostv
2020-06-16 14:10:34 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 2.0 seconds.
2020-06-16 14:10:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up coronavirus platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 443, in _async_add_entity
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 297, in async_write_ha_state
    self._async_write_ha_state()  # type: ignore
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/components/coronavirus/sensor.py", line 55, in state
    getattr(case, self.info_type) for case in self.coordinator.data.values()
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
2020-06-16 14:10:35 INFO (MainThread) [homeassistant.setup] Setup of domain device_tracker took 2.1 seconds.
2020-06-16 14:10:35 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
2020-06-16 14:10:35 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
2020-06-16 14:10:35 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
2020-06-16 14:10:35 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
2020-06-16 14:10:35 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.legacy
2020-06-16 14:10:35 INFO (MainThread) [homeassistant.components.kodi.media_player] Unable to fetch kodi data
2020-06-16 14:10:35 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:35 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:35 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:36 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:37 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:37 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:37 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:37 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.plex_recently_added (<class 'custom_components.plex_recently_added.sensor.PlexRecentlyAddedSensor'>) took 2.524 seconds. Please report it to the custom component author.
2020-06-16 14:10:37 WARNING (MainThread) [homeassistant.setup] Setup of hacs is taking over 10 seconds.
2020-06-16 14:10:38 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:38 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:38 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:39 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:39 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:39 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:39 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:40 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:40 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:40 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for plex_recently_added doing I/O at custom_components/plex_recently_added/sensor.py, line 323: r = requests.head(url, verify=False)
2020-06-16 14:10:41 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.plex_recently_added_2 (<class 'custom_components.plex_recently_added.sensor.PlexRecentlyAddedSensor'>) took 2.632 seconds. Please report it to the custom component author.
2020-06-16 14:10:41 INFO (MainThread) [hacs.repository.integration.hacs.integration] Registration complete
2020-06-16 14:10:41 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.mqtt
2020-06-16 14:10:41 INFO (MainThread) [homeassistant.setup] Setting up camera
2020-06-16 14:10:41 INFO (MainThread) [hacs.data] Restore started
2020-06-16 14:10:42 ERROR (SyncWorker_5) [homeassistant.util.json] JSON file reading failed: /config/.storage/hacs/120370503.hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 31, in load_json
    with open(filename, encoding="utf-8") as fdesc:
NotADirectoryError: [Errno 20] Not a directory: '/config/.storage/hacs/120370503.hacs'

```

</details>

**Comment by ludeeus** [comment]
Remove the file .storage/hacs
