### ISSUE TITLE
1.2.2 cannot be reinstalling

### ISSUE THREAD

**Issue by amamenu** [hacs/integration#1390]
Logger: homeassistant.config_entries
Source: config_entries.py:533
First occurred: 18:15:44 (2 occurrences)
Last logged: 18:20:36

Error occurred loading configuration flow for integration hacs: No module named 'custom_components.hacs.helpers.functions'

**Comment by Tom-ahawk** [comment]
I have the same problem. Innstaled HACS 1.2.2 and got in my GUi "Custom element doesn't exist: XYZ". And Icant reinstalled it from Intergartion.

From the log:

Log Details (ERROR)
Logger: aiohttp.server
Source: custom_components/hacs/helpers/functions/store.py:5
First occurred: 1:23:33 PM (2 occurrences)
Last logged: 1:26:38 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 186, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 73, in post
    "show_advanced_options": data["show_advanced_options"],
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 129, in async_init
    flow, flow.init_step, data, init_done
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/hacs/config_flow.py", line 86, in async_step_init
    return await self.async_step_user()
  File "/config/custom_components/hacs/config_flow.py", line 90, in async_step_user
    hacs = get_hacs()
  File "/config/custom_components/hacs/share.py", line 14, in get_hacs
    from custom_components.hacs.hacsbase.hacs import Hacs
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 21, in <module>
    from custom_components.hacs.helpers.functions.store import (
  File "/config/custom_components/hacs/helpers/functions/store.py", line 5, in <module>
    from custom_components.hacs.const import STORAGE_VERSION
ImportError: cannot import name 'STORAGE_VERSION' from 'custom_components.hacs.const' (/config/custom_components/hacs/const.py)

```
arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.11
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7
python_version | 3.7.7
supervisor | 229
timezone | Europe/Oslo
version | 0.112.4
virtualenv | false

```

**Comment by ludeeus** [comment]
that is not 1.2.2, that is 1.2.0 see #1389
