### ISSUE TITLE
HACS 1.3.0b not working with HA 0.113.0

### ISSUE THREAD

**Issue by clyra** [hacs/integration#1415]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.3.0b
| Home Assistant version     | 1.113.0
| Installation method for HA | Docker

## Checklist

- [ x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ x ] I have enabled debug logging for my installation.
- [ x ] I have filled out the issue template to the best of my ability.
- [ x ] I have read <https://hacs.xyz/docs/issues>
- [ x ] This issue is related to the backend of HACS.
- [ x ] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After upgrading hacs to the 1.3.0b version it no longer works. I had a previous HACS version running and tried to upgrade from hacs itself, but after I did the necessary restart of H.A. HACS no longer appears on UI. I found a log entry with the failed hacs component setup. I also tried to manually remove the hacs folder and did a "clean" install (unziping hacs.zip) with the same result.

### Steps to reproduce

1. unzip the 1.3.0b hacs.zip on custom_components folder of a Home-assistant 0.113.0 docker installation
2. confirm that there's no hacs on home-assistant ui.

## Debug logs

<details>
  <summary>Logs</summary>

```text

2020-07-30 13:37:41 INFO (MainThread) [homeassistant.setup] Setting up hacs
2020-07-30 13:37:42 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/config/custom_components/hacs/__init__.py", line 21, in async_setup
    return await hacs_yaml_setup(hass, config)
  File "/config/custom_components/hacs/operational/setup.py", line 72, in async_setup
    await hass.async_add_executor_job(_common_setup, hass)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hacs/operational/setup.py", line 41, in _common_setup
    hacs.session = async_create_clientsession(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 68, in async_create_clientsession
    connector = _async_get_connector(hass, verify_ssl)
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 182, in _async_get_connector
    connector = aiohttp.TCPConnector(enable_cleanup_closed=True, ssl=ssl_context)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 727, in __init__
    super().__init__(keepalive_timeout=keepalive_timeout,
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 229, in __init__
    loop = get_running_loop(loop)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 268, in get_running_loop
    loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'SyncWorker_4'.

```

</details>

**Comment by ludeeus** [comment]
HACS works just fine with all versions of Home Assistant 0.110+
Your event loop is closed by something.
Disable all other custom components.
If it still fails.
Enable debug for everything, and paste the life file here.

**Comment by tobydriver** [comment]
Same issue for me

**Comment by ludeeus** [comment]
Then you do what was asked

**Comment by thijsdejong** [comment]
Are you sure you released this version correctly? It's a beta right? I'm being prompted to install it in my home assistant installation
![image](https://user-images.githubusercontent.com/25135566/88953966-f32f1600-d299-11ea-8d71-eb8717086464.png)

**Comment by tanus10** [comment]
I installed fresh everything due to SD card failure. Started with empty .storage and custom_components folder.
copied 1.3.0b0 to the folder and done token and things with UI.
Stuck with HACS is starting up.
```
2020-07-31 02:31:30 INFO (MainThread) [custom_components.hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.3.0b0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-07-31 02:31:32 INFO (MainThread) [custom_components.hacs.repository.integration.hacs.integration] Registration complete
2020-07-31 02:31:32 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-07-31 02:31:32 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.hacs entity: sensor.hacs
```

**Comment by tanus10** [comment]
> HACS works just fine with all versions of Home Assistant 0.110+
> Your event loop is closed by something.
> Disable all other custom components.
> If it still fails.
> Enable debug for everything, and paste the log file here.

You are on 1.3.b0 right?

**Comment by oopiicaa** [comment]
The same issue, running HA Core in Python venv on Win10. Got update prompt in HA and after update, HACS is not available.

**Comment by tanus10** [comment]
Because of this
```
WARNING (MainThread) [frontend.js.latest.202007160] Icon mdi:github-circle was renamed to mdi:github, please change your config, it will be removed in version 0.115
```
We cannot stay with 1.2.2 for long.
(This warning is mass displayed when you hit the plus sign (+) in HACS. The github shadowy cat icon is the culprit.)
