### ISSUE TITLE
HACS stopped working after reinstall

### ISSUE THREAD

**Issue by mpejstrup** [hacs/integration#1499]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.5.2
| Home Assistant version     |114.4
| Installation method for HA |RPI 4 Hassio
| Web browser                |Chrome
| Web browser version        |Newest

## Checklist

- [X ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ X] I have filled out the issue template to the best of my ability.
- [ X] I have read <https://hacs.xyz/docs/issues>
- [ X] This issue is related to the frontend of HACS.
- [ X] This issue only contain 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Very long story, kept short.
Experienced the sidebar of Hacs (Community) disaaperared for no apparent reason. Did all the things I could find in issue to fix the problem. 
Deleted .storage/hacs folder
Reinstalled hacs multiple times
- When reinstalling hacs integration was succesfull, but no entity was created
Tried new github tokens
Etc.
Talked a bit with @ludeeus, but no luck.
Now I took it on to begin from scratch.
Flashed a new SD-card
Installed hacs as the first thing, to check if that helped. It did work and hacs was back in my sidebar.

Feeling good, I reinstalled all my integrations, plugins, lovelace cards, copied my .yaml files back, etc.
Restarted HA and all was back to normal => Normal being that the hacs sidebar is gone and hacs sensor is broken.
I'm without any more ideas, please help 👍 

### Steps to reproduce

No real steps to reproduce

All cards aren't working and when I look at the hacs entity it's unavailable.
I tried again to removed the .storage/hacs folder. No luck

### Screenshots

![2020-08-29_14h55_39](https://user-images.githubusercontent.com/55014016/91637527-6e0a5e80-ea09-11ea-833d-6db28164e832.png)

![2020-08-29_14h54_31](https://user-images.githubusercontent.com/55014016/91637528-71054f00-ea09-11ea-8390-5d789a1b1514.png)

![2020-08-29_15h09_37](https://user-images.githubusercontent.com/55014016/91637562-aad65580-ea09-11ea-8424-7aedcaf6a9f4.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```text

Logdetaljer (ERROR)
Logger: homeassistant.config_entries
Source: util/yaml/loader.py:64
First occurred: 15.13.00 (1 occurrences)
Last logged: 15.13.00

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 61, in load_yaml
    return yaml.load(conf_file, Loader=SafeLineLoader) or OrderedDict()
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 50, in compose_node
    node: yaml.nodes.Node = super().compose_node(parent, index)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 50, in compose_node
    node: yaml.nodes.Node = super().compose_node(parent, index)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 50, in compose_node
    node: yaml.nodes.Node = super().compose_node(parent, index)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 50, in compose_node
    node: yaml.nodes.Node = super().compose_node(parent, index)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 50, in compose_node
    node: yaml.nodes.Node = super().compose_node(parent, index)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 50, in compose_node
    node: yaml.nodes.Node = super().compose_node(parent, index)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 50, in compose_node
    node: yaml.nodes.Node = super().compose_node(parent, index)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/config/ui-lovelace.yaml", line 1901, column 13
expected <block end>, but found '<scalar>'
  in "/config/ui-lovelace.yaml", line 1905, column 20

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 222, in async_setup
    result = await component.async_setup_entry(  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 61, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 86, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 125, in async_hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 238, in system_health_info
    health_info.update(await hass.data[DOMAIN]["dashboards"][None].async_get_info())
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 174, in async_get_info
    config = await self.async_load(False)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 185, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 204, in _load_config
    config = load_yaml(self.path)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 64, in load_yaml
    raise HomeAssistantError(exc)
homeassistant.exceptions.HomeAssistantError: while parsing a block mapping
  in "/config/ui-lovelace.yaml", line 1901, column 13
expected <block end>, but found '<scalar>'
  in "/config/ui-lovelace.yaml", line 1905, column 20
```

</details>

**Comment by ludeeus** [comment]
Your Lovelace configuration is not valid
