### ISSUE TITLE
When Home Assistant runs in debug mode, HACS throws an error during startup and the sensor fails to load

### ISSUE THREAD

**Issue by rccoleman** [hacs/integration#1521]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.5.2
| Home Assistant version     | 0.115.0b7
| Installation method for HA | OS via KVM

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

I have lots of debug enabled to try to track down an issue I'm seeing in HA (https://github.com/home-assistant/core/issues/39817) and it's causing `sensor.hacs` to fail to load.  HACS itself seems to work fine, only the sensor indicating available updates fails to set up.  If reduce the debug, it works fine.

I don't think that this issue is related to the other one because I can repro the other with the hacs directory moved out of custom_components, but it may be worth investigating anyway.

### Steps to reproduce

I believe that simply using this will cause it to repro:

```yaml
logger:              
  default: debug 
```

I do also have asyncio debug enabled, and maybe that exacerbates it.

## Debug logs

<details>
  <summary>Logs</summary>

```
2020-09-12 08:44:54 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140280154326352] Sending {'id': 10, 'type': 'event', 'event': {'event_typ
2020-09-12 08:44:54 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs                                                                  
Traceback (most recent call last):                                                                                                                                      
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 228, in async_setup                                                                               
    result = await component.async_setup_entry(hass, self)  # type: ignore                                                                                              
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry                                                                                      
    return await hacs_ui_setup(hass, config_entry)                                                                                                                      
  File "/config/custom_components/hacs/operational/setup.py", line 61, in async_setup_entry                                                                             
    return await async_startup_wrapper_for_config_entry()                                                                                                               
  File "/config/custom_components/hacs/operational/setup.py", line 86, in async_startup_wrapper_for_config_entry                                                        
    startup_result = await async_hacs_startup()                                                                                                                         
  File "/config/custom_components/hacs/operational/setup.py", line 194, in async_hacs_startup                                                                           
    await async_add_sensor()                                                                                                                                            
  File "/config/custom_components/hacs/operational/setup_actions/sensor.py", line 28, in async_add_sensor                                                               
    await hacs.hass.async_add_executor_job(_add_sensor)                                                                                                                 
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run                                                                                         
    result = self.fn(*self.args, **self.kwargs)                                                                                                                         
  File "/config/custom_components/hacs/operational/setup_actions/sensor.py", line 18, in _add_sensor                                                                    
    hacs.hass.async_add_job(                                                                                                                                            
  File "/usr/src/homeassistant/homeassistant/core.py", line 316, in async_add_job                                                                                       
    task = self.loop.create_task(target)  # type: ignore                                                                                                                
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 431, in create_task                                                                                      
    task = tasks.Task(coro, loop=self, name=name)                                                                                                                       
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 721, in call_soon                                                                                        
    self._check_thread()                                                                                                                                                
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 758, in _check_thread                                                                                    
    raise RuntimeError(                                                                                                                                                 
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one                                                                             
2020-09-12 08:44:54 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=hacs>  
```

</details>

**Comment by rccoleman** [comment]
@balloob pointed out that this may just be an error made fatal when running in debug mode, rather than caused by lots of debug.

**Comment by ludeeus** [comment]
I'm not able to reproduce this on any of my installations.
Can you try this on an installation with nothing other than HACS?
You can use the devcontainer in this repo if that makes it easier.

**Comment by rccoleman** [comment]
Sure, I'll see if I can repro it on a simpler setup.  I wonder if having a lot of stuff going on is part of it.

**Comment by rccoleman** [comment]
As I continue to mess around with the dev container, it occurs to me that the problem is more that I was running Home Assistant in debug mode, rather than just having a lot of logging.  In my case, running Home Assistant OS in a VM, I used the custom component from https://github.com/home-assistant/core/issues/7133#issuecomment-372160280 and enabled it with `enable_debug:` to turn it on.  I suspect that's the key, and I believe should be similar to running "hass --debug".

**Comment by ludeeus** [comment]
With that I was instantly able to reproduce it :+1:

**Comment by rccoleman** [comment]
Excellent, sorry about the initial misdirection.  I didn't make the connection to "debug" until Paulus pointed it out.
