### ISSUE TITLE
Hacs unable to add it's own sideboard panel entry if Lovelace is in yaml mode

### ISSUE THREAD

**Issue by sshalyminov** [hacs/integration#1543]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.0 |
| Home Assistant version     | 0.115.2 |
| Installation method for HA | docker supervised @ Ubuntu 20.04.1 LTS |

## Checklist

- [*] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [*] I have enabled debug logging for my installation.
- [*] I have filled out the issue template to the best of my ability.
- [*] I have read <https://hacs.xyz/docs/issues>
- [*] This issue is related to the backend of HACS.
- [*] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS unable to add it's own side panel entry if Lovelace is in yaml mode.

### Steps to reproduce

1. Switch lovelace to yaml mode in configuration.yaml in lovelace section:
lovelace:
  mode: yaml
2. Restart HA
3. Hacs side panel entry disappear
4. Revert back lovelace in storage mode:
lovelace:
  mode: storage
5. Restart HA
6. Hacs side panel in place

## Debug logs

<details>
  <summary>Logs</summary>

2020-09-21 12:03:50 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 228, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 62, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 87, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 121, in async_hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 239, in system_health_info
    health_info.update(await hass.data[DOMAIN]["dashboards"][None].async_get_info())
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 181, in async_get_info
    return _config_info(self.mode, config)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 216, in _config_info
    "views": len(config.get("views", [])),
AttributeError: 'NodeListClass' object has no attribute 'get'

</details>

**Comment by ludeeus** [comment]
Your lovelace configuration is broken.

**Comment by sshalyminov** [comment]
@ludeeus Can you share more details of your suggestion please? What exactly is broken? What to check/fix?
There is nothing more in lovelace section of config.
ui-lovelace.yaml contains just stub:
title: Empty
views:
  - title: Empty
    badges:
      - entity: sun.sun
And page with this one badge looks fine.

**Comment by ludeeus** [comment]
I don't know, I don't use YAML.

```
File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 216, in _config_info
"views": len(config.get("views", [])),
AttributeError: 'NodeListClass' object has no attribute 'get'
```

Home Assistant can not read your configuration.
<https://www.home-assistant.io/lovelace/dashboards-and-views/>

**Comment by sshalyminov** [comment]
This is miracle. I've completely reset config and re-write it manually from scratch. And now it's working.
Sorry, this issue is not HACS related.
