### ISSUE TITLE
Actions are broken

### ISSUE THREAD

**Issue by KTibow** [hacs/integration#1546]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | N/A
| Home Assistant version     | N/A
| Installation method for HA | N/A

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [N/A] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [Related the most] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
The GitHub Actions are broken and now give this error:
```
AttributeError: type object 'HacsCore' has no attribute 'config_path'
```

### Steps to reproduce

1. Go to a check page like https://github.com/KTibow/lovelace-light-soft-ui-theme/runs/1146963826?check_suite_focus=true
2. Expand "HACS validation"
3. See error

## Debug logs

<details>
  <summary>Logs</summary>

```

Run hacs/integration/action@master
  with:
    GITHUB_TOKEN: ***
    CATEGORY: theme
/usr/bin/docker run --name e33460d0886a5d2ea44be82c7cc5c9ec0e414_b3b4d4 --label 9e3346 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_CATEGORY -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/lovelace-light-soft-ui-theme/lovelace-light-soft-ui-theme":"/github/workspace" 9e3346:0d0886a5d2ea44be82c7cc5c9ec0e414
::INFO:: Category: theme
::INFO:: Repository: KTibow/lovelace-light-soft-ui-theme
Traceback (most recent call last):
  File "/hacs/action.py", line 142, in <module>
    LOOP.run_until_complete(preflight())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/hacs/action.py", line 123, in preflight
    await validate_repository(repository, category, ref)
  File "/hacs/action.py", line 136, in validate_repository
    await register_repository(repository, category, ref=ref)
  File "/hacs/custom_components/hacs/helpers/functions/register_repository.py", line 26, in register_repository
    repository = RERPOSITORY_CLASSES[category](full_name)
  File "/hacs/custom_components/hacs/repositories/theme.py", line 19, in __init__
    self.content.path.local = self.localpath
  File "/hacs/custom_components/hacs/repositories/theme.py", line 26, in localpath
    return f"{self.hacs.core.config_path}/themes/{self.data.file_name.replace('.yaml', '')}"
AttributeError: type object 'HacsCore' has no attribute 'config_path'

```

</details>

**Comment by ludeeus** [comment]
Use `main` and not `master`

**Comment by KTibow** [comment]
Can you update it so that it gives a more descriptive error message @ludeeus?

**Comment by ludeeus** [comment]
That is already in place?
<https://github.com/hacs/integration/actions/runs/267090396>
