### ISSUE TITLE
HACS doesn't work anymore

### ISSUE THREAD

**Issue by Markobu98** [hacs/integration#1555]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.0
| Home Assistant version    | 0.115.4
| Installation method for | raspberry pi
| Web browser               | edge
| Web browser version       | newest

## Checklist

- [ X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ X] I have filled out the issue template to the best of my ability.
- [ X] I have read <https://hacs.xyz/docs/issues>
- [X ] This issue is related to the frontend of HACS.
- [ X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

So today I installed HACS. At first it worked just fine. However I restarted Hass and now it cant Start HACS and an error message is displayed in the logs. 

### Steps to reproduce

1. Installed HACS 
2. Restarted Hass
3. Opened HACS ; didnt work

### Screenshots

![Screenshot_20200928-213226.jpg](https://user-images.githubusercontent.com/72013479/94477399-2296cc00-01d2-11eb-9ff0-4f6705df044c.jpg)

## Javascript logs from your browser console

Using Hass on Smartphone 

PASTE YOUR DEBUG LOGS HERE

Logger: homeassistant.config_entries
Source: components/frontend/__init__.py:196
First occurred: 8:23:30 PM (1 occurrences)
Last logged: 8:23:30 PM

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 228, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 62, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 87, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 132, in async_hacs_startup
    await async_setup_frontend()
  File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
    hacs.hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs

**Comment by JoeAverge9** [comment]
I had to re-launch the app on my phone and acknowledge the latest terms before it would work

**Comment by kotlarz** [comment]
Having the exact same issue and stacktrace with the same versions. Not getting anything regarding terms in the app.

**Comment by ludeeus** [comment]
HACS is not a app.
Attach the HA startup log

**Comment by kotlarz** [comment]
```
  logs:
    custom_components.hacs: debug
    hacs: debug
    queueman: debug
    AIOGitHubAPI: debug
```

Everything related to HACS during startup:
```
2020-09-29 12:20:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-09-29 12:20:30 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'zone', 'webhook', 'logbook', 'ipp', 'mqtt', 'system_health', 'device_tracker', 'timer', 'updater', 'cast', 'climate', 'mobile_app', 'automation', 'tts', 'zeroconf', 'ssdp', 'upnp', 'openweathermap', 'air_quality', 'samsungtv', 'input_select', 'switch', 'pi_hole', 'tag', 'history', 'hacs', 'media_player', 'sun', 'airvisual', 'influxdb', 'met', 'script', 'tibber', 'zwave', 'input_text', 'speedtestdotnet', 'wake_on_lan', 'persistent_notification', 'openuv', 'map', 'nordpool', 'sensor'}
2020-09-29 12:20:33 INFO (MainThread) [homeassistant.setup] Setting up hacs
2020-09-29 12:20:33 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 0.0 seconds
2020-09-29 12:20:33 DEBUG (MainThread) [custom_components.hacs] Configuration type: flow
2020-09-29 12:20:33 INFO (MainThread) [custom_components.hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.6.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-09-29 12:20:33 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2020-09-29 12:20:33 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2020-09-29 12:20:33 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
2020-09-29 12:20:36 INFO (MainThread) [custom_components.hacs] HACS is ratelimited, repository updates will resume when the limit is cleared, this can take up to 1 hour
2020-09-29 12:20:36 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 5 seconds
2020-09-29 12:20:41 DEBUG (MainThread) [custom_components.hacs] Configuration type: flow
2020-09-29 12:20:41 INFO (MainThread) [custom_components.hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.6.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-09-29 12:20:41 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2020-09-29 12:20:41 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2020-09-29 12:20:41 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 228, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 62, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 87, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 132, in async_hacs_startup
    await async_setup_frontend()
  File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
    hacs.hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs
```

HA had some deprecation of HTML support from the frontend in 0.115, but that might not be related?

**Comment by ludeeus** [comment]
> HACS is ratelimited, repository updates will resume when the limit is cleared, this can take up to 1 hour

Wait 1 hour.

**Comment by kotlarz** [comment]
> > HACS is ratelimited, repository updates will resume when the limit is cleared, this can take up to 1 hour
> 
> Wait 1 hour.

I let HA run over the night and had the same issue in the morning. I'll let it run again though, thanks!

**Comment by Markobu98** [comment]
I let Hass run over night. Just checke, the problem seems to have gone. So maybe waiting is the solution

**Comment by AntonBorisovRu** [comment]
I have the same error installing HACS.

HACS
Integration version: | 1.6.2
Frontend version: | 202009091732

Home Assistant 0.117.6
Frontend version: 20201021.4 - latest

Log:
```
2020-11-15 13:21:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-15 13:22:03 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for xiaomi_miio_airpurifier which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-11-15 13:22:23 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 5 seconds
2020-11-15 13:22:28 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for hacs
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
return await hacs_ui_setup(hass, config_entry)
File "/config/custom_components/hacs/operational/setup.py", line 66, in async_setup_entry
return await async_startup_wrapper_for_config_entry()
File "/config/custom_components/hacs/operational/setup.py", line 91, in async_startup_wrapper_for_config_entry
startup_result = await async_hacs_startup()
File "/config/custom_components/hacs/operational/setup.py", line 139, in async_hacs_startup
await async_setup_frontend()
File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
hacs.hass.components.frontend.async_register_built_in_panel(
File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs
```
