### ISSUE TITLE
hacs integration showing up in hacs integrations tab

### ISSUE THREAD

**Issue by ggoodell2** [hacs/integration#1574]
| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.6.0
| Home Assistant version     |247
| Installation method for HA | image on rpi 4 (best i can describe it)
| Web browser                | firefox
| Web browser version        | most recent version

## Checklist

- [x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the frontend of HACS.
- [x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

Installed HACS per https://hacs.xyz/docs/installation/prerequisites Restarted HA. Installed Alexa Media Player and and the mode red integration on HACS. Restarted HA. HACS Began to act, to the best i can explain, act weird. Showed every single available integration, frontend, and automation in there respective categories as if they were installed and slowed down HA to the point it crashed. Restarted it and uninstalled HACS per instructions from above site. Rebooted HA about three times and tripple checked i got anything to do with HACS out of the files and reinstalled HACS. Rebooted HA again after reinstalling HACS. Attempted to install ONLY Alexa Media Player and rebooted ha. No alexa in installed but HACS still there with the three dots yellow. click on dots and yellow option brings me here...

logs....
this is the best i can get

2020-10-11 07:59:19 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-11 07:59:38 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook 7d2a68ba57c9f02bf4752f50bff5701bcc23fede4d5ad9c96d39f53bfac46b9d from cloud
2020-10-11 08:00:38 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-11 08:01:16 ERROR (MainThread) [custom_components.hacs.factory] maykar/custom-header - Repository is archived.
2020-10-11 08:02:42 ERROR (MainThread) [custom_components.hacs.factory] custom-components/uilogs - GitHub Ratelimit error
2020-10-11 08:02:42 ERROR (MainThread) [custom_components.hacs.factory] custom-components/templatesensor - GitHub Ratelimit error
2020-10-11 08:02:42 ERROR (MainThread) [custom_components.hacs.factory] custom-components/sytadin - GitHub Ratelimit error
2020-10-11 08:02:42 ERROR (MainThread) [custom_components.hacs.repository.integration.custom-components.srp_energy] Could not read manifest.json [GitHub Ratelimit error]
2020-10-11 08:02:42 ERROR (MainThread) [custom_components.hacs.factory] custom-components/unsplash - GitHub Ratelimit error
2020-10-11 08:02:43 ERROR (MainThread) [custom_components.hacs.factory] custom-components/ups - GitHub Ratelimit error
2020-10-11 08:02:43 ERROR (MainThread) [custom_components.hacs.factory] custom-components/weatheralerts - GitHub Ratelimit error
2020-10-11 08:02:43 ERROR (MainThread) [custom_components.hacs.factory] custom-components/wienerlinien - GitHub Ratelimit error
2020-10-11 08:02:44 ERROR (MainThread) [custom_components.hacs.factory] custom-components/youtube - GitHub Ratelimit error
2020-10-11 08:02:44 ERROR (MainThread) [custom_components.hacs.factory] custom-components/zaptec - GitHub Ratelimit error
2020-10-11 08:02:45 ERROR (MainThread) [custom_components.hacs.factory] cyberjunky/home-assistant-arpscan_tracker - GitHub Ratelimit error
2020-10-11 08:02:45 ERROR (MainThread) [custom_components.hacs.factory] cyberjunky/home-assistant-hvcgroep - GitHub Ratelimit error
2020-10-11 08:02:46 ERROR (MainThread) [custom_components.hacs.factory] cyberjunky/home-assistant-p2000 - GitHub Ratelimit error
2020-10-11 08:02:46 ERROR (MainThread) [custom_components.hacs.factory] cyberjunky/home-assistant-plugwise - GitHub Ratelimit error
2020-10-11 08:02:47 ERROR (MainThread) [custom_components.hacs.factory] cyberjunky/home-assistant-toon_boilerstatus - GitHub Ratelimit error
2020-10-11 08:02:47 ERROR (MainThread) [custom_components.hacs.factory] cyberjunky/home-assistant-toon_climate - GitHub Ratelimit error
2020-10-11 08:02:47 ERROR (MainThread) [custom_components.hacs.factory] cyberjunky/home-assistant-ttn_gateway - GitHub Ratelimit error
2020-10-11 08:02:47 ERROR (MainThread) [custom_components.hacs.factory] cyberjunky/home-assistant-toon_smartmeter - GitHub Ratelimit error
2020-10-11 08:02:47 ERROR (MainThread) [custom_components.hacs.factory] Cyr-ius/hass-cozytouch - GitHub Ratelimit error
2020-10-11 08:02:48 ERROR (MainThread) [custom_components.hacs.factory] Cyr-ius/hass-hue-service-advanced - GitHub Ratelimit error
2020-10-11 08:02:48 ERROR (MainThread) [custom_components.hacs.factory] Cyr-ius/hass-livebox-component - GitHub Ratelimit error
2020-10-11 08:02:48 ERROR (MainThread) [custom_components.hacs.factory] daenny/climate_group - GitHub Ratelimit error
2020-10-11 08:02:49 ERROR (MainThread) [custom_components.hacs.factory] Danielhiversen/home_assistant_adax - GitHub Ratelimit error
2020-10-11 08:02:49 ERROR (MainThread) [custom_components.hacs.factory] Danielhiversen/home_assistant_tractive - GitHub Ratelimit error
2020-10-11 08:02:49 ERROR (MainThread) [custom_components.hacs.factory] danobot/entity-controller - GitHub Ratelimit error
2020-10-11 08:02:50 ERROR (MainThread) [custom_components.hacs.factory] DarkSir23/sensor.mylar - GitHub Ratelimit error
2020-10-11 08:02:51 ERROR (MainThread) [custom_components.hacs.factory] dave-code-ruiz/uhomeuponor - GitHub Ratelimit error
2020-10-11 08:02:51 ERROR (MainThread) [custom_components.hacs.factory] DavidFW1960/bom_forecast - GitHub Ratelimit error
2020-10-11 08:02:51 ERROR (MainThread) [custom_components.hacs.factory] DavidMStraub/homeassistant-homeconnect - GitHub Ratelimit error
2020-10-11 08:02:52 ERROR (MainThread) [custom_components.hacs.factory] deblockt/hass-proscenic-790T-vacuum - GitHub Ratelimit error

**Comment by ludeeus** [comment]
You are ratelimited by Github.
Wait 1 hour

**Comment by ggoodell2** [comment]
restarted ha and got the following



Logger: homeassistant.config_entries
Source: components/frontend/__init__.py:196
First occurred: 8:30:03 AM (1 occurrences)
Last logged: 8:30:03 AM
Error setting up entry for hacs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 231, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 62, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 87, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 132, in async_hacs_startup
    await async_setup_frontend()
  File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
    hacs.hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs



Logger: homeassistant.config_entries
Source: config_entries.py:242
First occurred: 8:29:58 AM (1 occurrences)
Last logged: 8:29:58 AM
Config entry for hacs not ready yet. Retrying in 5 seconds 



Logger: homeassistant.loader
Source: loader.py:440
First occurred: 8:29:57 AM (1 occurrences)
Last logged: 8:29:57 AM
You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

**Comment by ludeeus** [comment]
Right... it has not been 1 hour yet...

**Comment by ggoodell2** [comment]
gotcha

**Comment by ggoodell2** [comment]
its been over an hour now....

logs under configerations shows 

2020-10-11 09:48:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-11 09:48:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-10-11 09:48:56 ERROR (MainThread) [custom_components.hacs.factory] maykar/custom-header - Repository is archived.

but hacs still shows hacs integrations with the three dots yellow....

**Comment by ludeeus** [comment]
And see, now the rate limit is gone ;)

For your other things I have no clue what you are talking about, share images

**Comment by ggoodell2** [comment]
![2020-10-11 (4)](https://user-images.githubusercontent.com/72327987/95685194-3ca9b480-0bab-11eb-8005-a6bd5fc655a7.jpg)
![2020-10-11 (5)](https://user-images.githubusercontent.com/72327987/95685197-3d424b00-0bab-11eb-8398-8fadbb627f72.jpg)
this is what concerns me.

**Comment by ggoodell2** [comment]
open issue on the HACS tile is the only one that does anything.

**Comment by ludeeus** [comment]
That looks like a perfectly, normal installation of HACS.
What exactly are you expecting?

**Comment by ggoodell2** [comment]
alexa media to be there after i installed it and rebooted ha

**Comment by ludeeus** [comment]
You removed and knowledge HACS had, when you uninstalled HACS.
You need to reinstall it for it to show

**Comment by ggoodell2** [comment]
im an idiot and read the directions wrong. you only install the apps in hacs. you do the rest in ha integrations... /tech support

**Comment by ludeeus** [comment]
HACS only download files, what you do with those files HACS does not have and say in.
