### ISSUE TITLE
HACS sometimes fails to startup with `Overwriting panel hacs`

### ISSUE THREAD

**Issue by bdraco** [hacs/integration#1605]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.0
| Home Assistant version     | 0.118dev
| Installation method for HA |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

### Steps to reproduce

1. HACS fails to startup 

<img width="672" alt="Screen Shot 2020-10-27 at 11 50 57 AM" src="https://user-images.githubusercontent.com/663432/97334406-b5b33800-184a-11eb-998e-00ad748803d7.png">

## Debug logs

<details>
  <summary>Logs</summary>

```
2020-10-27 16:42:22 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 63, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 88, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 133, in async_hacs_startup
    await async_setup_frontend()
  File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
    hacs.hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs
```

</details>

**Comment by bdraco** [comment]
I think this happens when I hit the github rate limit

**Comment by ShakataGaNai** [comment]
I'm seeing the same thing but https://api.github.com/rate_limit indicates I still have some API calls left in the minute.
