### ISSUE TITLE
HACS will not start with HA 0.117

### ISSUE THREAD

**Issue by tehbra1n** [hacs/integration#1609]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.0
| Home Assistant version     |0.117
| Installation method for HA |HA Core on Ubuntu

## Checklist

- [ X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ X] I have enabled debug logging for my installation.
- [X ] I have filled out the issue template to the best of my ability.
- [X ] I have read <https://hacs.xyz/docs/issues>
- [ X] This issue is related to the backend of HACS.
- [X ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

HACS fails to start on HA 0.117
### Steps to reproduce

1.  Start HA 0.117
2.  That's it
3.

## Debug logs

<details>
  <summary></summary>

```

Oct 28 15:49:21 ultra hass[777]: 2020-10-28 15:49:21 DEBUG (MainThread) [custom_components.hacs] Configuration type: yaml
Oct 28 15:49:21 ultra hass[777]: 2020-10-28 15:49:21 INFO (MainThread) [custom_components.hacs]
Oct 28 15:49:21 ultra hass[777]: -------------------------------------------------------------------
Oct 28 15:49:21 ultra hass[777]: HACS (Home Assistant Community Store)
Oct 28 15:49:21 ultra hass[777]: Version: 1.6.0
Oct 28 15:49:21 ultra hass[777]: This is a custom integration
Oct 28 15:49:21 ultra hass[777]: If you have any issues with this you need to open an issue here:
Oct 28 15:49:21 ultra hass[777]: https://github.com/hacs/integration/issues
Oct 28 15:49:21 ultra hass[777]: -------------------------------------------------------------------
Oct 28 15:49:21 ultra hass[777]: 2020-10-28 15:49:21 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
Oct 28 15:49:21 ultra hass[777]: 2020-10-28 15:49:21 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
Oct 28 15:49:21 ultra hass[777]: 2020-10-28 15:49:21 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
Oct 28 15:49:23 ultra hass[777]: 2020-10-28 15:49:23 DEBUG (MainThread) [custom_components.hacs] Can update 489 repositories
Oct 28 15:49:23 ultra hass[777]: 2020-10-28 15:49:23 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
Oct 28 15:49:23 ultra hass[777]: 2020-10-28 15:49:23 DEBUG (MainThread) [custom_components.hacs.repository.integration.hacs.integration] Checking repository.
Oct 28 15:49:31 ultra hass[777]: 2020-10-28 15:49:31 WARNING (MainThread) [homeassistant.setup] Setup of hacs is taking over 10 seconds.
Oct 28 15:50:18 ultra hass[777]: 2020-10-28 15:50:18 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: hacs
Oct 28 15:51:09 ultra hass[777]: 2020-10-28 15:51:09 CRITICAL (MainThread) [custom_components.hacs] [] - Could not load HACS!
Oct 28 15:51:09 ultra hass[777]: 2020-10-28 15:51:09 INFO (MainThread) [custom_components.hacs] Could not setup HACS, trying again in 15 min
Oct 28 15:51:09 ultra hass[777]: 2020-10-28 15:51:09 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Oct 28 15:51:09 ultra hass[777]: Traceback (most recent call last):
Oct 28 15:51:09 ultra hass[777]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
Oct 28 15:51:09 ultra hass[777]:     result = await task
Oct 28 15:51:09 ultra hass[777]:   File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 24, in async_setup
Oct 28 15:51:09 ultra hass[777]:     return await hacs_yaml_setup(hass, config)
Oct 28 15:51:09 ultra hass[777]:   File "/home/homeassistant/.homeassistant/custom_components/hacs/operational/setup.py", line 78, in async_setup
Oct 28 15:51:09 ultra hass[777]:     await async_startup_wrapper_for_yaml()
Oct 28 15:51:09 ultra hass[777]:   File "/home/homeassistant/.homeassistant/custom_components/hacs/operational/setup.py", line 112, in async_startup_wrapper_for_yaml
Oct 28 15:51:09 ultra hass[777]:     async_call_later(hacs.hass, 900, async_startup_wrapper_for_yaml())
Oct 28 15:51:09 ultra hass[777]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/event.py", line 1160, in async_call_later
Oct 28 15:51:09 ultra hass[777]:     return async_track_point_in_utc_time(
Oct 28 15:51:09 ultra hass[777]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/event.py", line 1134, in async_track_point_in_utc_time
Oct 28 15:51:09 ultra hass[777]:     job = action if isinstance(action, HassJob) else HassJob(action)
Oct 28 15:51:09 ultra hass[777]:   File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/core.py", line 174, in __init__
Oct 28 15:51:09 ultra hass[777]:     raise ValueError("Coroutine not allowed to be passed to HassJob")
Oct 28 15:51:09 ultra hass[777]: ValueError: Coroutine not allowed to be passed to HassJob


```

</details>

**Comment by ludeeus** [comment]
Fixed in https://github.com/hacs/integration/releases/tag/1.6.1
