### ISSUE TITLE
Circular import in HACS validate action

### ISSUE THREAD

**Issue by MatthewFlamm** [hacs/integration#1629]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |
| Home Assistant version     |
| Installation method for HA |

## Checklist

- [ ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
Hacs validate action now creates a circular import.

#1623 changed the order of importing in the module that has the ultimate circular import sequence. Im not sure if the fix should rather be in homeassistant to prevent the circular import.  Let me know if this issue should be there instead.

### Steps to reproduce

1.  Have HACS validate action run for integration
2.
3.

## Debug logs

https://github.com/MatthewFlamm/nwsradar/runs/1355799164?check_suite_focus=true#step:4:24

```


Traceback (most recent call last):
  File "/hacs/action.py", line 10, in <module>
    from custom_components.hacs.hacsbase.configuration import Configuration
  File "/hacs/custom_components/hacs/__init__.py", line 13, in <module>
    from .operational.setup import (
  File "/hacs/custom_components/hacs/operational/setup.py", line 8, in <module>
    from homeassistant.helpers.event import async_call_later
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/event.py", line 48, in <module>
    from homeassistant.helpers.template import RenderInfo, Template, result_as_boolean
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/template.py", line 34, in <module>
    from homeassistant.helpers import config_validation as cv, location as loc_helper
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/config_validation.py", line 534, in <module>
    def template(value: Optional[Any]) -> template_helper.Template:
AttributeError: partially initialized module 'homeassistant.helpers.template' has no attribute 'Template' (most likely due to a circular import)
```

</details>

**Comment by MatthewFlamm** [comment]
#1628 was submitted near simultaneously
