### ISSUE TITLE
Still getting "Error setting up entry for hacs" on fresh installation (HACS 1.6.2)

### ISSUE THREAD

**Issue by vomdth** [hacs/integration#1654]
I read that should have been fixed with 1.6.2, but I just installed HACS 1.6.2 on a fresh HA image and still get the following error, after installing the first repository from store (Meross Cloud):

Any idea why this error still occurs?

Logger: homeassistant.config_entries
Source: components/frontend/__init__.py:196
First occurred: 11:23:54 AM (1 occurrences)
Last logged: 11:23:54 AM

Error setting up entry for hacs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 234, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 66, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 91, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 139, in async_hacs_startup
    await async_setup_frontend()
  File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
    hacs.hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs

**Comment by ludeeus** [comment]
That's not fixed in 1.6.2, it's fixed in the next version
