### ISSUE TITLE
Why is HACs reporting against ZOOM when Zoom repository its not installed?

### ISSUE THREAD

**Issue by WedHumpDay** [hacs/integration#1663]
## Describe the issue

Receiving errors in the HA log ZOOM is reporting errors.

ZOOM repository is NOT installed.

Why would HACs be reporting against an integration when its not installed? Are there any other integrations which are running in the background that shouldn't be when not installed? This raises security concerns of rouge intergrations.

### Links

- **Link to action run:**
- **Link to action configuration:**

2020-11-18 20:04:35 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

Traceback (most recent call last):

File "/srv/homeassistant/lib/python3.8/site-packages/aiogithubapi/helpers.py", line 91, in async_call_api
response.data = await result.json()
File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1021, in json
await self.read()
File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 973, in read
self._body = await self.content.read()
File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/streams.py", line 358, in read
block = await self.readany()
File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/streams.py", line 380, in readany
await self._wait('readany')
File "/srv/homeassistant/lib/python3.8/site-packages/aiohttp/streams.py", line 296, in _wait
await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/homeassistant/.homeassistant/custom_components/hacs/hacsbase/hacs.py", line 265, in prosess_queue
await self.queue.execute(can_update)
File "/srv/homeassistant/lib/python3.8/site-packages/queueman/manager.py", line 63, in execute
await asyncio.gather(*local_queue)
File "/home/homeassistant/.homeassistant/custom_components/hacs/operational/factory.py", line 25, in safe_common_update
await repository.common_update()
File "/home/homeassistant/.homeassistant/custom_components/hacs/helpers/classes/repository.py", line 247, in common_update
await self.repository_object.set_last_commit()
File "/srv/homeassistant/lib/python3.8/site-packages/aiogithubapi/objects/repository/__init__.py", line 169, in set_last_commit
response = await self.client.get(endpoint=_endpoint)
File "/srv/homeassistant/lib/python3.8/site-packages/aiogithubapi/client.py", line 36, in get
response = await async_call_api(
File "/srv/homeassistant/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
ret = await target(*args, **kwargs)
File "/srv/homeassistant/lib/python3.8/site-packages/aiogithubapi/helpers.py", line 101, in async_call_api
raise AIOGitHubAPIException(response.data)
File "/srv/homeassistant/lib/python3.8/site-packages/async_timeout/__init__.py", line 55, in __aexit__
self._do_exit(exc_type)
File "/srv/homeassistant/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

2020-11-18 20:07:41 ERROR (MainThread) [custom_components.hacs.repository.integration.raman325.ha-zoom-automation]
2020-11-18 20:07:41 ERROR (MainThread) [custom_components.hacs.factory] raman325/ha-zoom-automation -

**Comment by ludeeus** [comment]
Because it's tracked as a default repository.
https://hacs.xyz/docs/default_repositories

**Comment by WedHumpDay** [comment]
You guys are funny! Read that document and it suggest there is an App installed in Zoom client that is reporting to HA. Not app is installed.  Clearly the documentation is misleading.

**Comment by ludeeus** [comment]
What's funny about that?

HACS fetches information from GitHub about every repository it tracks, not just installed repositories.
Without that, there would be nothing to show inside HACS, the information is only metadata about the repositories.

It's not downloading and installing anything.

**Comment by WedHumpDay** [comment]
If not installing, then why the error message in HA logs regarding Zoom.

**Comment by ludeeus** [comment]
Those are for HACS not for zoom,  you have/had network issues when it tried to fetch information about that repository.
