### ISSUE TITLE
Error setting up entry  for hacs

### ISSUE THREAD

**Issue by amitvaria** [hacs/integration#1672]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.2 |
| Home Assistant version     | 0.118.2 |
| Installation method for HA | hass.io|

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

When I visit the HACS panel from the left hand menu, I'm told: "HACS is disabled. Check your log file for more details". Debug logs are below.

This seems similar to https://github.com/hacs/integration/issues/1614, but those notes indicate that issue was resolved in 1.6.2 which is what I currently have installed.

### Steps to reproduce

1. Follow recommended installation steps - https://hacs.xyz/docs/installation/manual

## Debug logs

<details>
  <summary>Logs</summary>

```

2020-11-22 16:06:52 DEBUG (MainThread) [custom_components.hacs] Configuration type: flow
2020-11-22 16:06:52 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.6.2
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-11-22 16:06:52 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2020-11-22 16:06:52 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2020-11-22 16:06:52 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 66, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 91, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 139, in async_hacs_startup
    await async_setup_frontend()
  File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
    hacs.hass.components.frontend.async_register_built_in_panel(
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
    raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs

```

</details>

**Comment by ludeeus** [comment]
Restart HA and attach the complete startup log

**Comment by amitvaria** [comment]
[home-assistant.log](https://github.com/hacs/integration/files/5579886/home-assistant.log)

Full log file attached

**Comment by ludeeus** [comment]
There is nothing wrong there?

**Comment by amitvaria** [comment]
Oh yeah - turns out when I restarted this last time everything started working. I'll close this out. Sorry for the troubles.
