### ISSUE TITLE
HACS not loading (hacs config entries)

### ISSUE THREAD

**Issue by sicknesz** [hacs/integration#1691]
## Installation details

HACS 1.6.2               |
Home Assistant 0.118.4     |
Installation method for HA - docker |
Chrome

## Describe the issue

HACS does not start anymore 

### Steps to reproduce

1. Install HA
2. Install HACS 
3. Update to 1.6.2 
4. restart 
5. broken install

2020-12-02 18:51:00 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for hacs
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
return await hacs_ui_setup(hass, config_entry)
File "/config/custom_components/hacs/operational/setup.py", line 66, in async_setup_entry
return await async_startup_wrapper_for_config_entry()
File "/config/custom_components/hacs/operational/setup.py", line 91, in async_startup_wrapper_for_config_entry
startup_result = await async_hacs_startup()
File "/config/custom_components/hacs/operational/setup.py", line 139, in async_hacs_startup
await async_setup_frontend()
File "/config/custom_components/hacs/operational/setup_actions/frontend.py", line 38, in async_setup_frontend
hacs.hass.components.frontend.async_register_built_in_panel(
File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 196, in async_register_built_in_panel
raise ValueError(f"Overwriting panel {panel.frontend_url_path}")
ValueError: Overwriting panel hacs

**Comment by ludeeus** [comment]
Add full startup log with <https://hacs.xyz/docs/basic/logs>
