### ISSUE TITLE
HACS is Starting Up: Coroutine not allowed to be passed to HassJob

### ISSUE THREAD

**Issue by mechanimal82** [hacs/integration#1693]
## Installation details

| Description                | HACS fresh install remains as 'HACS is setting up': Coroutine not allowed to be passed to HassJob  |
| -------------------------- | ----- |
| HACS version              |  1.8.0b1 (had the same issue with 1.6.2)
| Home Assistant version    |  1.0.0b0
| Installation method for HA | OVA Virtual Machine

## Checklist

- 

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Originally had HA & HACS running on a Pi, moved to a VM and restored my config including HACS, but was failing to load (both were on the latest stable). I have since upgraded HA to 1.0 beta and HACS beta to see if there are any fixes, but still failing to startup and HACS reports 'HACS is setting up' but never completes. I have rebooted and reinstalled several times fully removing the hacs folder from storage and any hacs files in custom components, I have removed the previously installed HACS repositories that copied across in custom components and the www/community folder too. Full reinstall still fails, log seems to fail on the below:

### Steps to reproduce

1. Complete reinstall
2. Check HACS in Sidebar
3. Shows 'Starting up'

## Debug logs

<details>
  <summary>Logs</summary>

```

2020-12-04 08:11:40 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 67, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 92, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 197, in async_hacs_startup
    async_call_later(hacs.hass, 5, hacs.startup_tasks())
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1179, in async_call_later
    return async_track_point_in_utc_time(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1133, in async_track_point_in_utc_time
    job = action if isinstance(action, HassJob) else HassJob(action)
  File "/usr/src/homeassistant/homeassistant/core.py", line 174, in __init__
    raise ValueError("Coroutine not allowed to be passed to HassJob")
ValueError: Coroutine not allowed to be passed to HassJob

```
Full log:
[home-assistant.log](https://github.com/hacs/integration/files/5641443/home-assistant.log)

**Comment by ollimagic** [comment]
i have the same problem version 1.8 newes Beta Hassio Beta
Protokolldetails ( ERROR )
Logger: homeassistant.config_entries
Source: core.py:174
First occurred: 11:06:06 (1 occurrences)
Last logged: 11:06:06

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 67, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 92, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 197, in async_hacs_startup
    async_call_later(hacs.hass, 5, hacs.startup_tasks())
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1179, in async_call_later
    return async_track_point_in_utc_time(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1133, in async_track_point_in_utc_time
    job = action if isinstance(action, HassJob) else HassJob(action)
  File "/usr/src/homeassistant/homeassistant/core.py", line 174, in __init__
    raise ValueError("Coroutine not allowed to be passed to HassJob")
ValueError: Coroutine not allowed to be passed to HassJob
