### ISSUE TITLE
HACS integration randomly dissapeared from integrations

### ISSUE THREAD

**Issue by kpcz** [hacs/integration#1694]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.6.2 |
| Home Assistant version     | 0.118.3 |
| Installation method for HA | rpi4 image on SD card |

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Today logged in my HA and realized, that there is no community (HACS) tab on side bar, also no HACS integration in integrations anymore.  After clearing browser cache, lovelace card installed via HACS, broke as well. Tried multiple restarts, did not help. 

Only thing that changed to my system, was recent update of Supervisor 2020.12.2

Tried to add HACS to integrations back, did not work, error on logs.

### Steps to reproduce

1. Install HA
2. Install HACS
3. After supervisor update (?), HACS dissapeared. 

## Debug logs

<details>
  <summary>Logs</summary>

```
##NO USEFULL LOGS AFTER RESTART AND DEBBUGING ENABLED
only log, regadting to HACS:

2020-12-04 10:39:06 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.

##LOGS WHEN I TRIED TO ADD INTEGRATION BACK IN SUPERVISOR

2020-12-04 10:24:17 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/config/custom_components/hacs/helpers/functions/information.py", line 45, in get_repository
repository = await github.get_repo(repository_full_name)
File "/usr/local/lib/python3.8/site-packages/aiogithubapi/github.py", line 55, in get_repo
response = await self.client.get(endpoint=_endpoint, headers=_headers)
File "/usr/local/lib/python3.8/site-packages/aiogithubapi/client.py", line 36, in get
response = await async_call_api(
File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
ret = await target(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/aiogithubapi/helpers.py", line 83, in async_call_api
raise AIOGitHubAPIAuthenticationException(HttpStatusCode.UNAUTHORIZED)
aiogithubapi.common.exceptions.AIOGitHubAPIAuthenticationException: HttpStatusCode.UNAUTHORIZED
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
result: Dict = await getattr(flow, method)(user_input)
File "/config/custom_components/hacs/config_flow.py", line 41, in async_step_user
if await self._test_token(user_input["token"]):
File "/config/custom_components/hacs/config_flow.py", line 66, in _test_token
await get_repository(session, token, "hacs/org")
File "/config/custom_components/hacs/helpers/functions/information.py", line 48, in get_repository
raise HacsException(exception)
custom_components.hacs.helpers.classes.exceptions.HacsException: HttpStatusCode.UNAUTHORIZED





Logger: aiohttp.server
Source: custom_components/hacs/helpers/functions/information.py:48
First occurred: 10:24:17 AM (1 occurrences)
Last logged: 10:24:17 AM
Error handling request

Traceback (most recent call last):
  File "/config/custom_components/hacs/helpers/functions/information.py", line 45, in get_repository
    repository = await github.get_repo(repository_full_name)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/github.py", line 55, in get_repo
    response = await self.client.get(endpoint=_endpoint, headers=_headers)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/client.py", line 36, in get
    response = await async_call_api(
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/helpers.py", line 83, in async_call_api
    raise AIOGitHubAPIAuthenticationException(HttpStatusCode.UNAUTHORIZED)
aiogithubapi.common.exceptions.AIOGitHubAPIAuthenticationException: HttpStatusCode.UNAUTHORIZED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/hacs/config_flow.py", line 41, in async_step_user
    if await self._test_token(user_input["token"]):
  File "/config/custom_components/hacs/config_flow.py", line 66, in _test_token
    await get_repository(session, token, "hacs/org")
  File "/config/custom_components/hacs/helpers/functions/information.py", line 48, in get_repository
    raise HacsException(exception)
custom_components.hacs.helpers.classes.exceptions.HacsException: HttpStatusCode.UNAUTHORIZED



```

</details>

**Comment by kpcz** [comment]
From browser all hacs custom components gives browser 404
![error_chrome](https://user-images.githubusercontent.com/26654090/101146528-c57d2380-3623-11eb-86c6-54fd864de2a5.PNG)

404 on 
https://myhass.duckdns.org/hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
but all .js files are present 
on https://myhass.duckdns.org/local/community/lovelace-fold-entity-row/fold-entity-row.js

**Comment by kpcz** [comment]
generated new github key, readded HACS integration, restarted HA, now everything is fine. Thanks.
