### ISSUE TITLE
HACS doenst run and not showed up in sidebar

### ISSUE THREAD

**Issue by Strandlaken** [hacs/integration#1714]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version              | 1.6.2
| Home Assistant version     | 0.118.5
| Installation method for HA | Intergations
| Web browser                | Chrome
| Web browser version        |

## Checklist

- [ ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ X] I have filled out the issue template to the best of my ability.
- [ X] I have read <https://hacs.xyz/docs/issues>
- [ ] This issue is related to the frontend of HACS.
- [X ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I installed version 1.6.2 of HACS (also tried the latest version, but it gives the same error:

When adding the tokenkey, hacs doenst show up in the sidebar. In the logs i see the following errors;

```
Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 30, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 66, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 91, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 128, in async_hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/system_health.py", line 19, in system_health_info
    health_info.update(await hass.data[DOMAIN]["dashboards"][None].async_get_info())
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 106, in async_get_info
    await self._load()
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 150, in _load
    data = await self._store.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 105, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 110, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 124, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 38, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: Expecting value: line 2 column 1 (char 1)
```

### Steps to reproduce

1.tried with the newest version but same results

No idea what the error means.

**Comment by ludeeus** [comment]
Your Lovelace configuration is broken, fix that and HACS will work
