### ISSUE TITLE
ValueError: 502 is not a valid HttpStatusCode

### ISSUE THREAD

**Issue by caesar1987sk** [hacs/integration#1747]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.9.0
| Home Assistant version     |2020.12.0
| Installation method for HA | ha image on rpi 3b+

## Checklist

- [ x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ ] I have enabled debug logging for my installation.
- [ x] I have filled out the issue template to the best of my ability.
- [ x] I have read <https://hacs.xyz/docs/issues>
- [ x] This issue is related to the backend of HACS.
- [ x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue
In hacs I have long time this information:
Background tasks pending
Some repositories might not show until this is completed
 And this log is in log file. Not sure if it's related. 

`Logger: homeassistant
Source: custom_components/hacs/helpers/functions/information.py:54
First occurred: December 19, 2020, 12:55:57 PM (1 occurrences)
Last logged: December 19, 2020, 12:55:57 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 303, in recurring_tasks_all
    await self.data.async_write()
  File "/config/custom_components/hacs/hacsbase/data.py", line 57, in async_write
    await self.queue.execute()
  File "/usr/local/lib/python3.8/site-packages/queueman/manager.py", line 63, in execute
    await asyncio.gather(*local_queue)
  File "/config/custom_components/hacs/operational/factory.py", line 25, in safe_common_update
    await repository.common_update()
  File "/config/custom_components/hacs/helpers/classes/repository.py", line 247, in common_update
    await common_update_data(self, ignore_issues)
  File "/config/custom_components/hacs/helpers/functions/validate_repository.py", line 88, in common_update_data
    repository.tree = await get_tree(repository.repository_object, repository.ref)
  File "/config/custom_components/hacs/helpers/functions/information.py", line 54, in get_tree
    tree = await repository.get_tree(ref)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/objects/repository/__init__.py", line 127, in get_tree
    response = await self.client.get(endpoint=_endpoint, params=_params)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/client.py", line 36, in get
    response = await async_call_api(
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/helpers.py", line 87, in async_call_api
    f"GitHub returned {HttpStatusCode(response.status)} for {url}"
  File "/usr/local/lib/python3.8/enum.py", line 315, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 617, in __new__
    raise ve_exc
ValueError: 502 is not a valid HttpStatusCode`

### Steps to reproduce

1.
2.
3.

## Debug logs

<details>
  <summary>Logs</summary>

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by caesar1987sk** [comment]
@ludeeus what information you need from me?

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/103009601-4e0e2600-4537-11eb-8f0e-b00417c9a71c.png)

**Comment by caesar1987sk** [comment]
Log is pasted but on wrong place, is hard to move it on phone. And steps not sure, it's look like http call returned 502. I'm sure this is easy to simulate in dev (mock call) and hard on installed version.

**Comment by ludeeus** [comment]
The "logs" are not the requested debug logs from the log file, but a single entry from the UI

**Comment by caesar1987sk** [comment]
I have already restarted hassio, so I don't have this log anymore. But when there is some other place when I can find log you need I can try to find it.

**Comment by KTibow** [comment]
This is a problem with the GitHub API library, not HACS.

**Comment by caesar1987sk** [comment]
I expect that, but should it not be handled?

**Comment by KTibow** [comment]
Actually it's a problem with the GitHub API itself, not any dependencies. If you can't reproduce this error, then it might be a one-time-fluke that it's not worth adding support for.
