### ISSUE TITLE
problem after upgrading to 2020.12.7

### ISSUE THREAD

**Issue by pilot1981** [hacs/integration#1752]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |  1.9.0
| Home Assistant version     | 2020.12.7
| Installation method for HA | via configuration.yaml

## Checklist

- [ X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ X] I have enabled debug logging for my installation.
- [ X] I have filled out the issue template to the best of my ability.
- [ X] I have read <https://hacs.xyz/docs/issues>
- [ X] This issue is related to the backend of HACS.
- [ X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I always used HACS integrated using configuration.yaml with my HASSIO installation on Rpi3b+. After upgrading to 2020.12.7, HACS diapered from web guy of HA, in log I found error in Github token, so I try to remove HACS from integration GUI and configuration.yaml, but when I go to add again config in configuration.yaml I obtain this error:

Logger: custom_components.hacs
Source: custom_components/hacs/operational/setup.py:155 
Integration: HACS (documentation, issues) 
First occurred: 15:45:21 (1 occurrences) 
Last logged: 15:45:21

Your GitHub token is not valid

Logger: aiohttp.server
Source: custom_components/hacs/config_flow.py:78 
First occurred: 20 dicembre 2020, 18:30:42 (3 occurrences) 
Last logged: 11:45:10

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1005, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 871, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/resolver.py", line 31, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/hacs/config_flow.py", line 67, in async_step_user
    return await self._show_device_form()
  File "/config/custom_components/hacs/config_flow.py", line 78, in _show_device_form
    device_data = await self.device.async_register_device()
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/device.py", line 65, in async_register_device
    response = await async_call_api(
  File "/usr/local/lib/python3.8/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiogithubapi/helpers.py", line 62, in async_call_api
    result = await session.post(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1017, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host github.com:443 ssl:default [Try again]

or if I try to add integration in HA GUI, after I accepted every items I obtain this error:

"Unknown error occurred"

20-12-21 14:15:52 WARNING (MainThread) [supervisor.jobs] 'StoreManager.update_repositories' blocked from execution, no supervisor internet connection
20-12-21 14:15:52 INFO (MainThread) [supervisor.store] Loading add-ons from store: 70 all - 0 new - 0 remove
20-12-21 14:31:35 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
20-12-21 14:36:44 INFO (MainThread) [supervisor.api.security] /snapshots access from cebe7a76_hassio_google_drive_backup
20-12-21 14:37:58 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None

### Steps to reproduce

2 way; one:
1. add config to configuration.yaml

other:
1. add integration using HA GUI

## Debug logs

please see above

**Comment by ludeeus** [comment]
`aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host github.com:443 ssl:default [Try again]`
You have network issues on your HA server, you need to fix that, when that is fixed HACS will work.
