### ISSUE TITLE
Cannot install latest HACS in home-assistant:2020.12.1

### ISSUE THREAD

**Issue by wangjia184** [hacs/integration#1763]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | latest : https://github.com/hacs/integration/releases/latest/download/hacs.zip
| Home Assistant version     | docker image : homeassistant/home-assistant:2020.12.1
| Installation method for HA | Following instructions at https://hacs.xyz/docs/installation/installation

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

![image](https://user-images.githubusercontent.com/2765840/103138038-54ec9280-4709-11eb-8b91-3f08c03bfbd3.png)
After selecting HACS in above dialog, it is spinning forever.
![image](https://user-images.githubusercontent.com/2765840/103138027-37b7c400-4709-11eb-8e4f-672812b55920.png)

### Steps to reproduce

1. start a clean homeassistant as a docker container
```
docker run -d --name="home-assistant" --net=host --restart=always \
  -v /root/homeassistant/config:/config \
  homeassistant/home-assistant:2020.12.1
```
2. start bash in the container
```
docker exec -ti home-assistant /bin/bash
```
Within the bash of container, execute the following command, and it succeeded
```
wget -q -O - https://hacs.xyz/install | bash -
```

3. Restart the container

4. Go to Configuration => Intergration, click the + button, select HACS
![image](https://user-images.githubusercontent.com/2765840/103138038-54ec9280-4709-11eb-8b91-3f08c03bfbd3.png)
5.  It spins forever
![image](https://user-images.githubusercontent.com/2765840/103138027-37b7c400-4709-11eb-8e4f-672812b55920.png)

## Debug logs

```
020-12-25 15:07:51 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 119, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 532, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 74, in async_get_integration_with_requirements
    await async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 131, in async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for hacs not found: ['hacs_frontend==20201205162459'].
```

**Comment by cdrom1028** [comment]
I am seeing the exact same Issue

**Comment by wangjia184** [comment]
After rolling back to home-assistant:2020.12.0, it works well.

**Comment by Mikescops** [comment]
I confirm this issue too

**Comment by FaserF** [comment]
2020.12.2 still has issues :/

**Comment by Tizianob91** [comment]
i have installed hacc but after a reboot i get the following error:
![image](https://user-images.githubusercontent.com/76565218/103415741-d1f18f00-4b83-11eb-94f0-573f9d05ee38.png)

log:
2020-12-31 15:05:20 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-12-31 15:05:31 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 5 seconds
2020-12-31 15:05:32 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.7.3 is deprecated and will be removed in the first release after December 7, 2020. Please upgrade Python to 3.8.0 or higher.

system info:
![image](https://user-images.githubusercontent.com/76565218/103415812-0feeb300-4b84-11eb-82ae-b805e5e97cc8.png)


how do i solve?

**Comment by tmchow** [comment]
I've got same issue as reported above, i'm on HACS 1.9.0 on Home Assistant 2020.12.2.

Is the only thing to do right now is revert to 1.8.0 like @Mikescops mentioned?

**Comment by tmchow** [comment]
Update: this was resolved for me by updating to HA 2021.1.0 today.

**Comment by linosteenkamp** [comment]
Updated to  HA 2021.1.0, still experiencing the same issue. 

I'm seeing the following in the console:

![Screenshot 2021-01-07 at 09 09 33](https://user-images.githubusercontent.com/4083528/103862936-a3fed400-50c8-11eb-93b1-d4eed781e3e7.png)

**Comment by linosteenkamp** [comment]
A reboot of my HA pi sorted the issue

**Comment by Mikescops** [comment]
I guess this issue can be closed then.
