### ISSUE TITLE
HACS not removed and not installed

### ISSUE THREAD

**Issue by Gan2020** [hacs/integration#1776]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               |1.9
| Home Assistant version     | 0.105.2
| Installation method for HA | 
| Web browser                | Crome
| Web browser version        |

## Checklist

- [+ ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ +] I have filled out the issue template to the best of my ability.
- [ +] I have read <https://hacs.xyz/docs/issues>
- [ +] This issue is related to the frontend of HACS.
- [ +] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

Hi! please help me. After the update on the HACS is not removed and not installed.
![image](https://user-images.githubusercontent.com/60912547/103452722-632b4780-4ce3-11eb-8aa7-0666a525b400.png)
In the HACS integration section, see " : " . I can't delete it
![image](https://user-images.githubusercontent.com/60912547/103452689-1fd0d900-4ce3-11eb-9011-286d35f38bdd.png)

### Steps to reproduce

1.
2.
3.

## Javascript logs from your browser console

Error handling request
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/config/config_entries.py", line 103, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 603, in async_remove
    unload_success = await self.async_unload(entry_id)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 703, in async_unload
    return await entry.async_unload(self.hass)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 271, in async_unload
    component = integration.get_component()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 266, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 13, in <module>
    from .operational.setup import (
  File "/home/homeassistant/.homeassistant/custom_components/hacs/operational/setup.py", line 5, in <module>
    from homeassistant.const import EVENT_HOMEASSISTANT_STARTED
ImportError: cannot import name 'EVENT_HOMEASSISTANT_STARTED' from 'homeassistant.const' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/const.py)

```

PASTE YOUR DEBUG LOGS HERE

```

</details>

**Comment by ludeeus** [comment]
Your Home Assistant installation is too old.
You need 2020.12.0+

**Comment by Gan2020** [comment]
![image](https://user-images.githubusercontent.com/60912547/103457686-61c54380-4d12-11eb-944f-41f4b06763e9.png)

Thanks for the answer, but the version  2020.12.2

**Comment by ludeeus** [comment]
Newest is that, but you have not that one installed
