### ISSUE TITLE
After HA Update, HACS information say to me "HACS is DISABLED"

### ISSUE THREAD

**Issue by nicolap75** [hacs/integration#1802]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.9.0 |
| Home Assistant version     | 2021.1.1 |
| Installation method for HA | Hass OS |
| Web browser                | Microsoft Edge - Chromium |
| Web browser version        | 87.0.664.75 |

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the frontend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After updating HA to version 2021.1.1 I receive the following screenshot.

### Steps to reproduce

1. Update Home assistant to version 2021.1.1
2.
3.

### Screenshots

![image](https://user-images.githubusercontent.com/63191355/104103528-e5e37200-52a2-11eb-9a9b-fc5bf5fa9dc6.png)

## Javascript logs from your browser console

<details>
  <summary>Logs</summary>

```

HACS (Home Assistant Community Store)

Version: 1.9.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2021-01-09 17:18:29 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2021-01-09 17:18:29 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2021-01-09 17:18:29 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
2021-01-09 17:18:30 INFO (MainThread) [custom_components.hacs] HACS is ratelimited, repository updates will resume when the limit is cleared, this can take up to 1 hour
2021-01-09 17:18:30 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 5 seconds
2021-01-09 17:18:33 WARNING (MainThread) [aiohttp.websocket] websocket connection is closing.
2021-01-09 17:18:33 WARNING (MainThread) [aiohttp.websocket] websocket connection is closing.
2021-01-09 17:18:33 WARNING (MainThread) [aiohttp.websocket] websocket connection is closing.
2021-01-09 17:18:33 WARNING (MainThread) [aiohttp.websocket] websocket connection is closing.
2021-01-09 17:18:35 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ********.******@gmail.com - amazon.com for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 345, in async_setup_entry
    return await hass.data[DOMAIN].async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 155, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2021-01-09 17:18:36 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server.
2021-01-09 17:18:36 WARNING (MainThread) [homeassistant.config_entries] Config entry for ipp not ready yet. Retrying in 5 seconds
2021-01-09 17:18:39 ERROR (MainThread) [homeassistant.components.speedtestdotnet] Error fetching speedtestdotnet data: 
2021-01-09 17:19:49 ERROR (MainThread) [homeassistant.components.ipp] Error fetching ipp data: Invalid response from API: Timeout occurred while connecting to IPP server.

```

</details>

**Comment by ludeeus** [comment]
From the logs you posted:
> HACS is ratelimited, repository updates will resume when the limit is cleared, this can take up to 1 hour

**Comment by emeyedeejay** [comment]
Same issue now for 24 hours - I'll complete all the reqs for issue template. Q is - do I open a new issue as this is closed?
