### ISSUE TITLE
Integration installation - Stuck on Waiting for Device activation

### ISSUE THREAD

**Issue by Surgical17** [hacs/integration#1845]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.10.1
| Home Assistant version     | 5.10 (Core 2021.1.5)
| Installation method for HA | Integrations

## Checklist

- [X ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X ] I have enabled debug logging for my installation.
- [X ] I have filled out the issue template to the best of my ability.
- [X ] I have read <https://hacs.xyz/docs/issues>
- [X ] This issue is related to the backend of HACS.
- [X ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Issue

After starting the integration installation. Hacs requires authentication in order to connect to my GitHub account. After following the instructions and allowing access, Hacs gets stuck on the same page "Waiting for Device activation"

### Screenshots

![image](https://user-images.githubusercontent.com/76941635/105975916-32e38880-6098-11eb-878f-790552f09e0c.png)

![image](https://user-images.githubusercontent.com/76941635/105975951-3b3bc380-6098-11eb-9046-769fab32ba5f.png)

## Debug logs

<details>
  <summary>Logs</summary>

```

Traceback (most recent call last):
File "/config/custom_components/hacs/config_flow.py", line 59, in _wait_for_activation
self.activation = await self.device.async_device_activation()
File "/usr/local/lib/python3.8/site-packages/aiogithubapi/device.py", line 84, in async_device_activation
"device_code": self._device_code,
AttributeError: 'AIOGitHubAPIDeviceLogin' object has no attribute '_device_code'

```

</details>

**Comment by Surgical17** [comment]
Update:

I went back to the previous version of Hacs. Added he old Custome component files to Home assistant config. I was able to install Hacs. Next step is to test if I can Update Hacs to the latest version.
