### ISSUE TITLE
HACS integration stuck at starting up/ 

### ISSUE THREAD

**Issue by mattsmithuk** [hacs/integration#1850]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | 1.10.1
| Home Assistant version     |  2021.1.5
| Installation method for HA | Home Assistant Core

## Checklist

- [x] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] I have read <https://hacs.xyz/docs/issues>
- [x] This issue is related to the backend of HACS.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

HACS integration appears to be stuck at 'starting up'. Unable to load newly installed integration, previously installed integrations still works.
Homeassistant log shows error in hacsbase/hacs.py

```
Logger: homeassistant
Source: custom_components/hacs/hacsbase/hacs.py:177
First occurred: 12:57:43 (1 occurrences)
Last logged: 12:57:43

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/homeassistant/custom_components/hacs/hacsbase/hacs.py", line 139, in startup_tasks
    await self.handle_critical_repositories_startup()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/hacs/hacsbase/hacs.py", line 177, in handle_critical_repositories_startup
    if not repo["acknowledged"]:
TypeError: string indices must be integers
```
### Screenshot

![image](https://user-images.githubusercontent.com/37830884/106356937-fe233b80-62fa-11eb-9b4e-93f3bbac8bc1.png)

### Steps to reproduce

1. Install ha-smartthinq-sensors [https://github.com/ollo69/ha-smartthinq-sensors](url)
2. Start Homeassistant

## Debug logs

<details>
  <summary>Logs</summary>

```

2021-01-30 13:02:55 DEBUG (MainThread) [custom_components.hacs] Configuration type: yaml
2021-01-30 13:02:55 INFO (MainThread) [custom_components.hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.10.1
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2021-01-30 13:02:55 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2021-01-30 13:02:55 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.setup] Setting up esphome
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.setup] Setup of domain esphome took 0.0 seconds
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2021-01-30 13:02:55 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 0.1 seconds
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.setup] Setting up notify
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.0 seconds
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.setup] Setting up device_tracker
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.esphome
2021-01-30 13:02:55 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.esphome
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mobile_app
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.mobile_app
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mobile_app
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.mobile_app
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.setup] Setup of domain device_tracker took 0.3 seconds
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.setup] Setup of domain mysensors took 0.5 seconds
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.setup] Setting up default_config
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.0 seconds
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.updater] Submitted analytics to Home Assistant servers. Information submitted includes {}
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.device_tracker] Setting up device_tracker.mobile_app
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.esphome] Successfully connected to 192.168.1.210
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.esphome] Successfully connected to 192.168.1.206
2021-01-30 13:02:56 DEBUG (MainThread) [custom_components.hacs] Can update 260 repositories
2021-01-30 13:02:56 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
2021-01-30 13:02:56 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Checking repository.
2021-01-30 13:02:56 INFO (SyncWorker_0) [homeassistant.loader] Loaded cover from homeassistant.components.cover
2021-01-30 13:02:56 INFO (SyncWorker_4) [homeassistant.loader] Loaded switch from homeassistant.components.switch
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.light] Setting up light.tradfri
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.tradfri
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.setup] Setting up cover
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.setup] Setup of domain cover took 0.0 seconds
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.setup] Setting up switch
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.setup] Setup of domain switch took 0.0 seconds
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.cover] Setting up cover.tradfri
2021-01-30 13:02:56 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tradfri
2021-01-30 13:02:56 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.10.1
2021-01-30 13:02:57 INFO (MainThread) [homeassistant.components.tplink.common] Discovered 2 TP-Link smart home device(s)
2021-01-30 13:02:57 INFO (MainThread) [homeassistant.components.light] Setting up light.tplink
2021-01-30 13:02:57 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tplink
2021-01-30 13:02:57 INFO (SyncWorker_2) [homeassistant.loader] Loaded climate from homeassistant.components.climate
2021-01-30 13:02:57 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.hive
2021-01-30 13:02:57 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hive
2021-01-30 13:02:57 INFO (MainThread) [homeassistant.setup] Setting up climate
2021-01-30 13:02:57 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 0.0 seconds
2021-01-30 13:02:57 INFO (MainThread) [homeassistant.components.climate] Setting up climate.hive
2021-01-30 13:02:57 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> All (0) checks passed
2021-01-30 13:02:57 INFO (MainThread) [custom_components.hacs] <Integration hacs/integration> Registration completed
2021-01-30 13:02:57 INFO (MainThread) [custom_components.hacs] Restore started
2021-01-30 13:02:57 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-01-30 13:02:57 DEBUG (MainThread) [queueman.manager] Starting queue execution for 709 tasks
2021-01-30 13:02:59 DEBUG (MainThread) [queueman.manager] Queue execution finished for 709 tasks finished in 1.27 seconds
2021-01-30 13:02:59 INFO (MainThread) [custom_components.hacs] Restore done
2021-01-30 13:02:59 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.SENSOR
2021-01-30 13:02:59 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2021-01-30 13:02:59 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2021-01-30 13:02:59 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 4.4 seconds
2021-01-30 13:02:59 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2021-01-30 13:02:59 INFO (MainThread) [snitun.utils.aiohttp_client] AioHTTP snitun client connected to: eu-west-2.ui.nabu.casa:443
2021-01-30 13:03:05 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform command_line is taking over 10 seconds.
2021-01-30 13:03:11 WARNING (MainThread) [homeassistant.components.mysensors.gateway] Gateway /dev/ttyUSB0 not ready after 15.0 secs so continuing with setup
2021-01-30 13:03:11 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 21.47s
2021-01-30 13:03:11 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2021-01-30 13:03:11 INFO (MainThread) [homeassistant.core] Timer:starting
2021-01-30 13:03:11 INFO (SyncWorker_5) [homeassistant.components.zeroconf] Starting Zeroconf broadcast
2021-01-30 13:03:11 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2021-01-30 13:03:11 INFO (MainThread) [custom_components.hacs] setup task HacsSetupTask.CATEGORIES
2021-01-30 13:03:11 DEBUG (SyncWorker_3) [custom_components.hacs] Starting setup task: Extra stores
2021-01-30 13:03:11 DEBUG (SyncWorker_3) [custom_components.hacs] Enable category: HacsCategory.INTEGRATION
2021-01-30 13:03:11 DEBUG (SyncWorker_3) [custom_components.hacs] Enable category: HacsCategory.PLUGIN
2021-01-30 13:03:11 DEBUG (SyncWorker_3) [custom_components.hacs] Enable category: HacsCategory.THEME
2021-01-30 13:03:11 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/mnt/dietpi_userdata/homeassistant/custom_components/hacs/hacsbase/hacs.py", line 139, in startup_tasks
    await self.handle_critical_repositories_startup()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/hacs/hacsbase/hacs.py", line 177, in handle_critical_repositories_startup
    if not repo["acknowledged"]:
TypeError: string indices must be integers

```

</details>

**Comment by ludeeus** [comment]
Unless your filesystem is broken, or you have messed around in storrage files, this should not be possible, the format of that file has not changed.

What is the content of `/mnt/dietpi_userdata/homeassistant/.storage/hacs.critical` ?

**Comment by HFsi** [comment]
Same here, after upgrading to 2021.1.5
![image](https://user-images.githubusercontent.com/22999806/106392983-254d3c00-63d3-11eb-96da-678cfe1bff08.png)

**Comment by ludeeus** [comment]
Not the same thing

**Comment by mattsmithuk** [comment]
There was a problem with my ```hacs.critical``` file. At the end of the file there was a string of ```@``` symbols. I've removed these and HACS works fine now

Thanks
