### ISSUE TITLE
HACS not working after update HA to 2021.2.0

### ISSUE THREAD

**Issue by Bascht74** [hacs/integration#1863]
## Installation details

| Description                | Value |
| -------------------------- | ----- |
| HACS version               | newest. Installed via `wget -q -O - https://hacs.xyz/install | bash -`. As it doesn't work it doesn't show a version anymore
| Home Assistant version     | 2021.2.0
| Installation method for HA | via `SSH & Web Terminal` add-on and then `wget -q -O - https://hacs.xyz/install | bash -`

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.  ---> seams to, maybe in combination with HA 2021.2.0
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.

I updated to 2021.2.0 and HACS was gone. 

### Steps to reproduce

Install HA 2021.2.0 Update.

After that I tried the following: 
1. Restated HA CORE and nothing happened. HACS not there
2. Removed Integration -> Restart CORE -> Add integration ---> Result: It does add the integration, but there is not device:
![image](https://user-images.githubusercontent.com/66269310/106957789-c2dc9e80-6738-11eb-8d56-d980fb2e2028.png)
3. Removed HACS (https://hacs.xyz/docs/installation/remove) and installed again (https://hacs.xyz/docs/installation/installation) -> Restart CORE --> add integration HACS --> Everything is fine (as in the installation docs) until it shoes:
![image](https://user-images.githubusercontent.com/66269310/106958256-662db380-6739-11eb-85c3-e94a5c7033de.png)

4. Removed again and installed again -> same result...

## Debug logs

<details>
  <summary>Logs</summary>

I added to configuration.yaml
```
logger:
  default: critical
  logs:
#    custom_components.miele: debug
    zigpy.ota: debug
    YAMA: debug
    custom_components.hacs: debug
    hacs: debug
    queueman: debug
    AIOGitHubAPI: debug
```

```

PASTE YOUR DEBUG LOGS HERE

There is nothing logged !?

This is the only log:
2021-02-04 22:33:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-04 22:33:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-04 22:33:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for miele which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-04 22:33:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-04 22:33:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-04 22:33:41 INFO (MainThread) [zigpy.ota.provider] Trådfri: OTA provider enabled
2021-02-04 22:33:41 INFO (MainThread) [zigpy.ota.provider] Ledvance: OTA provider enabled
2021-02-04 22:33:41 DEBUG (SyncWorker_4) [zigpy.ota.provider] ImageKey(manufacturer_id=4107, image_type=269): /config/zigpy_ota/Sensor-ATmega_6.1.1.27575_0012.sbl-ota, version: 1107323831, hw_ver: (None, None), OTA string:
2021-02-04 22:33:41 DEBUG (MainThread) [zigpy.ota.provider] Ledvance: Finished downloading firmware update list
2021-02-04 22:33:42 DEBUG (MainThread) [zigpy.ota.provider] Trådfri: Finished downloading firmware update list

```

</details>

Before the 2021.2 Release HACS was working flawlessly...
The problems came right after the 2021.2 Update...

**Comment by ludeeus** [comment]
Posted logs are not relevant and does not match the logger configuration.

**Comment by Bascht74** [comment]
I know, that it seems strange, but there are no more logs...

That is why I posted them completely and the logger configuration as well...

**Comment by Bascht74** [comment]
Is there anything I can change or look at to get „more“ logs?

**Comment by ludeeus** [comment]
That's not active so a) it's in a file that is not loaded, b) HA has not been restarted with it

**Comment by Bascht74** [comment]
@ludeeus 
to a) it is in the configuration.yaml . If I add something else to e.g. debug I can see the debug messages of the line added in the log.  
![image](https://user-images.githubusercontent.com/66269310/106974987-f5e15b00-6755-11eb-9498-25afe9a8a081.png)

to b) Yes, I did. And I did now again. 
You can see the zigpy.ota messages in the log as it is configured in the logger part of the configuration.yaml

Here is the actual (complete) log, no HACS messages :-)( 
```
2021-02-05 01:57:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-05 01:57:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-05 01:57:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-05 01:57:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-05 01:57:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-05 01:57:54 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for miele which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-05 01:58:12 INFO (MainThread) [zigpy.ota.provider] Trådfri: OTA provider enabled
2021-02-05 01:58:12 INFO (MainThread) [zigpy.ota.provider] Ledvance: OTA provider enabled
2021-02-05 01:58:12 DEBUG (SyncWorker_6) [zigpy.ota.provider] ImageKey(manufacturer_id=4107, image_type=269): /config/zigpy_ota/Sensor-ATmega_6.1.1.27575_0012.sbl-ota, version: 1107323831, hw_ver: (None, None), OTA string:
2021-02-05 01:58:12 DEBUG (MainThread) [zigpy.ota.provider] Ledvance: Finished downloading firmware update list
2021-02-05 01:58:12 DEBUG (MainThread) [zigpy.ota.provider] Trådfri: Finished downloading firmware update list
```

Sebastian

**Comment by ludeeus** [comment]
Without logs there is nothing I can do 🤷
Updating HA does not break it, i update daily.

**Comment by Bascht74** [comment]
Ok, I will change the complete log to debug, let's see if there are traces of hacs there...
Somehow, HA seems to skip it...

**Comment by manuelbarbosa** [comment]
`Logger: homeassistant.setup
Source: util/yaml/loader.py:122
First occurred: February 4, 2021, 10:22:43 PM (1 occurrences)
Last logged: February 4, 2021, 10:22:43 PM

Error during setup of component hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 120, in _include_yaml
    return _add_reference(load_yaml(fname), loader, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 61, in load_yaml
    with open(fname, encoding="utf-8") as conf_file:
FileNotFoundError: [Errno 2] No such file or directory: '/config/lovelace/components/custom_header.yaml'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/hacs/__init__.py", line 20, in async_setup
    return await hacs_yaml_setup(hass, config)
  File "/config/custom_components/hacs/operational/setup.py", line 82, in async_setup
    await async_startup_wrapper_for_yaml()
  File "/config/custom_components/hacs/operational/setup.py", line 105, in async_startup_wrapper_for_yaml
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 122, in async_hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/system_health.py", line 23, in system_health_info
    dashboards_info = await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 174, in async_get_info
    config = await self.async_load(False)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 185, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 204, in _load_config
    config = load_yaml(self.path)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 62, in load_yaml
    return parse_yaml(conf_file)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 73, in parse_yaml
    return yaml.load(content, Loader=SafeLineLoader) or OrderedDict()
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 201, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 122, in _include_yaml
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError:   in "/config/lovelace-debug.yaml", line 3, column 16: Unable to read file /config/lovelace/components/custom_header.yaml.`

**Comment by Bascht74** [comment]
This is my output: 

So setting only HACS to debug is not enough... :-)
Maybe a hint in the documentation would help in future cases... 

```
Logger: homeassistant.config_entries
Source: custom_components/dwains_dashboard/process_yaml.py:87
First occurred: 2:02:41 (1 occurrences)
Last logged: 2:02:41

Error setting up entry for hacs
Traceback (most recent call last):
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 84, in _include_yaml
    return loader._add_reference(load_yaml(fname, args), ldr, node)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 49, in load_yaml
    with open(fname, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/config/dwains-dashboard/addons/popups/cover/popup.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 239, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 26, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 67, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 91, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 122, in async_hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/system_health.py", line 23, in system_health_info
    dashboards_info = await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 174, in async_get_info
    config = await self.async_load(False)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 185, in async_load
    is_updated, config = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/dashboard.py", line 204, in _load_config
    config = load_yaml(self.path)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 62, in load_yaml
    return parse_yaml(conf_file)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 73, in parse_yaml
    return yaml.load(content, Loader=SafeLineLoader) or OrderedDict()
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 201, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 84, in _include_yaml
    return loader._add_reference(load_yaml(fname, args), ldr, node)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 64, in load_yaml
    return loader.yaml.load(stream, Loader=loader.SafeLineLoader) or OrderedDict()
  File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 201, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 201, in _ordered_dict
    nodes = loader.construct_pairs(node)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "/usr/local/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 87, in _include_yaml
    raise HomeAssistantError(exc)
homeassistant.exceptions.HomeAssistantError: [Errno 2] No such file or directory: '/config/dwains-dashboard/addons/popups/cover/popup.yaml'
```

**Comment by manuelbarbosa** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: '/config/dwains-dashboard/addons/popups/cover/popup.yaml'`

You got your error right there

**Comment by Bascht74** [comment]
I removed the Dwans-dashboard integration and set the default log level to warning, let's see.

**Comment by Bascht74** [comment]
@manuelbarbosa Yes, I saw that.

**Comment by Bascht74** [comment]
Funny, that a missing file of another integration is causing this... 
Doesn't seem right.

**Comment by Bascht74** [comment]
So error is gone. Funny that it started after the update...
Thx for you help!

**Comment by AndreScalaPT** [comment]
Logger: homeassistant.util.json
Source: util/json.py:32
First occurred: 23:40:13 (2 occurrences)
Last logged: 23:41:41

Could not parse JSON content: /config/.storage/hacs.critical
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

HACS is broken? I cannot use it! Thanks
