### ISSUE TITLE
Option to open the integration missing

### ISSUE THREAD

**Issue by AndreScalaPT** [hacs/integration#1871]
| HACS version               | Latest
| Home Assistant version     | Latest
| Installation method for HA | The first one with Home Assistant OS wget with terminal (as always in my case)

- [ x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [ x ] I have enabled debug logging for my installation.
- [ x ] I have filled out the issue template to the best of my ability.
- [ x ] I have read <https://hacs.xyz/docs/issues>
- [ x ] This issue is related to the backend of HACS.
- [ x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

After the repository installation and after I add the repository the normal message that HACS is starting up appears but after a minute or two that cell disappears and I just got the other two. Check this [print](https://ibb.co/NL19wF9) pls.

Another thing is if you click in the Add-ons tab appears the message that will go to an external website but redirects to hassio/dashboard.

The About tab doesn't do nothing.

### Steps to reproduce

1. Fresh HA installation
2. Added File editor and Terminal & SSH
3. In Terminal I've run the command `wget -q -O - https://hacs.xyz/install | bash -`
4. Restarted the HA and went to integrations and added HACS
5. HACS starts and then disappear the option to enter

## Debug logs

<details>
  <summary>Logs</summary>

```

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:129 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 21:51:14 (2 occurrences) 
Last logged: 21:52:05

[2951403240] Error handling message: Expecting value: line 1 column 1 (char 0)

Logger: homeassistant.util.json
Source: util/json.py:32 
First occurred: 21:51:14 (3 occurrences) 
Last logged: 21:52:05

Could not parse JSON content: /config/.storage/hacs.critical
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Logger: homeassistant
Source: util/json.py:38 
First occurred: 21:51:16 (1 occurrences) 
Last logged: 21:51:16

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 32, in load_json
    return json.loads(fdesc.read())  # type: ignore
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 139, in startup_tasks
    await self.handle_critical_repositories_startup()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 173, in handle_critical_repositories_startup
    critical = await async_load_from_store(self.hass, "critical")
  File "/config/custom_components/hacs/helpers/functions/store.py", line 19, in async_load_from_store
    restored = await store.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 105, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 110, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 124, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 38, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: Expecting value: line 1 column 1 (char 0)

```

</details>

**Comment by ludeeus** [comment]
Ll ike I told you earlier, delete the file it's complains about, it's corrupted

**Comment by AndreScalaPT** [comment]
I didn't saw any answer!!!
Thank you
