### ISSUE TITLE
issue with "loading information.."

### ISSUE THREAD

**Issue by denisix** [hacs/integration#1952]
## System Health details
version | core-2021.2.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.0-65-generic
arch | x86_64
timezone | Europe/Vilnius

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 0
Installed Version | 1.11.3
Stage | running
Available Repositories | 602
Installed Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 1
mode | storage

</details>

## Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

I'm trying to install Sonoff integration, but unfortunately HACS shows empty modal with "loading information.." text, tried multiple times, also there's often issue with github rate limit, tried to remove/reinstall HA, then again, but still issue.
Is it possible to increase rate limits or skip searching github repos / adding manually manifests/files/etc?
Thanks!

### Steps to reproduce

1. click on HACS
2. open Integration
2. right bottom button "+ Explore & add repositories"
3. type "Sonoff"
4. click on Sonoff
5. empty modal window will appear with "loading information.." message

## Debug logs

<details>
  <summary>Logs</summary>

```
2021-02-22 19:01:42 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2021-02-22 19:05:55 ERROR (MainThread) [custom_components.hacs] opravdin/weback-hass - GitHub Ratelimit error
2021-02-22 19:05:56 ERROR (MainThread) [custom_components.hacs] <Integration ollo69/ha-smartthinq-sensors> Could not read manifest.json [GitHub Ratelimit error]
2021-02-22 19:05:56 ERROR (MainThread) [custom_components.hacs] Paul-dH/Home-Assisant-Sensor-OvApi - GitHub Ratelimit error
2021-02-22 19:05:56 ERROR (MainThread) [custom_components.hacs] peetereczek/ztm - GitHub Ratelimit error
2021-02-22 19:05:56 ERROR (MainThread) [custom_components.hacs] peternijssen/home-assistant-jumbo - GitHub Ratelimit error
2021-02-22 19:05:56 ERROR (MainThread) [custom_components.hacs] pfunkmallone/HACS-camect-integration - GitHub Ratelimit error
2021-02-22 19:05:56 ERROR (MainThread) [custom_components.hacs] pilotak/homeassistant-attributes - GitHub Ratelimit error
2021-02-22 19:05:57 ERROR (MainThread) [custom_components.hacs] pilotak/homeassistant-clientraw - GitHub Ratelimit error
2021-02-22 19:05:57 ERROR (MainThread) [custom_components.hacs] pilotak/homeassistant-mikrotik - GitHub Ratelimit error
2021-02-22 19:05:57 ERROR (MainThread) [custom_components.hacs] pinkywafer/Anniversaries - GitHub Ratelimit error
2021-02-22 19:05:58 ERROR (MainThread) [custom_components.hacs] pinkywafer/Calendarific - GitHub Ratelimit error
2021-02-22 19:05:58 ERROR (MainThread) [custom_components.hacs] PiotrMachowski/Home-Assistant-custom-components-Antistorm - GitHub Ratelimit error
2021-02-22 19:05:58 ERROR (MainThread) [custom_components.hacs] PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net - GitHub Ratelimit error
2021-02-22 19:05:59 ERROR (MainThread) [custom_components.hacs] PiotrMachowski/Home-Assistant-custom-components-Google-Keep - GitHub Ratelimit error
2021-02-22 19:05:59 ERROR (MainThread) [custom_components.hacs] PiotrMachowski/Home-Assistant-custom-components-iMPK - GitHub Ratelimit error
2021-02-22 19:06:01 ERROR (MainThread) [custom_components.hacs] PiotrMachowski/Home-Assistant-custom-components-Looko2 - GitHub Ratelimit error
2021-02-22 19:06:01 ERROR (MainThread) [custom_components.hacs] PiotrMachowski/Home-Assistant-custom-components-Rozkladzik - GitHub Ratelimit error
2021-02-22 19:06:01 ERROR (MainThread) [custom_components.hacs] PiotrMachowski/Home-Assistant-custom-components-Saver - GitHub Ratelimit error
2021-02-22 19:06:01 ERROR (MainThread) [custom_components.hacs] PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus - GitHub Ratelimit error
2021-02-22 19:06:01 ERROR (MainThread) [custom_components.hacs] pippyn/Home-Assistant-Sensor-Afvalbeheer - GitHub Ratelimit error
2021-02-22 19:06:01 ERROR (MainThread) [custom_components.hacs] pippyn/Home-Assistant-Sensor-Groningen-Afvalwijzer - GitHub Ratelimit error
2021-02-22 19:06:01 ERROR (MainThread) [custom_components.hacs] Poeschl/Remote-PicoTTS - GitHub Ratelimit error
2021-02-22 19:06:02 ERROR (MainThread) [custom_components.hacs] postlund/dlink_hnap - GitHub Ratelimit error
2021-02-22 19:06:02 ERROR (MainThread) [custom_components.hacs] Pouzor/freebox_player - GitHub Ratelimit error
2021-02-22 19:06:03 ERROR (MainThread) [custom_components.hacs] ppanagiotis/pymusiccast - GitHub Ratelimit error
2021-02-22 19:06:03 ERROR (MainThread) [custom_components.hacs] prairiesnpr/hass-tdameritrade - GitHub Ratelimit error
2021-02-22 19:06:03 ERROR (MainThread) [custom_components.hacs] ptimatth/GeorideHA - GitHub Ratelimit error
2021-02-22 19:06:03 ERROR (MainThread) [custom_components.hacs] PTST/O365-HomeAssistant - GitHub Ratelimit error
2021-02-22 19:06:04 ERROR (MainThread) [custom_components.hacs] py-smart-gardena/hass-gardena-smart-system - GitHub Ratelimit error
2021-02-22 19:06:05 ERROR (MainThread) [custom_components.hacs] Pyhive/HA-Hive-Custom-Component - GitHub Ratelimit error
2021-02-22 19:06:06 ERROR (MainThread) [custom_components.hacs] r-renato/ha-climacell-weather - GitHub Ratelimit error
2021-02-22 19:06:06 ERROR (MainThread) [custom_components.hacs] raman325/ha-zoom-automation - GitHub Ratelimit error
2021-02-22 19:06:06 ERROR (MainThread) [custom_components.hacs] rccoleman/lamarzocco - GitHub Ratelimit error
2021-02-22 19:06:06 ERROR (MainThread) [custom_components.hacs] rdehuyss/homeassistant-custom_components-denkovi - GitHub Ratelimit error
2021-02-22 19:06:06 ERROR (MainThread) [custom_components.hacs] reharmsen/hass-youless-component - GitHub Ratelimit error
2021-02-22 19:06:06 ERROR (MainThread) [custom_components.hacs] remco770/garbage-bar-homeassistant - GitHub Ratelimit error
2021-02-22 19:06:07 ERROR (MainThread) [custom_components.hacs] ReneNulschDE/mbapi2020 - GitHub Ratelimit error
2021-02-22 19:06:07 ERROR (MainThread) [custom_components.hacs] rgc99/irrigation_unlimited - GitHub Ratelimit error
2021-02-22 19:06:08 ERROR (MainThread) [custom_components.hacs] rgruebel/ha_zigbee2mqtt_networkmap - GitHub Ratelimit error
2021-02-22 19:06:08 ERROR (MainThread) [custom_components.hacs] rj175/home-assistant-aws-codepipeline - GitHub Ratelimit error
2021-02-22 19:06:08 ERROR (MainThread) [custom_components.hacs] rkoebrugge/hacs-youless-component - GitHub Ratelimit error
2021-02-22 19:06:09 ERROR (MainThread) [custom_components.hacs] rob196/home-assistant-fxmarketapi - GitHub Ratelimit error
2021-02-22 19:06:09 ERROR (MainThread) [custom_components.hacs] robbinjanssen/home-assistant-omnik-inverter - GitHub Ratelimit error
2021-02-22 19:06:09 ERROR (MainThread) [custom_components.hacs] roberodin/ha-samsungtv-custom - GitHub Ratelimit error
2021-02-22 19:06:10 ERROR (MainThread) [custom_components.hacs] RobHofmann/HomeAssistant-GreeClimateComponent - GitHub Ratelimit error
2021-02-22 19:06:11 ERROR (MainThread) [custom_components.hacs] RobHofmann/HomeAssistant-PhilipsAndroid2014 - GitHub Ratelimit error
2021-02-22 19:06:11 ERROR (MainThread) [custom_components.hacs] robinostlund/homeassistant-volkswagencarnet - GitHub Ratelimit error
2021-02-22 19:06:11 ERROR (MainThread) [custom_components.hacs] robmarkcole/HASS-amazon-rekognition - GitHub Ratelimit error
2021-02-22 19:06:11 ERROR (MainThread) [custom_components.hacs] robmarkcole/HASS-Deepstack-face - GitHub Ratelimit error
2021-02-22 19:06:11 ERROR (MainThread) [custom_components.hacs] robmarkcole/HASS-Deepstack-object - GitHub Ratelimit error
2021-02-22 19:06:12 ERROR (MainThread) [custom_components.hacs] robmarkcole/HASS-Machinebox-Classificationbox - GitHub Ratelimit error
2021-02-22 19:06:12 ERROR (MainThread) [custom_components.hacs] robmarkcole/Hue-sensors-HASS - GitHub Ratelimit error
2021-02-22 19:06:12 ERROR (MainThread) [custom_components.hacs] rospogrigio/localtuya - GitHub Ratelimit error
2021-02-22 19:06:13 ERROR (MainThread) [custom_components.hacs] rsnodgrass/hass-adtpulse - GitHub Ratelimit error
2021-02-22 19:06:13 ERROR (MainThread) [custom_components.hacs] rsnodgrass/hass-flo-water - GitHub Ratelimit error
2021-02-22 19:06:13 ERROR (MainThread) [custom_components.hacs] rsnodgrass/hass-integrations - GitHub Ratelimit error
2021-02-22 19:06:14 ERROR (MainThread) [custom_components.hacs] rsnodgrass/hass-lunos - GitHub Ratelimit error
2021-02-22 19:06:14 ERROR (MainThread) [custom_components.hacs] rsnodgrass/hass-poolmath - GitHub Ratelimit error
2021-02-22 19:06:14 ERROR (MainThread) [custom_components.hacs] rsnodgrass/hass-sensorpush - GitHub Ratelimit error
2021-02-22 19:06:15 ERROR (MainThread) [custom_components.hacs] rsnodgrass/hass-xantech - GitHub Ratelimit error
2021-02-22 19:06:16 ERROR (MainThread) [custom_components.hacs] rt400/ReversoTTS-HA - GitHub Ratelimit error
2021-02-22 19:06:16 ERROR (MainThread) [custom_components.hacs] rt400/School-Vacation - GitHub Ratelimit error
2021-02-22 19:06:16 ERROR (MainThread) [custom_components.hacs] ryanmac8/HA-Mint-Mobile - GitHub Ratelimit error
2021-02-22 19:06:16 ERROR (MainThread) [custom_components.hacs] ryanmac8/Home-Assistant-Marta - GitHub Ratelimit error
2021-02-22 19:06:17 ERROR (MainThread) [custom_components.hacs] ryannazaretian/hacs-nexia-climate-integration - GitHub Ratelimit error
2021-02-22 19:06:17 ERROR (MainThread) [custom_components.hacs] safepay/cover.hd_powerview - GitHub Ratelimit error
2021-02-22 19:06:17 ERROR (MainThread) [custom_components.hacs] safepay/sensor.fronius - GitHub Ratelimit error
2021-02-22 19:06:18 ERROR (MainThread) [custom_components.hacs] safepay/sensor.willyweather - GitHub Ratelimit error
2021-02-22 19:06:18 ERROR (MainThread) [custom_components.hacs] sbabcock23/hass-tryfi - GitHub Ratelimit error
2021-02-22 19:06:18 ERROR (MainThread) [custom_components.hacs] scottyphillips/mitsubishi_hass - GitHub Ratelimit error
2021-02-22 19:06:18 ERROR (MainThread) [custom_components.hacs] sebr/bhyve-home-assistant - GitHub Ratelimit error
2021-02-22 19:06:19 ERROR (MainThread) [custom_components.hacs] SebuZet/samsungrac - GitHub Ratelimit error
2021-02-22 19:06:19 ERROR (MainThread) [custom_components.hacs] Sennevds/media_player.template - GitHub Ratelimit error
2021-02-22 19:06:19 ERROR (MainThread) [custom_components.hacs] sermayoral/ha-samsungtv-encrypted - GitHub Ratelimit error
2021-02-22 19:06:20 ERROR (MainThread) [custom_components.hacs] shbatm/hacs-isy994 - GitHub Ratelimit error
2021-02-22 19:06:21 ERROR (MainThread) [custom_components.hacs] shogunxam/Home-Assistant-custom-components-cfr-toscana - GitHub Ratelimit error
2021-02-22 19:06:22 ERROR (MainThread) [custom_components.hacs] Sholofly/ZiggoNext - GitHub Ratelimit error
2021-02-22 19:06:22 ERROR (MainThread) [custom_components.hacs] shutupflanders/sensor.moneydashboard - GitHub Ratelimit error
2021-02-22 19:06:22 ERROR (MainThread) [custom_components.hacs] slesinger/HomeAssistant-BMR - GitHub Ratelimit error
2021-02-22 19:06:22 ERROR (MainThread) [custom_components.hacs] slesinger/HomeAssistant-PREdistribuce - GitHub Ratelimit error
2021-02-22 19:06:22 ERROR (MainThread) [custom_components.hacs] SLG/home-assistant-whatpulse - GitHub Ratelimit error
2021-02-22 19:06:22 ERROR (MainThread) [custom_components.hacs] snarky-snark/home-assistant-variables - GitHub Ratelimit error
2021-02-22 19:06:23 ERROR (MainThread) [custom_components.hacs] snicker/zwift_hass - GitHub Ratelimit error
2021-02-22 19:06:23 ERROR (MainThread) [custom_components.hacs] sockless-coding/garo_wallbox - GitHub Ratelimit error
2021-02-22 19:06:23 ERROR (MainThread) [custom_components.hacs] sockless-coding/panasonic_cc - GitHub Ratelimit error
2021-02-22 19:06:23 ERROR (MainThread) [custom_components.hacs] StyraHem/ShellyForHASS - GitHub Ratelimit error
2021-02-22 19:06:24 ERROR (MainThread) [custom_components.hacs] swartjean/ha-eskom-loadshedding - GitHub Ratelimit error
2021-02-22 19:06:24 ERROR (MainThread) [custom_components.hacs] swartjean/ha-seedboxes-cc - GitHub Ratelimit error
2021-02-22 19:06:25 ERROR (MainThread) [custom_components.hacs] syssi/nextbike - GitHub Ratelimit error
2021-02-22 19:06:25 ERROR (MainThread) [custom_components.hacs] syssi/philipslight - GitHub Ratelimit error
2021-02-22 19:06:26 ERROR (MainThread) [custom_components.hacs] syssi/xiaomi_airconditioningcompanion - GitHub Ratelimit error
2021-02-22 19:06:27 ERROR (MainThread) [custom_components.hacs] syssi/xiaomi_raw - GitHub Ratelimit error
2021-02-22 19:06:27 ERROR (MainThread) [custom_components.hacs] syssi/xiaomi_airpurifier - GitHub Ratelimit error
2021-02-22 19:06:27 ERROR (MainThread) [custom_components.hacs] syssi/xiaomiplug - GitHub Ratelimit error
2021-02-22 19:06:27 ERROR (MainThread) [custom_components.hacs] tefinger/hass-brematic - GitHub Ratelimit error
2021-02-22 19:06:27 ERROR (MainThread) [custom_components.hacs] TekniskSupport/home-assistant-resrobot - GitHub Ratelimit error
2021-02-22 19:06:27 ERROR (MainThread) [custom_components.hacs] tellerbop/havistapool - GitHub Ratelimit error
2021-02-22 19:06:28 ERROR (MainThread) [custom_components.hacs] tetienne/veolia-custom-component - GitHub Ratelimit error
2021-02-22 19:06:28 ERROR (MainThread) [custom_components.hacs] thebino/rki_covid - GitHub Ratelimit error
2021-02-22 19:06:28 ERROR (MainThread) [custom_components.hacs] ThermIQ/thermiq_mqtt-ha - GitHub Ratelimit error
2021-02-22 19:06:29 ERROR (MainThread) [custom_components.hacs] thevoltagesource/LennoxiComfort - GitHub Ratelimit error
2021-02-22 19:06:29 ERROR (MainThread) [custom_components.hacs] Thomas55555/husqvarna_automower - GitHub Ratelimit error
2021-02-22 19:06:30 ERROR (MainThread) [custom_components.hacs] thomasloven/hass-browser_mod - GitHub Ratelimit error
2021-02-22 19:06:30 ERROR (MainThread) [custom_components.hacs] thomasloven/hass-favicon - GitHub Ratelimit error
2021-02-22 19:06:30 ERROR (MainThread) [custom_components.hacs] thomasloven/hass-fontawesome - GitHub Ratelimit error
2021-02-22 19:06:32 ERROR (MainThread) [custom_components.hacs] thomasloven/hass-lovelace_gen - GitHub Ratelimit error
2021-02-22 19:06:32 ERROR (MainThread) [custom_components.hacs] TimSoethout/goodwe-sems-home-assistant - GitHub Ratelimit error
2021-02-22 19:06:32 ERROR (MainThread) [custom_components.hacs] tikismoke/home-assistant-plcbus - GitHub Ratelimit error
2021-02-22 19:06:32 ERROR (MainThread) [custom_components.hacs] tikismoke/home-assistant-nespressoble - GitHub Ratelimit error
2021-02-22 19:06:32 ERROR (MainThread) [custom_components.hacs] timvancann/homeassistant-growatt - GitHub Ratelimit error
2021-02-22 19:06:32 ERROR (MainThread) [custom_components.hacs] tmechen/ber_status - GitHub Ratelimit error
2021-02-22 19:06:33 ERROR (MainThread) [custom_components.hacs] tmonck/clean_up_snapshots - GitHub Ratelimit error
2021-02-22 19:06:33 ERROR (MainThread) [custom_components.hacs] tomaae/homeassistant-mikrotik_router - GitHub Ratelimit error
2021-02-22 19:06:34 ERROR (MainThread) [custom_components.hacs] tomaae/homeassistant-openmediavault - GitHub Ratelimit error
2021-02-22 19:06:34 ERROR (MainThread) [custom_components.hacs] tomasbedrich/home-assistant-skydance - GitHub Ratelimit error
2021-02-22 19:06:34 ERROR (MainThread) [custom_components.hacs] toreamun/amshan-homeassistant - GitHub Ratelimit error
2021-02-22 19:06:34 ERROR (MainThread) [custom_components.hacs] toreamun/victorsmartkill-homeassistant - GitHub Ratelimit error
2021-02-22 19:06:35 ERROR (MainThread) [custom_components.hacs] troykelly/hacs-amberelectric - GitHub Ratelimit error
2021-02-22 19:06:35 ERROR (MainThread) [custom_components.hacs] troykelly/hacs-trackimo - GitHub Ratelimit error
2021-02-22 19:06:36 ERROR (MainThread) [custom_components.hacs] tschamm/boschshc-hass - GitHub Ratelimit error
2021-02-22 19:06:37 ERROR (MainThread) [custom_components.hacs] turbokongen/hass-AMS - GitHub Ratelimit error
2021-02-22 19:06:37 ERROR (MainThread) [custom_components.hacs] turbulator/pandora-cas - GitHub Ratelimit error
2021-02-22 19:06:37 ERROR (MainThread) [custom_components.hacs] tuxuser/abfallapi_regioit_ha - GitHub Ratelimit error
2021-02-22 19:06:37 ERROR (MainThread) [custom_components.hacs] tuxuser/abfallapi_jumomind_ha - GitHub Ratelimit error
2021-02-22 19:06:37 ERROR (MainThread) [custom_components.hacs] twrecked/hass-aarlo - GitHub Ratelimit error
2021-02-22 19:06:38 ERROR (MainThread) [custom_components.hacs] twrecked/hass-momentary - GitHub Ratelimit error
2021-02-22 19:06:38 ERROR (MainThread) [custom_components.hacs] twrecked/hass-virtual - GitHub Ratelimit error
2021-02-22 19:06:38 ERROR (MainThread) [custom_components.hacs] tybritten/ical-sensor-homeassistant - GitHub Ratelimit error
2021-02-22 19:06:39 ERROR (MainThread) [custom_components.hacs] ualex73/monitor_docker - GitHub Ratelimit error
2021-02-22 19:06:39 ERROR (MainThread) [custom_components.hacs] uvjustin/alarmdotcom - GitHub Ratelimit error
2021-02-22 19:06:39 ERROR (MainThread) [custom_components.hacs] vanstinator/hass-raincloud - GitHub Ratelimit error
2021-02-22 19:06:40 ERROR (MainThread) [custom_components.hacs] Verbalinsurection/next_rocket_launch - GitHub Ratelimit error
2021-02-22 19:06:40 ERROR (MainThread) [custom_components.hacs] vigonotion/hass-simpleicons - GitHub Ratelimit error
2021-02-22 19:06:40 ERROR (MainThread) [custom_components.hacs] vinteo/hass-opensprinkler - GitHub Ratelimit error
2021-02-22 19:06:41 ERROR (MainThread) [custom_components.hacs] vlumikero/home-assistant-securitas - GitHub Ratelimit error
2021-02-22 19:06:42 ERROR (MainThread) [custom_components.hacs] walthowd/ha-automower - GitHub Ratelimit error
2021-02-22 19:06:42 ERROR (MainThread) [custom_components.hacs] willholdoway/hifiberry - GitHub Ratelimit error
2021-02-22 19:06:42 ERROR (MainThread) [custom_components.hacs] websylv/homeassistant-meteoswiss - GitHub Ratelimit error
2021-02-22 19:06:42 ERROR (MainThread) [custom_components.hacs] xlcnd/meteoalarmeu - GitHub Ratelimit error
2021-02-22 19:06:42 ERROR (MainThread) [custom_components.hacs] xirixiz/homeassistant-afvalwijzer - GitHub Ratelimit error
2021-02-22 19:06:43 ERROR (MainThread) [custom_components.hacs] xMrVizzy/Minecraft-Version - GitHub Ratelimit error
2021-02-22 19:06:43 ERROR (MainThread) [custom_components.hacs] xMrVizzy/Philips-AirPurifier - GitHub Ratelimit error
2021-02-22 19:06:44 ERROR (MainThread) [custom_components.hacs] xraver/mercedes_me_api - GitHub Ratelimit error
2021-02-22 19:06:44 ERROR (MainThread) [custom_components.hacs] youdroid/home-assistant-couchpotato - GitHub Ratelimit error
2021-02-22 19:06:44 ERROR (MainThread) [custom_components.hacs] youdroid/home-assistant-gitea - GitHub Ratelimit error
2021-02-22 19:06:44 ERROR (MainThread) [custom_components.hacs] youdroid/home-assistant-sickchill - GitHub Ratelimit error
2021-02-22 19:06:45 ERROR (MainThread) [custom_components.hacs] zachowj/hass-node-red - GitHub Ratelimit error
2021-02-22 19:06:45 ERROR (MainThread) [custom_components.hacs] zha-ng/zha-map - GitHub Ratelimit error
2021-02-22 19:06:45 ERROR (MainThread) [custom_components.hacs] zigul/HomeAssistant-CEZdistribuce - GitHub Ratelimit error
2021-02-22 19:06:46 ERROR (MainThread) [custom_components.hacs] hacs/integration - GitHub Ratelimit error
2021-02-22 19:07:31 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:07:31 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:07:31 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
2021-02-22 19:07:54 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:07:54 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:07:54 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
2021-02-22 19:08:04 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:08:04 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:08:05 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
2021-02-22 19:14:45 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:14:45 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:14:45 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
2021-02-22 19:14:52 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:14:52 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:14:52 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
2021-02-22 19:15:00 ERROR (MainThread) [custom_components.hacs] <Integration custom-components/alexa_media_player> GitHub Ratelimit error
2021-02-22 19:15:00 ERROR (MainThread) [custom_components.hacs] <Integration custom-components/alexa_media_player> GitHub Ratelimit error
2021-02-22 19:15:00 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
2021-02-22 19:16:25 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:16:26 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:16:26 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
2021-02-22 19:23:49 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:23:50 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:23:50 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
2021-02-22 19:31:53 ERROR (MainThread) [custom_components.hacs] <Integration hacs/integration> GitHub Ratelimit error
2021-02-22 19:31:53 ERROR (MainThread) [custom_components.hacs] hacs/integration - GitHub Ratelimit error
2021-02-22 19:31:55 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.REMOVED
2021-02-22 19:31:55 ERROR (MainThread) [custom_components.hacs] HACS is ratelimited, HACS will resume setup when the limit is cleared (19:57:57)
2021-02-22 19:31:55 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.RATE_LIMIT
2021-02-22 19:31:55 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/operational/reload.py", line 10, in async_reload_entry
    await async_setup_entry(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 68, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 97, in async_startup_wrapper_for_config_entry
    raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady
2021-02-22 19:32:31 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:32:32 ERROR (MainThread) [custom_components.hacs] <Integration AlexxIT/SonoffLAN> GitHub Ratelimit error
2021-02-22 19:32:32 ERROR (MainThread) [custom_components.hacs] GitHub Ratelimit error
```

</details>

Thank you!

**Comment by ludeeus** [comment]
Your installation has not completed the initial setup, this can take over 1h, until that is done it's partially broken and/or missing information.
https://hacs.xyz/docs/faq/initial_startup

**Comment by denisix** [comment]
1. is it possible to skip such a big timeout of waiting of installation, i have exact URL of repository of integration that i want to install.
2. is it possible not to use github api or switch to offline / manual mode?
3. what if someone doesnt have internet access (but have offline files) while trying to install some integration or HACS?

**Comment by ludeeus** [comment]
1) the timeout is added by github, nothing I can do about that.
2) You cant use HACS without internet <https://hacs.xyz/docs/installation/prerequisites>
3) see 2

**Comment by denisix** [comment]
1. can we skip using github in some cases (expert mode)?

**Comment by ludeeus** [comment]
no, HACS uses github for _everything_

**Comment by denisix** [comment]
okay, thank you for all the information and time spent for my replies :) will try to finish my hack installation tomorrow :) have a good day!
