### ISSUE TITLE
dckiller51/bodymiscale

### ISSUE THREAD

**Issue by pedroct** [hacs/integration#1993]
After doing the installation using the repository documentation, I restarted and this error message appeared in the HA logs:

Logger: homeassistant.setup
Source: custom_components/bodymiscale/__init__.py:280
First occurred: 12:16:14 (1 occurrences)
Last logged: 12:16:14

Error during setup of component bodymiscale
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/bodymiscale/__init__.py", line 114, in async_setup
    await component.async_add_entities(entities)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/bodymiscale/__init__.py", line 280, in state_attributes
    ATTR_WEIGHT: "{:.2f}".format(weight),
TypeError: unsupported format string passed to NoneType.__format__

`bodymiscale: !include components/bodymiscale.yaml`

My file: /config/components/bodymiscale.yaml
```
aurelien:
  sensors:
    weight: sensor.weight_aurelien
    impedance: sensor.impedance_aurelien
  height: 183
  born: "1978-02-08"
  gender: "male"
#  model_miscale: "181B"
```

**Comment by ludeeus** [comment]
and why should it be removed from HACS?

**Comment by pedroct** [comment]
> and why should it be removed from HACS?

I don't want to remove it from HACS, I just want it to work properly.

**Comment by ludeeus** [comment]
Then open issue in dckiller51/bodymiscale :+1:
