### ISSUE TITLE
Missing iot_class attribute results in wrong error message.

### ISSUE THREAD

**Issue by FeikoJoosten** [hacs/integration#2002]
## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.99
arch | x86_64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4901
Installed Version | 1.11.3
Stage | running
Available Repositories | 844
Installed Repositories | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 251.3 GB
disk_used | 13.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | FTP (4.0.2), File editor (5.2.0), Glances (0.11.2), Home Assistant Google Drive Backup (0.103.1), Internet Automated Dynamic DNS Client (0.1.11), MariaDB (2.2.2), Mosquitto broker (5.1.1), Nginx Proxy Manager (0.10.1), Node-RED (8.2.1), Portainer (1.4.0), RPC Shutdown (2.2), Ring Devices (4.5.2), SSH & Web Terminal (8.1.0), TasmoAdmin (0.14.0), Visual Studio Code (3.3.0), Samba share (9.3.1), Bitwarden RS (0.9.0), motionEye (0.11.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 17
views | 5
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

## Checklist

- [x ] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [x ] I have enabled debug logging for my installation.
- [x ] I have filled out the issue template to the best of my ability.
- [x ] I have read <https://hacs.xyz/docs/issues>
- [x ] This issue is related to the backend of HACS.
- [x ] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

## Describe the issue

A clear and concise description of what the issue is.
If you try to add an integration that is missing the iot_class attribute in it's `hacs.json` file. HACS will then complain about it not being able to find a `manifest.json`. Instead it should inform you that the `hacs.json` is not properly implemented.

### Steps to reproduce

1. Add this repro to your custom reporsitories: https://github.com/chomupashchuk/delete-file-home-assistant
2. Install version 1.6
3. Notice check your logs and notice that it informs you about a missing manifest.json file.
4. Install version 1.7
5. Notice it now successfully installs.

The only difference between v1.6 and v1.7 is the addition of the `iot_class` attribute.

## Debug logs

<details>
  <summary>Logs</summary>

```

2021-04-02 20:10:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-02 20:10:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration yahoofinance which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-02 20:10:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-02 20:10:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration delete which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-02 20:10:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-02 20:10:59 WARNING (MainThread) [homeassistant.loader] You are using a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-02 20:11:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration afvalbeheer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-02 20:11:01 WARNING (MainThread) [homeassistant.loader] You are using a custom integration prosenic which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-04-02 20:11:04 DEBUG (MainThread) [custom_components.hacs] Configuration type: flow
2021-04-02 20:11:04 INFO (MainThread) [custom_components.hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)
Version: 1.11.3
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------
2021-04-02 20:11:04 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2021-04-02 20:11:04 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2021-04-02 20:11:04 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
2021-04-02 20:11:04 ERROR (MainThread) [homeassistant.components.calendar] google: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
await task
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/google/calendar.py", line 103, in update
self.data.update()
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 285, in wrapper
result = method(*args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/google/calendar.py", line 172, in update
result = events.list(**params).execute()
File "/usr/local/lib/python3.8/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
return wrapped(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/googleapiclient/http.py", line 842, in execute
raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/feiko%40vertigo-games.com/events?orderBy=startTime&maxResults=5&singleEvents=true&timeMin=2021-04-02T20%3A11%3A04.831029%2B02%3A00&alt=json returned "Not Found">
2021-04-02 20:11:05 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-04-02 20:11:05 DEBUG (MainThread) [custom_components.hacs] Can update 248 repositories
2021-04-02 20:11:05 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
2021-04-02 20:11:05 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Checking repository.
2021-04-02 20:11:05 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.11.3
2021-04-02 20:11:06 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> All (0) checks passed
2021-04-02 20:11:06 INFO (MainThread) [custom_components.hacs] <Integration hacs/integration> Registration completed
2021-04-02 20:11:06 INFO (MainThread) [custom_components.hacs] Restore started
2021-04-02 20:11:06 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-04-02 20:11:06 DEBUG (MainThread) [queueman.manager] Starting queue execution for 844 tasks
2021-04-02 20:11:06 DEBUG (MainThread) [queueman.manager] Queue execution finished for 844 tasks finished in 0.27 seconds
2021-04-02 20:11:06 INFO (MainThread) [custom_components.hacs] Restore done
2021-04-02 20:11:06 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.SENSOR
2021-04-02 20:11:06 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2021-04-02 20:11:06 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2021-04-02 20:11:06 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-04-02 20:11:11 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2021-04-02 20:11:11 INFO (MainThread) [custom_components.hacs] setup task HacsSetupTask.CATEGORIES
2021-04-02 20:11:11 DEBUG (SyncWorker_1) [custom_components.hacs] Starting setup task: Extra stores
2021-04-02 20:11:11 DEBUG (SyncWorker_1) [custom_components.hacs] Enable category: HacsCategory.INTEGRATION
2021-04-02 20:11:11 DEBUG (SyncWorker_1) [custom_components.hacs] Enable category: HacsCategory.PLUGIN
2021-04-02 20:11:11 DEBUG (SyncWorker_1) [custom_components.hacs] Enable category: HacsCategory.THEME
2021-04-02 20:11:11 DEBUG (SyncWorker_1) [custom_components.hacs] Enable category: HacsCategory.APPDAEMON
2021-04-02 20:11:11 DEBUG (SyncWorker_1) [custom_components.hacs] Enable category: HacsCategory.NETDAEMON
2021-04-02 20:11:11 DEBUG (MainThread) [queueman.manager] The queue is empty
2021-04-02 20:11:11 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.critical'. Content did not change
2021-04-02 20:11:11 INFO (MainThread) [custom_components.hacs] Loading known repositories
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] Got 98 elements for HacsCategory.REMOVED
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] Can update 247 repositories, items in queue 5
2021-04-02 20:11:12 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-04-02 20:11:12 DEBUG (MainThread) [queueman.manager] Starting queue execution for 5 tasks
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] Got 62 elements for HacsCategory.THEME
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] Got 214 elements for HacsCategory.PLUGIN
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] Got 63 elements for HacsCategory.APPDAEMON
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] Got 3 elements for HacsCategory.NETDAEMON
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] Got 505 elements for HacsCategory.INTEGRATION
2021-04-02 20:11:12 DEBUG (MainThread) [queueman.manager] Queue execution finished for 5 tasks finished in 0.39 seconds
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] Starting recurring background task for installed repositories
2021-04-02 20:11:12 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-04-02 20:11:12 DEBUG (MainThread) [queueman.manager] Starting queue execution for 28 tasks
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Plugin PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/bar-card> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-layout-card> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Integration zachowj/hass-node-red> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/spotify-card> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Plugin mattieha/select-list-card> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Theme basnijholt/lovelace-ios-themes> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Integration snarky-snark/home-assistant-variables> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Integration FeikoJoosten/yahoofinance> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-state-switch> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Integration FeikoJoosten/ha-prosenic> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/config-template-card> Getting repository information
2021-04-02 20:11:12 DEBUG (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Getting repository information
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Plugin PiotrMachowski/Home-Assistant-Lovelace-Local-Conditional-card> Running checks against v1.1.1
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-layout-card> Running checks against 2.2.3
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Running checks against 0.0.16
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.11.3
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Integration zachowj/hass-node-red> Running checks against v0.4.5
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Plugin mattieha/select-list-card> Running checks against v1.2.0
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/spotify-card> Running checks against v2.3.7
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-state-switch> Running checks against 8
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/config-template-card> Running checks against 1.3.0
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Theme basnijholt/lovelace-ios-themes> Running checks against v2.5.0
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Integration fondberg/spotcast> Running checks against v3.4.7
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/bar-card> Running checks against 3.2.0
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Integration FeikoJoosten/yahoofinance> Running checks against master
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Integration FeikoJoosten/ha-prosenic> Running checks against v0.5.3
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] <Integration snarky-snark/home-assistant-variables> Running checks against v0.11.0
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] 'state_attr' is undefined
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] 'state' is undefined
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] 'is_state' is undefined
2021-04-02 20:11:13 DEBUG (MainThread) [custom_components.hacs] 'config' is undefined
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin maykar/lovelace-swipe-navigation> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-xiaomi-vacuum-card> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-template-entity-row> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Integration rospogrigio/localtuya> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/simple-weather-card> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin denysdovhan/vacuum-card> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin jcwillox/lovelace-paper-buttons-row> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Integration danobot/entity-controller> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Integration pippyn/Home-Assistant-Sensor-Afvalbeheer> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-card-mod> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin artem-sedykh/mini-climate-card> Getting repository information
2021-04-02 20:11:18 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Getting repository information
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Getting repository information
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin maykar/lovelace-swipe-navigation> Running checks against 1.3.5
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-template-entity-row> Running checks against 1.1.1
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-xiaomi-vacuum-card> Running checks against v4.2.0
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin jcwillox/lovelace-paper-buttons-row> Running checks against 0.5.0
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Integration danobot/entity-controller> Running checks against v9.2.1
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Integration rospogrigio/localtuya> Running checks against v3.2.2
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/simple-weather-card> Running checks against v0.8.1
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Integration pippyn/Home-Assistant-Sensor-Afvalbeheer> Running checks against v4.7.19
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin denysdovhan/vacuum-card> Running checks against v1.19.0
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-card-mod> Running checks against 3.0.12
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin artem-sedykh/mini-climate-card> Running checks against v1.2.7
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Running checks against v1.0.2
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Running checks against 1.7
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] 'states' is undefined
2021-04-02 20:11:19 DEBUG (MainThread) [custom_components.hacs] 'states' is undefined
2021-04-02 20:11:25 DEBUG (MainThread) [queueman.manager] Queue execution finished for 28 tasks finished in 12.18 seconds
2021-04-02 20:11:25 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.critical'. Content did not change
2021-04-02 20:11:25 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-04-02 20:11:25 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-04-02 20:11:25 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-04-02 20:11:25 DEBUG (MainThread) [queueman.manager] Starting queue execution for 844 tasks
2021-04-02 20:11:25 DEBUG (MainThread) [queueman.manager] Queue execution finished for 844 tasks finished in 0.03 seconds
2021-04-02 20:11:25 DEBUG (MainThread) [custom_components.hacs] Recurring background task for installed repositories done
2021-04-02 20:11:25 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2021-04-02 20:11:25 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2021-04-02 20:12:46 DEBUG (MainThread) [custom_components.hacs] Running release_notes for pippyn/Home-Assistant-Sensor-Afvalbeheer
2021-04-02 20:12:46 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-04-02 20:12:46 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-04-02 20:12:46 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-04-02 20:12:46 DEBUG (MainThread) [queueman.manager] Starting queue execution for 844 tasks
2021-04-02 20:12:46 DEBUG (MainThread) [queueman.manager] Queue execution finished for 844 tasks finished in 0.03 seconds
2021-04-02 20:12:46 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.repositories'. Content did not change
2021-04-02 20:12:58 DEBUG (MainThread) [custom_components.hacs] Running update for chomupashchuk/delete-file-home-assistant
2021-04-02 20:12:58 DEBUG (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Getting repository information
2021-04-02 20:12:58 DEBUG (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Running checks against 1.7
2021-04-02 20:12:59 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-04-02 20:12:59 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-04-02 20:12:59 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-04-02 20:12:59 DEBUG (MainThread) [queueman.manager] Starting queue execution for 844 tasks
2021-04-02 20:12:59 DEBUG (MainThread) [queueman.manager] Queue execution finished for 844 tasks finished in 0.03 seconds
2021-04-02 20:12:59 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.repositories'. Content did not change
2021-04-02 20:13:02 DEBUG (MainThread) [custom_components.hacs] Running install for chomupashchuk/delete-file-home-assistant
2021-04-02 20:13:02 DEBUG (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Getting repository information
2021-04-02 20:13:02 DEBUG (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Running checks against 1.6
2021-04-02 20:13:03 ERROR (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> No file found 'manifest.json'
2021-04-02 20:13:03 INFO (MainThread) [custom_components.hacs] Running pre installation steps
2021-04-02 20:13:03 INFO (MainThread) [custom_components.hacs] Pre installation steps completed
2021-04-02 20:13:03 INFO (MainThread) [custom_components.hacs] Running installation steps
2021-04-02 20:13:03 DEBUG (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Getting repository information
2021-04-02 20:13:03 DEBUG (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Running checks against 1.6
2021-04-02 20:13:04 ERROR (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> No file found 'manifest.json'
2021-04-02 20:13:04 DEBUG (SyncWorker_6) [custom_components.hacs] Backup for /config/custom_components/delete, created in /tmp/hacs_backup/delete
2021-04-02 20:13:04 INFO (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> ref: tags/1.6 --- tag: 1.7.
2021-04-02 20:13:04 INFO (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> ref: tags/1.6 --- tag: 1.6.
2021-04-02 20:13:04 INFO (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> ref: tags/1.6 --- tag: 1.5.
2021-04-02 20:13:04 INFO (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> ref: tags/1.6 --- tag: 1.4.
2021-04-02 20:13:04 INFO (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> ref: tags/1.6 --- tag: 1.3.1.
2021-04-02 20:13:04 DEBUG (SyncWorker_10) [custom_components.hacs] Backup dir /tmp/hacs_backup/ cleared
2021-04-02 20:13:04 INFO (MainThread) [custom_components.hacs] Installation steps completed
2021-04-02 20:13:04 INFO (MainThread) [custom_components.hacs] Running post installation steps
2021-04-02 20:13:04 INFO (MainThread) [custom_components.hacs] Post installation steps completed
2021-04-02 20:13:04 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-04-02 20:13:04 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-04-02 20:13:04 DEBUG (MainThread) [queueman.manager] Checking out tasks to execute
2021-04-02 20:13:04 DEBUG (MainThread) [queueman.manager] Starting queue execution for 844 tasks
2021-04-02 20:13:04 DEBUG (MainThread) [queueman.manager] Queue execution finished for 844 tasks finished in 0.07 seconds

```

</details>

**Comment by ludeeus** [comment]
1.6 has <https://github.com/chomupashchuk/delete-file-home-assistant/blob/1.6/hacs.json#L3>, with is wrong with that structure.

**Comment by FeikoJoosten** [comment]
Yep, you're entirely right. Thank you!
