### ISSUE TITLE
HACS not running after Lovelace mod multiremote instalation

### ISSUE THREAD

**Issue by trynqz** [hacs/integration#2053]
## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Warsaw

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.15
disk_total | 28.6 GB
disk_used | 15.3 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (5.1.1), Node-RED (9.0.1), File editor (5.3.0), Check Home Assistant configuration (3.7.1), Terminal & SSH (9.1.1), ADB - Android Debug Bridge (0.8.0), CEC Scanner (2.4), Home Assistant Google Drive Backup (0.103.1), Grafana (6.3.3), Samba NAS (9.3.0-nas8), RPC Shutdown (2.2), InfluxDB (4.0.6), Portainer (1.4.0), TasmoAdmin (0.15.0), Transmission NAS (3.00-r2-ls86), Duck DNS (1.12.5), Dnsmasq (1.4.4), Visual Studio Code (3.3.0), Qbittorrent (14.3.4.99202104300534-7354-9f8a6e8fbubuntu20.04.1-ls131)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 14
views | 11
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

HACS stopped working after HA restart.

I was trying to add this mod https://github.com/mcfrojd/hassio_lovelace_multiremote via HACS. Nothing happend, I tried again, I got message that it already exists in HACS. I searched (propably by multiremote). I installed mod for lovelace and restarted HA. After HA restarted HACS stopped working. I got below message, and HACS did not started at all...so do all other mods. Please advice

Logger: homeassistant.setup
Source: setup.py:164
First occurred: 18:45:19 (1 occurrences)
Last logged: 18:45:19

Setup failed for hacs: Unable to import component: cannot import name 'PACKAGE_NAME' from 'custom_components.hacs.const' (/config/custom_components/hacs/const.py)

File const.py exists in above location, I did not changed it.

### Reproduction steps

1. try to add repository mod https://github.com/mcfrojd/hassio_lovelace_multiremote via HACS.
2. try again
3. got message it already axists on list
4. searched on list and added multiremote mod for lovelace
3. restarted HA
4. HACS not started, 
5. looking for help
...

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: 22:38:31 (1 occurrences)
Last logged: 22:38:31

Error occurred loading configuration flow for integration hacs: cannot import name 'PACKAGE_NAME' from 'custom_components.hacs.const' (/config/custom_components/hacs/const.py)



Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/helpers/functions/logger.py:6
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:38:12 (1 occurrences)
Last logged: 22:38:12

[547392779072] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 323, in config_entry_disable
    result = await hass.config_entries.async_set_disabled_by(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 832, in async_set_disabled_by
    reload_result = await self.async_reload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in async_reload
    unload_result = await self.async_unload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 786, in async_unload
    return await entry.async_unload(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 331, in async_unload
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 477, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 23, in <module>
    from custom_components.hacs.constrains import check_constans, check_requirements
  File "/config/custom_components/hacs/constrains.py", line 6, in <module>
    from .helpers.misc import version_left_higher_then_right
  File "/config/custom_components/hacs/helpers/__init__.py", line 2, in <module>
    from custom_components.hacs.helpers.methods import (
  File "/config/custom_components/hacs/helpers/methods/__init__.py", line 2, in <module>
    from custom_components.hacs.helpers.methods.installation import (
  File "/config/custom_components/hacs/helpers/methods/installation.py", line 7, in <module>
    from custom_components.hacs.helpers.functions.download import download_content
  File "/config/custom_components/hacs/helpers/functions/download.py", line 15, in <module>
    from custom_components.hacs.helpers.functions.logger import getLogger
  File "/config/custom_components/hacs/helpers/functions/logger.py", line 6, in <module>
    from ...const import PACKAGE_NAME
ImportError: cannot import name 'PACKAGE_NAME' from 'custom_components.hacs.const' (/config/custom_components/hacs/const.py)
```

**Comment by trynqz** [comment]
I also tried to reinstall HACS, but manage only to remove it. 
Also HA Supervisor tab is not loading

**Comment by ludeeus** [comment]
That repo is not compatible with HACS.
Run the installation script for HACS and restart HA to clean up.

**Comment by trynqz** [comment]
I'm unable to instal lit again. Integrations -> HACS fails with following LOG. Is there a file that I can edit to remove this integration?

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/helpers/functions/logger.py:6
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:38:12 (2 occurrences)
Last logged: 23:08:23

[547392779072] Error handling message: Unknown error
[547645573200] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 18, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 323, in config_entry_disable
    result = await hass.config_entries.async_set_disabled_by(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 832, in async_set_disabled_by
    reload_result = await self.async_reload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in async_reload
    unload_result = await self.async_unload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 786, in async_unload
    return await entry.async_unload(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 331, in async_unload
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 477, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 23, in <module>
    from custom_components.hacs.constrains import check_constans, check_requirements
  File "/config/custom_components/hacs/constrains.py", line 6, in <module>
    from .helpers.misc import version_left_higher_then_right
  File "/config/custom_components/hacs/helpers/__init__.py", line 2, in <module>
    from custom_components.hacs.helpers.methods import (
  File "/config/custom_components/hacs/helpers/methods/__init__.py", line 2, in <module>
    from custom_components.hacs.helpers.methods.installation import (
  File "/config/custom_components/hacs/helpers/methods/installation.py", line 7, in <module>
    from custom_components.hacs.helpers.functions.download import download_content
  File "/config/custom_components/hacs/helpers/functions/download.py", line 15, in <module>
    from custom_components.hacs.helpers.functions.logger import getLogger
  File "/config/custom_components/hacs/helpers/functions/logger.py", line 6, in <module>
    from ...const import PACKAGE_NAME
ImportError: cannot import name 'PACKAGE_NAME' from 'custom_components.hacs.const' (/config/custom_components/hacs/const.py)

**Comment by ludeeus** [comment]
Run the installation script (from the havs website)

**Comment by trynqz** [comment]
thanks, processing
