### ISSUE TITLE
HACS fails after upgrade with error upgrading aiogithubapi to 21.4.0

### ISSUE THREAD

**Issue by Timeteo** [hacs/integration#2068]
## System Health

version | core-2021.4.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | America/Los_Angeles

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 19.03.15
disk_total | 28.6 GB
disk_used | 10.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.1.1), File editor (5.3.0), Node-RED (9.0.1), AppDaemon 4 (0.6.0), Z-Wave JS to MQTT (0.15.0), Duck DNS (1.12.5), NGINX Home Assistant SSL proxy (3.0.1), AirCast (3.1.0), Home Assistant Google Drive Backup (0.104.3), Check Home Assistant configuration (3.7.1), MariaDB (2.3.0), InfluxDB (4.1.0), Grafana (6.3.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 5
views | 8
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

My issue appears to be he same as https://github.com/hacs/integration/issues/2038 but none of the steps to resolve mentioned in that issue solve my issue.

When I change the manifest to 'aiogithubapi==21.2.0', I get the error about a front end mismatch. No number of restarts clears either the aiogithubapi or the frontend mismatch error.

I have removed the hacs dir in custom_components, restarted, ran install script and end up in the same situation.
I can't figure out other troubleshooting to attempt.

### Reproduction steps

1. Attempted HACS upgrade
2. Restarted

### Debug logs

```text
Logger: homeassistant.util.package
Source: util/package.py:96
First occurred: 7:15:17 AM (1 occurrences)
Last logged: 7:15:17 AM

Unable to install package aiogithubapi>=21.4.0: Traceback (most recent call last): File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/usr/local/lib/python3.8/site-packages/pip/__main__.py", line 23, in <module> from pip._internal.cli.main import main as _main # isort:skip # noqa File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 10, in <module> from pip._internal.cli.autocompletion import autocomplete File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module> from pip._internal.cli.main_parser import create_main_parser File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module> from pip._internal.cli import cmdoptions File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module> from pip._internal.cli.progress_bars import BAR_TYPES File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 7, in <module> from pip._vendor import six File "<frozen importlib._bootstrap>", line 991, in _find_and_load File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 671, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 779, in exec_module File "<frozen importlib._bootstrap_external>", line 911, in get_code File "<frozen importlib._bootstrap_external>", line 580, in _compile_bytecode ValueError: bad marshal data (unknown type code)
```

**Comment by Timeteo** [comment]
@ludeeus I see you changed the label. Should I open this over in the HA issue tracker instead? I am running HASSOS

**Comment by Timeteo** [comment]
was with HASS OS. Update fixed
