### ISSUE TITLE
Failed to set up - new installation fails

### ISSUE THREAD

**Issue by benalla** [hacs/integration#2069]
### Web browser

Chrome

### Web browser version

 90.0.4430.212 

## System Health

version | core-2021.5.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | May 24, 2021, 2:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 19.03.15
disk_total | 228.5 GB
disk_used | 10.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon 4 (0.6.0), Duck DNS (1.12.5), FTP (4.1.0), File editor (5.3.0), Home Assistant Google Drive Backup (0.104.3), MQTT Server & Web client (1.2.0), Samba share (9.3.1), Terminal & SSH (9.1.1), Zigbee2mqtt (1.18.1-1), Mosquitto broker (5.1.1), Node-RED (9.0.1)

</details>

<details><summary>Lovelace</summary>

error | failed to load: unknown
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I had issue with HACS: now showing up anymore in the leftside menu.
So I deleted it using the 'official' way as described on hacs.xyz.

Performing a new installation results in: Failed to set up

### Reproduction steps

1. Remove HACS
2. Install HACS
...

Error:
Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 27, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 74, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 98, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 129, in async_hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/system_health.py", line 22, in system_health_info
    health_info.update(await hass.data[DOMAIN]["resources"].async_get_info())
  File "/usr/src/homeassistant/homeassistant/components/lovelace/resources.py", line 66, in async_get_info
    await self.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 215, in async_load
    self.data[item[CONF_ID]] = item
KeyError: 'id'

### Screenshots

![image](https://user-images.githubusercontent.com/3511603/118658345-954dc980-b7ec-11eb-99ff-8a330871097f.png)

### Javascript logs from your browser console

```text
Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 27, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 74, in async_setup_entry
    return await async_startup_wrapper_for_config_entry()
  File "/config/custom_components/hacs/operational/setup.py", line 98, in async_startup_wrapper_for_config_entry
    startup_result = await async_hacs_startup()
  File "/config/custom_components/hacs/operational/setup.py", line 129, in async_hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/system_health.py", line 22, in system_health_info
    health_info.update(await hass.data[DOMAIN]["resources"].async_get_info())
  File "/usr/src/homeassistant/homeassistant/components/lovelace/resources.py", line 66, in async_get_info
    await self.async_load()
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 215, in async_load
    self.data[item[CONF_ID]] = item
KeyError: 'id'
```

**Comment by ludeeus** [comment]
Your lovelace configuration is broken, fix that and HACS will work.

**Comment by benalla** [comment]
> Your lovelace configuration is broken, fix that and HACS will work.

Care to tell me what is broken and how to fix this?

**Comment by ludeeus** [comment]
Not really, it looks like it's something with the resources
