### ISSUE TITLE
Can't Install or Uninstall Frontend Plugins

### ISSUE THREAD

**Issue by EliotHertenstein** [hacs/integration#2111]
## System Health

version | core-2021.6.6
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.8.0-59-generic
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 3991
Installed Version | 1.13.2
Stage | running
Available Repositories | 864
Installed Repositories | 51

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 29, 2021, 5:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 33
views | 16
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

When installing or uninstalling frontend components, HACS just loads forever, without actually making any progress. 

### Reproduction steps

1. Open HACS
2. Go to `Frontend`
3. Select a Component
4. Click the three dots
5. Click `Uninstall`
6. Click `Uninstall`
...

### Debug logs

```text
2021-07-03 22:51:44 DEBUG (MainThread) [custom_components.hacs] Configuration type: flow
2021-07-03 22:51:44 INFO (MainThread) [custom_components.hacs]
2021-07-03 22:51:44 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.WEBSOCKET
2021-07-03 22:51:44 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.FRONTEND
2021-07-03 22:51:44 INFO (MainThread) [custom_components.hacs] LovelaceMode.STORAGE mode, cache for /hacsfiles/: True
2021-07-03 22:51:45 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.CATEGORIES
2021-07-03 22:51:45 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-07-03 22:51:48 DEBUG (MainThread) [custom_components.hacs] Can update 221 repositories
2021-07-03 22:51:48 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.HACS_REPO
2021-07-03 22:51:48 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Checking repository.
2021-07-03 22:51:48 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.13.2
2021-07-03 22:51:49 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> All (0) checks passed
2021-07-03 22:51:49 INFO (MainThread) [custom_components.hacs] <Integration hacs/integration> Registration completed
2021-07-03 22:51:49 INFO (MainThread) [custom_components.hacs] Restore started
2021-07-03 22:51:49 INFO (MainThread) [custom_components.hacs] Restore done
2021-07-03 22:51:50 INFO (MainThread) [custom_components.hacs] Setup task HacsSetupTask.SENSOR
2021-07-03 22:51:50 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2021-07-03 22:51:50 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2021-07-03 22:51:50 INFO (MainThread) [custom_components.hacs] HACS is enabled
2021-07-03 22:52:15 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2021-07-03 22:52:15 INFO (MainThread) [custom_components.hacs] setup task HacsSetupTask.CATEGORIES
2021-07-03 22:52:15 DEBUG (SyncWorker_4) [custom_components.hacs] Starting setup task: Extra stores
2021-07-03 22:52:15 INFO (SyncWorker_4) [custom_components.hacs] Enable category: HacsCategory.INTEGRATION
2021-07-03 22:52:15 INFO (SyncWorker_4) [custom_components.hacs] Enable category: HacsCategory.PLUGIN
2021-07-03 22:52:15 INFO (SyncWorker_4) [custom_components.hacs] Enable category: HacsCategory.THEME
2021-07-03 22:52:15 INFO (MainThread) [custom_components.hacs] Loading known repositories
2021-07-03 22:52:15 DEBUG (MainThread) [custom_components.hacs] Got 107 elements for HacsCategory.REMOVED
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] Can update 221 repositories, items in queue 3
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] Got 556 elements for HacsCategory.INTEGRATION
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] Got 63 elements for HacsCategory.THEME
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] Got 234 elements for HacsCategory.PLUGIN
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] Starting recurring background task for installed repositories
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Integration LaggAt/hacs-govee> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin DBuit/thermostat-popup-card> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Integration mudape/iphonedetect> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin ofekashery/vertical-stack-in-card> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-fold-entity-row> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-state-switch> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Integration raman325/ha-zoom-automation> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Integration zachowj/hass-node-red> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin DBuit/light-popup-card> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Integration cyberjunky/home-assistant-google_fit> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin matisaul/vertical-style-card> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-hui-element> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-multiple-entity-row> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin maykar/kiosk-mode> Getting repository information
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Running checks against v1.1.0
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Integration LaggAt/hacs-govee> Running checks against 0.2.0b
2021-07-03 22:52:16 DEBUG (MainThread) [custom_components.hacs] <Plugin DBuit/thermostat-popup-card> Running checks against 0.2.6.1
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-hui-element> Running checks against master
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-state-switch> Running checks against 8
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Integration zachowj/hass-node-red> Running checks against v0.5.2
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Integration mudape/iphonedetect> Running checks against 1.4.0
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Plugin matisaul/vertical-style-card> Running checks against 0.1.1
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Plugin ofekashery/vertical-stack-in-card> Running checks against v0.4.1
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Integration cyberjunky/home-assistant-google_fit> Running checks against 1.0.4
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Plugin DBuit/light-popup-card> Running checks against 0.5
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Plugin benct/lovelace-multiple-entity-row> Running checks against v4.2.0
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Integration raman325/ha-zoom-automation> Running checks against v0.7.5
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-fold-entity-row> Running checks against 20.0.4
2021-07-03 22:52:17 DEBUG (MainThread) [custom_components.hacs] <Plugin maykar/kiosk-mode> Running checks against 1.7.1
2021-07-03 22:52:18 DEBUG (MainThread) [custom_components.hacs] 'is_state' is undefined
2021-07-03 22:52:18 DEBUG (MainThread) [custom_components.hacs] 'trigger' is undefined
2021-07-03 22:52:22 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-auto-entities> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration elad-bar/ha-hpprinter> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin jcwillox/lovelace-paper-buttons-row> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration leikoilja/ha-google-home> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin ljmerza/light-entity-card> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Theme JuanMTech/google_dark_theme> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin Villhellm/custom-sidebar> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration thomasloven/hass-lovelace_gen> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-gap-card> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin DBuit/Homekit-panel-card> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration azogue/eventsensor> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/healthchecksio> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration krahabb/meross_lan> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin bramkragten/swipe-card> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/alarmo> Getting repository information
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-auto-entities> Running checks against 1.9.1
2021-07-03 22:52:23 WARNING (MainThread) [custom_components.hacs] thomasloven/lovelace-gap-card - Repository is archived.
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration elad-bar/ha-hpprinter> Running checks against 1.0.1
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin jcwillox/lovelace-paper-buttons-row> Running checks against 0.5.0
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Integration leikoilja/ha-google-home> Running checks against v1.5.0
2021-07-03 22:52:23 DEBUG (MainThread) [custom_components.hacs] <Plugin Villhellm/custom-sidebar> Running checks against v0.2.2
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Plugin ljmerza/light-entity-card> Running checks against 4.3.0
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Integration thomasloven/hass-lovelace_gen> Running checks against 0.1.1
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Theme JuanMTech/google_dark_theme> Running checks against v1.9
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Integration krahabb/meross_lan> Running checks against v2.0.2
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Integration azogue/eventsensor> Running checks against v2.4.2
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Plugin bramkragten/swipe-card> Running checks against v4.0.0
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/healthchecksio> Running checks against 21.3.0
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Plugin DBuit/Homekit-panel-card> Running checks against 0.6.1
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/alarmo> Running checks against v1.6.2
2021-07-03 22:52:24 DEBUG (MainThread) [custom_components.hacs] 'states' is undefined
2021-07-03 22:52:25 DEBUG (MainThread) [custom_components.hacs] 'states' is undefined
2021-07-03 22:52:25 DEBUG (MainThread) [custom_components.hacs] expected token 'end of print statement', got 'open_sensors'
2021-07-03 22:52:28 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-card-tools> Getting repository information
2021-07-03 22:52:29 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-card-tools> Running checks against 11
2021-07-03 22:52:29 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/mini-graph-card> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Integration moralmunky/Home-Assistant-Mail-And-Packages> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/bar-card> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/mini-graph-card> Running checks against v0.10.0
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/state-element> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-layout-card> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin DBuit/media_player-popup-card> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Integration vigonotion/hass-simpleicons> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/button-card> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/circle-sensor-card> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Integration JoshuaMulliken/ha-wyzeapi> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Integration moralmunky/Home-Assistant-Mail-And-Packages> Running checks against 0.3.2
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Integration thomasloven/hass-browser_mod> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/roku-card> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/state-element> Running checks against 0.0.1
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin dylandoamaral/uptime-card> Getting repository information
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-layout-card> Running checks against 2.3.0
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin DBuit/media_player-popup-card> Running checks against 0.2.5
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Integration vigonotion/hass-simpleicons> Running checks against v1.18.3
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/circle-sensor-card> Running checks against 1.2.1
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/button-card> Running checks against v3.4.2
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Integration JoshuaMulliken/ha-wyzeapi> Running checks against 2021.7.3
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Integration thomasloven/hass-browser_mod> Running checks against 1.3.1
2021-07-03 22:52:30 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/bar-card> Running checks against 3.2.0
2021-07-03 22:52:31 DEBUG (MainThread) [custom_components.hacs] <Plugin dylandoamaral/uptime-card> Running checks against v0.6.0
2021-07-03 22:52:31 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/roku-card> Running checks against 1.2.2
2021-07-03 22:52:31 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/authenticated> Getting repository information
2021-07-03 22:52:31 DEBUG (MainThread) [custom_components.hacs] <Integration custom-components/authenticated> Running checks against 21.3.0
2021-07-03 22:52:34 DEBUG (MainThread) [custom_components.hacs] <Integration albertogeniola/meross-homeassistant> Getting repository information
2021-07-03 22:52:35 DEBUG (MainThread) [custom_components.hacs] <Integration albertogeniola/meross-homeassistant> Running checks against 1.0.7
2021-07-03 22:52:35 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-card-mod> Getting repository information
2021-07-03 22:52:35 DEBUG (MainThread) [custom_components.hacs] <Plugin dimagoltsman/refreshable-picture-card> Getting repository information
2021-07-03 22:52:36 DEBUG (MainThread) [custom_components.hacs] <Theme KTibow/lovelace-dark-soft-ui-theme> Getting repository information
2021-07-03 22:52:36 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-card-mod> Running checks against 3.0.12
2021-07-03 22:52:36 DEBUG (MainThread) [custom_components.hacs] <Plugin dimagoltsman/refreshable-picture-card> Running checks against 0.1.6
2021-07-03 22:52:36 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/decluttering-card> Getting repository information
2021-07-03 22:52:36 DEBUG (MainThread) [custom_components.hacs] <Theme KTibow/lovelace-dark-soft-ui-theme> Running checks against v0.60
2021-07-03 22:52:36 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/decluttering-card> Running checks against 0.6.3
2021-07-03 22:52:42 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.critical'. Content did not change
2021-07-03 22:52:42 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-07-03 22:52:42 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-07-03 22:52:42 DEBUG (MainThread) [custom_components.hacs] Recurring background task for installed repositories done
2021-07-03 22:52:42 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2021-07-03 22:52:42 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2021-07-03 22:53:59 DEBUG (MainThread) [custom_components.hacs] Running update for wassy92x/lovelace-ha-dashboard
2021-07-03 22:53:59 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Getting repository information
2021-07-03 22:54:00 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Running checks against v1.1.0
2021-07-03 22:54:01 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-07-03 22:54:01 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-07-03 22:54:01 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.repositories'. Content did not change
2021-07-03 22:54:02 DEBUG (MainThread) [custom_components.hacs] Running install for wassy92x/lovelace-ha-dashboard
2021-07-03 22:54:02 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Getting repository information
2021-07-03 22:54:03 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Running checks against v1.1.0
2021-07-03 22:54:04 INFO (MainThread) [custom_components.hacs] Running pre installation steps
2021-07-03 22:54:04 INFO (MainThread) [custom_components.hacs] Pre installation steps completed
2021-07-03 22:54:04 INFO (MainThread) [custom_components.hacs] Running installation steps
2021-07-03 22:54:04 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Getting repository information
2021-07-03 22:54:04 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Running checks against v1.1.0
2021-07-03 22:54:05 DEBUG (MainThread) [custom_components.hacs]
2021-07-03 22:54:05 DEBUG (MainThread) [custom_components.hacs] Downloading ha-dashboard.js
2021-07-03 22:54:05 DEBUG (MainThread) [custom_components.hacs] Downloading https://github.com/wassy92x/lovelace-ha-dashboard/releases/download/v1.1.0/ha-dashboard.js
2021-07-03 22:54:05 DEBUG (MainThread) [custom_components.hacs] Saving /config/www/community/lovelace-ha-dashboard/ha-dashboard.js
2021-07-03 22:54:05 INFO (MainThread) [custom_components.hacs] Download of ha-dashboard.js completed
2021-07-03 22:54:05 INFO (MainThread) [custom_components.hacs] Installation steps completed
2021-07-03 22:54:05 INFO (MainThread) [custom_components.hacs] Running post installation steps
2021-07-03 22:54:05 INFO (MainThread) [custom_components.hacs] Post installation steps completed
2021-07-03 22:54:05 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-07-03 22:54:05 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-07-03 22:54:05 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.repositories'. Content did not change
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] WS action 'clear_new'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'bernikr/lovelace-notify-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'finity69x2/fan-percent-button-row'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'jtbgroup/kodi-search-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'mampfes/ha-knx-uf-iconset'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'jampez77/Multiline-Entity-Card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'tmjo/charger-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'estevez-dev/extended-banner-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'JurajNyiri/PlexMeetsHomeAssistant'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'elax46/custom-brand-icons'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'finity69x2/fan-mode-button-row'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'MrBartusek/MeteoalarmCard'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'AitorDB/home-assistant-sun-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'bernikr/lovelace-webos-keyboard-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'adizanni/floor3d-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'wassy92x/lovelace-entities-btn-group'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'wassy92x/lovelace-digital-clock'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'mattieha/slider-button-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'rianadon/opensprinkler-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Clearing new flag from 'rianadon/timer-bar-card'
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-07-03 22:55:04 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-07-03 23:02:16 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2021-07-03 23:03:06 DEBUG (MainThread) [custom_components.hacs] Running update for bramstroker/homeassistant-powercalc
2021-07-03 23:03:06 DEBUG (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> Getting repository information
2021-07-03 23:03:07 DEBUG (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> Running checks against v0.2.4
2021-07-03 23:03:08 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-07-03 23:03:08 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-07-03 23:03:10 DEBUG (MainThread) [custom_components.hacs] Running install for bramstroker/homeassistant-powercalc
2021-07-03 23:03:10 DEBUG (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> Getting repository information
2021-07-03 23:03:10 DEBUG (MainThread) [custom_components.hacs] Did not update bramstroker/homeassistant-powercalc, content was not modified
2021-07-03 23:03:10 INFO (MainThread) [custom_components.hacs] Running pre installation steps
2021-07-03 23:03:10 INFO (MainThread) [custom_components.hacs] Pre installation steps completed
2021-07-03 23:03:10 INFO (MainThread) [custom_components.hacs] Running installation steps
2021-07-03 23:03:10 DEBUG (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> Getting repository information
2021-07-03 23:03:10 DEBUG (MainThread) [custom_components.hacs] Did not update bramstroker/homeassistant-powercalc, content was not modified
2021-07-03 23:03:10 INFO (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> ref: tags/v0.2.4 --- tag: v0.2.4.
2021-07-03 23:03:10 INFO (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> ref: tags/v0.2.4 --- tag: v0.2.3.
2021-07-03 23:03:10 INFO (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> ref: tags/v0.2.4 --- tag: v0.2.2.
2021-07-03 23:03:10 INFO (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> ref: tags/v0.2.4 --- tag: v0.2.1.
2021-07-03 23:03:10 INFO (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> ref: tags/v0.2.4 --- tag: v0.2.0.
2021-07-03 23:03:10 DEBUG (MainThread) [custom_components.hacs] Downloading https://github.com/bramstroker/homeassistant-powercalc/releases/download/v0.2.4/powercalc.zip
2021-07-03 23:03:11 DEBUG (MainThread) [custom_components.hacs] Saving /tmp/tmp8ykenw3s/powercalc.zip
2021-07-03 23:03:11 INFO (MainThread) [custom_components.hacs] <Integration bramstroker/homeassistant-powercalc> Download of powercalc.zip completed
2021-07-03 23:03:11 DEBUG (SyncWorker_14) [custom_components.hacs] Cleaning up /tmp/tmp8ykenw3s
2021-07-03 23:03:11 INFO (MainThread) [custom_components.hacs] Installation steps completed
2021-07-03 23:03:11 INFO (MainThread) [custom_components.hacs] Running post installation steps
2021-07-03 23:03:11 INFO (MainThread) [custom_components.hacs] Post installation steps completed
2021-07-03 23:03:11 DEBUG (MainThread) [custom_components.hacs] Saving data
2021-07-03 23:03:11 DEBUG (MainThread) [custom_components.hacs] Did not store data for 'hacs.hacs'. Content did not change
2021-07-03 23:12:16 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2021-07-03 23:22:16 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
```

**Comment by ludeeus** [comment]
Logs say install was complete, logs do not contain any uninstall commands.

What does your browser console say?

**Comment by EliotHertenstein** [comment]
> Logs say install was complete, logs do not contain any uninstall commands.
> 
> What does your browser console say?
I'm getting an "Unknown Command" Error

```
{
  "code": "unknown_command",
  "message": "Unknown command."
}
```

**Comment by ludeeus** [comment]
Restart homeassistant, it has not setup the websocket API for lovelace resources.

**Comment by EliotHertenstein** [comment]
I've restarted HA multiple times, nothing changed

**Comment by ludeeus** [comment]
Then there is a bug in homeassistant, from your system health info, you are using lovelace with storage, when you do that it set up the websocket endpoints.
(And if you don't filter on logs from hacs you will see that as an error in your logs as well)

**Comment by EliotHertenstein** [comment]
Ah, I do see that in the logs...

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/browser_mod/helpers.py:49
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:08:27 PM (4 occurrences)
Last logged: 11:08:30 PM

[140260312270448] Error handling message: Unknown error
[140260312141296] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 90, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 49, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
```

Is there a known fix? I understand this isn't really your issue, but if you know anything that could solve it...

**Comment by ludeeus** [comment]
a) Don't use YAML for lovelace at all
b) Don't use any UI dashboards (only YAML)
Those are your options AFAIK

**Comment by EliotHertenstein** [comment]
Okay, let me remove all UI dashboards, I switched to YAML a while back anyway.

**Comment by EliotHertenstein** [comment]
This fixed it, thanks!
