### ISSUE TITLE
Can't load HACS entry page

### ISSUE THREAD

**Issue by Carrjiang** [hacs/integration#2204]
## System Health

version | core-2021.9.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.0-0.bpo.7-amd64
arch | x86_64
timezone | Asia/Hong_Kong

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4979
Installed Version | 1.15.1
Stage | running
Available Repositories | 943
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.08.1
docker_version | 20.10.8
disk_total | 13.2 GB
disk_used | 10.7 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), ZeroTier One (0.11.1), Node-RED (10.0.0), AirSonos (3.1.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 1
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

can't load HACS entry page by side bar, page display 'Error while loading page entry.'

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Logger: homeassistant
Source: custom_components/hacs/helpers/functions/information.py:69
Integration: HACS (documentation, issues)
First occurred: 09:51:43 (1 occurrences)
Last logged: 09:51:43

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 141, in startup_tasks
    await self.prosess_queue()
  File "/config/custom_components/hacs/hacsbase/hacs.py", line 245, in prosess_queue
    await self.queue.execute(can_update)
  File "/usr/local/lib/python3.9/site-packages/queueman/manager.py", line 63, in execute
    await asyncio.gather(*local_queue)
  File "/config/custom_components/hacs/operational/factory.py", line 42, in safe_update
    await repository.update_repository()
  File "/config/custom_components/hacs/repositories/integration.py", line 74, in update_repository
    if not await self.common_update(ignore_issues, force):
  File "/config/custom_components/hacs/helpers/classes/repository.py", line 271, in common_update
    await common_update_data(self, ignore_issues, force)
  File "/config/custom_components/hacs/helpers/functions/validate_repository.py", line 114, in common_update_data
    repository.tree = await get_tree(repository.repository_object, repository.ref)
  File "/config/custom_components/hacs/helpers/functions/information.py", line 69, in get_tree
    tree = await repository.get_tree(ref)
  File "/usr/local/lib/python3.9/site-packages/aiogithubapi/objects/repository/__init__.py", line 127, in get_tree
    response = await self.client.get(endpoint=_endpoint, params=_params, headers=_headers)
  File "/usr/local/lib/python3.9/site-packages/aiogithubapi/legacy/client.py", line 60, in get
    response = await async_call_api(
  File "/usr/local/lib/python3.9/site-packages/aiogithubapi/helpers.py", line 37, in async_call_api
    return await legacy_async_call_api(
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 133, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogithubapi/legacy/helpers.py", line 51, in async_call_api
    result = await session.get(url, params=params or {}, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 381, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```

**Comment by ludeeus** [comment]
Your debug logs are missing from the issue

**Comment by bsimmo** [comment]
Similar here after updating at a similar time.  It's been fine before that.

I just see 
![image](https://user-images.githubusercontent.com/11537335/132125859-f600cf1e-aec5-4916-b3c9-806cc990606c.png)

and HA System - Core Log has which is the three times I tried from two devices (Win10 edge and Android App)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/hacs/sensor.py", line 55, in _update_and_write_state
    self._update()
  File "/config/custom_components/hacs/sensor.py", line 68, in _update
    repository.pending_upgrade
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 23, in pending_upgrade
    return self.pending_update
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 8, in pending_update
    if not self.can_install:
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 27, in version_left_higher_then_right
    return version.version_left_higher_then_right(left, right)
  File "/config/custom_components/hacs/utils/version.py", line 12, in version_left_higher_then_right
    return AwesomeVersion(left) >= AwesomeVersion(right)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
2021-09-05 12:46:16 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547297792928] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/api/hacs_repositories.py", line 25, in hacs_repositories
    "can_install": repo.can_install,
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 27, in version_left_higher_then_right
    return version.version_left_higher_then_right(left, right)
  File "/config/custom_components/hacs/utils/version.py", line 12, in version_left_higher_then_right
    return AwesomeVersion(left) >= AwesomeVersion(right)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
2021-09-05 12:51:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547384861600] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/api/hacs_repositories.py", line 25, in hacs_repositories
    "can_install": repo.can_install,
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 27, in version_left_higher_then_right
    return version.version_left_higher_then_right(left, right)
  File "/config/custom_components/hacs/utils/version.py", line 12, in version_left_higher_then_right
    return AwesomeVersion(left) >= AwesomeVersion(right)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
2021-09-05 12:51:48 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547384861600] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/api/hacs_repositories.py", line 25, in hacs_repositories
    "can_install": repo.can_install,
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 27, in version_left_higher_then_right
    return version.version_left_higher_then_right(left, right)
  File "/config/custom_components/hacs/utils/version.py", line 12, in version_left_higher_then_right
    return AwesomeVersion(left) >= AwesomeVersion(right)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
2021-09-05 12:53:29 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547384861600] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/api/hacs_repositories.py", line 25, in hacs_repositories
    "can_install": repo.can_install,
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 27, in version_left_higher_then_right
    return version.version_left_higher_then_right(left, right)
  File "/config/custom_components/hacs/utils/version.py", line 12, in version_left_higher_then_right
    return AwesomeVersion(left) >= AwesomeVersion(right)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
```

HA Core core-2021.9.1
HA Supervisor supervisor-2021.09.0
OS Home Assistant OS 6.2 (on RPi3)

Step to reproduce, click on HACS icon in sidebar.

Will enable HACS logs once I read how.

**Comment by N3rdix** [comment]
Having exactly the same issue, i am still on 2021.8.8

**Comment by ludeeus** [comment]
Upgrade to 1.15.2

**Comment by khcnz** [comment]
Can confirm that fixes the issue for me.

But you can't update from the UI because HACS doesn't load. For anyone else in this situation you'll need to reinstall HACS or manually make this change that was made here https://github.com/hacs/integration/commit/f13901d7a8106719b001c09e446ddc7f8f649fb5

@ludeeus could there be other parameters that trip up HACS in the future? Would it be worthwhile some exception handling in  for repo in repositories section in hacs_repositories.py?

**Comment by ludeeus** [comment]
No, all repo handling is being replaced anyway
