### ISSUE TITLE
HACS main page is not showing integrations: crashing on unknown version in AwesomeVersion code as version string contains the word 'core-'

### ISSUE THREAD

**Issue by ddp526** [hacs/integration#2206]
## System Health

version | core-2021.9.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.11.0-27-generic
arch | x86_64
timezone | Australia/Melbourne

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4485
Installed Version | 1.15.1
Stage | running
Available Repositories | 882
Installed Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 8
views | 7
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

HACS is failing on a version check.  I 'kludged' the code to get by, but I believe it relates to AwesomeVersion not handling a version string starting with 'core-'

I did this to get by for now:
in misc.py

```
def version_left_higher_then_right(left: str, right: str) -> bool:
    """Return a bool if source is newer than target, will also be true if identical."""
    # KLUDGE-start
    if left.find('core-') >=0:
        left = left.replace('core-','')
    if right.find('core-') >=0:
        right = right.replace('core-','')
    # KLUDGE-end
    return version.version_left_higher_then_right(left, right)
```

Its a definite hack as I don't know what the intent of the version checking is, so this might be totally the wrong thing to do logically :)

### Reproduction steps

1. upgraded to core-2021.9.1
2. click on HACS front page
3. all integrations are missing.
...

### Debug logs

```text
Example log:
2021-09-03 11:54:04 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback HACSSensor._update_and_write_state(<Event hacs/status[L]>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/hacs/sensor.py", line 55, in _update_and_write_state
    self._update()
  File "/config/custom_components/hacs/sensor.py", line 68, in _update
    repository.pending_upgrade
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 23, in pending_upgrade
    return self.pending_update
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 8, in pending_update
    if not self.can_install:
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 27, in version_left_higher_then_right
    return version.version_left_higher_then_right(left, right)
  File "/config/custom_components/hacs/utils/version.py", line 12, in version_left_higher_then_right
    return AwesomeVersion(left) >= AwesomeVersion(right)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
```

**Comment by ludeeus** [comment]
`core-*` is not a valid version schema

**Comment by DrSpaldo** [comment]
I am also getting the same error. 

![screenshot 2021-09-03](https://user-images.githubusercontent.com/8526509/131999927-84f27665-bc3b-489b-b5f7-b781f110f4a3.png)

```
Logger: homeassistant
Source: custom_components/hacs/utils/version.py:12
Integration: HACS (documentation, issues)
First occurred: 21:32:13 (3 occurrences)
Last logged: 21:32:45

Error doing job: Exception in callback HACSSensor._update_and_write_state(<Event hacs/status[L]>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/hacs/sensor.py", line 55, in _update_and_write_state
    self._update()
  File "/config/custom_components/hacs/sensor.py", line 68, in _update
    repository.pending_upgrade
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 23, in pending_upgrade
    return self.pending_update
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 8, in pending_update
    if not self.can_install:
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 27, in version_left_higher_then_right
    return version.version_left_higher_then_right(left, right)
  File "/config/custom_components/hacs/utils/version.py", line 12, in version_left_higher_then_right
    return AwesomeVersion(left) >= AwesomeVersion(right)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
```

**Comment by ludeeus** [comment]
You have <https://github.com/viktak/ha-cc-openweathermap_all> or <https://github.com/viktak/ha-cc-abalin-nameday> installed.

**Comment by DrSpaldo** [comment]
> You have https://github.com/viktak/ha-cc-openweathermap_all or https://github.com/viktak/ha-cc-abalin-nameday installed.

No. I have another weather one installed - https://github.com/bremor/bureau_of_meteorology

But, neither of the two you mentioned

**Comment by ludeeus** [comment]
Those are the only 2 default repositories that uses  `core-*` for version

**Comment by DrSpaldo** [comment]
Can I delete something to test it?

**Comment by ludeeus** [comment]
you can delete `custom_components/hacs/sensor.py`

**Comment by TimBE1989** [comment]
Have the same issue since today.

**Comment by Masterz69** [comment]
Just yesterday no issues with HACS. Today see NO integrations.
NO updates in HA CORE/OS or any Add-on.

Core log:
```
2021-09-03 18:57:58 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547592109936] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/api/hacs_repositories.py", line 25, in hacs_repositories
    "can_install": repo.can_install,
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 34, in version_left_higher_then_right
    return None
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
2021-09-03 18:57:58 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547592109936] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/api/hacs_repositories.py", line 25, in hacs_repositories
    "can_install": repo.can_install,
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 34, in version_left_higher_then_right
    return None
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
2021-09-03 18:57:58 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547592109936] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/api/hacs_repositories.py", line 25, in hacs_repositories
    "can_install": repo.can_install,
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 34, in version_left_higher_then_right
    return None
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
2021-09-03 18:57:58 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547592109936] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/api/hacs_repositories.py", line 25, in hacs_repositories
    "can_install": repo.can_install,
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 34, in version_left_higher_then_right
    return None
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
2021-09-03 18:58:12 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback HACSSensor._update_and_write_state(<Event hacs/status[L]>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/hacs/sensor.py", line 57, in _update_and_write_state
  File "/config/custom_components/hacs/sensor.py", line 70, in _update
    ):
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 23, in pending_upgrade
    return self.pending_update
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 8, in pending_update
    if not self.can_install:
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 21, in can_install
    return self.can_be_installed
  File "/config/custom_components/hacs/helpers/properties/can_be_installed.py", line 12, in can_be_installed
    if not version_left_higher_then_right(
  File "/config/custom_components/hacs/helpers/functions/misc.py", line 34, in version_left_higher_then_right
    return None
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 129, in __ge__
    return self.__eq__(compareto) or self.__gt__(compareto)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 117, in __gt__
    raise AwesomeVersionCompare(
awesomeversion.exceptions.AwesomeVersionCompare: Can't compare unknown
```

System Info:
## System Health

version | core-2021.8.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.6
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Riga

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4853
Installed Version | 1.14.0
Stage | running
Available Repositories | 941
Installed Repositories | 23

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.2
-- | --
update_channel | stable
supervisor_version | supervisor-2021.08.1
docker_version | 20.10.6
disk_total | 57.8 GB
disk_used | 16.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba Backup (4.5.0), SSH & Web Terminal (9.0.1), File editor (5.3.2), Mosquitto broker (6.0.1), Z-Wave JS to MQTT (0.23.4), Zigbee2mqtt (1.21.0-4), MariaDB (2.4.0), phpMyAdmin (0.5.0), Samba share (9.5.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 8
-- | --
resources | 12
views | 29
mode | storage

</details>

Activating debug on Add-on produce no additional records in log, just same as before ^^

**Comment by novisys** [comment]
The same strange  way on my Home Assistant since two days 🙃

**Comment by Masterz69** [comment]
Solved by reinstalling HACS according [official guide](https://hacs.xyz/docs/installation/installation/).

**Comment by DrSpaldo** [comment]
Reinstall didn't fix it for me...

**Comment by clemorphy** [comment]
Same problem for me.

**Comment by DrSpaldo** [comment]
For those reading, I had to delete the entire hacs folder then reinstall as per the official guide. When I reinstalled without removing the folder first, it didn't work. It appears working again for me after doing that ;)
