### ISSUE TITLE
HACS Action "comment" fails due to a dependency version conflict

### ISSUE THREAD

**Issue by eifinger** [hacs/integration#2252]
### Describe the issue

My nightly run on all my custom integrations reported an error in the "comment" check when using the hacs action.

Since it happens to all my repos and also the blueprint repo I figured this might be an issue with the action itself.

```bash
ERROR: aiohttp 3.8.0 has requirement async-timeout<5.0,>=4.0.0a3, but you'll have async-timeout 3.0.1 which is incompatible.
Traceback (most recent call last):
  File "/home/runner/work/_actions/hacs/action/main/helpers/post_result.py", line 4, in <module>
    from aiogithubapi import GitHub
  File "/home/runner/.local/lib/python3.8/site-packages/aiogithubapi/__init__.py", line 12, in <module>
    from .const import (
  File "/home/runner/.local/lib/python3.8/site-packages/aiogithubapi/const.py", line 9, in <module>
    from aiohttp.hdrs import ACCEPT, CONTENT_TYPE, USER_AGENT
  File "/home/runner/.local/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/runner/.local/lib/python3.8/site-packages/aiohttp/client.py", line 36, in <module>
    from . import hdrs, http, payload
  File "/home/runner/.local/lib/python3.8/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/home/runner/.local/lib/python3.8/site-packages/aiohttp/http_parser.py", line 29, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/home/runner/.local/lib/python3.8/site-packages/aiohttp/helpers.py", line 729, in <module>
    def ceil_timeout(delay: Optional[float]) -> async_timeout.Timeout:
AttributeError: module 'async_timeout' has no attribute 'Timeout'
Error: Process completed with exit code 1.
```

### Link to action run

https://github.com/eifinger/hass-weenect/runs/4064671288?check_suite_focus=true

### Link to action configuration

https://github.com/eifinger/hass-weenect/blob/master/.github/workflows/ci.yaml#L72

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the HACS action.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

**Comment by eifinger** [comment]
For reference [the failed run of the integration blueprint](https://github.com/custom-components/integration_blueprint/actions/runs/1405982456)

**Comment by ludeeus** [comment]
This was fixed 6 hours ago with the release of <https://github.com/ludeeus/aiogithubapi/releases/tag/21.11.0>
