### ISSUE TITLE
Error setting up entry for hacs

### ISSUE THREAD

**Issue by cybernard** [hacs/integration#2272]
### System Health details

good as far as I know

I can't even install hacs in homeassistant

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 39, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 98, in async_setup_entry
    await _async_common_setup(hass)
  File "/config/custom_components/hacs/operational/setup.py", line 54, in _async_common_setup
    await hacs.tasks.async_load()
  File "/config/custom_components/hacs/tasks/manager.py", line 43, in async_load
    await asyncio.gather(*[_load_module(task) for task in task_modules])
  File "/config/custom_components/hacs/tasks/manager.py", line 39, in _load_module
    task_module = import_module(f"{__package__}.{module}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hacs/tasks/setup_frontend.py", line 4, in <module>
    from hacs_frontend import locate_dir
ImportError: cannot import name 'locate_dir' from 'hacs_frontend' (/usr/local/lib/python3.9/site-packages/hacs_frontend/__init__.py)

### Reproduction steps

error just installing it
Goto the integrates tab in home assistant
click add
check the boxes
reboot 
get the error

### Debug logs

```text
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hacs/tasks/setup_frontend.py:4
Integration: HACS (documentation, issues)
First occurred: 11:30:34 PM (2 occurrences)
Last logged: 11:34:49 PM

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/hacs/__init__.py", line 39, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 98, in async_setup_entry
    await _async_common_setup(hass)
  File "/config/custom_components/hacs/operational/setup.py", line 54, in _async_common_setup
    await hacs.tasks.async_load()
  File "/config/custom_components/hacs/tasks/manager.py", line 43, in async_load
    await asyncio.gather(*[_load_module(task) for task in task_modules])
  File "/config/custom_components/hacs/tasks/manager.py", line 39, in _load_module
    task_module = import_module(f"{__package__}.{module}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hacs/tasks/setup_frontend.py", line 4, in <module>
    from hacs_frontend import locate_dir
ImportError: cannot import name 'locate_dir' from 'hacs_frontend' (/usr/local/lib/python3.9/site-packages/hacs_frontend/__init__.py)
```

**Comment by ludeeus** [comment]
Your python packages are no good.
Run `ha core rebuild`

**Comment by ludeeus** [comment]
Permanently fixed with https://github.com/hacs/integration/pull/2268
