### ISSUE TITLE
HACS is disabled - Restore of HACS failed

### ISSUE THREAD

**Issue by johnrobledo** [hacs/integration#2279]
## System Health

version | core-2021.11.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | America/Denver

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.16.0
Stage | running
Available Repositories | 902
Installed Repositories | 11
Disabled | restore

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 32

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 7, 2021, 5:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-2.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 109.3 GB
disk_used | 4.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Terminal & SSH (9.1.3), Home Assistant Google Drive Backup (0.105.2), Samba share (9.5.1), Z-Wave JS to MQTT (0.27.0), ArgonOne Active Cooling (24.1), RTSP Simple Server Add-on (v0.17.6), eufy_security_addon (0.3.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 6
views | 3
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

trying to use HACS but it says in the integration page: 
HACS is disabled - Restore of HACS failed

### Reproduction steps

1. Go to integration page
2.
3.
...

### Debug logs

```text
2021-11-11 22:35:45 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-11 22:35:45 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-11 22:35:45 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tuya_v2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-11 22:35:45 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-11-11 22:35:45 ERROR (SyncWorker_1) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/webrtc/manifest.json: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:35:52 ERROR (Thread-3) [tuya iot] error while get mqtt config
2021-11-11 22:35:52 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/site-packages/tuya_iot/openmq.py", line 173, in run
time.sleep(self.mq_config.expireTime - 60)
AttributeError: 'TuyaOpenMQ' object has no attribute 'mq_config'
2021-11-11 22:36:02 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Gym TV' for roku integration not ready yet: Invalid response from API: Error occurred while communicating with device; Retrying in background
2021-11-11 22:36:03 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:36:03 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:36:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:36:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:36:16 WARNING (MainThread) [homeassistant.components.automation] Error evaluating condition in 'Front Door off':
In 'condition':
In 'state':
In 'state' condition: unknown entity binary_sensor.hue_outdoor_motion_sensor_1_motion
2021-11-11 22:38:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:38:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:39:10 ERROR (MainThread) [frontend.js.latest.202111090] https://ffpu46yg581p0rc4y923mqj9yw91zh3t.ui.nabu.casa/frontend_latest/app.a6e743b8.js:1381:5135 Uncaught TypeError: Cannot read properties of null (reading 'tagName')
2021-11-11 22:39:54 ERROR (SyncWorker_4) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs/356778495.hacs
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:39:54 CRITICAL (MainThread) [custom_components.hacs] [Expecting value: line 1 column 1 (char 0)] Restore Failed!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/hacs/hacsbase/data.py", line 153, in restore
await hass.async_add_executor_job(_load_from_storage)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hacs/hacsbase/data.py", line 150, in _load_from_storage
if os.path.exists(store.path) and (data := store.load()):
File "/config/custom_components/hacs/helpers/functions/store.py", line 19, in load
data = json_util.load_json(self.path)
File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:39:54 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.RESTORE
2021-11-11 22:39:54 WARNING (MainThread) [homeassistant.config_entries] Config entry '' for hacs integration not ready yet: HacsDisabledReason.RESTORE; Retrying in background
2021-11-11 22:40:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:40:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:42:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:42:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:44:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:44:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:44:43 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
result = await component.async_unload_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-11 22:44:43 ERROR (SyncWorker_6) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs/356778495.hacs
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:44:43 CRITICAL (MainThread) [custom_components.hacs] [Expecting value: line 1 column 1 (char 0)] Restore Failed!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/hacs/hacsbase/data.py", line 153, in restore
await hass.async_add_executor_job(_load_from_storage)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hacs/hacsbase/data.py", line 150, in _load_from_storage
if os.path.exists(store.path) and (data := store.load()):
File "/config/custom_components/hacs/helpers/functions/store.py", line 19, in load
data = json_util.load_json(self.path)
File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:44:43 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.RESTORE
2021-11-11 22:44:43 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hacs/__init__.py", line 68, in async_reload_entry
await async_setup_entry(hass, config_entry)
File "/config/custom_components/hacs/__init__.py", line 39, in async_setup_entry
return await hacs_ui_setup(hass, config_entry)
File "/config/custom_components/hacs/operational/setup.py", line 99, in async_setup_entry
return await async_startup_wrapper_for_config_entry()
File "/config/custom_components/hacs/operational/setup.py", line 132, in async_startup_wrapper_for_config_entry
raise ConfigEntryNotReady(hacs.system.disabled_reason)
homeassistant.exceptions.ConfigEntryNotReady: HacsDisabledReason.RESTORE
2021-11-11 22:44:48 WARNING (MainThread) [custom_components.hacs] Skipping task load_hacs_repository, HACS is disabled - HacsDisabledReason.RESTORE
2021-11-11 22:46:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:46:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:48:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:48:05 WARNING (MainThread) [pytile.tile] Missing last_tile_state; can't report location info
2021-11-11 22:49:14 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
result = await component.async_unload_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-11 22:49:14 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
result = await component.async_unload_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-11 22:49:14 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in async_unload
result = await component.async_unload_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 134, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 181, in async_unload_entry
raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2021-11-11 22:49:14 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 128, in async_setup_entry
return await component.async_setup_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 164, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2021-11-11 22:49:14 ERROR (SyncWorker_6) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs/356778495.hacs
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:49:14 CRITICAL (MainThread) [custom_components.hacs] [Expecting value: line 1 column 1 (char 0)] Restore Failed!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/hacs/hacsbase/data.py", line 153, in restore
await hass.async_add_executor_job(_load_from_storage)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hacs/hacsbase/data.py", line 150, in _load_from_storage
if os.path.exists(store.path) and (data := store.load()):
File "/config/custom_components/hacs/helpers/functions/store.py", line 19, in load
data = json_util.load_json(self.path)
File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:49:14 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.RESTORE
2021-11-11 22:49:14 ERROR (SyncWorker_4) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs/356778495.hacs
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:49:14 CRITICAL (MainThread) [custom_components.hacs] [Expecting value: line 1 column 1 (char 0)] Restore Failed!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
return json.loads(fdesc.read()) # type: ignore
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/hacs/hacsbase/data.py", line 153, in restore
await hass.async_add_executor_job(_load_from_storage)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hacs/hacsbase/data.py", line 150, in _load_from_storage
if os.path.exists(store.path) and (data := store.load()):
File "/config/custom_components/hacs/helpers/functions/store.py", line 19, in load
data = json_util.load_json(self.path)
File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: Expecting value: line 1 column 1 (char 0)
2021-11-11 22:49:14 ERROR (MainThread) [custom_components.hacs] HACS is disabled - HacsDisabledReason.RESTORE
2021-11-11 22:49:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hacs/__init__.py", line 68, in async_reload_entry
await async_setup_entry(hass, config_entry)
File "/config/custom_components/hacs/__init__.py", line 39, in async_setup_entry
return await hacs_ui_setup(hass, config_entry)
File "/config/custom_components/hacs/operational/setup.py", line 99, in async_setup_entry
return await async_startup_wrapper_for_config_entry()
File "/config/custom_components/hacs/operational/setup.py", line 132, in async_startup_wrapper_for_config_entry
raise ConfigEntryNotReady(hacs.system.disabled_reason)
homeassistant.exceptions.ConfigEntryNotReady: HacsDisabledReason.RESTORE
2021-11-11 22:49:14 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hacs/__init__.py", line 68, in async_reload_entry
await async_setup_entry(hass, config_entry)
File "/config/custom_components/hacs/__init__.py", line 39, in async_setup_entry
return await hacs_ui_setup(hass, config_entry)
File "/config/custom_components/hacs/operational/setup.py", line 99, in async_setup_entry
return await async_startup_wrapper_for_config_entry()
File "/config/custom_components/hacs/operational/setup.py", line 132, in async_startup_wrapper_for_config_entry
raise ConfigEntryNotReady(hacs.system.disabled_reason)
homeassistant.exceptions.ConfigEntryNotReady: HacsDisabledReason.RESTORE
2021-11-11 22:49:19 WARNING (MainThread) [custom_components.hacs] Skipping task load_hacs_repository, HACS is disabled - HacsDisabledReason.RESTORE
2021-11-11 22:49:20 WARNING (MainThread) [aiogithubapi] You need to call .set_last_commit to set this property
```

**Comment by ludeeus** [comment]
One or more of your JSON files under `.storage` is blank.
Find it, and delete it. or restore it from a backup.

**Comment by johnrobledo** [comment]
How do I access this .storage folder and what files do I delete?

**Comment by ludeeus** [comment]
Same as you edit config files, the blank files

**Comment by johnrobledo** [comment]
Got it, thanks!
