### ISSUE TITLE
HACS main page is not showing integrations & frontend

### ISSUE THREAD

**Issue by johnjoemorgan** [hacs/integration#2311]
## System Health

version | core-2021.9.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.75
arch | x86_64
timezone | Asia/Manila

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 2480
Installed Version | 1.17.2
Stage | running
Available Repositories | 912
Installed Repositories | 55

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | December 13, 2021, 8:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.6
-- | --
update_channel | stable
supervisor_version | supervisor-2021.10.8
docker_version | 20.10.8
disk_total | 116.7 GB
disk_used | 12.0 GB
healthy | true
supported | true
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Home Assistant Google Drive Backup (0.103.1), Mosquitto broker (6.0.1), Samba share (9.5.1), Log Viewer (0.12.1), TasmoAdmin (0.16.0), ZeroTier One (0.12.1), Zigbee2mqtt (1.22.0-3), Home Panel (2.3.3), SSH & Web Terminal (9.1.1), Check Home Assistant configuration (3.9.0), Z-Wave JS (0.1.49), Grafana (7.3.1), InfluxDB (4.3.0), MariaDB (2.4.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 52
views | 13
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

Unable to access HACS integrations and frontend UIs

![Screenshot 2021-11-27 131918](https://user-images.githubusercontent.com/45795798/143669103-f6790804-06d6-462b-8ee7-845b07535f86.jpg)

### Reproduction steps

1.Access the HACS UI screen
2) Options for Integrations and Frontend are not visible
..
![Screenshot 2021-11-27 131918](https://user-images.githubusercontent.com/45795798/143669113-0bbfd9cd-b259-49b1-9891-616c36de6885.jpg)
.

### Debug logs

```text
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/hacs/helpers/properties/pending_update.py:20
Integration: HACS (documentation, issues)
First occurred: 1:24:27 PM (2 occurrences)
Last logged: 1:24:27 PM

Error doing job: Exception in callback HACSSensor._update_and_write_state(<Event hacs/status[L]>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/hacs/sensor.py", line 55, in _update_and_write_state
    self._update()
  File "/config/custom_components/hacs/sensor.py", line 68, in _update
    repository.pending_upgrade
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 33, in pending_upgrade
    return self.pending_update
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 20, in pending_update
    return AwesomeVersion(self.display_available_version) > AwesomeVersion(
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 120, in __gt__
    return CompareHandlers(self, compareto).check()
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/handlers.py", line 46, in check
    result: Optional[bool] = compare.handler()
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/comparehandlers/simple.py", line 15, in handler
    if self._compare_base_sections(self.ver_a, self.ver_b) is None:
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/comparehandlers/sections.py", line 28, in _compare_base_sections
    ver_a_section = ver_a.section(section)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 134, in section
    return int(RE_DIGIT.match(self.string.split(".")[idx]).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by johnjoemorgan** [comment]
Updated to  1.18 and the bug persists.

Error log:

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/hacs/helpers/properties/pending_update.py:20
Integration: HACS (documentation, issues)
First occurred: 6:56:52 PM (2 occurrences)
Last logged: 6:56:52 PM

Error doing job: Exception in callback HACSSensor._update_and_write_state(<Event hacs/status[L]>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/hacs/sensor.py", line 55, in _update_and_write_state
    self._update()
  File "/config/custom_components/hacs/sensor.py", line 68, in _update
    repository.pending_upgrade
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 33, in pending_upgrade
    return self.pending_update
  File "/config/custom_components/hacs/helpers/properties/pending_update.py", line 20, in pending_update
    return AwesomeVersion(self.display_available_version) > AwesomeVersion(
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 120, in __gt__
    return CompareHandlers(self, compareto).check()
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/handlers.py", line 46, in check
    result: Optional[bool] = compare.handler()
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/comparehandlers/simple.py", line 15, in handler
    if self._compare_base_sections(self.ver_a, self.ver_b) is None:
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/comparehandlers/sections.py", line 28, in _compare_base_sections
    ver_a_section = ver_a.section(section)
  File "/usr/local/lib/python3.9/site-packages/awesomeversion/awesomeversion.py", line 134, in section
    return int(RE_DIGIT.match(self.string.split(".")[idx]).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
`
