### ISSUE TITLE
Fell victim of the indefinite "HACS is starting up" message 

### ISSUE THREAD

**Issue by drthanwho** [hacs/integration#2448]
## System Health

version | core-2022.2.0.dev20220115
-- | --
installation_type | Home Assistant OS
dev | true
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.63-v8
arch | aarch64
timezone | Europe/Athens

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.19.3
Stage | startup
Available Repositories | 951
Downloaded Repositories | 72

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | pending

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.0.dev20211213
-- | --
update_channel | dev
supervisor_version | supervisor-2022.01.dev1105
docker_version | 20.10.9
disk_total | 109.3 GB
disk_used | 54.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), AdGuard Home (4.4.2), Glances (0.14.1), Let's Encrypt (4.12.0), Mosquitto broker (6.0.1), Node-RED (10.2.2), Spotify Connect (0.10.0), Terminal & SSH (9.3.0), WireGuard (0.6.0), deCONZ (6.11.1), Studio Code Server (3.7.0), Grafana (7.4.0), Home Assistant Google Drive Backup (0.105.2), MariaDB (2.4.0), Assistant Relay (0.7.4), InfluxDB (4.3.0), VSCode Remote (6541b8e), Network UPS Tools (0.9.0), SSH & Web Terminal (9.1.1), File editor (5.3.3), chrony (2.2.1), Nginx Proxy Manager (0.11.0), TasmoAdmin (0.16.0), Scrutiny (0.3.13-6), phpMyAdmin (0.6.0), Frigate NVR Proxy (1.3), Zigbee2mqtt (1.22.1-1), Double Take Proxy (1.0.0), ESPHome (2021.12.3), VLC (0.1.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 10
-- | --
resources | 51
views | 56
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

At some point I noticed HACS has been stuck at the `HACS is starting up` issue. It hasn't gone even after several hours of HA being up. And obviously have HACS installed for years, so not a fresh HACS install.

Apart from the HACS specific debug logs below there is also this error that shows up

```
2022-01-16 14:49:03 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 562, in startup_tasks
    await self.async_load_default_repositories()
  File "/config/custom_components/hacs/base.py", line 706, in async_load_default_repositories
    for item in await self.async_github_get_hacs_default_file(HacsCategory.REMOVED):
  File "/config/custom_components/hacs/base.py", line 441, in async_github_get_hacs_default_file
    response = await self.async_github_api_method(
  File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
    raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/removed
```

### Reproduction steps

N/A

### Debug logs

```text
2022-01-16 14:53:37 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.19.3
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2022-01-16 14:54:05 DEBUG (MainThread) [custom_components.hacs] Configuration type: ConfigurationType.CONFIG_ENTRY
2022-01-16 14:54:06 INFO (MainThread) [custom_components.hacs] Loaded 12 tasks
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] Scheduling HacsTask<check_ratelimit> to run every 1:00:00
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] Scheduling HacsTask<prosess_queue> to run every 0:10:00
2022-01-16 14:54:06 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.SETUP
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_constrains> Executing task
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<restore_data> Executing task
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_sensor> Executing task
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_sensor> took 0.000 seconds to complete
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_websocket_api> Executing task
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_websocket_api> took 0.000 seconds to complete
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_frontend> Executing task
2022-01-16 14:54:06 INFO (MainThread) [custom_components.hacs] HacsTask<setup_frontend> storage mode, cache for /hacsfiles/: True
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_frontend> took 0.006 seconds to complete
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<clear_old_storage> Executing task
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<verify_api> Executing task
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<activate_categories> Executing task
2022-01-16 14:54:06 INFO (MainThread) [custom_components.hacs] Enable category: integration
2022-01-16 14:54:06 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2022-01-16 14:54:06 INFO (MainThread) [custom_components.hacs] Enable category: python_script
2022-01-16 14:54:06 INFO (MainThread) [custom_components.hacs] Enable category: theme
2022-01-16 14:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<activate_categories> took 0.015 seconds to complete
2022-01-16 14:54:07 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_constrains> took 0.534 seconds to complete
2022-01-16 14:54:07 DEBUG (MainThread) [custom_components.hacs] HacsTask<clear_old_storage> took 0.527 seconds to complete
2022-01-16 14:54:08 INFO (MainThread) [custom_components.hacs] Restore started
2022-01-16 14:54:10 DEBUG (MainThread) [custom_components.hacs] HacsTask<verify_api> Can update 266 repositories
2022-01-16 14:54:10 DEBUG (MainThread) [custom_components.hacs] HacsTask<verify_api> took 3.792 seconds to complete
2022-01-16 14:54:11 INFO (MainThread) [custom_components.hacs] Restore done
2022-01-16 14:54:11 DEBUG (MainThread) [custom_components.hacs] HacsTask<restore_data> took 5.083 seconds to complete
2022-01-16 14:54:11 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2022-01-16 14:54:11 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2022-01-16 14:54:26 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2022-01-16 14:54:27 DEBUG (MainThread) [custom_components.hacs] HacsTask<load_hacs_repository> Executing task
2022-01-16 14:54:27 DEBUG (MainThread) [custom_components.hacs] HacsTask<load_hacs_repository> took 0.000 seconds to complete
2022-01-16 14:54:31 INFO (MainThread) [custom_components.hacs] Loading known repositories
2022-01-16 15:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 15:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 15:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 15:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 15:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 15:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 15:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 15:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 15:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 15:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 15:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 15:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 15:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 15:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 15:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 15:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> Executing task
2022-01-16 15:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> HACS is not running
2022-01-16 15:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> took 0.000 seconds to complete
2022-01-16 15:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 15:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 15:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 16:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 16:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 16:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 16:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 16:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 16:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 16:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 16:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 16:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 16:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 16:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 16:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 16:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 16:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 16:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 16:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> Executing task
2022-01-16 16:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> HACS is not running
2022-01-16 16:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> took 0.000 seconds to complete
2022-01-16 16:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 16:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 16:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 17:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 17:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 17:04:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 17:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 17:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 17:14:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.001 seconds to complete
2022-01-16 17:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 17:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 17:24:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 17:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 17:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 17:34:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 17:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-01-16 17:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Nothing in the queue
2022-01-16 17:44:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> took 0.000 seconds to complete
2022-01-16 17:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> Executing task
2022-01-16 17:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> HACS is not running
2022-01-16 17:54:06 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_ratelimit> took 0.000 seconds to complete
```

**Comment by WarC0zes** [comment]
same error:
```
2022-01-17 10:49:56 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/hacs/base.py", line 562, in startup_tasks
await self.async_load_default_repositories()
File "/config/custom_components/hacs/base.py", line 706, in async_load_default_repositories
for item in await self.async_github_get_hacs_default_file(HacsCategory.REMOVED):
File "/config/custom_components/hacs/base.py", line 441, in async_github_get_hacs_default_file
response = await self.async_github_api_method(
File "/config/custom_components/hacs/base.py", line 478, in async_github_api_method
raise HacsException(_exception)
custom_components.hacs.exceptions.HacsException: Timeout of 20 reached while waiting for https://api.github.com/repos/hacs/default/contents/removed
```
After a integration update, I have reboot HA and i have the issue. Reboot several times change nothing.
