### ISSUE TITLE
Cannot install backend integrations

### ISSUE THREAD

**Issue by tslytsly** [hacs/integration#2512]
## System Health

version | core-2022.2.6
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | abc
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.28-Unraid
arch | x86_64
timezone | Europe/London

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.22.0
Stage | running
Available Repositories | 987
Downloaded Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 9
-- | --
resources | 17
views | 29
mode | yaml

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Describe the issue

I cannot update or install the Drayton Wiser integration.
It was working fine, until I went to upgrade it this morning.
I got a 500 server error, `Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`.

I have tried downloading other versions, same result.

I can install the repo on HACs, restart the server, but adding the integration fails.

### Reproduction steps

1. Download Drayton Wiser Repo via HACs
2. Restart HA
3. Add Integration, select Drayton Wiser
4. wait a minute and you will get this error.

### Debug logs

```text
2022-02-15 12:11:39 ERROR (SyncWorker_6) [homeassistant.util.package] Unable to install package wiserHeatAPIv2==0.0.20: ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bffrb9fr/ruamel-yaml-clib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bffrb9fr/ruamel-yaml-clib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lvm0ia8u
cwd: /tmp/pip-install-bffrb9fr/ruamel-yaml-clib/
Complete output (3 lines):
sys.argv ['/tmp/pip-install-bffrb9fr/ruamel-yaml-clib/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-lvm0ia8u']
test compiling /tmp/tmp_ruamel_47zvfkcr/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_47zvfkcr/test_ruamel_yaml.c
Exception: command 'gcc' failed: No such file or directory
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2022-02-15 12:11:47 ERROR (MainThread) [custom_components.fullykiosk.coordinator] Error fetching 192.168.4.158 deviceInfo data: Cannot connect to host 192.168.4.158:2323 ssl:default [Connect call failed ('192.168.4.158', 2323)]
2022-02-15 12:11:57 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package wiserHeatAPIv2==0.0.20: ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ohff041s/ruamel-yaml-clib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ohff041s/ruamel-yaml-clib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cznvrxdl
cwd: /tmp/pip-install-ohff041s/ruamel-yaml-clib/
Complete output (3 lines):
sys.argv ['/tmp/pip-install-ohff041s/ruamel-yaml-clib/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-cznvrxdl']
test compiling /tmp/tmp_ruamel_plc8ngz6/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_plc8ngz6/test_ruamel_yaml.c
Exception: command 'gcc' failed: No such file or directory
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2022-02-15 12:12:16 ERROR (SyncWorker_11) [homeassistant.util.package] Unable to install package wiserHeatAPIv2==0.0.20: ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sgns745k/ruamel-yaml-clib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sgns745k/ruamel-yaml-clib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-2b7pu1sz
cwd: /tmp/pip-install-sgns745k/ruamel-yaml-clib/
Complete output (3 lines):
sys.argv ['/tmp/pip-install-sgns745k/ruamel-yaml-clib/setup.py', 'egg_info', '--egg-base', '/tmp/pip-pip-egg-info-2b7pu1sz']
test compiling /tmp/tmp_ruamel_chlh2tzl/test_ruamel_yaml.c -> test_ruamel_yaml compile error: /tmp/tmp_ruamel_chlh2tzl/test_ruamel_yaml.c
Exception: command 'gcc' failed: No such file or directory
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
2022-02-15 12:12:16 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 219, in auth_middleware
return await handler(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 132, in post
return await super().post(request)
File "/usr/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 72, in post
result = await self._flow_mgr.async_init(
File "/usr/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 203, in async_init
flow, result = await task
File "/usr/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 221, in _async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/lib/python3.9/site-packages/homeassistant/config_entries.py", line 730, in async_create_flow
await async_process_deps_reqs(self.hass, self._hass_config, integration)
File "/usr/lib/python3.9/site-packages/homeassistant/setup.py", line 351, in async_process_deps_reqs
await requirements.async_get_integration_with_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
await _async_process_integration(hass, integration, done)
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 99, in _async_process_integration
await async_process_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 162, in async_process_requirements
await _async_process_requirements(
File "/usr/lib/python3.9/site-packages/homeassistant/requirements.py", line 194, in _async_process_requirements
raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for wiser not found: ['wiserHeatAPIv2==0.0.20'].
```
```


### Diagnostics dump

_No response_

**Comment by ludeeus** [comment]
That has nothing to do with HACS, open an issue with the author of it.

**Comment by tslytsly** [comment]
Thanks ludeeus.
I have opened an issue with the author or the integration.
