### ISSUE TITLE
Developer Tools -> Services -> Error while loading page service

### ISSUE THREAD

**Issue by ClusterM** [hacs/integration#2525]
### Web browser

Google Chrome

### Web browser version

98.0.4758.102 (x64) (cohort: Stable) 

## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.9.2
os_name | Linux
os_version | 5.10.60-sunxi64
arch | aarch64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4949
Installed Version | 1.23.0
Stage | waiting
Available Repositories | 992
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 9
mode | storage

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

The "Services" tab is not working.

### Reproduction steps

1. Click on "Developer Tools"
2. Open "Services" tab

### Screenshots

![image](https://user-images.githubusercontent.com/4236181/155448133-98a4c1f6-886b-4d36-834c-48aaf46d1355.png)

### Javascript logs from your browser console

```text
hass-loading-screen.ts:11 Error loading page service SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at n.addFromStorage (16aeb4c3.js:1:715)
    at 16aeb4c3.js:1:1302
    at Object.decorateElement (ha-expansion-panel.ts:10:1)
    at Object.<anonymous> (ha-expansion-panel.ts:10:1)
    at Array.forEach (<anonymous>)
    at Object.decorateClass (ha-expansion-panel.ts:10:1)
    at ha-expansion-panel.ts:10:1
    at ha-expansion-panel.ts:10:1
    at Function.u.a (styles.ts:368:1)hass-loading-screen.ts:11 Error loading page service SyntaxError:
```

### Diagnostics dump

```JSON
{
  "home_assistant": {
    "installation_type": "Home Assistant Core",
    "version": "2022.2.9",
    "dev": false,
    "hassio": false,
    "virtualenv": true,
    "python_version": "3.9.2",
    "docker": false,
    "arch": "aarch64",
    "timezone": "Europe/Moscow",
    "os_name": "Linux",
    "os_version": "5.10.60-sunxi64",
    "run_as_root": false
  },
  "custom_components": {
    "ready4sky": {
      "version": "1.0",
      "requirements": [
        "bluepy"
      ]
    },
    "localtuya": {
      "version": "3.2.1",
      "requirements": []
    },
    "moon_lamp": {
      "version": "1.0",
      "requirements": []
    },
    "yandex_station": {
      "version": "3.9.0",
      "requirements": []
    },
    "mikrotik_router": {
      "version": "0.0.0",
      "requirements": [
        "librouteros==3.0.0",
        "mac-vendor-lookup==0.1.11"
      ]
    },
    "tuya_ir": {
      "version": "1.0",
      "requirements": [
        "asyncio==3.4.3"
      ]
    },
    "doorbell": {
      "version": "1.0",
      "requirements": []
    },
    "wake_on_lan_my": {
      "version": "1.0",
      "requirements": [
        "wakeonlan==2.0.1"
      ]
    },
    "wake_on_lan_ez": {
      "version": "1.0",
      "requirements": [
        "wakeonlan==2.0.1",
        "netifaces==0.11.0"
      ]
    },
    "philips_tv": {
      "version": "1.0",
      "requirements": []
    },
    "yandex_dialogs": {
      "version": "1.2",
      "requirements": []
    },
    "hacs": {
      "version": "1.23.0",
      "requirements": [
        "aiogithubapi>=21.11.0"
      ]
    },
    "skykettle": {
      "version": "1.0",
      "requirements": [
        "pexpect==4.8.0"
      ]
    },
    "yandex_smart_home": {
      "version": "0.3.7",
      "requirements": []
    }
  },
  "integration_manifest": {
    "codeowners": [
      "@ludeeus"
    ],
    "config_flow": true,
    "dependencies": [
      "http",
      "websocket_api",
      "frontend",
      "persistent_notification",
      "lovelace"
    ],
    "documentation": "https://hacs.xyz/docs/configuration/start",
    "domain": "hacs",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/hacs/integration/issues",
    "name": "HACS",
    "requirements": [
      "aiogithubapi>=21.11.0"
    ],
    "version": "1.23.0",
    "is_built_in": false
  },
  "data": {
    "entry": {
      "entry_id": "db29dfc36bc6cffa56d9e080682664e6",
      "version": 1,
      "domain": "hacs",
      "title": "",
      "data": {
        "token": "**REDACTED**"
      },
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "unique_id": null,
      "disabled_by": null
    },
    "hacs": {
      "stage": "running",
      "version": "1.23.0",
      "disabled_reason": null,
      "new": false,
      "startup": false,
      "categories": [
        "plugin",
        "theme",
        "integration"
      ],
      "renamed_repositories": {
        "9a4gl/hass-peltec": "9a4gl/hass-centrometal-boiler",
        "78wesley/Darkish-Theme": "78wesley/Home-Assistant-Darkish-Theme",
        "KartoffelToby/ai_thermostat": "KartoffelToby/better_thermostat",
        "nbogojevic/homeassistant-midea-dehumidifier-lan": "nbogojevic/homeassistant-midea-air-appliances-lan",
        "ClusterM/skykettle_ha": "ClusterM/skykettle-ha"
      },
      "archived_repositories": [
        "dr1rrb/ha-twinkly",
        "heinoldenhuis/home_assistant_omnik_solar"
      ],
      "ignored_repositories": [],
      "lovelace_mode": "storage",
      "configuration": {
        "appdaemon": false,
        "country": "ALL",
        "debug": false,
        "dev": false,
        "experimental": false,
        "netdaemon": false,
        "python_script": false,
        "release_limit": 5,
        "theme": false
      }
    },
    "custom_repositories": [
      "dr1rrb/ha-twinkly"
    ],
    "repositories": [
      {
        "data": {
          "archived": false,
          "authors": [
            "@ludeeus"
          ],
          "category": "integration",
          "content_in_root": false,
          "country": [],
          "config_flow": true,
          "default_branch": "main",
          "description": "HACS gives you a powerful UI to handle downloads of all your custom needs.",
          "domain": "hacs",
          "domains": [],
          "downloads": 11975,
          "etag_repository": "W/\"1c3e86c840757d423e5c023ef53ce87a5e9c6002b3f27188d9fe6c33453a899a\"",
          "file_name": "",
          "filename": "hacs.zip",
          "first_install": false,
          "fork": false,
          "full_name": "hacs/integration",
          "hacs": "0.19.0",
          "hide": false,
          "hide_default_branch": true,
          "homeassistant": "2021.9.0",
          "id": "172733314",
          "iot_class": null,
          "installed": true,
          "installed_commit": "da79607",
          "installed_version": "1.23.0",
          "open_issues": 1,
          "last_commit": "da1512e",
          "last_version": "1.23.0",
          "last_updated": "2022-02-23T12:22:33Z",
          "manifest_name": "HACS",
          "new": false,
          "persistent_directory": null,
          "pushed_at": "2022-02-23T12:22:33",
          "releases": true,
          "render_readme": false,
          "published_tags": [
            "1.23.0",
            "1.22.0",
            "1.21.0",
            "1.20.0",
            "1.19.3"
          ],
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 2303,
          "topics": [
            "community",
            "hacktoberfest",
            "hacs",
            "home-assistant",
            "integration",
            "package-manager",
            "python"
          ],
          "zip_release": true
        },
        "integration_manifest": {},
        "repository_manifest": {
          "name": "HACS",
          "content_in_root": false,
          "zip_release": true,
          "filename": "hacs.zip",
          "manifest": {
            "name": "HACS",
            "zip_release": true,
            "hide_default_branch": true,
            "homeassistant": "2021.9.0",
            "hacs": "0.19.0",
            "filename": "hacs.zip"
          },
          "hacs": "0.19.0",
          "hide_default_branch": true,
          "domains": [],
          "country": [],
          "homeassistant": "2021.9.0",
          "persistent_directory": null,
          "iot_class": null,
          "render_readme": false
        },
        "ref": "1.23.0",
        "paths": {
          "localpath": "/config/custom_components/hacs",
          "local": "/config/custom_components/hacs",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "content_in_root": false,
          "country": [],
          "config_flow": false,
          "default_branch": "master",
          "description": "Sets the background of your Home Assistant to match the entity picture of a media player",
          "domain": "",
          "domains": [],
          "downloads": 0,
          "etag_repository": "W/\"ce7e3f536de6126fc9d064e658ee098fcfd10eedff9b242191082d4d91ef160d\"",
          "file_name": "media-art-background.js",
          "filename": "",
          "first_install": false,
          "fork": false,
          "full_name": "TheLastProject/lovelace-media-art-background",
          "hacs": null,
          "hide": false,
          "hide_default_branch": false,
          "homeassistant": null,
          "id": "202874270",
          "iot_class": null,
          "installed": true,
          "installed_commit": "d5137b0",
          "installed_version": null,
          "open_issues": 3,
          "last_commit": "d5137b0",
          "last_version": null,
          "last_updated": "2021-04-14T16:38:05Z",
          "manifest_name": null,
          "new": false,
          "persistent_directory": null,
          "pushed_at": "2021-04-14T16:38:05",
          "releases": false,
          "render_readme": false,
          "published_tags": [],
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 18,
          "topics": [],
          "zip_release": false
        },
        "integration_manifest": {},
        "repository_manifest": {
          "name": null,
          "content_in_root": false,
          "zip_release": false,
          "filename": null,
          "manifest": {},
          "hacs": null,
          "hide_default_branch": false,
          "domains": [],
          "country": [],
          "homeassistant": null,
          "persistent_directory": null,
          "iot_class": null,
          "render_readme": false
        },
        "ref": "master",
        "paths": {
          "localpath": "/config/www/community/lovelace-media-art-background",
          "local": "/config/www/community/lovelace-media-art-background",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [],
          "category": "plugin",
          "content_in_root": false,
          "country": [],
          "config_flow": false,
          "default_branch": "master",
          "description": "\ud83d\udd39 Add CSS styles to (almost) any lovelace card",
          "domain": "",
          "domains": [],
          "downloads": 0,
          "etag_repository": "W/\"1940b6b8ddc8cffcfd5365f4c7bd0d8c7f9415c3cb7c93b0cd270899ed93b4a7\"",
          "file_name": "card-mod.js",
          "filename": null,
          "first_install": false,
          "fork": false,
          "full_name": "thomasloven/lovelace-card-mod",
          "hacs": null,
          "hide": false,
          "hide_default_branch": false,
          "homeassistant": "0.98.0",
          "id": "190927524",
          "iot_class": null,
          "installed": true,
          "installed_commit": "9748f1c",
          "installed_version": "3.1.2",
          "open_issues": 24,
          "last_commit": "9748f1c",
          "last_version": "3.1.2",
          "last_updated": "2022-02-07T22:29:22Z",
          "manifest_name": null,
          "new": false,
          "persistent_directory": null,
          "pushed_at": "2022-02-07T22:29:22",
          "releases": true,
          "render_readme": false,
          "published_tags": [
            "3.1.2",
            "3.1.1",
            "3.1.0",
            "3.0.13",
            "3.0.12"
          ],
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 444,
          "topics": [],
          "zip_release": false
        },
        "integration_manifest": {},
        "repository_manifest": {
          "name": "card-mod",
          "content_in_root": false,
          "zip_release": false,
          "filename": null,
          "manifest": {
            "name": "card-mod",
            "homeassistant": "0.98.0"
          },
          "hacs": null,
          "hide_default_branch": false,
          "domains": [],
          "country": [],
          "homeassistant": "0.98.0",
          "persistent_directory": null,
          "iot_class": null,
          "render_readme": false
        },
        "ref": "3.1.2",
        "paths": {
          "localpath": "/config/www/community/lovelace-card-mod",
          "local": "/config/www/community/lovelace-card-mod",
          "remote": null
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@AlexxIT"
          ],
          "category": "integration",
          "content_in_root": false,
          "country": [
            "RU"
          ],
          "config_flow": true,
          "default_branch": "master",
          "description": "\u0423\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u042f\u043d\u0434\u0435\u043a\u0441.\u0421\u0442\u0430\u043d\u0446\u0438\u0435\u0439 \u0438 \u0434\u0440\u0443\u0433\u0438\u043c\u0438 \u043a\u043e\u043b\u043e\u043d\u043a\u0430\u043c\u0438 \u0441 \u0410\u043b\u0438\u0441\u043e\u0439 \u0438\u0437 Home Assistant",
          "domain": "yandex_station",
          "domains": [],
          "downloads": 0,
          "etag_repository": "W/\"272afc7b09ed0fc622fa3cb4ceba5d20a7bacf898d5c907fc387b720e438ba93\"",
          "file_name": "",
          "filename": null,
          "first_install": false,
          "fork": false,
          "full_name": "AlexxIT/YandexStation",
          "hacs": null,
          "hide": false,
          "hide_default_branch": false,
          "homeassistant": null,
          "id": "236572107",
          "iot_class": null,
          "installed": true,
          "installed_commit": "20f0452",
          "installed_version": "v3.9.0",
          "open_issues": 34,
          "last_commit": "20f0452",
          "last_version": "v3.9.0",
          "last_updated": "2022-02-18T14:23:15Z",
          "manifest_name": "Yandex.Station",
          "new": false,
          "persistent_directory": null,
          "pushed_at": "2022-02-18T14:23:15",
          "releases": true,
          "render_readme": true,
          "published_tags": [
            "v3.9.0",
            "v3.8.0",
            "v3.7.0",
            "v3.6.2",
            "v3.6.1"
          ],
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 676,
          "topics": [
            "hacs",
            "home-assistant",
            "tts",
            "yandex-station"
          ],
          "zip_release": false
        },
        "integration_manifest": {},
        "repository_manifest": {
          "name": "Yandex.Station",
          "content_in_root": false,
          "zip_release": false,
          "filename": null,
          "manifest": {
            "name": "Yandex.Station",
            "render_readme": true,
            "country": [
              "RU"
            ]
          },
          "hacs": null,
          "hide_default_branch": false,
          "domains": [],
          "country": [
            "RU"
          ],
          "homeassistant": null,
          "persistent_directory": null,
          "iot_class": null,
          "render_readme": true
        },
        "ref": "v3.9.0",
        "paths": {
          "localpath": "/config/custom_components/yandex_station",
          "local": "/config/custom_components/yandex_station",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@dmitry-k",
            "@dext0r"
          ],
          "category": "integration",
          "content_in_root": false,
          "country": [
            "RU",
            "BY"
          ],
          "config_flow": true,
          "default_branch": "master",
          "description": "Adds support for Yandex Smart Home (Alice voice assistant) into Home Assistant",
          "domain": "yandex_smart_home",
          "domains": [],
          "downloads": 0,
          "etag_repository": "W/\"5fcc96b72752707bbc7a08232442a97f6467459450a9955470b5823f08342b05\"",
          "file_name": "",
          "filename": null,
          "first_install": false,
          "fork": false,
          "full_name": "dmitry-k/yandex_smart_home",
          "hacs": null,
          "hide": false,
          "hide_default_branch": false,
          "homeassistant": "2021.7",
          "id": "188698828",
          "iot_class": null,
          "installed": true,
          "installed_commit": "86e3eba",
          "installed_version": null,
          "open_issues": 8,
          "last_commit": "86e3eba",
          "last_version": "v0.3.7",
          "last_updated": "2022-02-21T05:59:42Z",
          "manifest_name": "Yandex Smart Home",
          "new": false,
          "persistent_directory": null,
          "pushed_at": "2022-02-21T05:59:42",
          "releases": true,
          "render_readme": true,
          "published_tags": [
            "v0.3.7",
            "v0.3.6",
            "v0.3.5",
            "v0.3.4",
            "v0.3.3"
          ],
          "selected_tag": "master",
          "show_beta": false,
          "stargazers_count": 486,
          "topics": [
            "alice",
            "home-assistant-component",
            "voice-assistant",
            "yandex"
          ],
          "zip_release": false
        },
        "integration_manifest": {},
        "repository_manifest": {
          "name": "Yandex Smart Home",
          "content_in_root": false,
          "zip_release": false,
          "filename": null,
          "manifest": {
            "country": [
              "RU",
              "BY"
            ],
            "homeassistant": "2021.7",
            "name": "Yandex Smart Home",
            "render_readme": true
          },
          "hacs": null,
          "hide_default_branch": false,
          "domains": [],
          "country": [
            "RU",
            "BY"
          ],
          "homeassistant": "2021.7",
          "persistent_directory": null,
          "iot_class": null,
          "render_readme": true
        },
        "ref": "master",
        "paths": {
          "localpath": "/config/custom_components/yandex_smart_home",
          "local": "/config/custom_components/yandex_smart_home",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@rospogrigio",
            "@postlund"
          ],
          "category": "integration",
          "content_in_root": false,
          "country": [],
          "config_flow": true,
          "default_branch": "master",
          "description": "local handling for Tuya devices",
          "domain": "localtuya",
          "domains": [
            "climate",
            "cover",
            "fan",
            "light",
            "number",
            "select",
            "sensor",
            "switch"
          ],
          "downloads": 0,
          "etag_repository": "W/\"c6d1fa16854cdc86d6844d359dbc6189d8a5a40d67c74e2692d3981fbb66c5bd\"",
          "file_name": "",
          "filename": null,
          "first_install": false,
          "fork": true,
          "full_name": "rospogrigio/localtuya",
          "hacs": null,
          "hide": false,
          "hide_default_branch": false,
          "homeassistant": "0.116.0",
          "id": "249381778",
          "iot_class": [
            "Local Push"
          ],
          "installed": true,
          "installed_commit": "2688a17",
          "installed_version": "v3.4.0",
          "open_issues": 394,
          "last_commit": "2688a17",
          "last_version": "v3.4.0",
          "last_updated": "2022-02-24T02:27:33Z",
          "manifest_name": "LocalTuya integration",
          "new": false,
          "persistent_directory": null,
          "pushed_at": "2022-02-24T02:27:33",
          "releases": true,
          "render_readme": false,
          "published_tags": [
            "v3.4.0",
            "v3.3.0",
            "v3.2.4",
            "v3.2.3",
            "v3.2.2"
          ],
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 959,
          "topics": [
            "localtuya",
            "tuya",
            "tuya-api"
          ],
          "zip_release": false
        },
        "integration_manifest": {},
        "repository_manifest": {
          "name": "Local Tuya",
          "content_in_root": false,
          "zip_release": false,
          "filename": null,
          "manifest": {
            "name": "Local Tuya",
            "domains": [
              "climate",
              "cover",
              "fan",
              "light",
              "number",
              "select",
              "sensor",
              "switch"
            ],
            "homeassistant": "0.116.0",
            "iot_class": [
              "Local Push"
            ]
          },
          "hacs": null,
          "hide_default_branch": false,
          "domains": [
            "climate",
            "cover",
            "fan",
            "light",
            "number",
            "select",
            "sensor",
            "switch"
          ],
          "country": [],
          "homeassistant": "0.116.0",
          "persistent_directory": null,
          "iot_class": [
            "Local Push"
          ],
          "render_readme": false
        },
        "ref": "v3.4.0",
        "paths": {
          "localpath": "/config/custom_components/localtuya",
          "local": "/config/custom_components/localtuya",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@tomaae"
          ],
          "category": "integration",
          "content_in_root": false,
          "country": [],
          "config_flow": true,
          "default_branch": "master",
          "description": "Mikrotik router integration for Home Assistant",
          "domain": "mikrotik_router",
          "domains": [
            "device_tracker",
            "switch",
            "button",
            "sensor",
            "binary_sensor"
          ],
          "downloads": 2191,
          "etag_repository": "W/\"294530ff869028d3eab0d62926fe8f810a255ec2a854f00d1c1cc73a9fe59dfd\"",
          "file_name": "",
          "filename": "mikrotik_router.zip",
          "first_install": false,
          "fork": false,
          "full_name": "tomaae/homeassistant-mikrotik_router",
          "hacs": null,
          "hide": false,
          "hide_default_branch": false,
          "homeassistant": "2021.12.1",
          "id": "225248441",
          "iot_class": "local_poll",
          "installed": true,
          "installed_commit": "5db1c78",
          "installed_version": "v1.8",
          "open_issues": 8,
          "last_commit": "2905acd",
          "last_version": "v1.8",
          "last_updated": "2022-02-20T04:39:52Z",
          "manifest_name": "Mikrotik Router",
          "new": false,
          "persistent_directory": null,
          "pushed_at": "2022-02-20T04:39:52",
          "releases": true,
          "render_readme": false,
          "published_tags": [
            "v1.8",
            "1.7.3",
            "1.7.2",
            "1.7.1",
            "1.7"
          ],
          "selected_tag": null,
          "show_beta": false,
          "stargazers_count": 113,
          "topics": [
            "hacs",
            "homeassistant",
            "homeassistant-components",
            "homeassistant-integration",
            "mikrotik"
          ],
          "zip_release": true
        },
        "integration_manifest": {},
        "repository_manifest": {
          "name": "Mikrotik Router",
          "content_in_root": false,
          "zip_release": true,
          "filename": "mikrotik_router.zip",
          "manifest": {
            "name": "Mikrotik Router",
            "homeassistant": "2021.12.1",
            "iot_class": "local_poll",
            "domains": [
              "device_tracker",
              "switch",
              "button",
              "sensor",
              "binary_sensor"
            ],
            "render_readme": false,
            "zip_release": true,
            "filename": "mikrotik_router.zip"
          },
          "hacs": null,
          "hide_default_branch": false,
          "domains": [
            "device_tracker",
            "switch",
            "button",
            "sensor",
            "binary_sensor"
          ],
          "country": [],
          "homeassistant": "2021.12.1",
          "persistent_directory": null,
          "iot_class": "local_poll",
          "render_readme": false
        },
        "ref": "v1.8",
        "paths": {
          "localpath": "/config/custom_components/mikrotik_router",
          "local": "/config/custom_components/mikrotik_router",
          "remote": "custom_components"
        }
      },
      {
        "data": {
          "archived": false,
          "authors": [
            "@clusterm"
          ],
          "category": "integration",
          "content_in_root": false,
          "country": [
            "RU"
          ],
          "config_flow": true,
          "default_branch": "master",
          "description": "Redmond SkyKettle integration for Home Assistant",
          "domain": "skykettle",
          "domains": [],
          "downloads": 0,
          "etag_repository": "W/\"552b172288a809e47d4852cdae6201889f6b32301d2af63ee2214db4fb4a6067\"",
          "file_name": "",
          "filename": null,
          "first_install": false,
          "fork": false,
          "full_name": "ClusterM/skykettle-ha",
          "hacs": null,
          "hide": false,
          "hide_default_branch": false,
          "homeassistant": "2021.12.3",
          "id": "450192057",
          "iot_class": null,
          "installed": true,
          "installed_commit": "e4e96b5",
          "installed_version": "v1.1",
          "open_issues": 4,
          "last_commit": "9834fbf",
          "last_version": "v1.3",
          "last_updated": "2022-02-20T12:44:15Z",
          "manifest_name": "SkyKettle",
          "new": false,
          "persistent_directory": null,
          "pushed_at": "2022-02-20T12:44:15",
          "releases": true,
          "render_readme": true,
          "published_tags": [
            "v1.3",
            "v1.2",
            "v1.1b",
            "v1.0"
          ],
          "selected_tag": null,
          "show_beta": true,
          "stargazers_count": 14,
          "topics": [
            "kettle",
            "redmond",
            "skykettle"
          ],
          "zip_release": false
        },
        "integration_manifest": {},
        "repository_manifest": {
          "name": "SkyKettle",
          "content_in_root": false,
          "zip_release": false,
          "filename": null,
          "manifest": {
            "name": "SkyKettle",
            "homeassistant": "2021.12.3",
            "render_readme": true,
            "country": [
              "RU"
            ]
          },
          "hacs": null,
          "hide_default_branch": false,
          "domains": [],
          "country": [
            "RU"
          ],
          "homeassistant": "2021.12.3",
          "persistent_directory": null,
          "iot_class": null,
          "render_readme": true
        },
        "ref": "v1.3",
        "paths": {
          "localpath": "/config/custom_components/skykettle",
          "local": "/config/custom_components/skykettle",
          "remote": "custom_components"
        }
      }
    ],
    "rate_limit": {
      "resources": {
        "core": {
          "limit": 5000,
          "used": 102,
          "remaining": 4898,
          "reset": 1645674996
        },
        "search": {
          "limit": 30,
          "used": 0,
          "remaining": 30,
          "reset": 1645672070
        },
        "graphql": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1645675610
        },
        "integration_manifest": {
          "limit": 5000,
          "used": 0,
          "remaining": 5000,
          "reset": 1645675610
        },
        "source_import": {
          "limit": 100,
          "used": 0,
          "remaining": 100,
          "reset": 1645672070
        },
        "code_scanning_upload": {
          "limit": 1000,
          "used": 0,
          "remaining": 1000,
          "reset": 1645675610
        }
      },
      "rate": {
        "limit": 5000,
        "used": 102,
        "remaining": 4898,
        "reset": 1645674996
      }
    }
  }
}
```

**Comment by ludeeus** [comment]
This is not a part of HACS.

**Comment by ClusterM** [comment]
Ouch. I'm an idiot, log says "hass", not "hacs". Sorry.
