### ISSUE TITLE
HACS integration not working

### ISSUE THREAD

**Issue by niyazialpay** [hacs/integration#2550]
## System Health

version | core-2022.3.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8+
arch | aarch64
timezone | Europe/Istanbul

<details><summary>Home Assistant Community Store</summary>

error | failed to load: unknown
-- | --

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 15

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.12
disk_total | 28.1 GB
disk_used | 12.3 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.3.0), Let's Encrypt (4.12.0), Spotify Connect (0.10.0), AdGuard Home (4.4.6), Vaultwarden (Bitwarden) (0.15.0), Studio Code Server (4.1.0), ESPHome (2022.2.6), NGINX Home Assistant SSL proxy (3.1.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 4
views | 4
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS integration not working

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Logger: homeassistant.config_entries
Source: custom_components/hacs/utils/store.py:8
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 12:04:19 AM (2 occurrences)
Last logged: 12:06:25 AM

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 39, in async_setup_entry
    return await hacs_ui_setup(hass, config_entry)
  File "/config/custom_components/hacs/operational/setup.py", line 94, in async_setup_entry
    await _async_common_setup(hass)
  File "/config/custom_components/hacs/operational/setup.py", line 50, in _async_common_setup
    await hacs.tasks.async_load()
  File "/config/custom_components/hacs/tasks/manager.py", line 43, in async_load
    await asyncio.gather(*[_load_module(task) for task in task_modules])
  File "/config/custom_components/hacs/tasks/manager.py", line 39, in _load_module
    task_module = import_module(f"{__package__}.{module}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hacs/tasks/update_critical_repositories.py", line 10, in <module>
    from custom_components.hacs.utils.store import (
  File "/config/custom_components/hacs/utils/store.py", line 8, in <module>
    from .logger import get_hacs_logger
ImportError: cannot import name 'get_hacs_logger' from 'custom_components.hacs.utils.logger' (/config/custom_components/hacs/utils/logger.py)
```

### Diagnostics dump

I can't download diognostics dump.
![image](https://user-images.githubusercontent.com/8478032/157118112-06bfa40d-1113-4c14-b659-41b252fe856e.png)

**Comment by ludeeus** [comment]
Your installation is not supported.
You can try running the download script again.
https://hacs.xyz/docs/setup/download
