### ISSUE TITLE
Installed components not detected by hacs

### ISSUE THREAD

**Issue by heroxy2111** [hacs/integration#2551]
## System Health

version | core-2022.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.92-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 0
Installed Version | 1.20.0
Stage | running
Available Repositories | 410
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 9. März 2022, 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 27.8 GB
disk_used | 15.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.105.2), File editor (5.3.3), Samba share (9.5.1), Terminal & SSH (9.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 3
views | 2
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

After installing a custom component through hacs it will not show up in hacs itself so I can't update it. 
![image](https://user-images.githubusercontent.com/77335261/157250691-5b89bab3-93ed-4f94-ba99-c31cc9e17157.png)

I already tried removing hacs using https://hacs.xyz/docs/setup/remove and reinstalled it, also tried reinstalling by deleting all custom_components manually using ssh. The issue continues to stay.

The issue first occured after updating to hassio 2021.12.0.

### Reproduction steps

Really no idea sorry.

### Debug logs

```text
2022-03-08 14:35:23 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration meross_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-08 14:35:23 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-08 14:35:23 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-08 14:35:23 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration spacex which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-08 14:35:23 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-08 14:35:23 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration xiaomi_miot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-03-08 14:35:35 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2022-03-08 14:35:45 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.20.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2022-03-08 14:35:46 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.
2022-03-08 14:35:47 WARNING (MainThread) [homeassistant.setup] Setup of coronavirus is taking over 10 seconds.
2022-03-08 14:35:47 WARNING (MainThread) [homeassistant.setup] Setup of zone is taking over 10 seconds.
2022-03-08 14:35:48 DEBUG (MainThread) [custom_components.hacs] Configuration type: ConfigurationType.CONFIG_ENTRY
2022-03-08 14:35:48 WARNING (MainThread) [homeassistant.setup] Setup of input_text is taking over 10 seconds.
2022-03-08 14:35:48 DEBUG (MainThread) [custom_components.hacs] Scheduling HacsTask<prosess_queue> to run every 0:10:00
2022-03-08 14:35:48 DEBUG (MainThread) [custom_components.hacs] Scheduling HacsTask<check_ratelimit> to run every 1:00:00
2022-03-08 14:35:48 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.SETUP
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<restore_data> Executing task
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_sensor> Executing task
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_sensor> took 0.000 seconds to complete
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<clear_old_storage> Executing task
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<verify_api> Executing task
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<activate_categories> Executing task
2022-03-08 14:35:49 INFO (MainThread) [custom_components.hacs] Enable category: integration
2022-03-08 14:35:49 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2022-03-08 14:35:49 INFO (MainThread) [custom_components.hacs] Enable category: theme
2022-03-08 14:35:49 INFO (MainThread) [custom_components.hacs] Enable category: appdaemon
2022-03-08 14:35:49 INFO (MainThread) [custom_components.hacs] Enable category: netdaemon
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<activate_categories> took 0.003 seconds to complete
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_constrains> Executing task
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_frontend> Executing task
2022-03-08 14:35:49 INFO (MainThread) [custom_components.hacs] HacsTask<setup_frontend> storage mode, cache for /hacsfiles/: True
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_frontend> took 0.007 seconds to complete
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_websocket_api> Executing task
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<setup_websocket_api> took 0.000 seconds to complete
022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<check_constrains> took 0.207 seconds to complete
2022-03-08 14:35:49 DEBUG (MainThread) [custom_components.hacs] HacsTask<clear_old_storage> took 0.215 seconds to complete
2022-03-08 14:35:52 ERROR (SyncWorker_6) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs.repositories
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 33, in load_json
    return json.loads(fdesc.read())  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1864 column 2 (char 86667)
2022-03-08 14:35:52 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(200907762XXXXXXXXXXXe92fe75e) has incorrect timestamp: 4294978 seconds behind HA
2022-03-08 14:35:52 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(201023880XXXXXXXXXXXXe93812e8) has incorrect timestamp: 25769751 seconds behind HA
2022-03-08 14:35:52 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(20102358XXXXXXXXXXXX1e9380cd3) has incorrect timestamp: 25769776 seconds behind HA
2022-03-08 14:35:52 ERROR (MainThread) [custom_components.hacs] HacsTask<restore_data> failed: Extra data: line 1864 column 2 (char 86667)
2022-03-08 14:35:53 DEBUG (MainThread) [custom_components.hacs] HacsTask<verify_api> Can update 68 repositories
2022-03-08 14:35:53 DEBUG (MainThread) [custom_components.hacs] HacsTask<verify_api> took 4.229 seconds to complete
2022-03-08 14:35:53 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2022-03-08 14:35:53 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2022-03-08 14:35:53 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(2010235XXXXXXXXXXX938255a) has incorrect timestamp: 25769754 seconds behind HA
2022-03-08 14:35:53 WARNING (MainThread) [custom_components.meross_lan] MerossDevice(20102394XXXXXXXXXX1e9380e3c) has incorrect timestamp: 25769895 seconds behind HA
2022-03-08 14:35:55 INFO (MainThread) [custom_components.spacex] Setting up platform: binary_sensor
2022-03-08 14:35:55 INFO (MainThread) [custom_components.spacex] Setting up platform: sensor
2022-03-08 14:36:03 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2022-03-08 14:36:03 DEBUG (MainThread) [custom_components.hacs] HacsTask<load_hacs_repository> Executing task
2022-03-08 14:36:03 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Checking repository.
2022-03-08 14:36:04 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.20.0
2022-03-08 14:36:05 DEBUG (MainThread) [custom_components.hacs] Loaded 5 validators for <Integration hacs/integration>
2022-03-08 14:36:05 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> All (0) checks passed
2022-03-08 14:36:10 INFO (MainThread) [custom_components.hacs] <Integration hacs/integration> Registration completed
2022-03-08 14:36:10 DEBUG (MainThread) [custom_components.hacs] HacsTask<load_hacs_repository> took 6.594 seconds to complete
2022-03-08 14:36:10 INFO (MainThread) [custom_components.hacs] Loading known repositories
2022-03-08 14:36:10 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Executing task
2022-03-08 14:36:10 DEBUG (MainThread) [custom_components.hacs] HacsTask<prosess_queue> Can update 67 repositories, items in queue 5
2022-03-08 14:36:10 DEBUG (MainThread) [custom_components.hacs] Checking out tasks to execute
[...]
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin tomasrudh/analogclock> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-card-tools> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin tomvanswam/compass-card> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-fold-entity-row> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin totaldebug/atomic-calendar-revive> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-hui-element> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin tungmeister/hass-blind-card> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-layout-card> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin turbulator/pandora-cas-card> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-more-info-card> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin twrecked/lovelace-hass-aarlo> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-slider-entity-row> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin Villhellm/custom-sidebar> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-state-switch> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin Villhellm/lovelace-animated-background> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-template-entity-row> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin Villhellm/lovelace-clock-card> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin tmjo/charger-card> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin Voxxie/lovelace-jumbo-card> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin tomasrudh/analogclock> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-digital-clock> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin tomvanswam/compass-card> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-entities-btn-group> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin tungmeister/hass-blind-card> GitHub Ratelimit error
2022-03-08 14:41:10 DEBUG (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> Checking repository.
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin totaldebug/atomic-calendar-revive> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin turbulator/pandora-cas-card> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin twrecked/lovelace-hass-aarlo> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin Villhellm/custom-sidebar> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin Villhellm/lovelace-clock-card> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin Villhellm/lovelace-animated-background> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin Voxxie/lovelace-jumbo-card> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-digital-clock> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-entities-btn-group> GitHub Ratelimit error
2022-03-08 14:41:10 ERROR (MainThread) [custom_components.hacs] <Plugin wassy92x/lovelace-ha-dashboard> GitHub Ratelimit error
```

### Diagnostics dump

[config_entry-hacs-57a6ad24ba70ec85a30006f3507de2ca.json.txt](https://github.com/hacs/integration/files/8206887/config_entry-hacs-57a6ad24ba70ec85a30006f3507de2ca.json.txt)

**Comment by heroxy2111** [comment]
Thanks for your reply! I got no backup from three months ago. Would it help to reinstall hacs to create a new one?

**Comment by ludeeus** [comment]
You can delete the file and restart Home Assistant, HACS will recreate it, but that file is what it use to track repositories so everything will be lost.
_Side note: You should really really really have backups ;)_

**Comment by heroxy2111** [comment]
Haha I create backups and also automatically upload them to Google Drive but only of the last few days. But the issue occurred earlier than the last backup I got ^^
Thanks for your help!
