### ISSUE TITLE
[feature request] Proxy settings for downloading integrations

### ISSUE THREAD

**Issue by WordlessEcho** [hacs/integration#2677]
## System Health

version | core-2022.5.4
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | echo
virtualenv | true
python_version | 3.9.2
os_name | Linux
os_version | 5.16.0-0.bpo.4-amd64
arch | x86_64
timezone | Asia/Shanghai

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: unreachable
GitHub Web | pending
GitHub API Calls Remaining | 4887
Installed Version | 1.24.5
Stage | running
Available Repositories | 1128
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | pending
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Xiaomi MIoT</summary>

logged_in | true
-- | --
can_reach_micloud_server | ok
accounts_count | 1
account_devices_count | 3
added_devices | 2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

It is very hard to access https://raw.githubusercontent.com/ for some reigon. I hope HACS could add some options of proxy settings for integrations download.
There is a familiar issue #2436

### Reproduction steps

1. Network behind the firewall.
2. Download integrations.

### Debug logs

```text
2022-05-18 23:34:19 ERROR (MainThread) [custom_components.hacs] Download failed - Cannot connect to host raw.githubusercontent.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'raw.githubusercontent.com'. (_ssl.c:1123)")]
Traceback (most recent call last):
File "/home/echo/.local/pipx/venvs/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
File "/usr/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
transport, protocol = await self._create_connection_transport(
File "/usr/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
await waiter
File "/usr/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
ssldata, appdata = self._sslpipe.feed_ssldata(data)
File "/usr/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
self._sslobj.do_handshake()
File "/usr/lib/python3.9/ssl.py", line 944, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'raw.githubusercontent.com'. (_ssl.c:1123)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/echo/.homeassistant/custom_components/hacs/base.py", line 605, in async_download_file
request = await self.session.get(
File "/home/echo/.local/pipx/venvs/homeassistant/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
conn = await self._connector.connect(
File "/home/echo/.local/pipx/venvs/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
proto = await self._create_connection(req, traces, timeout)
File "/home/echo/.local/pipx/venvs/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
File "/home/echo/.local/pipx/venvs/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
raise last_exc
File "/home/echo/.local/pipx/venvs/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
File "/home/echo/.local/pipx/venvs/homeassistant/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host raw.githubusercontent.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'raw.githubusercontent.com'. (_ssl.c:1123)")]
```

**Comment by ludeeus** [comment]
HACS does not do networking.
Proxying is something that will not be added to it.
Remember that this is just a small  module that runs inside Home Assistant.

**Comment by WordlessEcho** [comment]
For everyone who met this problem, see [Support HTTP Proxy - Feature Requests - Home Assistant Community](https://community.home-assistant.io/t/support-http-proxy/204661/2):

> I added this trust_env and it works. I would be glad if someone else suggests if this is a good idea or not.
>
> As [@frenck](https://community.home-assistant.io/u/frenck) said in [here 107](https://github.com/home-assistant/core/issues/36788) the above suggestion may not work in all situations as there is no control over third party libraries and they way they make HTTP requests.
>
> But I think at least we can have this option so that the official and most of the add-ons will support HTTP proxy and if an add-on will not work someone reports an issue and can fix it. Also python-requests library respects HTTP_PROXY by default without any configuration.

If you are using systemd to start HASS, those may be useful:
- [PassEnvironment= - systemd.exec](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PassEnvironment=)
- [Pass an environment variable from current shell to a systemd unit - Unix & Linux Stack Exchange](https://unix.stackexchange.com/a/383436)
- [set-environment _VARIABLE=VALUE…_ - systemctl](https://www.freedesktop.org/software/systemd/man/systemctl.html#set-environment%20VARIABLE=VALUE%E2%80%A6)

**Comment by WordlessEcho** [comment]
Unfortunatly, it seems that HACS does not respect environment proxy settings. I decide to edit codes directly. ([HACS更新后怎么添加代理从而顺畅下载 - 『HomeAssistant』综合讨论区 -  『瀚思彼岸』» 智能家居技术论坛 -  Powered by Discuz!](https://bbs.hassbian.com/thread-15358-1-1.html)).
In [line 693 of base.py](https://github.com/hacs/integration/blob/main/custom_components/hacs/base.py#L693):
```python
request = await self.session.get(
    url=url,
    timeout=ClientTimeout(total=60),
    headers=headers,
    proxy="http://<url>:<port>",
)
```
