### ISSUE TITLE
cannot install hacs 1.24.5

### ISSUE THREAD

**Issue by mikespdb** [hacs/integration#2681]
### Web browser

edge

### Web browser version

x64 101.0.1210.53

### System Health details

Error setting up entry for hacs

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

1 cannot install 1.24.5 directly
2 try 1.23.0, can be installed
3 update to 1.24.5, but can not work
4 unzip 1.24.5 to overwrite 1.23.0 files, can not work

### Reproduction steps

1. cannot install 1.24.5 directly
2. try 1.23.0, can be installed
3. update to 1.24.5, but can not work
4. unzip 1.24.5 to overwrite 1.23.0 files, still can not work
...

### Screenshots

![1653199272(1)](https://user-images.githubusercontent.com/14969638/169681151-67c6c44b-645a-464d-b22b-27a13c0e2fb8.png)

### Javascript logs from your browser console

```text
log:
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/hacs/tasks/setup_sensor.py:8
Integration: HACS (documentation, issues)
First occurred: 13:33:30 (1 occurrences)
Last logged: 13:33:30

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 168, in async_setup_entry
    return await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/hacs/__init__.py", line 104, in async_initialize_integration
    await hacs.tasks.async_load()
  File "/config/custom_components/hacs/tasks/manager.py", line 42, in async_load
    await asyncio.gather(*[_load_module(task) for task in task_modules])
  File "/config/custom_components/hacs/tasks/manager.py", line 38, in _load_module
    task_module = import_module(f"{__package__}.{module}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hacs/tasks/setup_sensor.py", line 8, in <module>
    from ..const import DOMAIN, PLATFORMS
ImportError: cannot import name 'PLATFORMS' from 'custom_components.hacs.const' (/config/custom_components/hacs/const.py)
```

**Comment by ludeeus** [comment]
You have files from 2 different versions. Most likely a result of a permission issue.
Follow the download instructions as a workaround.
https://hacs.xyz/docs/setup/prerequisites
