### ISSUE TITLE
Hacs Failed to Setup

### ISSUE THREAD

**Issue by budlyte56** [hacs/integration#2758]
### Web browser

Google

### Web browser version

Version 103.0.5060.66 (Official Build) (64-bit)

### System Health details

<html>
<body>

Version | core-2022.6.7
-- | --
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.12
Operating System Family | Linux
Operating System Version | 5.10.0-15-amd64
CPU Architecture | x86_64
Timezone | America/Los_Angeles

</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have downloaded and installed HACS is custom components cleared browser caches and added Hacs and authorized github. 

### Reproduction steps

1. downloaded and installed HACS in custom components directory
2. cleared cache in browser
3. selected HACS and followed github authorization directions 
...

### Screenshots

![image](https://user-images.githubusercontent.com/41169958/176784278-3b60c86f-2281-48c7-b5e6-e9e68a2998b6.png)

### Javascript logs from your browser console

```text
don't know how
```

### Diagnostics dump

Logger: homeassistant.config_entries
Source: helpers/storage.py:153
First occurred: 2:29:04 PM (1 occurrences)
Last logged: 2:29:04 PM

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 223, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/hacs/__init__.py", line 209, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 196, in async_try_startup
    startup_result = await async_startup()
  File "/config/custom_components/hacs/__init__.py", line 153, in async_startup
    if not await hacs.data.restore():
  File "/config/custom_components/hacs/utils/data.py", line 119, in restore
    hacs = await async_load_from_store(self.hacs.hass, "hacs") or {}
  File "/config/custom_components/hacs/utils/store.py", line 49, in async_load_from_store
    return await get_store_for_key(hass, key).async_load() or {}
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 114, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 123, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 153, in _async_load_data
    data["version"] == self.version
KeyError: 'version'

Full logs
2022-06-30 14:27:06 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-30 14:29:04 INFO (MainThread) [custom_components.hacs]
HACS (Home Assistant Community Store)
https://github.com/hacs/integration/issues
2022-06-30 14:29:04 DEBUG (MainThread) [custom_components.hacs] Configuration type: ConfigurationType.CONFIG_ENTRY
2022-06-30 14:29:04 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry for hacs
File "/config/custom_components/hacs/__init__.py", line 223, in async_setup_entry
File "/config/custom_components/hacs/__init__.py", line 209, in async_initialize_integration
File "/config/custom_components/hacs/__init__.py", line 196, in async_try_startup
File "/config/custom_components/hacs/__init__.py", line 153, in async_startup
if not await hacs.data.restore():
File "/config/custom_components/hacs/utils/data.py", line 119, in restore
hacs = await async_load_from_store(self.hacs.hass, "hacs") or {}
File "/config/custom_components/hacs/utils/store.py", line 49, in async_load_from_store

**Comment by ludeeus** [comment]
Your storage files are corrupt.
Restore .storrage/hacs.hacs from a backup or delete it.
