### ISSUE TITLE
automation not installing after upgrade

### ISSUE THREAD

**Issue by calisro** [hacs/integration#2783]
### System Health details

Version	core-2022.7.2
Installation Type	Home Assistant OS
Development	false
Supervisor	true
Docker	true
User	root
Virtual Environment	false
Python Version	3.10.5
Operating System Family	Linux
Operating System Version	5.15.32-v8
CPU Architecture	aarch64
Timezone	America/New_York
Configuration Directory	/config
Home Assistant Community Store
￼
MANAGE
GitHub API	ok
GitHub Content	ok
GitHub Web	ok
GitHub API Calls Remaining	4407
Installed Version	1.26.0
Stage	running
Available Repositories	1136
Downloaded Repositories	24

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I recently upgraded HACS and HA to the latest version.  One of my components installed with HACS went from installed to 'new'.  When I attempt to reinstall it, I get this:

```
2022-07-11 13:57:47 INFO (MainThread) [custom_components.hacs] <Appdaemon wernerhp/ha.appdaemon.wasp> Running pre installation steps
2022-07-11 13:57:47 INFO (MainThread) [custom_components.hacs] <Appdaemon wernerhp/ha.appdaemon.wasp> Pre installation steps completed
2022-07-11 13:57:47 INFO (MainThread) [custom_components.hacs] <Appdaemon wernerhp/ha.appdaemon.wasp> Running installation steps
2022-07-11 13:57:48 INFO (MainThread) [custom_components.hacs] <Appdaemon wernerhp/ha.appdaemon.wasp> Trying experimental download
2022-07-11 13:57:48 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547487720848] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 212, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 833, in async_install
    await self.async_install_repository()
  File "/config/custom_components/hacs/repositories/base.py", line 916, in async_install_repository
    await self.download_content()
  File "/config/custom_components/hacs/repositories/base.py", line 572, in download_content
    await self.download_repository_zip()
  File "/config/custom_components/hacs/repositories/base.py", line 626, in download_repository_zip
    zip_file.extractall(self.content.path.local, extractable)
  File "/usr/local/lib/python3.10/zipfile.py", line 1645, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.10/zipfile.py", line 1693, in _extract_member
    if member.is_dir():
  File "/usr/local/lib/python3.10/zipfile.py", line 530, in is_dir
    return self.filename[-1] == '/'
IndexError: string index out of range

```
I should note that this was already installed and only now comes up as a 'new' automation even though it was already there...  .  It was only after the latest HACS and HA 2022.07.3 upgrade that this happened (which I tried to roll back and it is still broken)

### Reproduction steps

1.  Simply try to install automation Appdaemon wernerhp/ha.appdaemon.wasp
2.
3.
...

### Debug logs

```text
I can gather these
```

**Comment by ludeeus** [comment]
That repository is not valid to be used with HACS.
<https://hacs.xyz/docs/publish/appdaemon#repository-structure>

**Comment by calisro** [comment]
Did something change?  I've used it for a long time and only recently did it become an issue?

**Comment by ludeeus** [comment]
If it worked before that was a bug, it should never have worked.

**Comment by calisro** [comment]
Hmm  Ok.  I've used it for over a year.  Thanks.

**Comment by DavidFW1960** [comment]
> Hmm Ok. I've used it for over a year. Thanks.

So have I and I see no errors in HACS

**Comment by calisro** [comment]
@DavidFW1960 What version HACS and HA are you on?

**Comment by DavidFW1960** [comment]
![image](https://user-images.githubusercontent.com/36390762/178613870-8850755e-12ba-429d-b37a-e0ccd19e5ab6.png)
Latest HA and latest HACS

**Comment by ludeeus** [comment]
<https://github.com/hacs/integration/releases/tag/1.26.1> Makes it so this can be installed again.
BUT! this is **not** supposed to work, and that **is** a bug in HACS that **will** be fixed in the future and then it **will** stop working again.

**Comment by calisro** [comment]
Yes it did in fact fix it.  I've linked an issue in the repo I was having trouble with.
