### ISSUE TITLE
Error setting up entry for hacs

### ISSUE THREAD

**Issue by mvaatain** [hacs/integration#2802]
### System Health details

Version | core-2022.7.6
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | Europe/Helsinki
Configuration Directory | /config

GitHub API | ok
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.26.2
Stage |  
Available Repositories | 0
Downloaded Repositories | 0

Logged In | true
Subscription Expiration | July 29, 2022 at 3:00 AM
Relayer Connected | true
Remote Enabled | true
Remote Connected | true
Alexa Enabled | true
Google Enabled | true
Remote Server | eu-west-2-1.ui.nabu.casa
Reach Certificate Server | ok
Reach Authentication Server | ok
Reach Home Assistant Cloud | ok

Host Operating System | Home Assistant OS 8.2
Update Channel | stable
Supervisor Version | supervisor-2022.07.0
Agent Version | 1.2.1
Docker Version | 20.10.14
Disk Total | 109.3 GB
Disk Used | 14.9 GB
Healthy | true
Supported | true
Board | rpi4-64
Supervisor API | ok
Version API | ok
Installed Add-ons | Samba share (10.0.0), ESPHome (2022.3.1), Log Viewer (0.14.0), File editor (5.3.3), Node-RED (13.1.0), Terminal & SSH (9.6.0), Check Home Assistant configuration (3.11.0), WireGuard (0.7.0), Mosquitto broker (6.1.2), Home Assistant Google Drive Backup (0.108.2), Simple Scheduler (0.60)

Dashboards | 2
-- | --
Resources | 4
Views | 7
Mode | storage

Oldest Run Start Time | July 14, 2022 at 9:45 AM
-- | --
Current Run Start Time | July 24, 2022 at 5:16 PM
Estimated Database Size (MiB) | 175.96 MiB
Database Engine | sqlite
Database Version | 3.38.5

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

There are 2 errors 

![image](https://user-images.githubusercontent.com/72567832/180654089-e61fb008-5840-455d-8f77-c8f9e709339c.png)

So far I have removed HACS and reinstalled it without success.  (https://hacs.xyz/docs/setup/remove)

`Logger: homeassistant.config_entries
Source: util/json.py:45
First occurred: 5:16:50 PM (1 occurrences)
Last logged: 5:16:50 PM

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
orjson.JSONDecodeError: expected value at line 1 column 1: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 223, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/hacs/__init__.py", line 209, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 196, in async_try_startup
    startup_result = await async_startup()
  File "/config/custom_components/hacs/__init__.py", line 153, in async_startup
    if not await hacs.data.restore():
  File "/config/custom_components/hacs/utils/data.py", line 120, in restore
    repositories = await async_load_from_store(self.hacs.hass, "repositories") or {}
  File "/config/custom_components/hacs/utils/store.py", line 49, in async_load_from_store
    return await get_store_for_key(hass, key).async_load() or {}
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 114, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 123, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 141, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 45, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: expected value at line 1 column 1: line 1 column 1 (char 0)
`
`Logger: homeassistant.util.json
Source: util/json.py:39
First occurred: 5:16:50 PM (1 occurrences)
Last logged: 5:16:50 PM

Could not parse JSON content: /config/.storage/hacs.repositories
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
orjson.JSONDecodeError: expected value at line 1 column 1: line 1 column 1 (char 0)
`

### Reproduction steps

1. Error comes right after reboot
2.
3.
...

### Debug logs

```text
2022-07-24 18:38:47 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-24 18:38:47 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-24 18:38:47 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-24 18:38:47 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-24 18:39:00 ERROR (MainThread) [homeassistant.components.automation] Blueprint Contact Sensor Left Open Notification generated invalid automation with inputs OrderedDict([('notification_color', 'red'), ('entity', 'binary_sensor.sonoff_door_7_ds01_jaakaap_ias_zone'), ('friendly_name', 'Jääkaapin ovi'), ('seconds', 30), ('notify_service', 'TelegramBot'), ('click_url', '/lovelace/')]): Service TelegramBot does not match format <domain>.<name> for dictionary value @ data['action'][0]['service']. Got None
2022-07-24 18:39:00 ERROR (MainThread) [homeassistant.components.automation] Blueprint Contact Sensor Left Open Notification generated invalid automation with inputs OrderedDict([('notification_color', 'red'), ('entity', 'binary_sensor.sonoff_door_7_ds01_jaakaap_ias_zone'), ('friendly_name', 'Jääkaapin ovi'), ('seconds', 30), ('notify_service', 'TelegramBot'), ('click_url', '/lovelace/')]): Service TelegramBot does not match format <domain>.<name> for dictionary value @ data['action'][0]['service']. Got None
2022-07-24 18:39:00 ERROR (MainThread) [homeassistant.components.automation] Blueprint Contact Sensor Left Open Notification generated invalid automation with inputs OrderedDict([('notification_color', 'red'), ('entity', 'binary_sensor.sonoff_door_7_ds01_jaakaap_ias_zone'), ('notification_icon_warning', 'alert'), ('friendly_name', 'Jääkaapin ovi'), ('seconds', 30), ('click_url', '/lovelace/'), ('notify_service', 'TelegramBot')]): Service TelegramBot does not match format <domain>.<name> for dictionary value @ data['action'][0]['service']. Got None
2022-07-24 18:39:09 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alexapy==1.25.3: ERROR: Cannot install alexapy==1.25.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-07-24 18:39:16 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alexapy==1.25.3: ERROR: Cannot install alexapy==1.25.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-07-24 18:39:24 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package alexapy==1.25.3: ERROR: Cannot install alexapy==1.25.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
2022-07-24 18:39:24 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration alexa_media: Requirements for alexa_media not found: ['alexapy==1.25.3'].
2022-07-24 18:39:28 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Canon MF641C (de:8a:29) (de:8a:29) (3) (de:8a:29 (de:8a:29) (2)' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2022-07-24 18:39:28 WARNING (MainThread) [homeassistant.config_entries] Config entry 'yeelight_ct_bulb_ulkovalo_0x0000000005ec984e' for yeelight integration not ready yet: Waiting for 0x5ec984e to be discovered; Retrying in background
2022-07-24 18:39:37 WARNING (MainThread) [homeassistant.components.mqtt.mixins] Manually configured MQTT sensor(s) found under platform key 'sensor', please move to the mqtt integration key, see https://www.home-assistant.io/integrations/sensor.mqtt/#new_format
2022-07-24 18:39:38 WARNING (MainThread) [homeassistant.config_entries] Config entry 'ulkovalo' for yeelight integration not ready yet: Failed to read from the socket at 10.10.15.46:55443: [Errno 113] Connect call failed ('10.10.15.46', 55443).; Retrying in background
2022-07-24 18:39:38 ERROR (SyncWorker_2) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs.repositories
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
orjson.JSONDecodeError: expected value at line 1 column 1: line 1 column 1 (char 0)
2022-07-24 18:39:39 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
orjson.JSONDecodeError: expected value at line 1 column 1: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 223, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/hacs/__init__.py", line 209, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 196, in async_try_startup
    startup_result = await async_startup()
  File "/config/custom_components/hacs/__init__.py", line 153, in async_startup
    if not await hacs.data.restore():
  File "/config/custom_components/hacs/utils/data.py", line 120, in restore
    repositories = await async_load_from_store(self.hacs.hass, "repositories") or {}
  File "/config/custom_components/hacs/utils/store.py", line 49, in async_load_from_store
    return await get_store_for_key(hass, key).async_load() or {}
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 114, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 123, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 141, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 45, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: expected value at line 1 column 1: line 1 column 1 (char 0)
2022-07-24 18:39:40 WARNING (MainThread) [homeassistant.components.google] The 'google' option near /config/configuration.yaml:2 is deprecated, please remove it from your configuration
2022-07-24 18:39:40 WARNING (MainThread) [homeassistant.components.google] Configuration of Google Calendar in YAML in configuration.yaml is is deprecated and will be removed in a future release; Your existing OAuth Application Credentials and access settings have been imported into the UI automatically and can be safely removed from your configuration.yaml file
2022-07-24 18:39:44 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for ylakerta_kukkavalo @ 10.10.15.83: Error connecting to ('10.10.15.83', 6053): [Errno 113] Connect call failed ('10.10.15.83', 6053)
2022-07-24 18:39:44 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for pistorasia_s20_2 @ 10.10.15.231: Error connecting to ('10.10.15.231', 6053): [Errno 113] Connect call failed ('10.10.15.231', 6053)
2022-07-24 18:39:44 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for pistorasia_s20_3 @ 10.10.15.227: Error connecting to ('10.10.15.227', 6053): [Errno 113] Connect call failed ('10.10.15.227', 6053)
2022-07-24 18:39:44 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for makuuhuone_temp @ 10.10.15.88: Error connecting to ('10.10.15.88', 6053): [Errno 113] Connect call failed ('10.10.15.88', 6053)
2022-07-24 18:39:44 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for flora_tracker_kellari @ 10.10.15.84: Error connecting to ('10.10.15.84', 6053): [Errno 113] Connect call failed ('10.10.15.84', 6053)
2022-07-24 18:39:45 WARNING (MainThread) [homeassistant.config_entries] Config entry 'DENON AVR-2113 vahvari' for denonavr integration not ready yet: NetworkError: All connection attempts failed; Retrying in background
2022-07-24 18:39:49 WARNING (MainThread) [homeassistant.config_entries] Config entry 'RBR50 (AP)' for upnp integration not ready yet: Device not discovered: uuid:4d696e69-444c-164e-9d42-3c37860fb64d::urn:schemas-upnp-org:device:InternetGatewayDevice:1; Retrying in background
2022-07-24 18:39:49 WARNING (MainThread) [homeassistant.config_entries] Config entry 'RBR50 (AP)' for upnp integration not ready yet: Device not discovered: uuid:4d696e69-444c-164e-9d42-3c37860fb64d::urn:schemas-upnp-org:device:InternetGatewayDevice:1; Retrying in background
2022-07-24 18:39:49 WARNING (MainThread) [homeassistant.config_entries] Config entry 'RBR50 (AP)' for upnp integration not ready yet: Device not discovered: uuid:4d696e69-444c-164e-9d42-::urn:schemas-upnp-org:device:InternetGatewayDevice:1; Retrying in background
2022-07-24 18:40:00 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: zha
2022-07-24 18:40:13 ERROR (MainThread) [homeassistant.components.homekit.util] media_player.bdp_s4500 does not support any media_player features
2022-07-24 18:40:13 WARNING (MainThread) [homeassistant.components.homekit] The bridge HASS Bridge MMVE has entity media_player.lg_webos_tv_oled65b7v. For best performance, and to prevent unexpected unavailability, create and pair a separate HomeKit instance in accessory mode for this entity
2022-07-24 18:40:13 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.warm_water_stop_temp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 245, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 209, in __init__
    CHAR_TARGET_HEATING_COOLING, value=list(self.hc_homekit_to_hass)[0]
IndexError: list index out of range
2022-07-24 18:40:13 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.operating_mode_1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 245, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 209, in __init__
    CHAR_TARGET_HEATING_COOLING, value=list(self.hc_homekit_to_hass)[0]
IndexError: list index out of range
2022-07-24 18:40:13 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.room_temp_setpoint
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 245, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 209, in __init__
    CHAR_TARGET_HEATING_COOLING, value=list(self.hc_homekit_to_hass)[0]
IndexError: list index out of range
2022-07-24 18:40:13 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.room_sensor_influence
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 245, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 209, in __init__
    CHAR_TARGET_HEATING_COOLING, value=list(self.hc_homekit_to_hass)[0]
IndexError: list index out of range
2022-07-24 18:40:13 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.heat_set_1_curvel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 245, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 209, in __init__
    CHAR_TARGET_HEATING_COOLING, value=list(self.hc_homekit_to_hass)[0]
IndexError: list index out of range
2022-07-24 18:40:13 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.heating_setpoint_start
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 245, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 209, in __init__
    CHAR_TARGET_HEATING_COOLING, value=list(self.hc_homekit_to_hass)[0]
IndexError: list index out of range
2022-07-24 18:40:13 ERROR (MainThread) [homeassistant.components.homekit] Failed to create a HomeKit accessory for climate.warm_water_start_temp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit/__init__.py", line 628, in add_bridge_accessory
    acc = get_accessory(self.hass, self.driver, state, aid, conf)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 245, in get_accessory
    return TYPES[a_type](hass, driver, name, state.entity_id, aid, config)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 209, in __init__
    CHAR_TARGET_HEATING_COOLING, value=list(self.hc_homekit_to_hass)[0]
IndexError: list index out of range
2022-07-24 18:40:26 WARNING (MainThread) [homeassistant.components.homekit] The bridge HASS Bridge MMVE has entity media_player.lg_webos_tv_oled65b7v. For best performance, and to prevent unexpected unavailability, create and pair a separate HomeKit instance in accessory mode for this entity
2022-07-24 18:40:39 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xCBDA:1:0x0008]: async_initialize: all attempts have failed: [DeliveryError('[0xcbda:1:0x0008]: Message send failure'), DeliveryError('[0xcbda:1:0x0008]: Message send failure'), DeliveryError('[0xcbda:1:0x0008]: Message send failure'), DeliveryError('[0xcbda:1:0x0008]: Message send failure')]
2022-07-24 18:40:40 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xCBDA:1:0x0006]: async_initialize: all attempts have failed: [DeliveryError('[0xcbda:1:0x0006]: Message send failure'), DeliveryError('[0xcbda:1:0x0006]: Message send failure'), DeliveryError('[0xcbda:1:0x0006]: Message send failure'), DeliveryError('[0xcbda:1:0x0006]: Message send failure')]
2022-07-24 18:40:43 WARNING (MainThread) [homeassistant.components.zha.core.channels.base] [0xCBDA:1:0x0300]: async_initialize: all attempts have failed: [DeliveryError('[0xcbda:1:0x0300]: Message send failure'), DeliveryError('[0xcbda:1:0x0300]: Message send failure'), DeliveryError('[0xcbda:1:0x0300]: Message send failure'), DeliveryError('[0xcbda:1:0x0300]: Message send failure')]
```

### Diagnostics dump

Cant take the dump because HACS wont start

**Comment by ludeeus** [comment]
The file it complaints about is empty.
Restore it from a backup or delete it and restart Home Assistant.

**Comment by baaswietse** [comment]
Where can I find this file?
I have the same issue but the folder /usr/src/ seems to be empty.
![image](https://user-images.githubusercontent.com/40791418/182400523-b3ca9322-27ee-4627-b6f1-612d4475d711.png)



Below the error I get.

> Logger: homeassistant.config_entries
> Source: util/json.py:45
> First occurred: 4:01:53 PM (1 occurrences)
> Last logged: 4:01:53 PM
> 
> Error setting up entry for hacs
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
>     return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
> orjson.JSONDecodeError: key must be a string at line 17844 column 4: line 17844 column 4 (char 586778)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/hacs/__init__.py", line 223, in async_setup_entry
>     setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
>   File "/config/custom_components/hacs/__init__.py", line 209, in async_initialize_integration
>     await async_try_startup()
>   File "/config/custom_components/hacs/__init__.py", line 196, in async_try_startup
>     startup_result = await async_startup()
>   File "/config/custom_components/hacs/__init__.py", line 153, in async_startup
>     if not await hacs.data.restore():
>   File "/config/custom_components/hacs/utils/data.py", line 120, in restore
>     repositories = await async_load_from_store(self.hacs.hass, "repositories") or {}
>   File "/config/custom_components/hacs/utils/store.py", line 49, in async_load_from_store
>     return await get_store_for_key(hass, key).async_load() or {}
>   File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 114, in async_load
>     return await self._load_task
>   File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 123, in _async_load
>     return await self._async_load_data()
>   File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 141, in _async_load_data
>     data = await self.hass.async_add_executor_job(
>   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/homeassistant/homeassistant/util/json.py", line 45, in load_json
>     raise HomeAssistantError(error) from error
> homeassistant.exceptions.HomeAssistantError: key must be a string at line 17844 column 4: line 17844 column 4 (char 586778)

AND

> Logger: homeassistant.util.json
> Source: util/json.py:39
> First occurred: 4:01:53 PM (2 occurrences)
> Last logged: 4:03:04 PM
> 
> Could not parse JSON content: /config/.storage/hacs.repositories
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
>     return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
> orjson.JSONDecodeError: key must be a string at line 17844 column 4: line 17844 column 4 (char 586778)
