### ISSUE TITLE
Could not parse JSON content: /config/.storage/hacs.repositories

### ISSUE THREAD

**Issue by Tijgerd** [hacs/integration#2812]
## System Information

version | core-2022.8.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.55
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.26.2
Stage | null
Available Repositories | 0
Downloaded Repositories | 0

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.07.0
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 916.8 GB
disk_used | 6.4 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.0), File editor (5.3.3), FTP (4.6.0), Studio Code Server (5.2.0), ESPHome (2022.6.2), Cloudflared (2.0.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 12
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 27, 2022 at 7:41 AM
-- | --
current_recorder_run | August 5, 2022 at 12:42 PM
estimated_db_size | 220.36 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Got this error in the log after updating to home assistant 2022.8.1

Logger: homeassistant.util.json
Source: util/json.py:39
First occurred: 12:45:12 PM (1 occurrences)
Last logged: 12:45:12 PM

Could not parse JSON content: /config/.storage/hacs.repositories
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 98304: invalid continuation byte

Rebooting the system resulted in the same error

### Reproduction steps

1. Have HACS 1.26.2 installed and running without issues (even after reboot)
2. Install home assistant 2022.8.0 without issues
3. Update home assistant to 2022.8.1, reboot (this is done automatically after the update)
4. Check integration page: error at HACS, HACS is also not available in the side panel

### Debug logs

```text
2022-08-05 12:42:39.042 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:39.043 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration var which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:39.044 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:39.046 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:39.047 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_dehumidifier_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:39.048 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:39.049 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:39.051 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:39.052 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-05 12:42:48.653 WARNING (MainThread) [homeassistant.components.number] custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2022-08-05 12:42:49.943 ERROR (SyncWorker_6) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs.repositories
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 98304: invalid continuation byte
2022-08-05 12:42:49.985 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 98304: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 223, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/hacs/__init__.py", line 209, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 196, in async_try_startup
    startup_result = await async_startup()
  File "/config/custom_components/hacs/__init__.py", line 153, in async_startup
    if not await hacs.data.restore():
  File "/config/custom_components/hacs/utils/data.py", line 120, in restore
    repositories = await async_load_from_store(self.hacs.hass, "repositories") or {}
  File "/config/custom_components/hacs/utils/store.py", line 49, in async_load_from_store
    return await get_store_for_key(hass, key).async_load() or {}
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 116, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 125, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 143, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 45, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: 'utf-8' codec can't decode byte 0xde in position 98304: invalid continuation byte
2022-08-05 12:42:59.309 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2022-08-05 12:45:12.386 ERROR (SyncWorker_4) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs.repositories
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 98304: invalid continuation byte
2022-08-05 12:45:12.388 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 39, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xde in position 98304: invalid continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 223, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/hacs/__init__.py", line 209, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 196, in async_try_startup
    startup_result = await async_startup()
  File "/config/custom_components/hacs/__init__.py", line 153, in async_startup
    if not await hacs.data.restore():
  File "/config/custom_components/hacs/utils/data.py", line 120, in restore
    repositories = await async_load_from_store(self.hacs.hass, "repositories") or {}
  File "/config/custom_components/hacs/utils/store.py", line 49, in async_load_from_store
    return await get_store_for_key(hass, key).async_load() or {}
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 116, in async_load
    return await self._load_task
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 125, in _async_load
    return await self._async_load_data()
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 143, in _async_load_data
    data = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 45, in load_json
    raise HomeAssistantError(error) from error
homeassistant.exceptions.HomeAssistantError: 'utf-8' codec can't decode byte 0xde in position 98304: invalid continuation byte
```

**Comment by ludeeus** [comment]
Restore that file from a backup, and restart Home Assistant.
