### ISSUE TITLE
HACS doesn’t start

### ISSUE THREAD

**Issue by Remko76** [hacs/integration#2835]
## System Information

version | core-2022.8.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3932
Installed Version | 1.26.2
Stage | running
Available Repositories | 1102
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.08.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 219.4 GB
disk_used | 27.5 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Samba share (10.0.0), Duck DNS (1.15.0), AdGuard Home (4.7.3), SSH & Web Terminal (12.0.2), Vaultwarden (Bitwarden) (0.17.3), Nginx Proxy Manager (0.12.2), MariaDB (2.5.1), Mosquitto broker (6.1.2), Zigbee2MQTT Edge (edge), Samba Backup (5.1.2), Meross Local Broker Addon (0.0.1-alpha45)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 22
views | 21
mode | storage

</details>

<details><summary>MercedesME 2020</summary>

websocket_connection_state | connected
-- | --
api_endpoint_reachable | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 28, 2022, 6:55 PM
-- | --
current_recorder_run | August 28, 2022, 8:57 AM
estimated_db_size | 5494.27 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Since yesterday all of a sudden HACS doesn’t start anymore. I get errors in my logs like below and don’t know what to do.

```
Logger: homeassistant.util.logging
Source: util/logging.py:167 
First occurred: 8:58:24 AM (42 occurrences) 
Last logged: 8:58:30 AM

Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'denysdovhan/vacuum-card', 'repository_id': '261291295'},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'Makin-Things/platinum-weather-card', 'repository_id': '488086721'},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'ekutner/home-connect-hass', 'repository_id': '454859084'},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'danielperna84/custom_homematic', 'repository_id': '389120303'},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
```

### Reproduction steps

I have removed HACS completely and reinstalled.

### Debug logs

```text
Logger: homeassistant.util.logging
Source: util/logging.py:167 
First occurred: 8:58:24 AM (42 occurrences) 
Last logged: 8:58:30 AM

Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'denysdovhan/vacuum-card', 'repository_id': '261291295'},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'Makin-Things/platinum-weather-card', 'repository_id': '488086721'},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'ekutner/home-connect-hass', 'repository_id': '454859084'},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'danielperna84/custom_homematic', 'repository_id': '389120303'},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({},) Traceback (most recent call last): File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state self._update() File "/config/custom_components/hacs/sensor.py", line 33, in _update repositories = [ File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp> if repository.pending_update File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update result := version_left_higher_then_right( File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right return left_version > right_version File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__ return self._compare_versions(self, compareto) File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b)) File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier SEMVER_MODIFIER_MAP[version_a.modifier_type] KeyError: 'mmppt'
```

**Comment by ludeeus** [comment]
Missing debug logs and diagnostics
