### ISSUE TITLE
HACS doe not show Integrations or Frontend anymore

### ISSUE THREAD

**Issue by Remko76** [hacs/integration#2837]
## System Information

version | core-2022.8.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.32-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4186
Installed Version | 1.27.0
Stage | running
Available Repositories | 1104
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.5
-- | --
update_channel | stable
supervisor_version | supervisor-2022.08.3
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 219.4 GB
disk_used | 29.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.3), Samba share (10.0.0), Duck DNS (1.15.0), AdGuard Home (4.7.3), SSH & Web Terminal (12.0.2), Vaultwarden (Bitwarden) (0.17.3), Nginx Proxy Manager (0.12.2), MariaDB (2.5.1), Mosquitto broker (6.1.2), Zigbee2MQTT Edge (edge), Samba Backup (5.1.2), Meross Local Broker Addon (0.0.1-alpha45)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 22
views | 21
mode | storage

</details>

<details><summary>MercedesME 2020</summary>

websocket_connection_state | connected
-- | --
api_endpoint_reachable | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 28, 2022 at 6:55 PM
-- | --
current_recorder_run | August 28, 2022 at 10:28 AM
estimated_db_size | 5494.27 MiB
database_engine | mysql
database_version | 10.6.8

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS doe show in sidebar, but no Integrations or Frontend shows. The logs show all kinds of errors and I don't know how to solve this.. I unfortunately do not know what caused, this; I have been running HACS for a couple of years and it worked flawlesly. I also did not add or remove any other integrations and run the latest version of HASS.

I hope this issue is filed correctly, I tried to follow every step of the issue guide.

![image](https://user-images.githubusercontent.com/75678314/187064952-3029df1f-60fa-4dd2-ab9e-969b0d9d15d5.png)

### Reproduction steps

I have completely uninstalled HACS by following the guide, revoked the Oauth and reinstalled completely following the guide provided.

### Debug logs

```text
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.27.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2022-08-28 10:29:10.361 DEBUG (MainThread) [custom_components.hacs] Configuration type: ConfigurationType.CONFIG_ENTRY
2022-08-28 10:29:10.840 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore started
2022-08-28 10:29:11.899 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore done
2022-08-28 10:29:16.846 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform mobile_app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/sensor.py", line 113, in native_value
    and (timestamp := dt_util.parse_datetime(state)) is not None
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 185, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not datetime.datetime
2022-08-28 10:29:16.929 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mobile_app platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 776, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/usr/src/homeassistant/homeassistant/components/mobile_app/sensor.py", line 113, in native_value
    and (timestamp := dt_util.parse_datetime(state)) is not None
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 185, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
TypeError: argument 1 must be str, not datetime.datetime
2022-08-28 10:29:17.521 DEBUG (MainThread) [aiogithubapi] 'GitHubRateLimitResourcesModel' is missing key 'dependency_snapshots' for <class 'dict'>
2022-08-28 10:29:17.521 DEBUG (MainThread) [custom_components.hacs] Can update 345 repositories
2022-08-28 10:29:17.523 INFO (MainThread) [custom_components.hacs] Enable category: integration
2022-08-28 10:29:17.524 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2022-08-28 10:29:17.524 INFO (MainThread) [custom_components.hacs] Enable category: theme
2022-08-28 10:29:17.532 INFO (MainThread) [custom_components.hacs] <HacsFrontend> LovelaceMode.STORAGE mode, cache for /hacsfiles/: True
2022-08-28 10:29:17.537 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.SETUP
2022-08-28 10:29:17.539 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.WAITING
2022-08-28 10:29:17.539 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2022-08-28 10:29:17.838 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'IPCAM', but will retry later. Error: 
2022-08-28 10:29:17.847 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'IPCAM', but will retry later. Error: 
2022-08-28 10:29:17.856 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'IPCAM', but will retry later. Error: 
2022-08-28 10:29:17.861 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'IPCAM', but will retry later. Error: 
2022-08-28 10:29:17.895 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Cam Garden' for onvif integration not ready yet: None; Retrying in background
2022-08-28 10:29:17.898 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Cam Parking' for onvif integration not ready yet: None; Retrying in background
2022-08-28 10:29:17.900 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Cam Front Door' for onvif integration not ready yet: None; Retrying in background
2022-08-28 10:29:17.902 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Cam Living' for onvif integration not ready yet: None; Retrying in background
2022-08-28 10:29:25.319 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.STARTUP
2022-08-28 10:29:25.626 WARNING (MainThread) [custom_components.solaredge_modbus_multi] Polling frequency < 10, requiring keep modbus open.
2022-08-28 10:29:33.319 INFO (MainThread) [custom_components.hacs] Loading removed repositories
2022-08-28 10:29:38.247 ERROR (MainThread) [homeassistant.components.alexa.state_report] Timeout sending report to Alexa for cover.rollladen_unten
2022-08-28 10:29:38.256 ERROR (MainThread) [homeassistant.components.alexa.state_report] Timeout sending report to Alexa for light.alle_licht_schalter
2022-08-28 10:29:38.261 ERROR (MainThread) [homeassistant.components.alexa.state_report] Timeout sending report to Alexa for cover.rollladen_oben
2022-08-28 10:29:38.289 ERROR (MainThread) [homeassistant.components.alexa.state_report] Timeout sending report to Alexa for cover.alle_rollladen
2022-08-28 10:29:38.295 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Timeout fetching homeassistant_alerts data
2022-08-28 10:29:38.746 INFO (MainThread) [custom_components.hacs] Loading known repositories
2022-08-28 10:29:38.852 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'IPCAM', but will retry later. Error: 
2022-08-28 10:29:38.882 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'IPCAM', but will retry later. Error: 
2022-08-28 10:29:38.909 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'IPCAM', but will retry later. Error: 
2022-08-28 10:29:39.016 WARNING (MainThread) [homeassistant.components.onvif] Couldn't connect to camera 'IPCAM', but will retry later. Error: Server disconnected without sending a response.
2022-08-28 10:29:39.618 INFO (MainThread) [custom_components.hacs] Starting recurring background task for downloaded repositories
2022-08-28 10:29:39.619 DEBUG (MainThread) [custom_components.hacs] Recurring background task for downloaded repositories done
2022-08-28 10:29:39.619 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2022-08-28 10:29:39.832 DEBUG (MainThread) [custom_components.hacs] <QueueManager> The queue is empty
2022-08-28 10:29:39.838 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.critical'. Content did not change
2022-08-28 10:29:40.005 DEBUG (MainThread) [aiogithubapi] 'GitHubRateLimitResourcesModel' is missing key 'dependency_snapshots' for <class 'dict'>
2022-08-28 10:29:40.005 DEBUG (MainThread) [custom_components.hacs] Can update 344 repositories, items in queue 41
2022-08-28 10:29:40.005 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Checking out tasks to execute
2022-08-28 10:29:40.005 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Starting queue execution for 41 tasks
2022-08-28 10:29:40.008 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2022-08-28 10:29:40.014 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Getting repository information
2022-08-28 10:29:40.022 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/mini-media-player> Getting repository information
2022-08-28 10:29:40.028 DEBUG (MainThread) [custom_components.hacs] <Plugin ljmerza/light-entity-card> Getting repository information
2022-08-28 10:29:40.029 DEBUG (MainThread) [custom_components.hacs] <Plugin r-renato/ha-card-weather-conditions> Getting repository information
2022-08-28 10:29:40.032 DEBUG (MainThread) [custom_components.hacs] <Plugin reptilex/tesla-style-solar-power-card> Getting repository information
2022-08-28 10:29:40.037 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-fold-entity-row> Getting repository information
2022-08-28 10:29:40.039 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-template-entity-row> Getting repository information
2022-08-28 10:29:40.041 DEBUG (MainThread) [custom_components.hacs] <Integration binsentsu/home-assistant-solaredge-modbus> Getting repository information
2022-08-28 10:29:40.043 DEBUG (MainThread) [custom_components.hacs] <Integration garbled1/homeassistant_ecowitt> Getting repository information
2022-08-28 10:29:40.548 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Running checks against 0.0.17
2022-08-28 10:29:40.591 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-template-entity-row> Running checks against 1.3.0
2022-08-28 10:29:40.610 DEBUG (MainThread) [custom_components.hacs] <Plugin r-renato/ha-card-weather-conditions> Running checks against 1.9.12
2022-08-28 10:29:40.648 DEBUG (MainThread) [custom_components.hacs] <Integration binsentsu/home-assistant-solaredge-modbus> Running checks against V1.6.0
2022-08-28 10:29:40.670 DEBUG (MainThread) [custom_components.hacs] <Integration garbled1/homeassistant_ecowitt> Running checks against 0.7
2022-08-28 10:29:40.703 DEBUG (MainThread) [custom_components.hacs] <Plugin ljmerza/light-entity-card> Running checks against 5.0.0
2022-08-28 10:29:40.739 DEBUG (MainThread) [custom_components.hacs] <Plugin thomasloven/lovelace-fold-entity-row> Running checks against 2.2.0
2022-08-28 10:29:40.754 DEBUG (MainThread) [custom_components.hacs] <Plugin reptilex/tesla-style-solar-power-card> Running checks against v1.3.2
2022-08-28 10:29:40.819 DEBUG (MainThread) [aiogithubapi] 'GitHubReleaseModel' is missing key 'discussion_url' for <class 'str'>
2022-08-28 10:29:40.829 DEBUG (MainThread) [custom_components.hacs] <Plugin kalkih/mini-media-player> Running checks against v1.16.4
2022-08-28 10:29:40.881 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.27.1
2022-08-28 10:29:41.415 DEBUG (MainThread) [custom_components.hacs] 'state_attr' is undefined
2022-08-28 10:29:41.451 ERROR (MainThread) [homeassistant.util.logging] Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository': ({'id': 1337, 'action': 'update', 'repository': 'gadgetchnnel/lovelace-card-templater', 'repository_id': '184333163'},)
Traceback (most recent call last):
  File "/config/custom_components/hacs/entity.py", line 63, in _update_and_write_state
    self._update()
  File "/config/custom_components/hacs/sensor.py", line 33, in _update
    repositories = [
  File "/config/custom_components/hacs/sensor.py", line 36, in <listcomp>
    if repository.pending_update
  File "/config/custom_components/hacs/repositories/base.py", line 368, in pending_update
    result := version_left_higher_then_right(
  File "/config/custom_components/hacs/utils/version.py", line 23, in version_left_higher_then_right
    return left_version > right_version
  File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 170, in __gt__
    return self._compare_versions(self, compareto)
  File "/usr/local/lib/python3.10/site-packages/awesomeversion/awesomeversion.py", line 198, in _compare_versions
    result = handler(AwesomeVersion(version_a), AwesomeVersion(version_b))
  File "/usr/local/lib/python3.10/site-packages/awesomeversion/comparehandlers/modifier.py", line 28, in compare_handler_semver_modifier
    SEMVER_MODIFIER_MAP[version_a.modifier_type]
KeyError: 'mmppt'
```

### Diagnostics dump

[config_entry-hacs-c4b5614b0ee2f7bcbb6fde4c0ef37539.json.txt](https://github.com/hacs/integration/files/9439323/config_entry-hacs-c4b5614b0ee2f7bcbb6fde4c0ef37539.json.txt)

**Comment by Remko76** [comment]
As one extra bit of information: The error:
```Exception in _update_and_write_state when dispatching 'hacs_dispatch_repository'....```

Shows up for all of the custom components and frontend components I have added through HACS.

**Comment by ludeeus** [comment]
You are missing the rest of the debug logs.
The startup has not completed at that stage

**Comment by Remko76** [comment]
I coudln't post the full log (exceeded the amount of characters), so I have added it as attachment now. I waited until HASS reports "Startup completed" and copied the log file after that. It keeps filling with the same error messages, so I hope this is enough...
[home-assistant.log](https://github.com/hacs/integration/files/9439344/home-assistant.log)
?

**Comment by ludeeus** [comment]
WillCodeForCats/solaredge-modbus-multi is using an invalid version format.

Update HACS to 1.27.1 or wait for Home Assistant 2022.9.0

**Comment by Remko76** [comment]
Can you help me by telling me how to upgrade HACS to 1.27.1? As I mentioned, I reinstalled following the guide, so was expecting to get the latest version.

**Comment by ludeeus** [comment]
do it again
it was released today

**Comment by Remko76** [comment]
I actually just did it 30 minutes ago and the logs you are seeing are from that version....

**Comment by ludeeus** [comment]
No its not "Version: 1.27.0"

**Comment by Remko76** [comment]
I understand that, but what should I do then? I completely removed HACS following the guide (including all the restarts) and started installing it from scratch again, following the original setup guide....should I just wait a couple more hours before I try again...?

**Comment by ludeeus** [comment]
I told you what you need to do.
What you do with that is 100% up to you.
