### ISSUE TITLE
unable to activate device at installations

### ISSUE THREAD

**Issue by sopparus** [hacs/integration#2856]
## System Information

version | core-2022.9.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.5
os_name | Linux
os_version | 5.15.67
arch | x86_64
timezone | Europe/Stockholm
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.0
-- | --
update_channel | stable
supervisor_version | supervisor-2022.09.1
agent_version | 1.3.0
docker_version | 20.10.17
disk_total | 30.8 GB
disk_used | 4.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Let's Encrypt (4.12.7), Terminal & SSH (9.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 15 september 2022 07:01
-- | --
current_recorder_run | 24 september 2022 06:22
estimated_db_size | 16.64 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

My first installation of HACS, everything went fine until device activation.
I've tried for three days at different times with two different github accounts.

### Reproduction steps

1. follow hacs install guide
2. add integration hacs
3.
...

### Debug logs

```text
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/hacs/config_flow.py", line 62, in _wait_for_activation
    response = await self.device.activation(device_code=self._login_device.device_code)
  File "/usr/local/lib/python3.10/site-packages/aiogithubapi/device.py", line 160, in activation
    raise GitHubException(response.data.get("error_description"))
aiogithubapi.exceptions.GitHubException: Too many requests have been made in the same timeframe.
```

**Comment by ludeeus** [comment]
Make sure you only have 1 HA running and only 1 window open.
It's not possible to get into this situation without triggering it more than once.

**Comment by sopparus** [comment]
I do have only one HA running and only 1 windows open.
I've logged out on phone as well.

**Comment by mmacai** [comment]
Having the same issue, even if I wait for an hour, still ends up with the same error.

**Comment by ludeeus** [comment]
Something is messing with time on your system.
Disable all other custom integrations.

**Comment by mmacai** [comment]
Think you are right. Changed my timezone and seems to work fine for now. Perhaps it would be worth to mention it in some FAQ as I can imagine there are more people having the same issue due to the same reason.
