### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'repositories'

### ISSUE THREAD

**Issue by jomach** [hacs/integration#2975]
## System Information

version | core-2022.12.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4324
Installed Version | 1.29.0
Stage | running
Available Repositories | 1268
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 57.8 GB
disk_used | 9.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), Studio Code Server (5.5.1), Mosquitto broker (6.1.3), deCONZ (6.17.1), Node-RED (14.0.0), Zigbee2MQTT (1.28.4-1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 1
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 20, 2022 at 9:21 PM
-- | --
current_recorder_run | December 29, 2022 at 9:58 PM
estimated_db_size | 67.99 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I'm getting 

```
2022-12-30 07:02:02.712 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546873685904] Error handling message: Unknown error (unknown_error) from 2a02:810d:bcc0:5dc::b657 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repositories.py", line 68, in hacs_repositories_list
for repo in hacs.repositories.list_all
AttributeError: 'NoneType' object has no attribute 'repositories'
```

my hacs page does not load fully now. I cannot see the frontend tab for example. 

### Reproduction steps

1.
2.
3.
...
s

### Debug logs

```text
2022-12-30 07:02:02.712 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546873685904] Error handling message: Unknown error (unknown_error) from 2a02:810d:bcc0:5dc::b657 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repositories.py", line 68, in hacs_repositories_list
for repo in hacs.repositories.list_all
AttributeError: 'NoneType' object has no attribute 'repositories'
```

**Comment by shurickdaryin** [comment]
+1, seeing this error in the log and the UI does not load (cannot add any new integration).
