### ISSUE TITLE
Config flow could not be loaded: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by kimwowboom** [hacs/integration#3040]
### System Health details

<html>
<body>
<div class="mdc-dialog__container" style="display: flex; flex-direction: row; align-items: var(--vertical-align-dialog, center); justify-content: space-around; box-sizing: border-box; height: 745.6px; transform: none; opacity: 1; pointer-events: none; color: rgb(33, 33, 33); font-family: Roboto, Noto, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mdc-dialog__surface" style="box-shadow: var(--mdc-dialog-box-shadow, 0px 11px 15px -7px rgba(0, 0, 0, 0.2), 0px 24px 38px 3px rgba(0, 0, 0, 0.14), 0px 9px 46px 8px rgba(0, 0, 0, 0.12)); position: var(--dialog-surface-position, relative); display: flex; flex-direction: column; flex-grow: 0; flex-shrink: 0; box-sizing: border-box; max-width: var(--mdc-dialog-max-width, 560px); max-height: var(--mdc-dialog-max-height, calc(100% - 32px)); pointer-events: auto; overflow-y: auto; background-color: var(--mdc-theme-surface, #fff); border-radius: var(--ha-dialog-border-radius, 28px); min-width: var(--mdc-dialog-min-width, 280px); top: var(--dialog-surface-top); margin-top: var(--dialog-surface-margin-top); min-height: var(--mdc-dialog-min-height, auto);"><h2 id="title" class="mdc-dialog__title" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-headline6-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-headline6-font-size, 1.25rem); line-height: var(--mdc-typography-headline6-line-height, 2rem); font-weight: var(--mdc-typography-headline6-font-weight, 500); letter-spacing: var(--mdc-typography-headline6-letter-spacing, 0.0125em); text-decoration: var(--mdc-typography-headline6-text-decoration, inherit); text-transform: var(--mdc-typography-headline6-text-transform, inherit); display: block; position: relative; flex-shrink: 0; box-sizing: border-box; margin: 0px 0px 1px; padding: 24px 24px 0px; color: var(--mdc-dialog-heading-ink-color, rgba(0, 0, 0, 0.87));"><div class="header_title" style="margin-right: 32px; margin-inline-end: 32px; margin-inline-start: initial; direction: var(--direction);">Systeeminformatie</div><ha-icon-button dialogaction="close" class="header_button" style="display: inline-block; outline: none; position: absolute; right: 16px; top: 14px; text-decoration: none; color: inherit; inset-inline-start: initial; inset-inline-end: 16px; direction: var(--direction);"><mwc-icon-button title="Sluit" style="display: inline-block; outline: none; --mdc-ripple-color: currentcolor; -webkit-tap-highlight-color: transparent; vertical-align: top; --mdc-theme-on-primary: currentColor; --mdc-theme-text-disabled-on-light: var(--disabled-text-color);"><button class="mdc-icon-button mdc-icon-button--display-flex" aria-label="Sluit" style="font-size: 24px; width: var(--mdc-icon-button-size, 48px); height: var(--mdc-icon-button-size, 48px); padding: calc( (var(--mdc-icon-button-size, 48px) - var(--mdc-icon-size, 24px)) / 2 ); display: inline-flex; position: relative; box-sizing: border-box; border: none; outline: none; background-color: transparent; fill: currentcolor; color: inherit; text-decoration: none; cursor: pointer; user-select: none; z-index: 0; overflow: visible; align-items: center; justify-content: center; vertical-align: top;"><span><slot><ha-svg-icon style="display: block; align-items: center; justify-content: center; position: relative; vertical-align: middle; fill: currentcolor; width: var(--mdc-icon-size, 24px); height: var(--mdc-icon-size, 24px);"><svg preserveAspectRatio="xMidYMid meet" focusable="false" role="img" aria-hidden="true" viewBox="0 0 24 24"><g><path d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></g></svg></ha-svg-icon></slot></span></button></mwc-icon-button></ha-icon-button></h2><div id="content" class="mdc-dialog__content" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-body1-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-body1-font-size, 1rem); line-height: var(--mdc-typography-body1-line-height, 1.5rem); font-weight: var(--mdc-typography-body1-font-weight, 400); letter-spacing: var(--mdc-typography-body1-letter-spacing, 0.03125em); text-decoration: var(--mdc-typography-body1-text-decoration, inherit); text-transform: var(--mdc-typography-body1-text-transform, inherit); flex-grow: 1; box-sizing: border-box; margin: 0px; overflow: auto; color: var(--mdc-dialog-content-ink-color, rgba(0, 0, 0, 0.6)); padding: var(--dialog-content-padding, 24px); position: var(--dialog-content-position, relative);"><slot id="contentSlot" style="margin-top: 0px; margin-bottom: 0px;"><div><div>

Versie | core-2023.1.1
-- | --
Type installatie | Home Assistant Container
Ontwikkeling | false
Supervisor | false
Docker | true
Gebruiker | root
Virtuele omgeving | false
Python-versie | 3.10.7
Besturingssysteem | Linux
Versie van het besturingssysteem | 4.4.180+
CPU-architectuur | x86_64
Tijdzone | Europe/Amsterdam
Configuratiemap | /config

</div></div></slot></div><footer id="actions" class=" mdc-dialog__actions " style="display: flex; position: relative; flex-shrink: 0; flex-wrap: wrap; align-items: center; justify-content: var(--justify-action-buttons, flex-end); box-sizing: border-box; min-height: 52px; margin: 0px; padding: 0px 24px 24px; border-top: 1px solid transparent;"><span style="flex: var(--secondary-action-button-flex, unset);"><slot name="secondaryAction"></slot></span><span style="flex: var(--primary-action-button-flex, unset);"><slot name="primaryAction"><mwc-button slot="primaryAction" style="display: inline-flex; outline: none; -webkit-tap-highlight-color: transparent; vertical-align: top; margin-left: 8px; margin-right: 0px; max-width: 100%; text-align: right;"><button id="button" class="mdc-button   " aria-label="Kopiëren" style="-webkit-font-smoothing: antialiased; font-family: var(--mdc-typography-button-font-family, var(--mdc-typography-font-family, Roboto, sans-serif)); font-size: var(--mdc-typography-button-font-size, 0.875rem); line-height: inherit; font-weight: var(--mdc-typography-button-font-weight, 500); letter-spacing: var(--mdc-typography-button-letter-spacing, 0.0892857em); text-decoration: var(--mdc-typography-button-text-decoration, none); text-transform: var(--mdc-typography-button-text-transform, uppercase); position: relative; display: inline-flex; align-items: center; justify-content: center; box-sizing: border-box; min-width: 64px; border: none; outline: none; user-select: none; appearance: none; overflow: hidden; vertical-align: middle; background: transparent; padding-top: 0px; padding-right: var(--mdc-button-horizontal-padding, 8px); padding-bottom: 0px; padding-left: var(--mdc-button-horizontal-padding, 8px); height: 36px; border-radius: var(--mdc-shape-small, 4px); flex: 1 1 auto; color: var(--mdc-theme-primary, #6200ee);"><span class="leading-icon"><slot name="icon"></slot></span><span class="mdc-button__label" style="position: relative;">KOPIËREN</span><span class="slot-container   " style="display: inline-flex; align-items: center; justify-content: center;"><slot></slot></span><span class="trailing-icon"><slot name="trailingIcon"></slot></span></button></mwc-button></slot></span></footer></div></div><br class="Apple-interchange-newline">
</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have seen many messages with this error message but didn't find a solution. 

Installed hacs.
Want to add it trough intergration. Then it gives me this error message.

Config flow could not be loaded: {"message":"Invalid handler specified"}

### Reproduction steps

1. Installed hacs trough the terminal in the Docker container of Synoly nas
2. Restarted home assistant
3. Cleared browser
4. Go to intergrations
5. search for Hacs to configure it
6. Error pops up
...

### Debug logs

```text
2023-01-27 07:27:46.807 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-01-27 07:27:47.694 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.1 seconds
2023-01-27 07:27:47.694 INFO (MainThread) [homeassistant.bootstrap] Setting up frontend: {'frontend'}
2023-01-27 07:27:47.785 INFO (MainThread) [homeassistant.setup] Setting up device_automation
2023-01-27 07:27:47.785 INFO (MainThread) [homeassistant.setup] Setup of domain device_automation took 0.0 seconds
2023-01-27 07:27:48.205 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2023-01-27 07:27:48.210 INFO (MainThread) [homeassistant.setup] Setting up http
2023-01-27 07:27:48.215 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.0 seconds
2023-01-27 07:27:48.280 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.1 seconds
2023-01-27 07:27:48.291 INFO (MainThread) [homeassistant.setup] Setting up api
2023-01-27 07:27:48.294 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.0 seconds
2023-01-27 07:27:48.296 INFO (MainThread) [homeassistant.setup] Setting up auth
2023-01-27 07:27:48.298 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds
2023-01-27 07:27:48.334 INFO (MainThread) [homeassistant.setup] Setting up config
2023-01-27 07:27:48.451 INFO (MainThread) [homeassistant.setup] Setting up diagnostics
2023-01-27 07:27:48.486 INFO (MainThread) [homeassistant.setup] Setting up repairs
2023-01-27 07:27:48.488 INFO (MainThread) [homeassistant.setup] Setup of domain repairs took 0.0 seconds
2023-01-27 07:27:48.896 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.6 seconds
2023-01-27 07:27:48.898 INFO (MainThread) [homeassistant.setup] Setup of domain diagnostics took 0.4 seconds
2023-01-27 07:27:50.025 INFO (MainThread) [homeassistant.setup] Setting up file_upload
2023-01-27 07:27:50.025 INFO (MainThread) [homeassistant.setup] Setup of domain file_upload took 0.0 seconds
2023-01-27 07:27:51.318 INFO (MainThread) [homeassistant.setup] Setting up image_upload
2023-01-27 07:27:51.320 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2023-01-27 07:27:51.321 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds
2023-01-27 07:27:51.325 INFO (MainThread) [homeassistant.setup] Setup of domain image_upload took 0.0 seconds
2023-01-27 07:27:51.330 INFO (MainThread) [homeassistant.setup] Setting up person
2023-01-27 07:27:51.346 INFO (SyncWorker_2) [homeassistant.loader] Loaded group from homeassistant.components.group
2023-01-27 07:27:53.946 INFO (MainThread) [homeassistant.setup] Setting up analytics
2023-01-27 07:27:54.120 INFO (MainThread) [homeassistant.setup] Setting up search
2023-01-27 07:27:54.121 INFO (MainThread) [homeassistant.setup] Setup of domain search took 0.0 seconds
2023-01-27 07:27:54.121 INFO (MainThread) [homeassistant.setup] Setup of domain analytics took 0.2 seconds
2023-01-27 07:27:54.137 INFO (MainThread) [homeassistant.setup] Setup of domain person took 2.8 seconds
2023-01-27 07:27:54.140 INFO (SyncWorker_0) [homeassistant.loader] Loaded hassio from homeassistant.components.hassio
2023-01-27 07:27:54.142 INFO (SyncWorker_5) [homeassistant.loader] Loaded panel_custom from homeassistant.components.panel_custom
2023-01-27 07:27:54.147 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2023-01-27 07:27:54.150 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.0 seconds
2023-01-27 07:27:54.152 INFO (MainThread) [homeassistant.setup] Setting up frontend
2023-01-27 07:27:54.177 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.0 seconds
2023-01-27 07:27:54.179 INFO (MainThread) [homeassistant.bootstrap] Setting up recorder: {'recorder'}
2023-01-27 07:27:54.183 INFO (MainThread) [homeassistant.setup] Setting up recorder
2023-01-27 07:27:54.191 INFO (MainThread) [homeassistant.components.http] Now listening on port 8123
2023-01-27 07:27:54.331 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 0.1 seconds
2023-01-27 07:27:54.333 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 1: {'ssdp', 'dhcp', 'http', 'websocket_api', 'network', 'zeroconf', 'api', 'webhook', 'usb', 'cloud', 'bluetooth'}
2023-01-27 07:27:54.380 INFO (MainThread) [homeassistant.setup] Setting up webhook
2023-01-27 07:27:54.381 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds
2023-01-27 07:27:55.238 INFO (MainThread) [homeassistant.setup] Setting up dhcp
2023-01-27 07:27:55.239 INFO (MainThread) [homeassistant.setup] Setup of domain dhcp took 0.0 seconds
2023-01-27 07:27:55.247 INFO (MainThread) [homeassistant.setup] Setting up network
2023-01-27 07:27:55.254 INFO (MainThread) [homeassistant.setup] Setup of domain network took 0.0 seconds
2023-01-27 07:27:55.317 INFO (MainThread) [homeassistant.setup] Setting up usb
2023-01-27 07:27:55.318 INFO (MainThread) [homeassistant.setup] Setup of domain usb took 0.0 seconds
2023-01-27 07:27:55.342 INFO (SyncWorker_0) [homeassistant.loader] Loaded google_assistant from homeassistant.components.google_assistant
2023-01-27 07:27:55.371 INFO (SyncWorker_6) [homeassistant.loader] Loaded alexa from homeassistant.components.alexa
2023-01-27 07:27:55.522 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2023-01-27 07:27:55.526 INFO (MainThread) [zeroconf] Address in use when adding (('fe80::211:32ff:feaa:7a08', 0, 3), 3) to multicast group, it is expected to happen on some systems
2023-01-27 07:27:55.813 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2023-01-27 07:27:55.818 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 0.3 seconds
2023-01-27 07:27:55.835 INFO (SyncWorker_3) [homeassistant.loader] Loaded camera from homeassistant.components.camera
2023-01-27 07:27:56.873 INFO (MainThread) [homeassistant.setup] Setting up bluetooth
2023-01-27 07:27:57.012 ERROR (MainThread) [homeassistant.setup] Error handling when_setup callback for frontend
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 166, in __new__
    port = val.port
  File "/usr/local/lib/python3.10/urllib/parse.py", line 178, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as '8123:8123'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 420, in when_setup
    await when_setup_cb(hass, component)
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 200, in _async_zeroconf_hass_start
    await _async_register_hass_zc_service(hass, aio_zc, uuid)
  File "/usr/src/homeassistant/homeassistant/components/zeroconf/__init__.py", line 267, in _async_register_hass_zc_service
    params["external_url"] = get_url(hass, allow_internal=False)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 156, in get_url
    return _get_external_url(
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 266, in _get_external_url
    external_url = yarl.URL(hass.config.external_url)
  File "/usr/local/lib/python3.10/site-packages/yarl/_url.py", line 168, in __new__
```

### Diagnostics dump

not available

**Comment by ludeeus** [comment]
There is nothing that can be done in HACS for this, as this feature is 100% on the HA side.
You get this because of 1 (or more of the following):
- The download script did not complete
- You are not meeting the required minimum version of HA
- The instance is not properly restarted
- The browser cache is not properly cleared
- There are other issues with your instance that prevent it from loading the configuration flow
