### ISSUE TITLE
hacs integration cannot load

### ISSUE THREAD

**Issue by vrabi-cv** [hacs/integration#3088]
### Web browser

chrome

### Web browser version

110.0.5481.180

### System Health details

Cannot find this item, so just copied the info:
Home Assistant 2023.3.3
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.0 - latest

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Some weeks ago stopped the hacs with error see bellow.

### Reproduction steps

1. first tried to remove the hacs
2. restarted HA
3. cleared cache
4. deleted all data about hacs
5. restarted HA
6. installed hacs again
7. restarted HA
8. the error shows  up again:(

here is log:
[home-assistant_2023-03-11T16-13-56.286Z.log](https://github.com/hacs/integration/files/10948944/home-assistant_2023-03-11T16-13-56.286Z.log)

### Screenshots

![hacs error](https://user-images.githubusercontent.com/110232498/224496217-7eb093a9-f406-4c88-abec-7f112454667e.JPG)

### Javascript logs from your browser console

```text
2023-03-11 17:03:07.342 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-11 17:03:07.353 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration auto_backup which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-11 17:03:07.358 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-11 17:03:07.364 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-11 17:03:07.369 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration cz_energy_spot_prices which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-11 17:03:07.374 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-11 17:03:07.379 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-11 17:03:07.385 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration cezdistribuce which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-11 17:03:24.510 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2023-03-11 17:03:38.820 ERROR (MainThread) [homeassistant.components.sensor] The filesize platform for the sensor integration does not support platform setup. Please remove it from your config.
2023-03-11 17:03:39.449 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for cz_energy_spot_prices using this method at custom_components/cz_energy_spot_prices/__init__.py, line 24: hass.config_entries.async_setup_platforms(entry, ['sensor'])
2023-03-11 17:03:54.533 WARNING (MainThread) [homeassistant.components.mqtt] The 'broker' option near /config/configuration.yaml:21 is deprecated, please remove it from your configuration
2023-03-11 17:03:54.577 WARNING (MainThread) [homeassistant.components.mqtt] The 'password' option near /config/configuration.yaml:21 is deprecated, please remove it from your configuration
2023-03-11 17:03:54.581 WARNING (MainThread) [homeassistant.components.mqtt] The 'port' option near /config/configuration.yaml:21 is deprecated, please remove it from your configuration
2023-03-11 17:03:54.584 WARNING (MainThread) [homeassistant.components.mqtt] The 'username' option near /config/configuration.yaml:21 is deprecated, please remove it from your configuration
2023-03-11 17:03:54.684 WARNING (MainThread) [homeassistant.setup] Setup of automation is taking over 10 seconds.
2023-03-11 17:03:54.687 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform samsungtv is taking over 10 seconds.
2023-03-11 17:03:54.690 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2023-03-11 17:03:54.707 WARNING (MainThread) [homeassistant.components.mqtt] Deprecated configuration settings found in configuration.yaml. These settings from your configuration entry will override: {'broker': 'core-mosquitto'}
2023-03-11 17:03:54.848 WARNING (MainThread) [custom_components.smartthinq_sensors] Connection not available. ThinQ platform not ready
Traceback (most recent call last):
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 245, in async_setup_entry
    client = await lge_auth.create_client_from_token(refresh_token, oauth2_url)
  File "/config/custom_components/smartthinq_sensors/__init__.py", line 145, in create_client_from_token
    return await ClientAsync.from_token(
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 1422, in from_token
    gateway = await Gateway.discover(core)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 689, in discover
    gw_info = await core.gateway_info()
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 395, in gateway_info
    result = await self.thinq2_get(V2_GATEWAY_URL)
  File "/config/custom_components/smartthinq_sensors/wideq/core_async.py", line 282, in thinq2_get
    async with self._get_session().get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
2023-03-11 17:03:54.929 WARNING (MainThread) [homeassistant.config_entries] Config entry 'LGE Devices' for smartthinq_sensors integration not ready yet: ThinQ platform not ready; Retrying in background
2023-03-11 17:03:58.137 INFO (Thread-2 (_thread_main)) [homeassistant.components.mqtt.client] Connected to MQTT server core-mosquitto:1883 (0)
2023-03-11 17:03:59.173 DEBUG (SyncWorker_1) [homeassistant.components.mqtt.client] Subscribing to esp/dht/tep_obyvak, mid: 1, qos: 0
2023-03-11 17:04:00.932 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received retained message on esp/dht/tep_obyvak (qos=0): b'22.50'
2023-03-11 17:04:00.944 DEBUG (SyncWorker_4) [homeassistant.components.mqtt.client] Subscribing to esp/dht/vlh_obyvak, mid: 2, qos: 0
2023-03-11 17:04:02.318 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received retained message on esp/dht/vlh_obyvak (qos=0): b'52.80'
2023-03-11 17:04:02.318 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.vlhkost_obyvak (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement '°C' which is not a valid unit for the device class ('humidity') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
2023-03-11 17:04:02.429 DEBUG (SyncWorker_4) [homeassistant.components.mqtt.client] Subscribing to esp/dht/tep_veru, mid: 3, qos: 0
2023-03-11 17:04:04.264 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received retained message on esp/dht/tep_veru (qos=0): b'20.40'
2023-03-11 17:04:04.344 DEBUG (SyncWorker_4) [homeassistant.components.mqtt.client] Subscribing to esp/dht/vlh_veru, mid: 4, qos: 0
2023-03-11 17:04:04.475 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received retained message on esp/dht/vlh_veru (qos=0): b'50.80'
2023-03-11 17:04:04.476 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.vlhkost_verca (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement '°C' which is not a valid unit for the device class ('humidity') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
2023-03-11 17:04:04.521 DEBUG (SyncWorker_2) [homeassistant.components.mqtt.client] Subscribing to tarif, mid: 5, qos: 0
2023-03-11 17:04:04.938 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Domov' for shelly integration not ready yet: DeviceConnectionError(); Retrying in background
2023-03-11 17:04:05.517 DEBUG (SyncWorker_2) [homeassistant.components.mqtt.client] Subscribing to homeassistant/+/+/config, mid: 6, qos: 0
2023-03-11 17:04:05.581 DEBUG (SyncWorker_1) [homeassistant.components.mqtt.client] Subscribing to homeassistant/+/+/+/config, mid: 7, qos: 0
2023-03-11 17:04:06.000 DEBUG (SyncWorker_1) [homeassistant.components.mqtt.client] Subscribing to dsmr/#, mid: 8, qos: 0
2023-03-11 17:04:06.080 DEBUG (SyncWorker_5) [homeassistant.components.mqtt.client] Subscribing to fully/deviceInfo/+, mid: 9, qos: 0
2023-03-11 17:04:08.910 DEBUG (SyncWorker_3) [homeassistant.components.mqtt.client] Subscribing to tasmota/discovery/#, mid: 10, qos: 0
2023-03-11 17:04:09.194 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for google_home using this method at custom_components/google_home/__init__.py, line 78: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
2023-03-11 17:04:09.807 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for auto_backup using this method at custom_components/auto_backup/__init__.py, line 192: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
2023-03-11 17:04:14.237 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.40'
2023-03-11 17:04:14.343 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.80'
2023-03-11 17:04:14.439 DEBUG (MainThread) [homeassistant.components.mqtt.client] Transmitting message on homeassistant/status: 'online', mid: 11, qos: 1
2023-03-11 17:04:58.221 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:05:13.975 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.40'
2023-03-11 17:05:14.301 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.70'
2023-03-11 17:05:58.209 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:06:13.971 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.50'
2023-03-11 17:06:14.324 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.70'
2023-03-11 17:06:58.216 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:07:13.977 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.50'
2023-03-11 17:07:14.192 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.80'
2023-03-11 17:07:58.211 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:08:13.979 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.40'
2023-03-11 17:08:14.239 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.90'
2023-03-11 17:08:58.211 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:09:13.981 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.40'
2023-03-11 17:09:14.436 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.70'
2023-03-11 17:09:58.219 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:10:14.576 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.40'
2023-03-11 17:10:14.576 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.60'
2023-03-11 17:10:35.319 ERROR (SyncWorker_1) [homeassistant.util.json] Could not parse JSON content: /config/.storage/hacs.repositories
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/json.py", line 68, in load_json
    return orjson.loads(fdesc.read())  # type: ignore[no-any-return]
orjson.JSONDecodeError: unexpected character: line 126 column 3403 (char 7394)
2023-03-11 17:10:35.330 ERROR (MainThread) [custom_components.hacs] Could not read /config/.storage/hacs.repositories, restore the file from a backup - unexpected character: line 126 column 3403 (char 7394)
2023-03-11 17:10:35.333 ERROR (MainThread) [custom_components.hacs] HACS is disabled - restore
2023-03-11 17:10:58.218 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:11:13.975 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.50'
2023-03-11 17:11:14.198 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.70'
2023-03-11 17:11:58.778 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:12:13.979 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.50'
2023-03-11 17:12:14.319 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.70'
2023-03-11 17:13:04.230 WARNING (MainThread) [custom_components.smartthinq_sensors.wideq.device] Connection to ThinQ failed. Network connection error - Device: Sušička LG
2023-03-11 17:13:07.746 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on tarif (qos=0): b'0'
2023-03-11 17:13:14.512 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/tep_veru (qos=0): b'20.50'
2023-03-11 17:13:14.890 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on esp/dht/vlh_veru (qos=0): b'50.70'
2023-03-11 17:13:51.811 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/core_mosquitto/stats request
2023-03-11 17:13:52.224 WARNING (MainThread) [homeassistant.components.hassio] Could not fetch stats for core_mosquitto: 
2023-03-11 17:13:52.227 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_nodered/stats request
2023-03-11 17:13:52.230 WARNING (MainThread) [homeassistant.components.hassio] Could not fetch stats for a0d7b954_nodered: 
2023-03-11 17:13:52.233 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/5c53de3b_esphome/stats request
2023-03-11 17:13:52.239 WARNING (MainThread) [homeassistant.components.hassio] Could not fetch stats for 5c53de3b_esphome: 
2023-03-11 17:13:52.244 ERROR (MainThread) [homeassistant.components.hassio.handler] Timeout on /addons/a0d7b954_vscode/stats request
2023-03-11 17:13:52.247 WARNING (MainThread) [homeassistant.components.hassio] Could not fetch stats for a0d7b954_vscode:
```

**Comment by ludeeus** [comment]
Restore the file it's complaining about from a backup.

**Comment by vrabi-cv** [comment]
> Restore the file it's complaining about from a backup.

Hi, thanks for reply. Unfortunatelly do not have any backup file to restore from. As mentioned in the post I deleted all files about hacs from drive, so there cannot be any backup file:(

**Comment by lvta0909** [comment]
I had a similar issue, two days ago, the line number/column was different.
I used terminal to edit the /config/.storage/hacs.repositores
I found a weird character on the line with the error. Deleted it and restart the addon. It went back to normal.

**Comment by vrabi-cv** [comment]
Unfortunately there is no ".storage" under my config directory: 
![list](https://user-images.githubusercontent.com/110232498/227729780-c32b51f4-d7cb-43d0-ae5b-3d465ef35264.JPG)
