### ISSUE TITLE
Add custom repositories stays blank

### ISSUE THREAD

**Issue by Sk1nk** [hacs/integration#3099]
## System Information

version | core-2023.3.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 5.15.84-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4954
Installed Version | 1.31.0
Stage | running
Available Repositories | 1244
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.03.3
agent_version | 1.4.1
docker_version | 20.10.22
disk_total | 28.5 GB
disk_used | 4.4 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.6.1), Home Assistant Google Drive Backup (0.110.3), File editor (5.5.0), AdGuard Home (4.8.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 1
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24. März 2023, 05:35
-- | --
current_recorder_run | 2. April 2023, 23:16
estimated_db_size | 348.00 MiB
database_engine | sqlite
database_version | 3.38.5

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I tried to get a viomi_v8 to work. AddedViomi Robot Vacuum Cleaner and Map Extractor via HACS.
When I try to add a custom repository the new window that opens up is just empty.
I tried clearing the cache, reloading HA.

### Reproduction steps

1. Open HACS
2. 3 Dots in top right corner
3. Add custom Repositories
...

### Debug logs

```text
2023-04-02 23:28:21.990 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-02 23:28:21.991 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-02 23:28:21.992 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration viomise which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-02 23:28:42.196 ERROR (MainThread) [custom_components.viomise.vacuum] Device Stauboga unavailable or token incorrect: Unable to discover the device 192.168.179.2
2023-04-02 23:28:42.266 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up viomise platform for vacuum
Traceback (most recent call last):
  File "/config/custom_components/viomise/vacuum.py", line 213, in __init__
    self._miio_info = vacuum.info()
  File "/usr/local/lib/python3.10/site-packages/miio/click_common.py", line 184, in _wrap
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 148, in info
    return self._fetch_info()
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 153, in _fetch_info
    devinfo = DeviceInfo(self.send("miIO.info"))
  File "/usr/local/lib/python3.10/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.10/site-packages/miio/miioprotocol.py", line 161, in send
    self.send_handshake()
  File "/usr/local/lib/python3.10/site-packages/miio/miioprotocol.py", line 74, in send_handshake
    raise DeviceException("Unable to discover the device %s" % self.ip)
miio.exceptions.DeviceException: Unable to discover the device 192.168.179.2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/viomise/vacuum.py", line 166, in async_setup_platform
    mirobo = MiroboVacuum2(name, vacuum)
  File "/config/custom_components/viomise/vacuum.py", line 216, in __init__
    raise PlatformNotReady from exc
NameError: name 'PlatformNotReady' is not defined
2023-04-02 23:28:44.319 ERROR (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to log in, check credentials
2023-04-02 23:28:44.643 INFO (SyncWorker_2) [fritzconnection] Unable to retrieve resource 'http://192.168.178.23:49000/igddesc.xml' from the device.
2023-04-02 23:28:44.686 INFO (SyncWorker_1) [fritzconnection] Unable to retrieve resource 'http://192.168.178.22:49000/igddesc.xml' from the device.
2023-04-02 23:28:49.473 WARNING (SyncWorker_6) [custom_components.xiaomi_cloud_map_extractor.camera] Got exception while fetching the state: Unable to discover the device 192.168.179.2
2023-04-02 23:28:53.135 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2023-04-02 23:29:35.558 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Akku Zahnbürste' trigger: In 'numeric_state' condition: unknown entity sensor.io_series_6_7_c8a2_battery
2023-04-02 23:29:43.329 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:29:48.330 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2023-04-02 23:29:48.333 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:29:53.331 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:29:58.332 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:03.333 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:08.334 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:13.335 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:18.336 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:23.337 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:28.338 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:38.341 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:43.342 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2023-04-02 23:30:43.348 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:48.344 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:53.345 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:30:58.346 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:03.347 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:08.349 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:13.350 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:18.351 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:23.352 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:33.354 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:38.355 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:38.359 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2023-04-02 23:31:43.356 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:48.358 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:53.360 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:31:58.362 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:32:03.364 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2023-04-02 23:32:08.365 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
```

### Diagnostics dump

[config_entry-hacs-bba4ac23665e1b6f1838e48dabb379f6.json.txt](https://github.com/hacs/integration/files/11133411/config_entry-hacs-bba4ac23665e1b6f1838e48dabb379f6.json.txt)
![Bildschirmfoto 2023-04-02 um 23 38 56](https://user-images.githubusercontent.com/13984365/229380368-6555e39a-0e08-4349-9eb6-2459e4a56385.png)

**Comment by ludeeus** [comment]
This is the old UI, it will not be fixed.
This is fixed in the new UI you can enable with experimental features and a restart of HA (+clear cache)
