### ISSUE TITLE
"SpaceX Next Launch and Starman" keeps showing as new

### ISSUE THREAD

**Issue by tjorim** [hacs/integration#3100]
## System Information

version | core-2023.4.0b6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.10
os_name | Linux
os_version | 6.1.19-v8
arch | aarch64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4928
Installed Version | 1.31.0
Stage | running
Available Repositories | 1251
Downloaded Repositories | 67
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.0.rc3
-- | --
update_channel | beta
supervisor_version | supervisor-2023.04.0
agent_version | 1.5.1
docker_version | 23.0.2
disk_total | 458.4 GB
disk_used | 38.4 GB
healthy | true
supported | true
board | yellow
supervisor_api | ok
version_api | ok
installed_addons | AirCast (3.5.2), Spotify Connect (0.12.3), SSH & Web Terminal (13.1.0), File editor (5.5.0), Studio Code Server (5.5.6), Zigbee2MQTT (1.30.3-1), Home Assistant Google Drive Backup (0.110.3), MariaDB (2.5.2), phpMyAdmin (0.8.5), JupyterLab (0.10.0), The Lounge (0.17.1), Glances (0.18.1), Tailscale (0.10.0), ZeroTier One (0.16.2), AdGuard Home (4.8.3), Nginx Proxy Manager (0.12.3), Uptime Kuma (0.7.1), WireGuard (0.8.0), CUPS Print Server (2.0.2), ESPHome (2023.3.2), Grafana (8.2.1), Music Assistant BETA (2.0.0b24), Mosquitto broker (6.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 28
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 11, 2022 at 7:18 AM
-- | --
current_recorder_run | April 4, 2023 at 1:09 PM
estimated_db_size | 7009.72 MiB
database_engine | mysql
database_version | 10.6.10

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Every HA restart or HACS reload, "SpaceX Next Launch and Starman" shows up as new repo.

![image](https://user-images.githubusercontent.com/1294876/229774745-4a4f3dbb-febe-4256-9d48-fc3b1b88ebd1.png)

However, this repo has been removed here: https://github.com/hacs/default/pull/1765

### Reproduction steps

1. Restart HA or reload HA
2. Open HACS (and optionally filter on new repo)
3. "SpaceX Next Launch and Starman" will show up...

### Debug logs

```text
2023-04-04 13:09:02.239 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tplink_deco which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.242 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration mbapi2020 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.244 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.246 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration temperature_feels_like which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.249 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration neerslag which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.251 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.254 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration load_shedding which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.256 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.258 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration youfone_be which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.260 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration eskom_loadshedding which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.263 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.265 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration buienalarm which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.267 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration composite which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.269 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration qr_generator which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.271 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tgtg which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.273 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration mijntuin which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.275 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hpprinter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.277 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration upnp_availability which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.279 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration auto_areas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.281 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration spook which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.283 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.285 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration npm_switches which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.287 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration google_photos which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.289 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.291 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration telenet_telemeter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.293 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration spotcast which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.295 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.297 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration snowtire which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.299 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.301 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration google_keep which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.303 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration casambi_bt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.305 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration telenet which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.307 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration sonicare_bletb which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.309 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration uptime_kuma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.311 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ledfx which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.313 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration lghorizon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.315 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration car_wash which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.317 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration recycle_app which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.320 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration bibliotheek_be which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.327 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:02.329 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration carbu_com which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 13:09:33.384 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.31.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2023-04-04 13:09:34.299 DEBUG (MainThread) [custom_components.hacs] Configuration type: config_entry
2023-04-04 13:09:35.073 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform adguard is taking over 10 seconds.
2023-04-04 13:09:35.084 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform adguard is taking over 10 seconds.
2023-04-04 13:09:35.363 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore started
2023-04-04 13:09:36.360 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore done
2023-04-04 13:09:36.361 INFO (MainThread) [custom_components.hacs] Enable category: integration
2023-04-04 13:09:36.363 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2023-04-04 13:09:36.363 INFO (MainThread) [custom_components.hacs] Enable category: theme
2023-04-04 13:09:36.363 INFO (MainThread) [custom_components.hacs] <HacsFrontend> Using experimental frontend
2023-04-04 13:09:36.367 INFO (MainThread) [custom_components.hacs] Setting up plugin endpoint
2023-04-04 13:09:36.367 INFO (MainThread) [custom_components.hacs] <HacsFrontend> storage mode, cache for /hacsfiles/: True
2023-04-04 13:09:44.570 INFO (MainThread) [custom_components.hacs] Stage changed: setup
2023-04-04 13:09:44.572 INFO (MainThread) [custom_components.hacs] Stage changed: waiting
2023-04-04 13:09:44.572 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2023-04-04 13:09:44.615 ERROR (MainThread) [custom_components.google_home] Request from Google Home Mini device error: https://fe80::22df:b9ff:fe0c:701a:8443/setup/assistant/alarms
2023-04-04 13:09:44.626 ERROR (MainThread) [custom_components.google_home] Request from Google Home Mini device error: https://fe80::22df:b9ff:fe0c:701a:8443/setup/assistant/alarms/volume
2023-04-04 13:09:44.628 ERROR (MainThread) [custom_components.google_home] Request from Google Home Mini device error: https://fe80::22df:b9ff:fe0c:701a:8443/setup/assistant/notifications
2023-04-04 13:09:48.572 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform bibliotheek_be is taking over 10 seconds.
2023-04-04 13:09:54.306 ERROR (MainThread) [homeassistant.components.sensor] Platform carbu_com does not generate unique IDs. ID Carbu.com diesel prediction already exists - ignoring sensor.carbu_com_diesel_prediction
2023-04-04 13:09:54.377 ERROR (MainThread) [homeassistant.components.sensor] Platform carbu_com does not generate unique IDs. ID Carbu.com diesel prediction already exists - ignoring sensor.carbu_com_diesel_prediction
2023-04-04 13:10:00.525 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 129, in validate
    raise vol.Invalid(f"Expected positive event duration ({start}, {end})")
voluptuous.error.Invalid: Expected positive event duration (2023-10-08 02:00:00+02:00, 2023-10-08 02:00:00+02:00)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 343, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: Expected positive event duration (2023-10-08 02:00:00+02:00, 2023-10-08 02:00:00+02:00)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/google/calendar.py", line 439, in refresh
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 89, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 226, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 341, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 142, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/google/calendar.py", line 475, in _handle_coordinator_update
    self._apply_coordinator_update()
  File "/usr/src/homeassistant/homeassistant/components/google/calendar.py", line 465, in _apply_coordinator_update
    self._event = _get_calendar_event(api_event)
  File "/usr/src/homeassistant/homeassistant/components/google/calendar.py", line 550, in _get_calendar_event
    return CalendarEvent(
  File "<string>", line 11, in __init__
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 345, in __post_init__
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Failed to validate CalendarEvent: Expected positive event duration (2023-10-08 02:00:00+02:00, 2023-10-08 02:00:00+02:00)
2023-04-04 13:10:13.466 WARNING (MainThread) [homeassistant.components.integration.sensor] sensor.lidl_livarno_lux_gu10_spot_cct_energy could not restore last state unknown: [<class 'decimal.ConversionSyntax'>]
2023-04-04 13:10:14.571 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform scrape
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1611, in multiply
    return float(value) * amount
ValueError: could not convert string to float: '-'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 168, in async_added_to_hass
    self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 175, in _async_update_from_rest_data
    value = template.async_render_with_possible_json_value(value, None)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 702, in async_render_with_possible_json_value
    return _render_with_context(self.template, compiled, **variables).strip()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2121, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1615, in multiply
    raise_no_default("multiply", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1580, in raise_no_default
    raise ValueError(
ValueError: Template error: multiply got invalid input '-' when rendering template '{{ value | multiply(0.01) }}' but no default was specified
2023-04-04 13:10:14.591 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up scrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1611, in multiply
    return float(value) * amount
ValueError: could not convert string to float: '-'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 312, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 455, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 731, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 822, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 168, in async_added_to_hass
    self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 175, in _async_update_from_rest_data
    value = template.async_render_with_possible_json_value(value, None)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 702, in async_render_with_possible_json_value
    return _render_with_context(self.template, compiled, **variables).strip()
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2121, in _render_with_context
    return template.render(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1615, in multiply
    raise_no_default("multiply", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1580, in raise_no_default
    raise ValueError(
ValueError: Template error: multiply got invalid input '-' when rendering template '{{ value | multiply(0.01) }}' but no default was specified
2023-04-04 13:10:16.189 INFO (MainThread) [custom_components.hacs] Stage changed: startup
2023-04-04 13:10:16.449 DEBUG (MainThread) [custom_components.hacs] There are 6 scheduled recurring tasks
2023-04-04 13:10:16.449 INFO (MainThread) [custom_components.hacs] Loading removed repositories
2023-04-04 13:10:17.966 INFO (MainThread) [custom_components.hacs] <Integration djtimca/HASpaceX> Starting removal
2023-04-04 13:10:17.983 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2023-04-04 13:10:18.192 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.hacs'. Content did not change
2023-04-04 13:10:21.680 INFO (MainThread) [custom_components.hacs] Loading known repositories
2023-04-04 13:10:21.782 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for theme
2023-04-04 13:10:21.812 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for plugin
2023-04-04 13:10:21.813 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for integration
2023-04-04 13:10:27.141 DEBUG (MainThread) [custom_components.hacs] <Integration KoljaWindeler/kaco> Unregister stale custom repository
2023-04-04 13:10:27.286 INFO (MainThread) [custom_components.hacs] Stage changed: running
2023-04-04 13:10:28.373 DEBUG (MainThread) [custom_components.hacs] <QueueManager> The queue is empty
2023-04-04 13:10:28.498 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.bibliotheek_be_jorim_tielemans_stuifzand is taking over 10 seconds
2023-04-04 13:10:31.278 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.critical'. Content did not change
2023-04-04 13:10:31.278 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2023-04-04 13:10:35.021 WARNING (MainThread) [homeassistant.components.switch] Updating adguard switch took longer than the scheduled update interval 0:00:10
2023-04-04 13:10:36.362 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.carbu_com_diesel_2440_price is taking over 10 seconds
2023-04-04 13:10:37.002 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.carbu_com_diesel_2470_price is taking over 10 seconds
2023-04-04 13:10:37.055 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.carbu_com_diesel_2300_price is taking over 10 seconds
2023-04-04 13:10:46.651 DEBUG (MainThread) [custom_components.hacs] <Integration djtimca/HASpaceX> Getting repository information
2023-04-04 13:10:48.053 DEBUG (MainThread) [custom_components.hacs] <Integration djtimca/HASpaceX> Running checks against 035
2023-04-04 13:10:49.086 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2023-04-04 13:10:49.089 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.hacs'. Content did not change
```

### Diagnostics dump

[config_entry-hacs-072a1789dcbadf08f22e433d09e40449.json.txt](https://github.com/hacs/integration/files/11147815/config_entry-hacs-072a1789dcbadf08f22e433d09e40449.json.txt)

**Comment by tjorim** [comment]
3 other people reported the same here: https://github.com/djtimca/HASpaceX/issues/49

**Comment by ludeeus** [comment]
Probably https://github.com/hacs/default/commit/6a1591208a095cb46ff23d73a8fb87b48914a7ac
