### ISSUE TITLE
HACS unable to update, does not load. 

### ISSUE THREAD

**Issue by supersebbo** [hacs/integration#3158]
### System Health details

<html><body>

Version | core-2023.6.1
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.11.3
Operating System Family | Linux
Operating System Version | 6.1.25
CPU Architecture | x86_64
Timezone | Europe/London
Configuration Directory | /config

</body>
</html>

<html><body>
<h3>Home Assistant Community Store</h3>  <a class="manage" href="https://ha.sdjb.net:8123/hacs"> <mwc-button></mwc-button></a><a class="manage" href="https://ha.sdjb.net:8123/hacs"></a> 

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4844
Installed Version | 1.27.2
Stage |  
Available Repositories | 1288
Downloaded Repositories | 11

</body>
</html>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi, some time recently HACS integration stopped loading correctly on my HA instance, however existing integrations were still working so I did not give it high priority.  Yesterday I needed to update some HACS integrations and frontend components.  The upgrades of the front-end components worked just fine (and continues to work fine), however I was unable to update the integrations, or HACS itself. 

Errors are as follows. 

1. Clicking the Upgrade button on the HACS integration or any other HACS sourced integration has no effect.  Log error:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/integration.py:157
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 13:02:03 (17 occurrences)
Last logged: 13:12:25

    [139909290640720] Error handling message: Unknown error (unknown_error) Seb from 192.168.1.114 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0)
    [139909207817232] Error handling message: Unknown error (unknown_error) Seb from 192.168.1.114 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 40, in hacs_repository_info
    await repository.update_repository(ignore_issues=True, force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 110, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 157, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No RepositoryFile.MAINIFEST_JSON file found 'custom_components/bmw_connected_drive/RepositoryFile.MAINIFEST_JSON'
```

2. Clicking the Integration tile (which would normally take you to the integration info page) results in 'Unknown Error' displayed in the browser. Log Error:

![image](https://github.com/hacs/integration/assets/29370445/db191888-ba2a-4927-942e-1e11e2d5b7b6)
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hacs/repositories/integration.py:157
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 13:02:03 (18 occurrences)
Last logged: 13:13:55

    [139909290640720] Error handling message: Unknown error (unknown_error) Seb from 192.168.1.114 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0)
    [139909207817232] Error handling message: Unknown error (unknown_error) Seb from 192.168.1.114 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 40, in hacs_repository_info
    await repository.update_repository(ignore_issues=True, force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 110, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 157, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No RepositoryFile.MAINIFEST_JSON file found 'custom_components/bmw_connected_drive/RepositoryFile.MAINIFEST_JSON'
```

3. Attempting to reload HACS integration fails with "Failed to Set Up", and following log error:
```
Logger: homeassistant.config_entries
Source: custom_components/hacs/__init__.py:171
Integration: HACS ([documentation](https://hacs.xyz/docs/configuration/start), [issues](https://github.com/hacs/integration/issues))
First occurred: 13 June 2023 at 21:51:06 (4 occurrences)
Last logged: 13:15:38
Error setting up entry for hacs

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 220, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 206, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 193, in async_try_startup
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 171, in async_startup
    hass.config_entries.async_setup_platforms(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

I have tried:
1. Restarting HA, Rebooting the Host many many times. 
2. Deleting the HACS integration, restarting and re-adding - works, but situation remains the same as above. 
3. Deleting HACS integration, restarting, deleting HACS directory from config folder, restarting, re-adding HACS integration - fails to add integration with following error: 
```
Logger: homeassistant.config_entries
Source: custom_components/hacs/__init__.py:171
Integration: HACS (documentation, issues)
First occurred: 11:46:54 (1 occurrences)
Last logged: 11:46:54

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hacs/__init__.py", line 220, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
  File "/config/custom_components/hacs/__init__.py", line 206, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 193, in async_try_startup
    startup_result = await async_startup()
  File "/config/custom_components/hacs/__init__.py", line 171, in async_startup
    hass.config_entries.async_setup_platforms(
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

### Reproduction steps

Unknown. 

### Debug logs

```text
See above.
```

**Comment by ludeeus** [comment]
Downgrade HA, or reinstall HACS.
Nothing I can do when you choose to ignore updates for that long.

**Comment by supersebbo** [comment]
Ok, thanks, it's been so long I forgot HACS was installed from the terminal.   Opened SSH, ran:
'wget -O - https://get.hacs.xyz | bash -'

All is working again now.
