### ISSUE TITLE
HACS 1.28.3 does not work with HASS 2023.7.2 and does not update

### ISSUE THREAD

**Issue by darkbasic** [hacs/integration#3199]
### System Health details

```
## System Information

version | core-2023.7.2
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 5.10.0-23-armmp
arch | armv7l
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.28.3
Stage | null
Available Repositories | 1283
Downloaded Repositories | 2

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2023.07.1
agent_version | 1.4.1
docker_version | 24.0.4
disk_total | 56.2 GB
disk_used | 16.5 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS UI (1.15.0), Duck DNS (1.15.0), File editor (5.6.0), Network UPS Tools (0.12.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 8
-- | --
resources | 1
views | 8
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 10 July 2023 at 08:42
-- | --
current_recorder_run | 19 July 2023 at 12:25
estimated_db_size | 206.07 MiB
database_engine | sqlite
database_version | 3.41.2

</details>
```

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

![image](https://github.com/hacs/integration/assets/1047358/a3dbb350-875e-41bf-b87b-00babf605678)

HACS fails with the following error when starting HASS (it used to work previously):

```
2023-07-19 18:35:46.564 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 220, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 206, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 193, in async_try_startup
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 171, in async_startup
    hass.config_entries.async_setup_platforms(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

I wanted to see if a newer version would fix it but unfortunately I get this error whenever I try to update it:

```
2023-07-19 18:37:05.344 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2023-07-19 18:37:06.294 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2023-07-19 18:37:06.363 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.32.1
2023-07-19 18:37:07.024 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2023-07-19 18:37:07.373 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2023-07-19 18:37:07.385 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2649788816] Error handling message: Unknown error (unknown_error) Niccolò Belli from IP (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 40, in hacs_repository_info
    await repository.update_repository(ignore_issues=True, force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 173, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No RepositoryFile.MAINIFEST_JSON file found 'custom_components/hacs/RepositoryFile.MAINIFEST_JSON'
```

### Reproduction steps

I guess it can only be reproduced on my system unfortunately.

### Debug logs

```text
Logs are from `docker logs -f ghcr.io/home-assistant/raspberrypi2-homeassistant:2023.7.2` with the following in `configuration.yaml`:


logger:
  default: info
  logs:
    custom_components.hacs: debug
    aiogithubapi: debug
```

Let me know if there are additional logs I can provide.
```


### Diagnostics dump

_No response_

**Comment by ludeeus** [comment]
Downgrade HA, or reinstall HACS.

**Comment by darkbasic** [comment]
@ludeeus so is it expected that old versions won't work with newer versions of hass? If so I should remember to update it regularly.
