### ISSUE TITLE
Issues with HACS not updating, Failed to setup

### ISSUE THREAD

**Issue by Safislab777** [hacs/integration#3238]
## System Information

version | core-2023.8.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.28.3
Stage | null
Available Repositories | 1282
Downloaded Repositories | 41

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.1
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 28.6 GB
disk_used | 7.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.2), Duck DNS (1.15.0), Terminal & SSH (9.7.1), motionEye (0.19.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 26
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 27, 2023 at 23:45
-- | --
current_recorder_run | August 28, 2023 at 10:50
estimated_db_size | 133.31 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I am NOT able to run the newest version of HACS, currently running version 1.28.3. When I open HACS from the side panel it tells me to update yet when I click on the Blue update button that surrounds the HACS Integration, Nothing happens. It also gives me an Error that says; Not loaded in Lovelace
You have 25 Lovelace elements that are not loaded properly in Lovelace.

When I go to my HA Integrations page, it says HACS has failed to setup. When I open the integration and click on the 3 vertical dots and Reload, it still says the same thing. 

Not sure why my HACS fails to setup and won't let me update.
![Screen Shot 2023-08-28 at 11 25 01 AM](https://github.com/hacs/integration/assets/95108511/2d9f9759-5ea0-4f27-bb58-0e5b7db8a1b7)
![Screen Shot 2023-08-28 at 11 15 42 AM](https://github.com/hacs/integration/assets/95108511/2f8da986-eb61-48b9-a438-a0ec88a43d8f)
![Screen Shot 2023-08-28 at 11 15 58 AM](https://github.com/hacs/integration/assets/95108511/ec01296e-1382-433f-925e-993e4087c3dd)
![Screen Shot 2023-08-28 at 11 16 19 AM](https://github.com/hacs/integration/assets/95108511/fbd88e26-55ee-4717-94c2-1ac1394a6f12)

### Reproduction steps

1. Open HACS from side menu. 
2. Click on Update Button ( currently running version 1.28.3)
3. Nothing happens when clicking button
4. Failed to Setup
5. OPen HACS from HA integrations page and try reloading but still says Failed to setup.
...

### Debug logs

```text
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/hacs/__init__.py:171
Integration: HACS (documentation, issues)
First occurred: 11:41:15 (1 occurrences)
Last logged: 11:41:15

Error setting up entry for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 220, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 206, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 193, in async_try_startup
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 171, in async_startup
    hass.config_entries.async_setup_platforms(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

### Diagnostics dump

No 3 dots available to click on so no option to download diagnostic file. Please see photo of integration view.

**Comment by ludeeus** [comment]
Downgrade HA, or reinstall HACS or just remove HACS.

**Comment by Safislab777** [comment]
Thank you for this. Since I am currently using some of the integrations and frontends from HACS, If I remove and redownload will they automatically come back? Or will I need to search and redownload them again?

**Comment by MacDada** [comment]
> Downgrade HA, or reinstall HACS or just remove HACS.

argh, isn't it possible to fix with an update instead? all those options seem kinda bad…

i mean… how do i reinstall it? delete integration and install it again? i hope this would be a lossless operation…
