### ISSUE TITLE
HACS Display Issue

### ISSUE THREAD

**Issue by cncservsys** [hacs/integration#3284]
### Web browser

Google Chrome

### Web browser version

Version 117.0.5938.92 (Official Build) (64-bit)

## System Information

version | core-2023.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/London
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.33.0
Stage | running
Available Repositories | 1372
Downloaded Repositories | 6
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 10 March 2024 at 00:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-8.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 228.5 GB
disk_used | 5.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.7.1), File editor (5.6.0), Samba share (10.0.2), Mosquitto broker (6.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 1
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 1 October 2023 at 01:01
-- | --
current_recorder_run | 2 October 2023 at 17:57
estimated_db_size | 37.47 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have recently started with a fresh install  of HA, with a M.2 SSD to get a nice clean install and freshen everyhting up.

I have installed HACS according to the instructions both according to the documentation and with various youtube videos.

Everything is working correctly apat from the opening display when selecting HACS from the sidebar.

Instead of the normal selections I see a list like entities of my installed HACS integrations - I attach a screenshot FYI

Please advise how I may resolve this, my main concern is that I may be missing some functionality due to incorrect installation.

### Reproduction steps

1. Click HACS on sidebar
2.
3.
...

### Screenshots

![image](https://github.com/hacs/integration/assets/107553153/670b7198-9f85-4cde-a6d2-5834cc09f6d1)

### Javascript logs from your browser console

```text
2023-10-02 17:57:45.648 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration octopus_energy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-02 17:57:45.651 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration solax_modbus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-02 17:57:45.653 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hildebrandglow_dcc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-02 17:57:45.654 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hildebrand_glow_ihd which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-02 17:57:45.656 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-10-02 17:58:09.428 ERROR (MainThread) [custom_components.hildebrandglow_dcc.sensor] Unexpected exception: 'description'. Please open an issue
Traceback (most recent call last):
  File "/config/custom_components/hildebrandglow_dcc/sensor.py", line 64, in async_setup_entry
    resources = await hass.async_add_executor_job(virtual_entity.get_resources)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/glowmarkt/glowmarkt.py", line 43, in get_resources
    return self.client.get_resources(self.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/glowmarkt/glowmarkt.py", line 169, in get_resources
    r.description = elt["description"]
                    ~~~^^^^^^^^^^^^^^^
KeyError: 'description'
2023-10-02 17:58:09.781 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hill_house_smart_electricity_meter_cost_today (<class 'custom_components.hildebrandglow_dcc.sensor.Cost'>) is using state class 'total_increasing' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
2023-10-02 17:58:17.240 ERROR (MainThread) [homeassistant.components.homeassistant_alerts] Error requesting homeassistant_alerts data: Cannot connect to host alerts.home-assistant.io:443 ssl:default [Try again]
2023-10-02 18:04:58.374 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2023-10-02 18:04:58.519 INFO (MainThread) [custom_components.hacs] Removing sidepanel
2023-10-02 18:04:58.743 INFO (MainThread) [custom_components.hacs] HACS is enabled
2023-10-02 18:04:58.743 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.33.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2023-10-02 18:04:58.752 DEBUG (MainThread) [custom_components.hacs] Configuration type: config_entry
2023-10-02 18:04:58.766 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore started
2023-10-02 18:04:59.013 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore done
2023-10-02 18:04:59.014 INFO (MainThread) [custom_components.hacs] Enable category: integration
2023-10-02 18:04:59.015 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2023-10-02 18:04:59.016 INFO (MainThread) [custom_components.hacs] Enable category: template
2023-10-02 18:04:59.016 INFO (MainThread) [custom_components.hacs] Enable category: theme
2023-10-02 18:04:59.016 INFO (MainThread) [custom_components.hacs] Enable category: appdaemon
2023-10-02 18:04:59.017 INFO (MainThread) [custom_components.hacs] <HacsFrontend> Using experimental frontend
2023-10-02 18:04:59.035 INFO (MainThread) [custom_components.hacs] Stage changed: setup
2023-10-02 18:04:59.036 INFO (MainThread) [custom_components.hacs] Stage changed: waiting
2023-10-02 18:04:59.037 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2023-10-02 18:04:59.039 INFO (MainThread) [custom_components.hacs] Stage changed: startup
2023-10-02 18:04:59.043 DEBUG (MainThread) [custom_components.hacs] There are 12 scheduled recurring tasks
2023-10-02 18:04:59.043 INFO (MainThread) [custom_components.hacs] Loading removed repositories
2023-10-02 18:04:59.938 INFO (MainThread) [custom_components.hacs] Loading known repositories
2023-10-02 18:04:59.939 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for plugin
2023-10-02 18:04:59.943 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for template
2023-10-02 18:04:59.944 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for integration
2023-10-02 18:04:59.945 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for appdaemon
2023-10-02 18:04:59.946 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for theme
2023-10-02 18:05:00.095 INFO (MainThread) [custom_components.hacs] Stage changed: running
2023-10-02 18:05:00.127 DEBUG (MainThread) [custom_components.hacs] <QueueManager> The queue is empty
2023-10-02 18:05:00.131 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.critical'. Content did not change
2023-10-02 18:05:00.131 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2023-10-02 18:14:59.046 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2023-10-02 18:24:59.048 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2023-10-02 18:34:59.048 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2023-10-02 18:42:52.773 DEBUG (MainThread) [custom_components.hacs] <Plugin lozzd/octopus-energy-rates-card> Getting repository information
2023-10-02 18:42:56.260 DEBUG (MainThread) [custom_components.hacs] <Plugin lozzd/octopus-energy-rates-card> Running checks against v0.2.0
2023-10-02 18:44:59.051 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2023-10-02 18:54:59.053 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2023-10-02 19:04:59.054 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
```

### Diagnostics dump

[config_entry-hacs-d1e1bde817f5d12787431cfa8d169f0b.json.txt](https://github.com/hacs/integration/files/12785005/config_entry-hacs-d1e1bde817f5d12787431cfa8d169f0b.json.txt)

**Comment by ludeeus** [comment]
That is how it should look.

**Comment by cncservsys** [comment]
Used to look like this

***@***.***

**Comment by clowgg** [comment]
![image](https://github.com/hacs/integration/assets/145304547/e960c436-873f-41f7-972f-1f26bbfc123f)
I have the same issue as cncservsys. All discussions I have read refer to the above menu being what should come up first.
Have you changed the way the integration works?

**Comment by clowgg** [comment]
It seems this behaviour is caused by enabling the experimental features during installation.
What is the correct process to reconfigure HACS without the experimental features enabled?

**Comment by tjorim** [comment]
Reconfigure HACS, restart HA, clear cache.
To be honest you better get used to this new layout as it will be the default sooner than later.

**Comment by clowgg** [comment]
Thank you.
That worked.
