### ISSUE TITLE
Setup failed for custom integration hacs: Unable to import component: Exception importing custom_components.hacs

### ISSUE THREAD

**Issue by ALaDoffe** [hacs/integration#3287]
## System Information

version | core-2023.10.0
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.11.2
os_name | Linux
os_version | 6.1.55-v7+
arch | armv7l
timezone | Europe/Paris
config_dir | /home/homeassistant/.homeassistant

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 3
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 6, 2023 at 05:47
-- | --
current_recorder_run | October 6, 2023 at 10:42
estimated_db_size | 1714.73 MiB
database_engine | mysql
database_version | 10.11.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hi 

After upgrading to HA 2023.10.0 from 2023.9.3 i get this issue.

File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)

ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration hacs: Unable to import component: Exception importing custom_components.hacs

### Reproduction steps

Same  with fresh install of HA 2023.10.0 on a new VENV. 

### Debug logs

```text
2023-10-06 16:13:10.532 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component custom_components.hacs
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 12, in <module>
    from aiogithubapi import AIOGitHubAPIException, GitHub, GitHubAPI
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/__init__.py", line 20, in <module>
    from .device import GitHubDeviceAPI
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/device.py", line 14, in <module>
    from .client import GitHubClient
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/client.py", line 27, in <module>
    from .legacy.client import AIOGitHubAPIClient as LegacyAIOGitHubAPIClient
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/legacy/client.py", line 15, in <module>
    from ..helpers import async_call_api
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/helpers.py", line 8, in <module>
    from sigstore.verify import (
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/verify/__init__.py", line 54, in <module>
    from sigstore.verify.models import (
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/verify/models.py", line 36, in <module>
    from sigstore._internal.rekor import RekorClient
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/_internal/rekor/client.py", line 35, in <module>
    from sigstore.transparency import LogEntry
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/transparency.py", line 123, in <module>
    class LogInclusionProof(BaseModel):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)
2023-10-06 16:13:10.572 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration hacs: Unable to import component: Exception importing custom_components.hacs
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/hacs/__init__.py", line 12, in <module>
    from aiogithubapi import AIOGitHubAPIException, GitHub, GitHubAPI
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/__init__.py", line 20, in <module>
    from .device import GitHubDeviceAPI
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/device.py", line 14, in <module>
    from .client import GitHubClient
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/client.py", line 27, in <module>
    from .legacy.client import AIOGitHubAPIClient as LegacyAIOGitHubAPIClient
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/legacy/client.py", line 15, in <module>
    from ..helpers import async_call_api
  File "/srv/homeassistant/lib/python3.11/site-packages/aiogithubapi/helpers.py", line 8, in <module>
    from sigstore.verify import (
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/verify/__init__.py", line 54, in <module>
    from sigstore.verify.models import (
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/verify/models.py", line 36, in <module>
    from sigstore._internal.rekor import RekorClient
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/_internal/rekor/client.py", line 35, in <module>
    from sigstore.transparency import LogEntry
  File "/srv/homeassistant/lib/python3.11/site-packages/sigstore/transparency.py", line 123, in <module>
    class LogInclusionProof(BaseModel):
  File "pydantic/main.py", line 186, in pydantic.main.ModelMetaclass.__new__
TypeError: Argument 'bases' has incorrect type (expected list, got tuple)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.hacs
```

**Comment by ludeeus** [comment]
Your pydantic version is wrong, when you use core setup it’s important that you follow the core requirements.

**Comment by ALaDoffe** [comment]
Here is my version installed by HA
What is the good one ?

Name: pydantic
Version: 1.10.12
Summary: Data validation and settings management using python type hints
Home-page: https://github.com/pydantic/pydantic
Author: Samuel Colvin
Author-email: s@muelcolvin.com
License: MIT
Location: /srv/homeassistant/lib/python3.11/site-packages
Requires: typing-extensions
Required-by: id, radios, sigstore

**Comment by ludeeus** [comment]
Version number is correct.
But it’s built wrong, look at their issue tracker on how to solve it.
Or use HA container.
