### ISSUE TITLE
Prereleases are displayed to users by default

### ISSUE THREAD

**Issue by alandtse** [hacs/integration#3443]
### System Health details

N/A

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Prerelease HACS integrations are showing up by default for HACS users (this may be limited to those using "experimental features." Previously, these were gated by a beta flag.

We have a broken release due to a GitHub CI error. I have not had time to fix it but made it a prerelease which used to hide the release (unless beta was enabled manually by users). Users are now reporting it as an available [update](https://github.com/alandtse/tesla/issues/817
).

### Reproduction steps

1. Enable a prerelease in a HACS repository.
2. It will appear for users by default.
3. See https://github.com/alandtse/tesla/issues/817
...

### Debug logs

```text
N/A
```

### Diagnostics dump

N/A

**Comment by ludeeus** [comment]
They do not show by default This is from my own instance:
![image](https://github.com/hacs/integration/assets/15093472/3390ea94-f986-49dd-8179-4f398a496f36)

This is the base dataset that is used for experimental <https://data-v2.hacs.xyz/integration/data.json> as you can see, both show 3.19.5 as the "latest", which reflects what is shown in the repo itself.

Please provide debug logs and a diagnostics file if you still believe this is wrong.

**Comment by alandtse** [comment]
Ok. I'm currently traveling so can't access my instance but will reopen this once I've confirmed it with debug logs. Thanks!

**Comment by ludeeus** [comment]
Given how popular that integration is I would have expected a lot more traction on the linked issue if this was the case.

**Comment by alandtse** [comment]
We're probably going to archive soon to be honest; Tesla basically killed direct access. We've been telling people to migrate to some of the paid integrations now that have an agreement with Tesla in place.

**Comment by ludeeus** [comment]
Well that sucks :( I guess data mining companies is not really that can of sharing data

**Comment by mcc05** [comment]
Debug log from HACS for Telsa pre-release

2024-01-10 15:33:26.778 INFO (MainThread) [custom_components.hacs] Stage changed: startup
2024-01-10 15:33:26.835 DEBUG (MainThread) [custom_components.hacs] There are 7 scheduled recurring tasks
2024-01-10 15:33:26.835 INFO (MainThread) [custom_components.hacs] Loading removed repositories
2024-01-10 15:33:27.167 INFO (MainThread) [custom_components.hacs] Loading known repositories
2024-01-10 15:33:29.227 INFO (MainThread) [custom_components.hacs] Starting recurring background task for downloaded repositories
2024-01-10 15:33:29.227 DEBUG (MainThread) [custom_components.hacs] Recurring background task for downloaded repositories done
2024-01-10 15:33:29.227 INFO (MainThread) [custom_components.hacs] Stage changed: running
2024-01-10 15:33:29.441 DEBUG (MainThread) [custom_components.hacs] <QueueManager> The queue is empty
2024-01-10 15:33:29.442 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.critical'. Content did not change
2024-01-10 15:33:29.602 DEBUG (MainThread) [custom_components.hacs] Can update 384 repositories, items in queue 19
2024-01-10 15:33:29.603 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Checking out tasks to execute
2024-01-10 15:33:29.603 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Starting queue execution for 19 tasks
2024-01-10 15:33:29.603 DEBUG (MainThread) [custom_components.hacs] <Integration dolezsa/thermal_comfort> Getting repository information
2024-01-10 15:33:29.605 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Getting repository information
2024-01-10 15:33:29.605 DEBUG (MainThread) [custom_components.hacs] <Plugin nielsfaber/scheduler-card> Getting repository information
2024-01-10 15:33:29.606 DEBUG (MainThread) [custom_components.hacs] <Integration CJNE/ha-myenergi> Getting repository information
2024-01-10 15:33:29.606 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/alexa_media_player> Getting repository information
2024-01-10 15:33:29.606 DEBUG (MainThread) [custom_components.hacs] <Integration amosyuen/ha-epson-projector-link> Getting repository information
2024-01-10 15:33:29.607 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/button-card> Getting repository information
2024-01-10 15:33:29.607 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/scheduler-component> Getting repository information
2024-01-10 15:33:29.607 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Getting repository information
2024-01-10 15:33:29.607 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Getting repository information
2024-01-10 15:33:30.168 DEBUG (MainThread) [custom_components.hacs] <Integration amosyuen/ha-epson-projector-link> Running checks against v1.0.0
2024-01-10 15:33:30.357 DEBUG (MainThread) [custom_components.hacs] <Plugin gadgetchnnel/lovelace-card-templater> Running checks against 0.0.17
2024-01-10 15:33:30.360 DEBUG (MainThread) [custom_components.hacs] <Integration CJNE/ha-myenergi> Running checks against 0.0.24
2024-01-10 15:33:30.385 DEBUG (MainThread) [custom_components.hacs] <Plugin nielsfaber/scheduler-card> Running checks against v3.2.12
2024-01-10 15:33:30.414 DEBUG (MainThread) [custom_components.hacs] <Integration Hyundai-Kia-Connect/kia_uvo> Running checks against v2.18.2
2024-01-10 15:33:30.419 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/alexa_media_player> Running checks against v4.9.0
2024-01-10 15:33:30.427 DEBUG (MainThread) [custom_components.hacs] <Integration dolezsa/thermal_comfort> Running checks against 2.2.2
2024-01-10 15:33:30.455 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running checks against v3.19.6
2024-01-10 15:33:30.511 DEBUG (MainThread) [custom_components.hacs] <Integration nielsfaber/scheduler-component> Running checks against v3.2.15
2024-01-10 15:33:30.567 DEBUG (MainThread) [custom_components.hacs] <Plugin custom-cards/button-card> Running checks against v4.1.1
2024-01-10 15:33:31.067 DEBUG (MainThread) [custom_components.hacs] Encountered unknown tag 'endif'.
2024-01-10 15:33:31.068 DEBUG (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> Getting repository information
2024-01-10 15:33:31.169 DEBUG (MainThread) [custom_components.hacs] <Integration BottlecapDave/HomeAssistant-OctopusEnergy> Getting repository information
2024-01-10 15:33:31.176 DEBUG (MainThread) [custom_components.hacs] 'state_attr' is undefined
2024-01-10 15:33:31.181 DEBUG (MainThread) [custom_components.hacs] <Integration jaruba/ha-samsungtv-tizen> Getting repository information
2024-01-10 15:33:31.235 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/config-template-card> Getting repository information
2024-01-10 15:33:31.241 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Getting repository information
2024-01-10 15:33:31.266 DEBUG (MainThread) [custom_components.hacs] <Plugin alexarch21/history-explorer-card> Getting repository information
2024-01-10 15:33:31.285 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2024-01-10 15:33:31.397 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Getting repository information
2024-01-10 15:33:31.440 DEBUG (MainThread) [custom_components.hacs] <Integration Alexwijn/SAT> Getting repository information
2024-01-10 15:33:31.973 DEBUG (MainThread) [custom_components.hacs] <Integration oziee/ha-solcast-solar> Running checks against v4.0.14
2024-01-10 15:33:31.975 DEBUG (MainThread) [custom_components.hacs] <Plugin iantrich/config-template-card> Running checks against 1.3.6
2024-01-10 15:33:32.006 DEBUG (MainThread) [custom_components.hacs] <Integration BottlecapDave/HomeAssistant-OctopusEnergy> Running checks against v10.0.2
2024-01-10 15:33:32.055 DEBUG (MainThread) [custom_components.hacs] <Integration Alexwijn/SAT> Running checks against 3.0.1
2024-01-10 15:33:32.081 DEBUG (MainThread) [custom_components.hacs] <Integration jaruba/ha-samsungtv-tizen> Running checks against v1.6.1
2024-01-10 15:33:32.150 DEBUG (MainThread) [custom_components.hacs] <Plugin nervetattoo/simple-thermostat> Running checks against v2.5.0
2024-01-10 15:33:32.179 DEBUG (MainThread) [custom_components.hacs] <Integration AlexxIT/WebRTC> Running checks against v3.5.1
2024-01-10 15:33:32.252 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.33.0
2024-01-10 15:33:32.349 DEBUG (MainThread) [custom_components.hacs] <Plugin alexarch21/history-explorer-card> Running checks against v1.0.51
2024-01-10 15:33:33.303 DEBUG (MainThread) [custom_components.hacs] 'state_attr' is undefined
2024-01-10 15:33:34.419 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Queue execution finished for 19 tasks finished in 4.82 seconds
2024-01-10 15:33:34.419 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-01-10 15:36:32.737 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Getting repository information
2024-01-10 15:36:33.714 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running checks against v3.19.6
2024-01-10 15:36:38.292 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Getting repository information
2024-01-10 15:36:39.140 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running checks against v3.19.6
2024-01-10 15:36:40.103 INFO (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running pre installation steps
2024-01-10 15:36:40.103 INFO (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Pre installation steps completed
2024-01-10 15:36:40.103 INFO (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running installation steps
2024-01-10 15:36:40.103 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Getting repository information
2024-01-10 15:36:41.039 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Running checks against v3.19.6
2024-01-10 15:36:42.138 DEBUG (SyncWorker_8) [custom_components.hacs] Backup for /config/custom_components/tesla_custom, created in /tmp/hacs_backup/tesla_custom
2024-01-10 15:36:42.139 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Local path is set to /config/custom_components/tesla_custom
2024-01-10 15:36:42.139 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> Remote path is set to custom_components/tesla_custom
2024-01-10 15:36:42.139 DEBUG (MainThread) [custom_components.hacs] <Integration alandtse/tesla> ref: v3.19.6 --- tag: v3.19.6
2024-01-10 15:36:42.139 ERROR (MainThread) [custom_components.hacs] <Integration alandtse/tesla> No assets found for release 'tags/v3.19.6'
2024-01-10 15:36:42.151 DEBUG (SyncWorker_9) [custom_components.hacs] Restored /config/custom_components/tesla_custom, from backup /tmp/hacs_backup/tesla_custom
2024-01-10 15:36:42.152 DEBUG (SyncWorker_5) [custom_components.hacs] Backup dir /tmp/hacs_backup/ cleared
2024-01-10 15:36:42.152 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140194249235648] Error handling message: Unknown error (unknown_error) Mark from xxx,xxx.xxx.xxx (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
await repository.async_install()
File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
await self.async_install_repository()
File "/config/custom_components/hacs/repositories/base.py", line 995, in async_install_repository
raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details

**Comment by ludeeus** [comment]
That's not experimental logs.
And it's missing the diagnostic file.

**Comment by mcc05** [comment]
@ludeeus this what your after?

[config_entry-hacs-860cf6241b743d353312d0373c836bb0.json.txt](https://github.com/hacs/integration/files/13890277/config_entry-hacs-860cf6241b743d353312d0373c836bb0.json.txt)

**Comment by ludeeus** [comment]
Yes 👍
![image](https://github.com/hacs/integration/assets/15093472/06527489-5349-432f-a4c8-e78f7c2cd354)
HACS is doing what it's supposed to do here.
