### ISSUE TITLE
Infinite loading and silent error when installing release version of integration

### ISSUE THREAD

**Issue by dkarv** [hacs/integration#3445]
## System Information

version | core-2023.12.2
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.0-15-amd64
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1379
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | January 11, 2024 at 5:25 PM
-- | --
current_recorder_run | January 11, 2024 at 6:26 PM
estimated_db_size | 0.20 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Hello,

I developed a custom integration [/dkarv/hacs-bwt-perla](https://github.com/dkarv/hacs-bwt-perla). It works fine by picking the master branch to install in HACS. But whenever I try to install one of the release versions the button keeps loading forever:
![loading_forever](https://github.com/hacs/integration/assets/3708591/c9887f56-16d7-47da-aa8f-a2bb9473ff94)

I cannot see a difference to how others publish their releases and tried a bunch of things without success. The same happens to others using my integration. And I can reproduce this again on a blank new integration: [/dkarv/hacs-test](https://github.com/dkarv/hacs-test).
I tried using
* a different Github account in HACS
* Different names and tags
* on a blank new HA instance and on my main one
* I can install release versions fine from other custom integrations

The error message seems to suggest the release doesn't have an asset. I did not upload an asset, only the source code assets Github adds by default.

Two questions:
* What's wrong with my releases, am I missing something?
* Can HACS show an error if this happens and stop the loading animation?

I'm happy to assist with more information if needed.

### Reproduction steps

1. Add custom repository https://github.com/dkarv/hacs-test
2. Go to /hacs/repository/741632985 and click the download button
3. Pick version with a release, e.g. 3 [link to release on Github](https://github.com/dkarv/hacs-test/releases/tag/3)
4. Click Download
5. The button is loading forever

### Debug logs

```text
2024-01-11 18:30:06.605 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Getting repository information
2024-01-11 18:30:07.157 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Running checks against 3
2024-01-11 18:30:08.108 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-01-11 18:30:09.251 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Getting repository information
2024-01-11 18:30:09.678 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Running checks against 3
2024-01-11 18:30:10.648 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-01-11 18:30:12.736 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Getting repository information
2024-01-11 18:30:13.193 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Running checks against 3
2024-01-11 18:30:14.127 INFO (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Running pre installation steps
2024-01-11 18:30:14.128 INFO (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Pre installation steps completed
2024-01-11 18:30:14.128 INFO (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Running installation steps
2024-01-11 18:30:14.128 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Getting repository information
2024-01-11 18:30:14.587 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Running checks against 3
2024-01-11 18:30:15.536 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Local path is set to /config/custom_components/integration-hacs
2024-01-11 18:30:15.536 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> Remote path is set to custom_components/integration-hacs
2024-01-11 18:30:15.536 DEBUG (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> ref: 3 --- tag: 3
2024-01-11 18:30:15.536 ERROR (MainThread) [custom_components.hacs] <Integration dkarv/hacs-test> No assets found for release 'tags/3'
2024-01-11 18:30:15.537 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140121861013184] Error handling message: Unknown error (unknown_error) david from 127.0.0.1 (Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
await repository.async_install()
File "/config/custom_components/hacs/repositories/base.py", line 899, in async_install
await self.async_install_repository()
File "/config/custom_components/hacs/repositories/base.py", line 995, in async_install_repository
raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

**Comment by ludeeus** [comment]
You told hacs to look for a file in the release assets that does not exist < https://github.com/dkarv/hacs-test/blob/master/hacs.json#L5>.

As for showing errors, that's already handled, but not yet released.
