### ISSUE TITLE
HACS not working after HA upgrade

### ISSUE THREAD

**Issue by pachi81** [hacs/integration#3516]
## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4928
Installed Version | 1.28.3
Stage | null
Available Repositories | 1398
Downloaded Repositories | 28

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.02.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 28.5 GB
disk_used | 8.1 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.9.0), File editor (5.8.0), Samba share (12.3.0), MariaDB (2.6.1), Duck DNS (1.15.0), Mosquitto broker (6.4.0), Weather Station MQTT (0.1), Samba Backup (5.2.0), SQLite Web (4.1.2), Nginx Proxy Manager (1.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 20
views | 22
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 8. Februar 2024 um 09:24
-- | --
current_recorder_run | 21. Februar 2024 um 10:32
estimated_db_size | 132.35 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I have upgrade my homeassistant to current version. Unfortunatelly I could not update HACS before and now it is not working and I can not update it. What can I do to solve this problem, without losing my configuration?
![image](https://github.com/hacs/integration/assets/56817032/8fa89f46-95a0-4963-b85e-46f143820d9c)
![HACS_menu](https://github.com/hacs/integration/assets/56817032/54a8869e-d23d-44b1-b490-e753accde588)

If I click on the HACS entry, nothing happens...

### Reproduction steps

1. install 2022.10.1
2. upgrade to 2024.2

### Debug logs

```text
...
2024-02-21 10:43:56.302 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
2024-02-21 10:43:56.303 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
2024-02-21 10:43:56.303 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
2024-02-21 10:43:56.303 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
2024-02-21 10:43:56.304 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
2024-02-21 10:43:56.305 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
2024-02-21 10:43:56.305 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
2024-02-21 10:43:56.305 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
2024-02-21 10:43:56.307 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Received unknown command: hacs/subscribe
...

2024-02-21 10:43:58.969 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up command_line.binary_sensor
2024-02-21 10:43:58.972 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up command_line platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/command_line/binary_sensor.py", line 55, in async_setup_platform
    name: str = binary_sensor_config.get(CONF_NAME, DEFAULT_NAME)
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2024-02-21 10:43:58.987 INFO (MainThread) [homeassistant.bootstrap] Setting up stage 2: {'fritzbox', 'homematic', 'automation', 'persistent_notification', 'nightscout', 'mobile_app', 'homeassistant_alerts', 'input_datetime', 'lovelace', 'input_select', 'input_text', 'input_button', 'cast', 'input_number', 'assist_pipeline', 'filesize', 'rpi_power', 'device_automation', 'conversation', 'switch', 'generic', 'fontawesome', 'deebot', 'hardware', 'min_max', 'media_source', 'met', 'kodi', 'image_upload', 'person', 'openweathermap', 'variable', 'tts', 'raspberry_pi', 'onboarding', 'file_upload', 'history', 'wake_word', 'system_health', 'config', 'timer', 'dwd_weather', 'scene', 'map', 'search', 'input_boolean', 'template', 'sensor', 'stt', 'alert', 'analytics', 'media_player', 'dreame_vacuum', 'systemmonitor', 'scheduler', 'application_credentials', 'blueprint', 'rest_command', 'upnp', 'stream', 'logbook', 'auth', 'script', 'energy', 'melcloud', 'ipp', 'trace', 'binary_sensor', 'hacs', 'zone', 'google', 'default_config', 'workday', 'sun', 'dlna_dmr', 'climate', 'my', 'fritz', 'diagnostics', 'repairs', 'group', 'tag', 'counter', 'ffmpeg', 'dlna_dms', 'mqtt', 'schedule'}
2024-02-21 10:43:59.050 INFO (MainThread) [homeassistant.setup] Setting up homematic
...

2024-02-21 10:44:06.083 INFO (MainThread) [homeassistant.setup] Setting up hacs
2024-02-21 10:44:06.083 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 0.0 seconds
2024-02-21 10:44:06.085 INFO (MainThread) [homeassistant.setup] Setting up media_source
2024-02-21 10:44:06.097 INFO (MainThread) [homeassistant.setup] Setup of domain variable took 3.8 seconds
2024-02-21 10:44:06.216 INFO (MainThread) [homeassistant.setup] Setting up my
2024-02-21 10:44:06.217 INFO (MainThread) [homeassistant.setup] Setup of domain my took 0.0 seconds
2024-02-21 10:44:06.286 INFO (MainThread) [homeassistant.setup] Setting up fritz
2024-02-21 10:44:06.287 INFO (MainThread) [homeassistant.setup] Setup of domain fritz took 0.0 seconds
2024-02-21 10:44:06.297 INFO (MainThread) [homeassistant.setup] Setting up system_health
2024-02-21 10:44:07.402 INFO (MainThread) [homeassistant.setup] Setting up mqtt
2024-02-21 10:44:07.404 INFO (MainThread) [homeassistant.setup] Setup of domain mqtt took 0.0 seconds
2024-02-21 10:44:07.495 INFO (MainThread) [homeassistant.setup] Setting up map
2024-02-21 10:44:07.496 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.0 seconds
2024-02-21 10:44:07.518 INFO (MainThread) [homeassistant.setup] Setup of domain input_select took 5.7 seconds
2024-02-21 10:44:07.613 INFO (MainThread) [homeassistant.setup] Setup of domain input_text took 5.8 seconds
2024-02-21 10:44:07.622 INFO (MainThread) [homeassistant.setup] Setting up energy
2024-02-21 10:44:07.623 INFO (MainThread) [homeassistant.setup] Setup of domain energy took 0.0 seconds
2024-02-21 10:44:07.625 INFO (MainThread) [homeassistant.setup] Setting up assist_pipeline
2024-02-21 10:44:07.686 INFO (MainThread) [homeassistant.setup] Setting up cover
2024-02-21 10:44:07.695 INFO (MainThread) [homeassistant.setup] Setup of domain cover took 0.0 seconds
2024-02-21 10:44:07.984 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.28.3
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------
...

2024-02-21 10:44:13.442 INFO (SyncWorker_13) [pyfritzhome.fritzhome] Updating Devices ...
2024-02-21 10:44:13.586 DEBUG (MainThread) [custom_components.hacs] Configuration type: ConfigurationType.CONFIG_ENTRY
2024-02-21 10:44:13.624 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 2.2 seconds
2024-02-21 10:44:13.710 INFO (MainThread) [homeassistant.setup] Setting up notify
2024-02-21 10:44:13.711 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.0 seconds
2024-02-21 10:44:13.746 INFO (MainThread) [homeassistant.setup] Setup of domain homematic took 14.7 seconds
2024-02-21 10:44:13.776 INFO (MainThread) [homeassistant.components.sensor] Setting up time_date.sensor
2024-02-21 10:44:13.863 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2024-02-21 10:44:13.914 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore started
2024-02-21 10:44:14.195 INFO (MainThread) [homeassistant.components.sensor] Setting up statistics.sensor
2024-02-21 10:44:14.599 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore done
2024-02-21 10:44:14.677 INFO (MainThread) [homeassistant.components.scene] Setting up homeassistant.scene
...

2024-02-21 10:44:14.964 INFO (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Voltage normalized. Everything is working as intended.
2024-02-21 10:44:15.025 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:15.026 DEBUG (MainThread) [aiogithubapi] 'GitHubRateLimitResourcesModel' is missing key 'dependency_snapshots' for <class 'dict'>
2024-02-21 10:44:15.026 DEBUG (MainThread) [aiogithubapi] 'GitHubRateLimitResourcesModel' is missing key 'audit_log' for <class 'dict'>
2024-02-21 10:44:15.027 DEBUG (MainThread) [aiogithubapi] 'GitHubRateLimitResourcesModel' is missing key 'code_search' for <class 'dict'>
2024-02-21 10:44:15.027 DEBUG (MainThread) [custom_components.hacs] Can update 392 repositories
2024-02-21 10:44:15.027 INFO (MainThread) [custom_components.hacs] Enable category: integration
2024-02-21 10:44:15.029 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2024-02-21 10:44:15.029 INFO (MainThread) [custom_components.hacs] Enable category: theme
2024-02-21 10:44:15.035 INFO (MainThread) [custom_components.hacs] <HacsFrontend> LovelaceMode.STORAGE mode, cache for /hacsfiles/: True
2024-02-21 10:44:15.038 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 220, in async_setup_entry
    setup_result = await async_initialize_integration(hass=hass, config_entry=config_entry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 206, in async_initialize_integration
    await async_try_startup()
  File "/config/custom_components/hacs/__init__.py", line 193, in async_try_startup
    startup_result = await async_startup()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/__init__.py", line 171, in async_startup
    hass.config_entries.async_setup_platforms(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'. Did you mean: 'async_unload_platforms'?
...

2024-02-21 10:44:49.190 ERROR (MainThread) [pyemby.server] Error fetching Emby data: 
2024-02-21 10:44:49.194 ERROR (MainThread) [pyemby.server] Unable to register emby client.
2024-02-21 10:44:52.694 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2024-02-21 10:44:53.409 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:53.434 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.34.0
2024-02-21 10:44:53.687 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2024-02-21 10:44:53.988 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:54.177 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:54.184 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Error handling message: Unknown error (unknown_error) pachi81 from 192.168.178.61 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 40, in hacs_repository_info
    await repository.update_repository(ignore_issues=True, force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 173, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No RepositoryFile.MAINIFEST_JSON file found 'custom_components/hacs/RepositoryFile.MAINIFEST_JSON'
2024-02-21 10:44:54.380 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:54.404 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.34.0
2024-02-21 10:44:54.426 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2024-02-21 10:44:54.786 WARNING (MainThread) [aiogithubapi] You need to call .set_last_commit to set this property
2024-02-21 10:44:54.948 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:55.016 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:55.038 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.34.0
2024-02-21 10:44:55.128 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:55.135 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Error handling message: Unknown error (unknown_error) pachi81 from 192.168.178.61 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 40, in hacs_repository_info
    await repository.update_repository(ignore_issues=True, force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 173, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No RepositoryFile.MAINIFEST_JSON file found 'custom_components/hacs/RepositoryFile.MAINIFEST_JSON'
2024-02-21 10:44:55.633 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:55.817 DEBUG (MainThread) [aiogithubapi] 'GitHubResponseHeadersModel' is missing key 'x_github_api_version_selected' for <class 'str'>
2024-02-21 10:44:55.824 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547995860032] Error handling message: Unknown error (unknown_error) pachi81 from 192.168.178.61 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 40, in hacs_repository_info
    await repository.update_repository(ignore_issues=True, force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
    if manifest := await self.async_get_integration_manifest():
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/repositories/integration.py", line 173, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No RepositoryFile.MAINIFEST_JSON file found 'custom_components/hacs/RepositoryFile.MAINIFEST_JSON'
2024-02-21 10:45:00.335 WARNING (MainThread) [homeassistant.components.template.trigger] Error evaluating 'template' trigger for 'Urlaub Ende 12h vorher': ValueError: Template error: as_timestamp got invalid input 'None' when rendering template '{{ (now().timestamp() | timestamp_custom('%d.%m.%y %H:%M', true)) == ((as_timestamp(state_attr('calendar.urlaub', 'end_time')) - 43200) |  timestamp_custom('%d.%m.%y %H:%M', true)) }}' but no default was specified
2024-02-21 10:45:02.278 WARNING (zeroconf-ServiceBrowser-_googlecast._tcp-160) [pychromecast.dial] Failed to determine cast type for host <unknown> (<urlopen error _ssl.c:983: The handshake operation timed out>) (services:{ServiceInfo(type='mdns', data='Onkyo-TX-RZ730-b680ae308518d9a39085f9ff4341e289._googlecast._tcp.local.')})
```

**Comment by pachi81** [comment]
[home-assistant_hacs_2024-02-21T09-46-15.780Z.log](https://github.com/hacs/integration/files/14357768/home-assistant_hacs_2024-02-21T09-46-15.780Z.log)

**Comment by pachi81** [comment]
It was not possible to upgrade HACS before upgrading HA. I tried. So on which version I can upgrade it?
Or is it possible to re-install HACS with new version???

**Comment by ludeeus** [comment]
2023.7.x

Yes.
