### ISSUE TITLE
Config entry state is mutated externally

### ISSUE THREAD

**Issue by bdraco** [hacs/integration#3537]
### System Health details

n/a

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

https://github.com/hacs/integration/blob/a42209065cffe7f5dc3a63ed18314aea47726c3d/custom_components/hacs/base.py#L408

I added a check for this in https://github.com/home-assistant/core/pull/110023 because the code in config entries assumes `.state` is an internal state does not handle it being changed out from under it (changing externally means we don't dispatch the state change to the UI, or update the retry count)

### Reproduction steps

Have an invalid token

### Debug logs

```text
2024-03-01 11:26:44.322 ERROR (MainThread) [custom_components.hacs] HACS is disabled - invalid_token
2024-03-01 11:26:44.323 ERROR (MainThread) [custom_components.hacs] state cannot be changed
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/config/custom_components/hacs/base.py", line 511, in async_github_api_method
    return await method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bdraco/home-assistant/venv/lib/python3.12/site-packages/aiogithubapi/github.py", line 224, in rate_limit
    response = await self._client.async_call_api(endpoint="/rate_limit", **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bdraco/home-assistant/venv/lib/python3.12/site-packages/aiogithubapi/client.py", line 146, in async_call_api
    raise exception(message or response.data)
aiogithubapi.exceptions.GitHubAuthenticationException: Bad credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/config/custom_components/hacs/base.py", line 471, in async_can_update
    response = await self.async_github_api_method(self.githubapi.rate_limit)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bdraco/home-assistant/config/custom_components/hacs/base.py", line 513, in async_github_api_method
    self.disable_hacs(HacsDisabledReason.INVALID_TOKEN)
  File "/Users/bdraco/home-assistant/config/custom_components/hacs/base.py", line 408, in disable_hacs
    self.configuration.config_entry.state = ConfigEntryState.SETUP_ERROR
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bdraco/home-assistant/homeassistant/config_entries.py", line 413, in __setattr__
    raise AttributeError(f"{key} cannot be changed")
AttributeError: state cannot be changed
```
```


### Diagnostics dump

_No response_

**Comment by ludeeus** [comment]
How did yo manage that?
It _should_ not be possible to use a token anymore 🤔

**Comment by bdraco** [comment]
I enabled an old config entry on a test instance
