### ISSUE TITLE
Unable to download custom repository

### ISSUE THREAD

**Issue by ecoen66** [hacs/integration#3580]
## System Information

version | core-2024.4.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.1.73-haos-raspi
arch | aarch64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4947
Installed Version | 1.34.0
Stage | running
Available Repositories | 1409
Downloaded Repositories | 25
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 7, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-2.ui.nabu.casa
certificate_status | ready
instance_id | 3bace3c63f684c76aabb442c56f37ac5
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.03.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 233.9 GB
disk_used | 13.9 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Ring-MQTT with Video Streaming (5.6.3), Advanced SSH & Web Terminal (17.2.0), Mosquitto broker (6.4.0), Duck DNS (1.16.0), Node-RED (17.0.11), Z-Wave JS (0.4.5), Samba share (12.3.1), EMQX (0.5.0), Matter Server (5.5.1), Network UPS Tools (0.13.0), Home Assistant Google Drive Backup (0.112.1), Studio Code Server (5.15.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 10
views | 25
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 28, 2024 at 3:04 PM
-- | --
current_recorder_run | April 7, 2024 at 11:56 AM
estimated_db_size | 1067.82 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Although this used to work my own public repos, I can no longer download a custom integration from my repo.
For the repo https://github.com/ecoen66/cisco_imc, HACS attempts to download from:
https://github.com/ecoen66/cisco_imc/releases/download/v0.9.29-beta/cisco_imc.zip (which fails)
And then from:
https://github.com/ecoen66/cisco_imc/releases/download/tags/v0.9.29-beta/cisco_imc.zip (which also fails).

The correct download location on Github appears to be:
https://github.com/ecoen66/cisco_imc/archive/refs/tags/v0.9.29-beta.zip

As I said, I did have this working prior, but cannot figure out why either HACS is looking in the wrong place or Github is not publishing at the correct URL.

### Reproduction steps

1. Add custom repo to HACS: https://github.com/ecoen66/cisco_imc
2. Attempt to download either version of this Integration using HACS.
3. Check the detailed log file.
...

### Debug logs

```text
2024-04-07 12:07:43.318 INFO (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Running pre installation steps
2024-04-07 12:07:43.319 INFO (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Pre installation steps completed
2024-04-07 12:07:43.323 INFO (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Running installation steps
2024-04-07 12:07:43.323 DEBUG (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Getting repository information
2024-04-07 12:07:43.582 DEBUG (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Running checks against v0.9.29-beta
2024-04-07 12:07:43.896 DEBUG (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Getting documentation for version=v0.9.29-beta,filename=README.md
2024-04-07 12:07:43.897 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/ecoen66/cisco_imc/v0.9.29-beta/README.md
2024-04-07 12:07:43.991 DEBUG (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Local path is set to /config/custom_components/cisco_imc
2024-04-07 12:07:43.991 DEBUG (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Remote path is set to custom_components/cisco_imc
2024-04-07 12:07:43.991 DEBUG (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Version to install: v0.9.29-beta
2024-04-07 12:07:43.992 DEBUG (MainThread) [custom_components.hacs] Trying to download https://github.com/ecoen66/cisco_imc/releases/download/v0.9.29-beta/cisco_imc.zip
2024-04-07 12:07:44.135 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/ecoen66/cisco_imc/releases/download/v0.9.29-beta/cisco_imc.zip
Traceback (most recent call last):
File "/config/custom_components/hacs/base.py", line 730, in async_download_file
raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/ecoen66/cisco_imc/releases/download/v0.9.29-beta/cisco_imc.zip
2024-04-07 12:07:44.137 ERROR (MainThread) [custom_components.hacs] <Integration ecoen66/cisco_imc> Failed to download https://github.com/ecoen66/cisco_imc/releases/download/tags/v0.9.29-beta/cisco_imc.zip
2024-04-07 12:07:44.138 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547753801280] Error handling message: Unknown error (unknown_error) Ed from 192.168.1.91 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
await repository.async_install()
File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
await self.async_install_repository(version=version)
File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

**Comment by ecoen66** [comment]
@ludeeus Yes

**Comment by ecoen66** [comment]
That fixed it.  Thank you!
