### ISSUE TITLE
HACS not starting due to failed `securesystemslib` import

### ISSUE THREAD

**Issue by guidocioni** [hacs/integration#3691]
## System Information

version | core-2024.4.4
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | pi
virtualenv | false
python_version | 3.12.3
os_name | Linux
os_version | 6.1.21-v8+
arch | aarch64
timezone | Europe/Berlin
config_dir | /home/pi/.homeassistant

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 14
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 19, 2024 at 14:46
-- | --
current_recorder_run | May 20, 2024 at 17:00
estimated_db_size | 446.19 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

This is the same issue reported in the core repository here https://github.com/home-assistant/core/issues/117451. 

When starting Home Assistant 2024.4.4, HACS cannot start as it cannot import some features from `securesystemslib`

```
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/tuf/api/metadata.py", line 56, in <module>
    from securesystemslib import keys as sslib_keys
ImportError: cannot import name 'keys' from 'securesystemslib' (/home/pi/.homeassistant/deps/lib/python3.12/site-packages/securesystemslib/__init__.py)
```

I tried to `pip install securesystemslib==0.31.0` as suggested but this did not fix the issue. 

### Reproduction steps

The issue description already explains how to reproduce the error. 

### Debug logs

```text
Setup failed for custom integration 'hacs': Unable to import component: cannot import name 'keys' from 'securesystemslib' (/home/pi/.homeassistant/deps/lib/python3.12/site-packages/securesystemslib/__init__.py)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.12/site-packages/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/pi/.homeassistant/custom_components/hacs/__init__.py", line 12, in <module>
    from aiogithubapi import AIOGitHubAPIException, GitHub, GitHubAPI
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/__init__.py", line 20, in <module>
    from .device import GitHubDeviceAPI
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/device.py", line 14, in <module>
    from .client import GitHubClient
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/client.py", line 27, in <module>
    from .legacy.client import AIOGitHubAPIClient as LegacyAIOGitHubAPIClient
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/legacy/client.py", line 15, in <module>
    from ..helpers import async_call_api
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/helpers.py", line 8, in <module>
    from sigstore.verify import (
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/verify/__init__.py", line 54, in <module>
    from sigstore.verify.models import (
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/verify/models.py", line 36, in <module>
    from sigstore._internal.rekor import RekorClient
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/_internal/rekor/client.py", line 33, in <module>
    from sigstore._internal.tuf import TrustUpdater
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/_internal/tuf.py", line 42, in <module>
    from tuf.ngclient import RequestsFetcher, Updater
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/tuf/ngclient/__init__.py", line 14, in <module>
    from tuf.ngclient.updater import Updater
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/tuf/ngclient/updater.py", line 48, in <module>
    from tuf.api.metadata import (
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/tuf/api/metadata.py", line 56, in <module>
    from securesystemslib import keys as sslib_keys
ImportError: cannot import name 'keys' from 'securesystemslib' (/home/pi/.homeassistant/deps/lib/python3.12/site-packages/securesystemslib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.12/site-packages/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/home/pi/.local/lib/python3.12/site-packages/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/.local/lib/python3.12/site-packages/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/pi/.homeassistant/custom_components/hacs/__init__.py", line 12, in <module>
    from aiogithubapi import AIOGitHubAPIException, GitHub, GitHubAPI
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/__init__.py", line 20, in <module>
    from .device import GitHubDeviceAPI
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/device.py", line 14, in <module>
    from .client import GitHubClient
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/client.py", line 27, in <module>
    from .legacy.client import AIOGitHubAPIClient as LegacyAIOGitHubAPIClient
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/legacy/client.py", line 15, in <module>
    from ..helpers import async_call_api
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/aiogithubapi/helpers.py", line 8, in <module>
    from sigstore.verify import (
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/verify/__init__.py", line 54, in <module>
    from sigstore.verify.models import (
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/verify/models.py", line 36, in <module>
    from sigstore._internal.rekor import RekorClient
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/_internal/rekor/client.py", line 33, in <module>
    from sigstore._internal.tuf import TrustUpdater
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/sigstore/_internal/tuf.py", line 42, in <module>
    from tuf.ngclient import RequestsFetcher, Updater
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/tuf/ngclient/__init__.py", line 14, in <module>
    from tuf.ngclient.updater import Updater
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/tuf/ngclient/updater.py", line 48, in <module>
    from tuf.api.metadata import (
  File "/home/pi/.homeassistant/deps/lib/python3.12/site-packages/tuf/api/metadata.py", line 56, in <module>
    from securesystemslib import keys as sslib_keys
ImportError: cannot import name 'keys' from 'securesystemslib' (/home/pi/.homeassistant/deps/lib/python3.12/site-packages/securesystemslib/__init__.py)
```

**Comment by guidocioni** [comment]
Ok apparently the proposed solution worked. The problem is that due to my core installation in something that is not a venv the `1.0` version of `securesystemslib` was still picked and used by homeassistant when starting. 
I'll close this for now but I'd suggest the devs in constraining `securesystemslib` to something different than the `1.0` release for now
