### ISSUE TITLE
I can't load any of the custom integrations

### ISSUE THREAD

**Issue by penthousegoldameir** [hacs/integration#3708]
### System Health details

I'm using the latest version

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I can see all my integrations within HACS. Once I click on one, it creates a log, and it takes forever to load up (loop).

### Reproduction steps

I've tried the following steps 

1. reinstall hacs 
2. Take out the hacs integration (devices) and reconnect it

I don't know what to do next. Please advice

### Debug logs

```text
Here are some of the logs :

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/hacs/system_health.py:23
integration: HACS (documentation, issues)
First occurred: 20:12:57 (2 occurrences)
Last logged: 21:04:31

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/client.py", line 138, in async_call_api
    result = await self._session.request(**request_arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1102, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1005, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 124, in handle_info
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 89, in get_integration_info
    data = await registration.info_callback(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hacs/system_health.py", line 23, in system_health_info
    response = await hacs.githubapi.rate_limit()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/github.py", line 239, in rate_limit
    response = await self._client.async_call_api(endpoint="/rate_limit", **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/client.py", line 140, in async_call_api
    raise GitHubConnectionException(
aiogithubapi.exceptions.GitHubConnectionException: Request exception for 'https://api.github.com/rate_limit' with - 

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/repositories/base.py:1088
integration: HACS (documentation, issues)
First occurred: 20:03:05 (6 occurrences)
Last logged: 20:07:15

<Integration thomasloven/hass-browser_mod>
<Plugin kalkih/mini-media-player>
<Integration AlexxIT/WebRTC>
<Plugin ofekashery/vertical-stack-in-card>

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/websocket/repository.py:48
integration: HACS (documentation, issues)
First occurred: 20:03:25 (3 occurrences)
Last logged: 20:06:29

<Integration thomasloven/hass-browser_mod> No manifest.json file found 'custom_components/None/manifest.json'
<Integration AlexxIT/WebRTC> No manifest.json file found 'custom_components/None/manifest.json'
```

**Comment by Jens-Wymeersch** [comment]
@ludeeus It's the first time I really have trouble with HACS and don't know what's going on. I have 2 instances of home assistant running and both have the same problem. Loading/downloading the integrations stays in a loop without end. 
This behaviour started a week ago. Sometimes it sorts itself out, but this isn't a satisfactory situation

**Comment by mesoblaste** [comment]
just here to say I got the same issue and I thikgnit also start about a week ago...

**Comment by ludeeus** [comment]
This is not a problem with HACS.
You have network issues on the host running Home Assistant or somewhere in your network between that host and GitHub.

**Comment by Jens-Wymeersch** [comment]
@ludeeus I have 2 environments in 2 homes, each with their own network - not linked. 
On both environments, I am getting the same issue. And effectively it started approx a week ago.
