### ISSUE TITLE
I can't download Midea AC LAN due to URL is wrong (404 error)

### ISSUE THREAD

**Issue by loeiks** [hacs/integration#3779]
## System Information

version | core-2024.5.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.8.0-35-generic
arch | x86_64
timezone | Europe/Athens
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 3791
Installed Version | 1.34.0
Stage | running
Available Repositories | 1392
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 3, 2024 at 6:53 AM
-- | --
current_recorder_run | June 12, 2024 at 6:16 PM
estimated_db_size | 102.65 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

So here is the error log:

2024-06-12 18:19:49.913 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/v0.3.22/mieda_ac_lan.zip

As you can see there is a small typo mistake it's `mieda` but it should be `midea` instead of mieda and because of that I can't download the latest version of midea ac lan.

Correct download URL: https://github.com/georgezhao2010/midea_ac_lan/releases/download/v0.3.22/midea_ac_lan.zip

Here is what I see:

![image](https://github.com/hacs/integration/assets/90484193/57ca9bb2-8619-4ba8-a5a8-886b5d82cf12)

### Reproduction steps

1. Go to HACS
2. Try to install latest version (v0.3.22) of mieda ac lan integration
3. You won't be able to install it

Either you'll see loading state (infinite loop) or it'll throw an error. If you have installed HA with docker see logs with:

`docker logs -f homeassistant`

### Debug logs

```text
2024-06-12 18:29:32.415 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-12 18:29:33.371 INFO (SyncWorker_5) [fritzconnection] Unable to retrieve resource 'https://192.168.178.21:49443/igddesc.xml' from the device.
2024-06-12 18:29:33.654 INFO (MainThread) [custom_components.hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 1.34.0
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2024-06-12 18:29:33.656 DEBUG (MainThread) [custom_components.hacs] Configuration type: config_entry
2024-06-12 18:29:33.759 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore started
2024-06-12 18:29:33.918 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore done
2024-06-12 18:29:34.175 DEBUG (MainThread) [custom_components.hacs] Can update 279 repositories
2024-06-12 18:29:34.176 INFO (MainThread) [custom_components.hacs] Enable category: integration
2024-06-12 18:29:34.177 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2024-06-12 18:29:34.177 INFO (MainThread) [custom_components.hacs] Enable category: theme
2024-06-12 18:29:34.182 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-12 18:29:34.186 INFO (MainThread) [custom_components.hacs] Stage changed: setup
2024-06-12 18:29:34.186 INFO (MainThread) [custom_components.hacs] Stage changed: waiting
2024-06-12 18:29:34.186 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2024-06-12 18:29:41.529 INFO (MainThread) [custom_components.hacs] Stage changed: startup
2024-06-12 18:29:41.532 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-06-12 18:29:41.533 DEBUG (MainThread) [custom_components.hacs] There are 7 scheduled recurring tasks
2024-06-12 18:29:41.533 INFO (MainThread) [custom_components.hacs] Loading removed repositories
2024-06-12 18:29:41.771 INFO (MainThread) [custom_components.hacs] Loading known repositories
2024-06-12 18:29:42.108 INFO (MainThread) [custom_components.hacs] Starting recurring background task for downloaded repositories
2024-06-12 18:29:42.108 DEBUG (MainThread) [custom_components.hacs] Recurring background task for downloaded repositories done
2024-06-12 18:29:42.108 INFO (MainThread) [custom_components.hacs] Stage changed: running
2024-06-12 18:29:42.326 DEBUG (MainThread) [custom_components.hacs] <QueueManager> The queue is empty
2024-06-12 18:29:42.327 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.critical'. Content did not change
2024-06-12 18:29:42.502 DEBUG (MainThread) [custom_components.hacs] Can update 278 repositories, items in queue 1
2024-06-12 18:29:42.502 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Checking out tasks to execute
2024-06-12 18:29:42.502 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Starting queue execution for 1 tasks
2024-06-12 18:29:42.502 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2024-06-12 18:29:43.138 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.34.0
2024-06-12 18:29:43.776 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting documentation for version=1.34.0,filename=info.md
2024-06-12 18:29:43.777 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/hacs/integration/1.34.0/info.md
2024-06-12 18:29:44.127 DEBUG (MainThread) [custom_components.hacs] <QueueManager> Queue execution finished for 1 tasks finished in 1.63 seconds
2024-06-12 18:29:44.127 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-06-12 18:30:04.229 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Getting repository information
2024-06-12 18:30:04.852 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Running checks against v0.3.22
2024-06-12 18:30:05.482 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Getting documentation for version=v0.3.22,filename=README.md
2024-06-12 18:30:05.482 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/georgezhao2010/midea_ac_lan/v0.3.22/README.md
2024-06-12 18:30:07.192 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Getting repository information
2024-06-12 18:30:07.784 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Running checks against v0.3.22
2024-06-12 18:30:08.562 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Getting documentation for version=v0.3.22,filename=README.md
2024-06-12 18:30:08.562 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/georgezhao2010/midea_ac_lan/v0.3.22/README.md
2024-06-12 18:30:08.869 DEBUG (MainThread) [custom_components.hacs] <HacsData async_write> Saving data
2024-06-12 18:30:09.019 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Getting repository information
2024-06-12 18:30:09.638 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Running checks against v0.3.22
2024-06-12 18:30:10.266 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Getting documentation for version=v0.3.22,filename=README.md
2024-06-12 18:30:10.266 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/georgezhao2010/midea_ac_lan/v0.3.22/README.md
2024-06-12 18:30:10.525 INFO (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Running pre installation steps
2024-06-12 18:30:10.525 INFO (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Pre installation steps completed
2024-06-12 18:30:10.526 INFO (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Running installation steps
2024-06-12 18:30:10.526 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Getting repository information
2024-06-12 18:30:11.078 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Running checks against v0.3.22
2024-06-12 18:30:11.699 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Getting documentation for version=v0.3.22,filename=README.md
2024-06-12 18:30:11.699 DEBUG (MainThread) [custom_components.hacs] Trying to download https://raw.githubusercontent.com/georgezhao2010/midea_ac_lan/v0.3.22/README.md
2024-06-12 18:30:11.933 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Local path is set to /config/custom_components/midea_ac_lan
2024-06-12 18:30:11.933 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Remote path is set to custom_components/midea_ac_lan
2024-06-12 18:30:11.933 DEBUG (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Version to install: v0.3.22
2024-06-12 18:30:11.933 DEBUG (MainThread) [custom_components.hacs] Trying to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/v0.3.22/mieda_ac_lan.zip
2024-06-12 18:30:12.190 ERROR (MainThread) [custom_components.hacs] Download failed - Got status code 404 when trying to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/v0.3.22/mieda_ac_lan.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/v0.3.22/mieda_ac_lan.zip
2024-06-12 18:30:12.192 ERROR (MainThread) [custom_components.hacs] <Integration georgezhao2010/midea_ac_lan> Failed to download https://github.com/georgezhao2010/midea_ac_lan/releases/download/tags/v0.3.22/mieda_ac_lan.zip
2024-06-12 18:30:12.193 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [137736776934464] Error handling message: Unknown error (unknown_error) Enes from 192.168.178.20 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

**Comment by ludeeus** [comment]
The author controls this, not HACS.

**Comment by loeiks** [comment]
> The author controls this, not HACS.

sorry for wrong place
