### ISSUE TITLE
Unexpected exception importing platform custom_components.hacs.config_flow

### ISSUE THREAD

**Issue by chryan** [hacs/integration#3825]
## System Information

version | core-2024.6.4
-- | --
installation_type | Unsupported Third Party Container
dev | false
hassio | false
docker | true
user | abc
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.0-21-amd64
arch | x86_64
timezone | America/Los_Angeles
config_dir | /config

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 15
views | 2
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 2024.3.0
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 16, 2024 at 12:16 AM
-- | --
current_recorder_run | June 26, 2024 at 2:57 AM
estimated_db_size | 22.68 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/issues>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I had previously installed HACS and had it working until it was exhibiting "Unloaded" errors, so I attempted a reinstall and integrate.

Integrating HACS on HA Container yields the following error:
`Unexpected exception importing platform custom_components.hacs.config_flow`

I've attempted the following to no avail:
- Installing HACS on an existing HA Container (nuking `custom_components/hacs` before doing so)
- Installing HACS on a fresh HA Container

### Reproduction steps

1. Install HACS via the `docker exec` and `wget -O - https://get.hacs.xyz | bash -`
2. Attempt to integrate HACS in HA

### Installation Bash Log
```

Connecting to get.hacs.xyz (172.67.143.44:443)
Connecting to raw.githubusercontent.com (185.199.109.133:443)
writing to stdout
-                    100% |********************************|  4525  0:00:00 ETA
written to stdout
INFO: Trying to find the correct directory...
INFO: Found Home Assistant configuration directory at '//config'
INFO: Creating custom_components directory...
INFO: Changing to the custom_components directory...
INFO: Downloading HACS
Connecting to github.com (140.82.116.4:443)
Connecting to github.com (140.82.116.4:443)
Connecting to objects.githubusercontent.com (185.199.109.133:443)
saving to 'hacs.zip'
hacs.zip             100% |********************************| 15.0M  0:00:00 ETA
'hacs.zip' saved
INFO: Creating HACS directory...
INFO: Unpacking HACS...

INFO: Verifying versions
INFO: Current version is 2024.6.4, minimum version is 2023.6.0

INFO: Removing HACS zip file...
INFO: Installation complete.

INFO: Remember to restart Home Assistant before you configure it
```

### System Error Log
Logger: homeassistant.loader
Source: loader.py:1249
First occurred: 2:57:47 AM (4 occurrences)
Last logged: 2:59:09 AM
Unexpected exception importing platform custom_components.hacs.config_flow

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1249, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/loader.py", line 1281, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 12, in <module>
    from aiogithubapi import AIOGitHubAPIException, GitHub, GitHubAPI
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/__init__.py", line 20, in <module>
    from .device import GitHubDeviceAPI
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/device.py", line 14, in <module>
    from .client import GitHubClient
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/client.py", line 27, in <module>
    from .legacy.client import AIOGitHubAPIClient as LegacyAIOGitHubAPIClient
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/legacy/client.py", line 15, in <module>
    from ..helpers import async_call_api
  File "/usr/local/lib/python3.12/site-packages/aiogithubapi/helpers.py", line 8, in <module>
    from sigstore.verify import (
  File "/usr/local/lib/python3.12/site-packages/sigstore/verify/__init__.py", line 54, in <module>
    from sigstore.verify.models import (
  File "/usr/local/lib/python3.12/site-packages/sigstore/verify/models.py", line 30, in <module>
    from sigstore._internal.rekor import RekorClient
  File "/usr/local/lib/python3.12/site-packages/sigstore/_internal/rekor/__init__.py", line 19, in <module>
    from .client import RekorClient
  File "/usr/local/lib/python3.12/site-packages/sigstore/_internal/rekor/client.py", line 45, in <module>
    class RekorBundle(BaseModel):
  File "pydantic/main.py", line 286, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/main.py", line 807, in pydantic.main.BaseModel.__try_update_forward_refs__
  File "pydantic/typing.py", line 554, in pydantic.typing.update_model_forward_refs
  File "pydantic/typing.py", line 520, in pydantic.typing.update_field_forward_refs
  File "pydantic/typing.py", line 66, in pydantic.typing.evaluate_forwardref
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```
```


### Diagnostics dump

_No response_

**Comment by ludeeus** [comment]
Use the official Home Assistant container image.
