### ISSUE TITLE
No module named 'custom_components.hacs.repositories.appdaemon' When installing Alexa Media Player

### ISSUE THREAD

**Issue by alvoram** [hacs/integration#4079]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to one the HACS add-ons.
- [X] This is a bug and not a feature request.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).

### Which Add-on are you reporting an issue for?

get

### Describe the issue

First of all, I have no coding background, and I'm very new to Home Assistant, so please excuse me if I'm not able to explain this issue as clearly as you'd like. 

I recently tried to install the Alexa Media Player add on. Up until that point HACS had been working faultlessly, and always had, except one time I had issues with AppDaemon and ControllerX so chose to uninstall/remove those. HACS had however, worked flawlessly ever since, with plenty of add ons running. 

Until I went to install this Alexa add on. Now HACS has completely stopped working, all entities are disabled, with no way of restarting them (example image attached.) 

![Screenshot 2024-09-20 212824](https://github.com/user-attachments/assets/0224ae93-7cf0-4eb7-afb2-6764c2559399)

HACS has disappeared from the side bar. Every time I start my HA, I get the following notification. 

`Invalid config
The following integrations and platforms could not be set up:

[hacs](https://hacs.xyz/docs/configuration/start) ([Show logs](http://homeassistant.local:8123/config/logs?filter=hacs))
Please check your config and [logs](http://homeassistant.local:8123/config/logs).`

The log to which is attached. 

And HACS appears as "Not Loaded" on my devices page (example image attached.) 

![Screenshot 2024-09-20 212704](https://github.com/user-attachments/assets/08dbfdab-000d-4573-8cbb-60438fb16440)

Me being me, a tinkerer with no actual skills, noticed that it mentioned appdaemon, and figured it was probably something to do with the uninstall of appdaemon. So I reinstalled Appdaemon, which 'seems' to be running fine. However the issue is not fixed.

Any help appreciated. 

### Add-on logs

Logbook
No logbook events found.

### Supervisor logs

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 21:09:33 (1 occurrences)
Last logged: 21:09:33

Setup failed for custom integration 'hacs': Unable to import component: No module named 'custom_components.hacs.repositories.appdaemon'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hacs/__init__.py", line 23, in <module>
    from .base import HacsBase
  File "/config/custom_components/hacs/base.py", line 61, in <module>
    from .repositories import REPOSITORY_CLASSES
  File "/config/custom_components/hacs/repositories/__init__.py", line 6, in <module>
    from .appdaemon import HacsAppdaemonRepository
ModuleNotFoundError: No module named 'custom_components.hacs.repositories.appdaemon'

**Comment by alvoram** [comment]
Fixed it

Followed guide to completely uninstall HACS, (used a Samba Share network share for deleting the populated HACS custom_componenets folder,) reinstalled HACS, and all seems well.
