### ISSUE TITLE
HACS throws trace when trying to update component that requires newer HA

### ISSUE THREAD

**Issue by hmmbob** [hacs/integration#4179]
## System Information

version | core-2024.10.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.0-26-amd64
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4986
Installed Version | 2.0.1
Stage | running
Available Repositories | 1462
Downloaded Repositories | 37

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 15
views | 19
mode | yaml

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 25 oktober 2024 om 20:05
-- | --
current_recorder_run | 4 november 2024 om 09:27
estimated_db_size | 1695.42 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

Well, SSIA - but I got a notification of an update for Spotcast, which requires HA 2024.11.0 but I am on HA 2024.10.4. The toast message is clear and fine, I just think that the error in de logs is too verbose with the complete trace.

![image](https://github.com/user-attachments/assets/381701bd-2e1a-442a-951b-19752b41fdb6)

### Reproduction steps

Try to update a component which needs a newer HA than currently installed

### Debug logs

```text
2024-11-04 12:07:21.097 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139983994417024] Unexpected exception
Traceback (most recent call last):
File "/config/custom_components/hacs/update.py", line 88, in async_install
await self.repository.async_download_repository(ref=version or self.latest_version)
File "/config/custom_components/hacs/repositories/base.py", line 1417, in async_download_repository
await self._ensure_download_capabilities(ref)
File "/config/custom_components/hacs/repositories/base.py", line 1407, in _ensure_download_capabilities
raise HacsException(
custom_components.hacs.exceptions.HacsException: This version requires Home Assistant 2024.11.0 or newer.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 154, in async_install
await entity.async_install_with_progress(version, backup)
File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 463, in async_install_with_progress
await self.async_install(version, backup)
File "/config/custom_components/hacs/update.py", line 90, in async_install
raise HomeAssistantError(exception) from exception
homeassistant.exceptions.HomeAssistantError: This version requires Home Assistant 2024.11.0 or newer.
```

**Comment by hmmbob** [comment]
Oh, ok. Tx!
