### ISSUE TITLE
HACS: Error while loading page dashboard. 

### ISSUE THREAD

**Issue by sinojelly** [hacs/integration#4265]
### Web browser

Edge

### Web browser version

Microsoft Edge 版本 131.0.2903.99 (正式版本) (64 位)

## System Information

version | core-2024.12.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 5.19.17-z4pro-generic
arch | x86_64
timezone | Asia/Shanghai
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: unreachable
GitHub Web | failed to load: timeout
HACS Data | ok
GitHub API Calls Remaining | 4995
Installed Version | 2.0.1
Stage | running
Available Repositories | 1486
Downloaded Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 0
views | 0
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 15, 2024 at 12:15 AM
-- | --
current_recorder_run | December 15, 2024 at 8:42 AM
estimated_db_size | 0.28 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the frontend of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

HACS: Error while loading page dashboard. 

### Reproduction steps

Manual copy hacs to home assistant docker directory, click hacs on HomeAssist web site.
![image](https://github.com/user-attachments/assets/395c9166-c094-40f2-af06-e46e976b1af0)

### Screenshots

![image](https://github.com/user-attachments/assets/67007114-fbbc-4abe-bf1f-55d826a903e9)

### Javascript logs from your browser console

```text
4131.cFQLnEuDJBs.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
VM205 entrypoint.3UR5SnLC394.js:6  Error loading page dashboard TypeError: Failed to fetch dynamically imported module: http://192.168.31.88:8848/hacsfiles/frontend/frontend_latest/4131.cFQLnEuDJBs.js
(匿名) @ VM205 entrypoint.3UR5SnLC394.js:6
4131.cFQLnEuDJBs.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 (Not Found)
VM205 entrypoint.3UR5SnLC394.js:6  Error loading page dashboard TypeError: Failed to fetch dynamically imported module: http://192.168.31.88:8848/hacsfiles/frontend/frontend_latest/4131.cFQLnEuDJBs.js
(匿名) @ VM205 entrypoint.3UR5SnLC394.js:6
[新] 通过在 Microsoft Edge 中使用 Copilot 来解释控制台错误: 在上面
         
         以说明错误。
        了解更多信息
        不再显示
:8848/config/integrations/integration/hacs:1  The file at 'http://192.168.31.88:8848/api/error_log?authSig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjZjgzNDhiNTNmZTE0NjEyOWZmY2Q3YTJiOGVlZDBhYyIsInBhdGgiOiIvYXBpL2Vycm9yX2xvZyIsInBhcmFtcyI6W10sImlhdCI6MTczNDIyNDEwNiwiZXhwIjoxNzM0MjI0MTM2fQ.2pjDnCUjhVr1zKXx_z5YDxGC-IDQZd4FEIAQxmxYe14' was loaded over an insecure connection. This file should be served over HTTPS.
:8848/config/dashboard:1  Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: div
Ancestor with aria-hidden:  <div class=​"focus-trap" tabindex=​"0" aria-hidden=​"true">​</div>​
socket.js:34  WebSocket connection to 'ws://192.168.31.88:8848/api/websocket' failed: 
o @ socket.js:34
(匿名) @ socket.js:103
u @ socket.js:103
(匿名) @ connection.js:96
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}code: "unknown_command"message: "Unknown command."[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'unknown_command', message: 'Unknown command.'}
Promise.then
(匿名) @ connection.js:155
_setSocket @ connection.js:153
(匿名) @ connection.js:97
setTimeout
n @ connection.js:88
(匿名) @ connection.js:113
setTimeout
n @ connection.js:88
_handleClose @ connection.js:125
:8848/config/dashboard:1  Uncaught (in promise) {code: 'not_found', message: 'Subscription not found.'}
VM452 entrypoint.3UR5SnLC394.js:6 
        
        
        GET http://192.168.31.88:8848/hacsfiles/frontend/frontend_latest/4131.cFQLnEuDJBs.js net::ERR_ABORTED 404 (Not Found)
c.f.j @ VM452 entrypoint.3UR5SnLC394.js:6
(匿名) @ VM452 entrypoint.3UR5SnLC394.js:6
c.e @ VM452 entrypoint.3UR5SnLC394.js:6
load @ VM452 entrypoint.3UR5SnLC394.js:6
value @ VM452 entrypoint.3UR5SnLC394.js:6
performUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
scheduleUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
_$Ej @ VM452 entrypoint.3UR5SnLC394.js:6
await in _$Ej
requestUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
_$Eu @ VM452 entrypoint.3UR5SnLC394.js:6
w @ VM452 entrypoint.3UR5SnLC394.js:6
r @ VM452 entrypoint.3UR5SnLC394.js:6
r @ VM452 entrypoint.3UR5SnLC394.js:6
u @ VM452 entrypoint.3UR5SnLC394.js:6
g @ VM452 entrypoint.3UR5SnLC394.js:6
_$AI @ VM452 entrypoint.3UR5SnLC394.js:6
ce @ VM452 entrypoint.3UR5SnLC394.js:6
update @ VM452 entrypoint.3UR5SnLC394.js:6
performUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
scheduleUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
_$Ej @ VM452 entrypoint.3UR5SnLC394.js:6
await in _$Ej
requestUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
set @ VM452 entrypoint.3UR5SnLC394.js:6
value @ VM452 entrypoint.3UR5SnLC394.js:6
value @ VM452 entrypoint.3UR5SnLC394.js:6
await in value
value @ VM452 entrypoint.3UR5SnLC394.js:6
value @ VM452 entrypoint.3UR5SnLC394.js:6
performUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
scheduleUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
_$Ej @ VM452 entrypoint.3UR5SnLC394.js:6
await in _$Ej
requestUpdate @ VM452 entrypoint.3UR5SnLC394.js:6
_$Eu @ VM452 entrypoint.3UR5SnLC394.js:6
w @ VM452 entrypoint.3UR5SnLC394.js:6
ue @ VM452 entrypoint.3UR5SnLC394.js:6
(匿名) @ VM452 entrypoint.3UR5SnLC394.js:6
r @ VM452 entrypoint.3UR5SnLC394.js:6
r @ VM452 entrypoint.3UR5SnLC394.js:6
finisher @ VM452 entrypoint.3UR5SnLC394.js:6
runClassFinishers @ VM452 entrypoint.3UR5SnLC394.js:6
s @ VM452 entrypoint.3UR5SnLC394.js:6
(匿名) @ VM452 entrypoint.3UR5SnLC394.js:6
VM452 entrypoint.3UR5SnLC394.js:6  Error loading page dashboard TypeError: Failed to fetch dynamically imported module: http://192.168.31.88:8848/hacsfiles/frontend/frontend_latest/4131.cFQLnEuDJBs.js
```

### Debug logs

```text
2024-12-15 08:55:58.197 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 08:55:59.840 INFO (MainThread) [custom_components.hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 2.0.1
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2024-12-15 08:55:59.852 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore started
2024-12-15 08:55:59.891 INFO (MainThread) [custom_components.hacs] <HacsData restore> Restore done
2024-12-15 08:55:59.892 INFO (MainThread) [custom_components.hacs] Enable category: integration
2024-12-15 08:55:59.892 INFO (MainThread) [custom_components.hacs] Enable category: plugin
2024-12-15 08:55:59.892 INFO (MainThread) [custom_components.hacs] Enable category: template
2024-12-15 08:55:59.892 INFO (MainThread) [custom_components.hacs] Enable category: theme
2024-12-15 08:56:00.047 INFO (MainThread) [custom_components.hacs] Stage changed: setup
2024-12-15 08:56:00.047 INFO (MainThread) [custom_components.hacs] Stage changed: waiting
2024-12-15 08:56:00.047 INFO (MainThread) [custom_components.hacs] Setup complete, waiting for Home Assistant before startup tasks starts
2024-12-15 08:56:00.577 INFO (MainThread) [custom_components.hacs] Stage changed: startup
2024-12-15 08:56:00.578 DEBUG (MainThread) [custom_components.hacs] There are 6 scheduled recurring tasks
2024-12-15 08:56:00.578 INFO (MainThread) [custom_components.hacs] Loading removed repositories
2024-12-15 08:56:01.153 INFO (MainThread) [custom_components.hacs] Loading known repositories
2024-12-15 08:56:01.153 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for template
2024-12-15 08:56:01.154 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for integration
2024-12-15 08:56:01.154 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for plugin
2024-12-15 08:56:01.154 DEBUG (MainThread) [custom_components.hacs] Fetching updated content for theme
2024-12-15 08:56:02.221 INFO (MainThread) [custom_components.hacs] Stage changed: running
2024-12-15 08:56:02.412 DEBUG (MainThread) [custom_components.hacs] <QueueManager> The queue is empty
2024-12-15 08:56:02.413 DEBUG (MainThread) [custom_components.hacs] <HACSStore async_save_to_store> Did not store data for 'hacs.critical'. Content did not change
2024-12-15 08:56:02.413 DEBUG (MainThread) [custom_components.hacs] Nothing in the queue
2024-12-15 08:56:17.876 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 137, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 114, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 112, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1315, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1350, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 237, in async_step_zeroconf
    await self._async_aggregate_discoveries(host, unique_id)
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 279, in _async_aggregate_discoveries
    self._async_check_and_update_in_progress(host, unique_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 287, in _async_check_and_update_in_progress
    if self.hass.config_entries.flow.async_has_matching_flow(self):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1609, in async_has_matching_flow
    if other_flow is not flow and flow.is_matching(other_flow):  # type: ignore[arg-type]
                                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/apple_tv/config_flow.py", line 299, in is_matching
    other_flow.all_identifiers.add(self.unique_id)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AppleTVConfigFlow' object has no attribute 'all_identifiers'. Did you mean: 'atv_identifiers'?
```

### Diagnostics dump

[config_entry-hacs-01JF3VFBAWFX660MFJMD2S93WV.json](https://github.com/user-attachments/files/18138380/config_entry-hacs-01JF3VFBAWFX660MFJMD2S93WV.json)

**Comment by ludeeus** [comment]
Use the script as instructed in the docs.

**Comment by Tuinslak** [comment]
Sorry, which script or docs are you referring to? I don't see anything in https://www.hacs.xyz/docs/use/update/

**Comment by tjorim** [comment]
https://www.hacs.xyz/docs/use/download/download/#to-download-hacs
