### ISSUE TITLE
Home assistant container not installing integrations python requirements for hacks

### ISSUE THREAD

**Issue by pedrol3001** [hacs/integration#4273]
## System Information

version | core-2024.12.3
-- | --
installation_type | Unknown
dev | false
hassio | false
docker | false
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 5.10.160-legacy-rk35xx
arch | aarch64
timezone | America/Sao_Paulo
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | failed to load: timeout
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4959
Installed Version | 2.0.1
Stage | running
Available Repositories | 1488
Downloaded Repositories | 35

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 14 de janeiro de 2025 às 21:00
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
cloud_ice_servers_enabled | true
remote_server | us-east-1-2.ui.nabu.casa
certificate_status | ready
instance_id | 70ef370cfd3f474b90ffe2bd894370cf
can_reach_cert_server | failed to load: timeout
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 20
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 de novembro de 2024 às 02:32
-- | --
current_recorder_run | 16 de dezembro de 2024 às 22:11
estimated_db_size | 2416.83 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 1 / 1
local_online | 0 / 0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I'm running the newest version of HACS <https://github.com/hacs/integration/releases/latest>
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] I have read <https://hacs.xyz/docs/help/issues/>
- [X] This issue is related to the backend (integration part) of HACS.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This is a bug and not a feature request.
- [X] This issue is not a duplicate issue of currently [open](https://github.com/hacs/integration/issues) or issues [pending release](https://github.com/hacs/integration/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc+milestone%3Anext).

### Describe the issue

I installed the home assistant container (2024.12.3), but it is not installing integrations python requirements on container startup.
For home assistant integrations, it works normally. But for hacks integrations it ir not working.

If i install the package inside the container, it works normally: `pip install alexapy`

### Reproduction steps

1. install homeasistant container
2. install hacks
3. install alkexa media player addon
4. addon does not work with the error descriver

### Debug logs

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/alexa_media/__init__.py", line 18, in <module>
    from alexapy import (
    ...<9 lines>...
    )
ModuleNotFoundError: No module named 'alexapy'
```

### Diagnostics dump

Cant get because the integration does not loads

**Comment by pedrol3001** [comment]
Dont think the problem is in hacks. Will seek help with homeassistant. Sorry for the issue.
