### ISSUE TITLE
Two Hacs installation

### ISSUE THREAD

**Issue by Raphael99-99** [hacs/integration#740]
## Version of HACS

Installed version: | 0.15.11
-- | --

## Describe the bug

I found out two HACS installation. I cannot uninstall one or the other and I suspect can be some conflict

## Debug log

```text

Add your logs here.
HACS (Home Assistant Community Store)

Version: 0.15.11
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/hacs/issues
-------------------------------------------------------------------

2019-10-25 15:27:58 INFO (MainThread) [homeassistant.setup] Setting up shelly
2019-10-25 15:27:58 INFO (SyncWorker_15) [custom_components.shelly] Starting shelly, 0.1.0
2019-10-25 15:27:58 INFO (MainThread) [homeassistant.setup] Setting up sun
2019-10-25 15:27:58 INFO (SyncWorker_15) [pyShelly] Init pyShelly 0.1.0
2019-10-25 15:27:58 INFO (SyncWorker_15) [custom_components.shelly] pyShelly, 0.1.0
2019-10-25 15:27:58 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.1 seconds.
2019-10-25 15:27:58 INFO (MainThread) [homeassistant.setup] Setting up sensor
2019-10-25 15:27:58 ERROR (MainThread) [homeassistant.setup] Setup failed for introduction: Integration not found.
2019-10-25 15:27:58 INFO (SyncWorker_1) [homeassistant.loader] Loaded binary_sensor from homeassistant.components.binary_sensor
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.darksky
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up history
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds.
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up api
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up script
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds.
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up config
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up system_health
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds.
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up auth
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
2019-10-25 15:27:59 INFO (SyncWorker_8) [homeassistant.loader] Loaded google_translate from homeassistant.components.google_translate
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up webhook
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain shelly took 1.0 seconds.
2019-10-25 15:27:59 INFO (SyncWorker_6) [homeassistant.loader] Loaded fritz from homeassistant.components.fritz
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 0.0 seconds.
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.5 seconds.
2019-10-25 15:27:59 INFO (MainThread) [homeassistant.setup] Setting up tts
2019-10-25 15:27:59 WARNING (SyncWorker_14) [homeassistant.components.darksky.sensor] Monitored condition temperature_max is deprecated
2019-10-25 15:27:59 WARNING (SyncWorker_14) [homeassistant.components.darksky.sensor] Monitored condition temperature_min is deprecated
2019-10-25 15:27:59 WARNING (SyncWorker_14) [homeassistant.components.darksky.sensor] Monitored condition apparent_temperature_max is deprecated
2019-10-25 15:27:59 WARNING (SyncWorker_14) [homeassistant.components.darksky.sensor] Monitored condition apparent_temperature_min is deprecated
2019-10-25 15:28:00 ERROR (MainThread) [homeassistant.config] Invalid config for [device_tracker.fritz]: [new_devices_defaults] is an invalid option for [device_tracker.fritz]. Check: device_tracker.fritz->new_devices_defaults. (See /config/configuration.yaml, line 81). Please check the docs at https://home-assistant.io/integrations/device_tracker.fritz/
2019-10-25 15:28:00 INFO (MainThread) [homeassistant.setup] Setting up device_tracker
2019-10-25 15:28:00 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.8 seconds.
2019-10-25 15:28:00 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2019-10-25 15:28:00 ERROR (Thread-2) [pyShelly] Error http GET: http://192.168.178.113/settings Extra data: line 1 column 5 (char 4) Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/__init__.py", line 214, in http_get
    resp_json = json.loads(s(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by ludeeus** [comment]
See #724

**Comment by Raphael99-99** [comment]
Thanks a lot. Nice job
