### ISSUE TITLE
Fresh install does not work with 0.16.2

### ISSUE THREAD

**Issue by SimonO93** [hacs/integration#757]
## Version of HACS
Home Assistant - 0.100.3
HACS - 0.16.2 configured via UI

## Describe the bug
This is my first time with HACS. Fresh install. After unziping hacs.zip tu custom_components i mange to do initial configuration with personal token from github. Steps written in configuration page went ok.
Problem is that hacs shows "The frontend of HACS have been disabled until you restart Home Assistant". I did restart it 3 times, no changes. I checked my .storage folder and it does not contain any hacs files.
Below is what I see in logs.

I tried version 0.16.1 with fresh install and it works.

## Debug log

```text
2019-11-02 13:10:03 WARNING (MainThread) [homeassistant.components.frontend] Overwriting integration hacs                                                                                                                    
2019-11-02 13:10:03 CRITICAL (MainThread) [hacs.data] ['view'] Restore Failed! see https://github.com/hacs/integration/issues/639 for more details.
2019-11-02 13:10:03 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry  for sensor                                                                                                                      
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/config_entries.py", line 265, in async_unload                                                                                                               
    hass, self
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/sensor/__init__.py", line 65, in async_unload_entry                                                                                              
    return await hass.data[DOMAIN].async_unload_entry(entry)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 168, in async_unload_entry                                                                                               
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2019-11-02 13:10:03 WARNING (MainThread) [homeassistant.components.frontend] Removing unknown panel hacs_web
2019-11-02 13:10:03 WARNING (MainThread) [homeassistant.config_entries] Config entry for hacs not ready yet. Retrying in 80 seconds.
```

**Comment by ludeeus** [comment]
Uuups... :(

**Comment by SimonO93** [comment]
ehh that python :) .

Thanks
