### ISSUE TITLE
Ability to cope with loss of internet

### ISSUE THREAD

**Issue by jarrah31** [hacs/integration#762]
## Version of HACS
15.7

## Describe the bug
My internet router/modem suffered a hardware failure so I’m without internet for 5 days. 

I’ve noticed that HACS repeatedly sends the following timeout error to the logs after a reboot:

```
2019-11-05 20:26:18 INFO (MainThread) [backoff] Backing off get_ratelimit(...) for 0.6s (concurrent.futures._base.TimeoutError)
2019-11-05 20:26:18 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again
```

I know that HACS requires the internet in order to check for version information and store details, but would it be possible to detect the lack of internet and handle timeouts graciously? I received over 60 of the above timeout errors, so perhaps it could stop trying after a couple of instances and continue loading the rest of HA please?

I also tried rebooting with HACS commented out, but I found that my custom card plugins failed to load so had to re-enable. 

Apologies for the lack of details, I’m writing this on my mobile phone. 

Thanks. 

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
A lot have changed since the version you are running and the latest, retry with that, your logs does not make any sense against the current codebase

**Comment by jarrah31** [comment]
I’m sorry, I’m unable to download the latest version at the moment. I will try again with the latest version when my replacement modem arrives later this week. It’s like having an arm cut off without the internet at home. :)
