### ISSUE TITLE
custom-components/alexa_media_player

### ISSUE THREAD

**Issue by lweberru** [hacs/integration#768]
Hi,

I am getting millions of error messages in the log and 50% of the entities are not available. I am using newest stable version, with no filtering right now.

`2019-11-02 16:33:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 181, in async_send_delete_message
    alexa_entity = ENTITY_ADAPTERS[domain](hass, config, hass.states.get(entity_id))
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 150, in __init__
    self.entity_conf = config.entity_config.get(entity.entity_id, {})
AttributeError: 'NoneType' object has no attribute 'entity_id'
2019-11-02 16:33:29 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/alexa/state_report.py", line 147, in async_send_add_or_update_message
    alexa_entity = ENTITY_ADAPTERS[domain](hass, config, hass.states.get(entity_id))
  File "/usr/src/homeassistant/homeassistant/components/alexa/entities.py", line 150, in __init__
    self.entity_conf = config.entity_config.get(entity.entity_id, {})
AttributeError: 'NoneType' object has no attribute 'entity_id' `

Any idea?
Lukas

**Comment by ludeeus** [comment]
You need to open an issue for that repository, HACS does not have any power over how individual integrations work.

**Comment by hefal** [comment]
I have this same issue, did you fin a solution? :(
