### ISSUE TITLE
500 Internal Server Error when attempting to upgrade 16.3 to 17

### ISSUE THREAD

**Issue by repvik** [hacs/integration#783]
Issues not containing the minimum requirements will be closed:

- Issues without a description (using the header is not good enough) will be closed.
- Issues without debug logging will be closed.

## Version of HACS

Current version 16.3 (Restarted Home Assistant after upgrading from 15.x to 16.3, as noted in release notes)

## Describe the bug

Attempting to upgrade to 17.0 results in a HTTP 500 Internal Server error. Upgrade fails. 

## Debug log

```text

2019-11-17 19:53:32 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.17.0  ---  tag: 0.17.0
2019-11-17 19:53:32 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.17.0  ---  tag: 0.16.3
2019-11-17 19:53:32 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.17.0  ---  tag: 0.16.2
2019-11-17 19:53:32 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.17.0  ---  tag: 0.16.1
2019-11-17 19:53:32 INFO (MainThread) [hacs.repository.integration.hacs.integration] ref: tags/0.17.0  ---  tag: 0.16.0
2019-11-17 19:53:34 INFO (MainThread) [hacs.repository.integration.hacs.integration] download of hacs.zip complete
2019-11-17 19:53:34 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/hacs/http.py", line 78, in get
  File "/config/custom_components/hacs/http.py", line 239, in response
  File "/config/custom_components/hacs/http.py", line 98, in render
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: repository.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 136, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 122, in handle
    result = await result
  File "/config/custom_components/hacs/http.py", line 80, in get
  File "/config/custom_components/hacs/http.py", line 98, in render
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: error.html

```

**Comment by ludeeus** [comment]
From the release notes:

> This version removes the old UI, this means that when the update is done the frontend of HACS will be broken until you restart Home Assistant.

**Comment by repvik** [comment]
From my bug report:

Current version 16.3 (**Restarted Home Assistant after upgrading from 15.x to 16.3, as noted in release notes**)
