### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by chusrufo** [hacs/integration#805]
-->

## Version of HACS

017

## Describe the bug
Hi, how are you?

I have copied the "custom_components" folder and restarted. Then I have put in configuration.yaml:

hacs:
       token: mitoken

and when I give it a restart it won't let me

I have to ssh and delete the phrase "configuration.yaml" and so reboot

what could be the mistake?

## Debug log

Detalles de registro (ERROR)
Wed Nov 20 2019 21:18:22 GMT+0100 (hora estándar de Europa central)
Error executing service <ServiceCall homeassistant.restart (c:d4a9c934396d4dc0bef9853eeac12a90)>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1244, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1261, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 265, in async_handle_core_service
    errors = await conf_util.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/config.py", line 795, in async_check_ha_config_file
    res = await check_config.async_check_ha_config_file(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 107, in async_check_ha_config_file
    integration = await async_get_integration_with_requirements(hass, domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 48, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 77, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 45, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3137, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

Detalles de registro (WARNING)
Wed Nov 20 2019 21:12:50 GMT+0100 (hora estándar de Europa central)
You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

**Comment by chusrufo** [comment]
I think now, hahahaha

**Comment by chusrufo** [comment]
I think now, hahahaha

**Comment by ludeeus** [comment]
It can not get packages from pypi, check network/DNS
