### ISSUE TITLE
HA 0.102, template not found

### ISSUE THREAD

**Issue by bachoo786** [hacs/integration#808]
## Version of HACS

0.17.4

## Describe the bug
So I updated HA to 0.102 and I am running 0.17.4 of HACS. I get the following error message that is continuous.

## Debug log
```
2019-11-21 21:31:24 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/hacs/http.py", line 78, in get
  File "/config/custom_components/hacs/http.py", line 169, in response
  File "/config/custom_components/hacs/http.py", line 98, in render
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: settings.html
```

**Comment by ludeeus** [comment]
You are not using 0.17.x
The http file is only 57lines, you log have higher numbers then that.
Clear your cache, if that fails do a manual reinstall
