### ISSUE TITLE
Error during setup of component hacs

### ISSUE THREAD

**Issue by bend** [hacs/integration#811]
## Version of HACS
0.17.3 & 0.17.4

## Describe the bug

I've updated to latest version of homeassistant (0.102.1) and since then, hacs is no longer loading.
I see the hacs component in homeassistant UI, It does not see any of my already installed modules and plugins. I tried updating and reverting the version of hacs, without luck. I also tried to delete the .storage/hacs.hacs file.

## Debug log

```text

2019-11-22 09:39:34 ERROR (MainThread) [homeassistant.setup] Error during setup of component hacs
Traceback (most recent call last):                                                                                                                                                      
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component                                                                                             
    hass, processed_config                                                                                                                                                              
  File "/config/custom_components/hacs/__init__.py", line 39, in async_setup
    await startup_wrapper_for_yaml(Hacs)                                                                                                                                                
  File "/config/custom_components/hacs/__init__.py", line 72, in startup_wrapper_for_yaml
    startup_result = await hacs_startup(hacs)
  File "/config/custom_components/hacs/__init__.py", line 120, in hacs_startup
    if not await hacs.data.restore():
  File "/config/custom_components/hacs/hacsbase/data.py", line 61, in restore
    hacs = await async_load_from_store(self.hass, "hacs")
  File "/config/custom_components/hacs/store.py", line 10, in async_load_from_store
    restored = await store.async_load()                                                                                                                                                 
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 99, in async_load                                                                                                
    return await self._load_task                                                                                                                                                        
  File "/usr/src/homeassistant/homeassistant/helpers/storage.py", line 117, in _async_load                                                                                              
    if data["version"] == self.version:                                                                                                                                                 
KeyError: 'version'           

```

**Comment by ludeeus** [comment]
You get this if you did not upgrade to 0.16.2/3 before going to 0.17.x as stated in the release notes.
To get around it delete the `hacs.repositories` file and restart HA.
