### ISSUE TITLE
Can't update from HACS (issue opened on my repository)

### ISSUE THREAD

**Issue by bruxy70** [hacs/integration#839]
## Version of HACS
0.17.4

## Describe the bug
I have 2 guys that report [this issue](https://github.com/bruxy70/Garbage-Collection/issues/50)
They try to update garbage_collection to the latest version (2.7), currently on 2.6. It says that update is available, but when they update, it still says that they are on 2.6 and that update is still available (even after the restart).

I have tried to replicate, but it works fine for me, upgraded to 2.7 with no issue. The integration is used by about 400 users, not sure if the others have the issue, I do not think so.

Woodcat64 claims, that the issue started on version 2.1. This is when I switched to "zip_release", using the action stolen from (provided by) @ludeeus. So I guess it is related.

In his last attempt, he uninstalled garbage_collection, completely removed it from custom_componnets, restarted HA, HACS showed that 2.7 is available. It installed 2.5 and keeps saying 2.7 is available (even after the restart). His log is below.

Can you please help. I have no idea how to troubleshoot it - if there is something wrong with my release action? Thanks!

## Debug log

```text
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving compact-custom-header/compact-custom-header.js from /config/www/community/compact-custom-header/compact-custom-header.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving fan-control-entity-row/fan-control-entity-row.js from /config/www/community/fan-control-entity-row/fan-control-entity-row.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving simple-thermostat/simple-thermostat.js from /config/www/community/simple-thermostat/simple-thermostat.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving vertical-stack-in-card/vertical-stack-in-card.js from /config/www/community/vertical-stack-in-card/vertical-stack-in-card.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving weather-card/weather-card.js from /config/www/community/weather-card/weather-card.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving light-entity-card/light-entity-card.js from /config/www/community/light-entity-card/light-entity-card.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving button-card/button-card.js from /config/www/community/button-card/button-card.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving swipe-card/swipe-card.js from /config/www/community/swipe-card/swipe-card.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving garbage-collection-card/garbage-collection-card.js from /config/www/community/garbage-collection-card/garbage-collection-card.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving lovelace-fold-entity-row/fold-entity-row.js from /config/www/community/lovelace-fold-entity-row/fold-entity-row.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js from /config/www/community/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving rgb-light-card/card.js from /config/www/community/rgb-light-card/card.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving bignumber-card/bignumber-card.js from /config/www/community/bignumber-card/bignumber-card.js.gz

2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving fan-control-entity-row/fan-control-entity-row.js from /config/www/community/fan-control-entity-row/fan-control-entity-row.js.gz
2019-12-04 19:51:02 DEBUG (MainThread) [hacs] Serving bignumber-card/bignumber-card.js from /config/www/community/bignumber-card/bignumber-card.js.gz
2019-12-04 19:51:05 DEBUG (MainThread) [hacs] 4977
2019-12-04 19:51:05 DEBUG (MainThread) [hacs] 2019-12-05 01:50:57
2019-12-04 19:51:05 INFO (MainThread) [hacs] Loading known repositories
2019-12-04 19:51:09 DEBUG (MainThread) [hacs] Starting recuring background task for installed repositories
2019-12-04 19:51:09 DEBUG (MainThread) [hacs] 4962
2019-12-04 19:51:09 DEBUG (MainThread) [hacs] 2019-12-05 01:50:57
2019-12-04 19:51:11 DEBUG (MainThread) [hacs.repository.integration.hacs.integration] Information update done.
2019-12-04 19:51:13 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.vertical-stack-in-card] Information update done.
2019-12-04 19:51:15 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.beer-card] Information update done.
2019-12-04 19:51:17 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.button-card] Information update done.

2019-12-04 19:51:20 DEBUG (MainThread) [hacs.repository.plugin.nervetattoo.simple-thermostat] Information update done.
2019-12-04 19:51:22 DEBUG (MainThread) [hacs.repository.plugin.maykar.compact-custom-header] Information update done.
2019-12-04 19:51:24 DEBUG (MainThread) [hacs.repository.integration.rgruebel.ha_zigbee2mqtt_networkmap] Information update done.
2019-12-04 19:51:25 DEBUG (MainThread) [hacs.repository.plugin.ljmerza.light-entity-card] Information update done.
2019-12-04 19:51:27 DEBUG (MainThread) [hacs.repository.plugin.custom-cards.bignumber-card] Information update done.
2019-12-04 19:51:28 DEBUG (MainThread) [hacs.repository.plugin.finity69x2.fan-control-entity-row] Information update done.
2019-12-04 19:51:30 DEBUG (MainThread) [hacs.repository.plugin.bramkragten.weather-card] Information update done.
2019-12-04 19:51:31 DEBUG (MainThread) [hacs.repository.plugin.bramkragten.swipe-card] Information update done.
2019-12-04 19:51:32 DEBUG (MainThread) [hacs.repository.theme.seangreen2.slate_theme] Information update done.
2019-12-04 19:51:34 DEBUG (MainThread) [hacs.repository.plugin.dmulcahey.zha-network-card] Information update done.
2019-12-04 19:51:35 DEBUG (MainThread) [hacs.template] 'now' is undefined
2019-12-04 19:51:35 DEBUG (MainThread) [hacs.repository.plugin.azuwis.zigbee2mqtt-networkmap] Information update done.
2019-12-04 19:51:37 DEBUG (MainThread) [hacs.repository.theme.bbbenji.synthwave-hass] Information update done.
2019-12-04 19:51:38 DEBUG (MainThread) [hacs.repository.integration.bruxy70.Garbage-Collection] Information update done.
2019-12-04 19:51:39 DEBUG (MainThread) [hacs.repository.integration.twrecked.hass-momentary] Information update done.
2019-12-04 19:51:41 DEBUG (MainThread) [hacs.repository.plugin.amaximus.garbage-collection-card] Information update done.
2019-12-04 19:51:42 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.amoled] Information update done.
2019-12-04 19:51:43 DEBUG (MainThread) [hacs.repository.appdaemon.bieniu.ha-ad-brother-printer] Information update done.
2019-12-04 19:51:45 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.midnight] Information update done.
2019-12-04 19:51:46 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.blue-night] Information update done.
2019-12-04 19:51:47 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.grey-night] Information update done.
2019-12-04 19:51:49 DEBUG (MainThread) [hacs.repository.plugin.bokub.rgb-light-card] Information update done.
2019-12-04 19:51:50 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.solarized-light] Information update done.
2019-12-04 19:51:52 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.material-dark-green] Information update done.
2019-12-04 19:51:53 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.teal] Information update done.
2019-12-04 19:51:54 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.halloween] Information update done.
2019-12-04 19:51:56 DEBUG (MainThread) [hacs.repository.plugin.PiotrMachowski.Home-Assistant-Lovelace-Local-Conditional-card] Information update done.
2019-12-04 19:51:57 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.dark-orange] Information update done.
2019-12-04 19:51:58 DEBUG (MainThread) [hacs.repository.theme.naofireblade.clear-theme] Information update done.
2019-12-04 19:51:59 DEBUG (MainThread) [hacs.repository.theme.naofireblade.clear-theme-dark] Information update done.
2019-12-04 19:52:01 DEBUG (MainThread) [hacs.repository.appdaemon.xaviml.z2m_ikea_controller] Information update done.
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving compact-custom-header/compact-custom-header.js from /config/www/community/compact-custom-header/compact-custom-header.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving fan-control-entity-row/fan-control-entity-row.js from /config/www/community/fan-control-entity-row/fan-control-entity-row.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving simple-thermostat/simple-thermostat.js from /config/www/community/simple-thermostat/simple-thermostat.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving vertical-stack-in-card/vertical-stack-in-card.js from /config/www/community/vertical-stack-in-card/vertical-stack-in-card.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving weather-card/weather-card.js from /config/www/community/weather-card/weather-card.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving light-entity-card/light-entity-card.js from /config/www/community/light-entity-card/light-entity-card.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving button-card/button-card.js from /config/www/community/button-card/button-card.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving swipe-card/swipe-card.js from /config/www/community/swipe-card/swipe-card.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving garbage-collection-card/garbage-collection-card.js from /config/www/community/garbage-collection-card/garbage-collection-card.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving lovelace-fold-entity-row/fold-entity-row.js from /config/www/community/lovelace-fold-entity-row/fold-entity-row.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js from /config/www/community/zigbee2mqtt-networkmap/zigbee2mqtt-networkmap.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving rgb-light-card/card.js from /config/www/community/rgb-light-card/card.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving bignumber-card/bignumber-card.js from /config/www/community/bignumber-card/bignumber-card.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving fan-control-entity-row/fan-control-entity-row.js from /config/www/community/fan-control-entity-row/fan-control-entity-row.js.gz
2019-12-04 19:52:02 DEBUG (MainThread) [hacs.repository.theme.home-assistant-community-themes.midnight-blue] Information update done.
2019-12-04 19:52:02 DEBUG (MainThread) [hacs] Serving bignumber-card/bignumber-card.js from /config/www/community/bignumber-card/bignumber-card.js.gz
2019-12-04 19:52:04 DEBUG (MainThread) [hacs.repository.integration.custom-components.sensor.mitemp_bt] Information update done.
2019-12-04 19:52:04 DEBUG (MainThread) [hacs.data] Saving data
2019-12-04 19:52:04 DEBUG (MainThread) [hacs] Recuring background task for installed repositories done
2019-12-04 19:52:04 DEBUG (MainThread) [hacs.data] Saving data
2019-12-04 19:52:07 INFO (MainThread) [hacs] Running set_state for bruxy70/Garbage-Collection
2019-12-04 19:52:07 DEBUG (MainThread) [hacs.data] Saving data
2019-12-04 19:52:07 INFO (MainThread) [hacs] Running update for bruxy70/Garbage-Collection
2019-12-04 19:52:08 DEBUG (MainThread) [hacs.data] Saving data
2019-12-04 20:00:59 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 275, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 394, in _async_write_ha_state
    self.entity_id, state, attr, self.force_update, self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 988, in async_set
    state = State(entity_id, new_state, attributes, last_changed, None, context)
  File "/usr/src/homeassistant/homeassistant/core.py", line 733, in __init__
    ).format(entity_id)
homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity id: sensor.forecast. State max length is 255 characters.
```

**Comment by bruxy70** [comment]
Trying to figure out where HACS store the version. On my (working) instance, I have found that .storage/hacs.repositories registers the integration, "installed_commit": "4d2f779", that is same as last commit (and it is the kast commit indeed) and the last_release_tag and version_installed is v2.7, which is correct (on my working instance). Is this something that could get wrong for these two guys?
Then there is one thing I do not understand. hacs.installed
        "bruxy70/Garbage-Collection": {
            "version_type": "version",
            "version_installed": "v2.2",
            "version_available": "v2.2"
        },
It says 2.2, whilst it should be 2.7. Is that normal? (still on my instance that works)...

**Comment by ludeeus** [comment]
I have no clue, the logs is not from the installation so it's not really helpful

**Comment by bruxy70** [comment]
Ok. I will tell them that I am sorry and close it. Before I do, The fact that hacs.installed shows 2.2 is normal? Suppose it shows the version at the time it was installed, and it does not get updated after that?

**Comment by ludeeus** [comment]
Installed version is the version (tag) that was installed, by the looks of it, it might be a network/storage issue

**Comment by bruxy70** [comment]
Thanks
