### ISSUE TITLE
Installation does not work when lovelace is in yaml mode

### ISSUE THREAD

**Issue by Triceert2** [hacs/integration#848]
## Version of HACS
0.102.3 
installed in docker ce 2.1.0.3 on OS X 10.14.6

## Describe the bug
Something minor, but might be of interest:
HACS is not recognised when adding the integration when 
```
lovelace:
  mode: yaml
```
is set in configuration.yaml

It how ever works in Vanilla mode:

2019-12-09 19:10:28 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

**Comment by ludeeus** [comment]
I'm unable to replicate this.

**Comment by ercsey** [comment]
Same issue here. 
On a fresh install on (Intel nuc with ubuntu and Hass.io) I have installed HACS (based on instalattion instruction)  without a problem. Then I've changed the lovelace to yaml mode. After restart hacs was unavailable. Deleted the whole integration conform documentation and disabled yaml mode. After restart I've managed to reinstall HACS. Enabled yaml mode for lovelace again and same error:
```Error setting up entry  for hacs```
```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/config/custom_components/hacs/__init__.py", line 67, in async_setup_entry
    startup_result = await hacs_startup(Hacs)
  File "/config/custom_components/hacs/__init__.py", line 103, in hacs_startup
    lovelace_info = await system_health_info(hacs.hass)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 235, in system_health_info
    return await hass.data[DOMAIN].async_get_info()
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 140, in async_get_info
    return _config_info("yaml", config)
  File "/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py", line 242, in _config_info
    "resources": len(config.get("resources", [])),
TypeError: object of type 'NoneType' has no len()```
