### ISSUE TITLE
Adding HACS to HA fails

### ISSUE THREAD

**Issue by dkagedal** [hacs/integration#906]
## Version of HACS

0.20.4

## Describe the bug

I followed the installation instructions, and have a ´/config/custom_components/hacs`that looks like: 

```
.                        configuration_schema.py  helpers                  services.yaml
..                       const.py                 http.py                  setup.py
.translations            constrains.py            manifest.json            store.py
__init__.py              hacsbase                 repositories             ws_api_handlers.py
config_flow.py           handler                  sensor.py
```

I restarted HA and cleared the browser cache. I click the "add an integration" button and select HACS. Then the UI spins for a long time and eventually I get thrown back to the integration selection box.
## Debug log

The HA log shows this:

```text
2019-12-30 19:48:49 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 40, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 136, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 48, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 60, in post
    handler, context={"source": config_entries.SOURCE_USER}
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 66, in async_init
    flow = await self._async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 638, in _async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 292, in async_process_deps_reqs
    hass, integration.domain
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 51, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 90, in async_process_requirements
    ret = await hass.async_add_executor_job(_install, hass, req, kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 103, in _install
    progress_path.unlink()
  File "/usr/local/lib/python3.7/pathlib.py", line 1294, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/config/.pip_progress'
```

**Comment by dkagedal** [comment]
A simple `touch .pip_progress` worked as a workaround, but it shouldn't be needed.

**Comment by ludeeus** [comment]
```
FileNotFoundError: [Errno 2] No such file or directory: '/config/.pip_progress'
```
Restart HA and try again.
This is out of control for HACS.

**Comment by FlorinAcsinte** [comment]
Problem still present in latest versions. Maybe update the installation log with this tip?
