### ISSUE TITLE
Platform hacs does not generate unique IDs

### ISSUE THREAD

**Issue by T2evh** [hacs/integration#933]
## Version of HACS

 
Latest version installed, now Home Assistant HASS.IO fails to load

## Describe the bug
Upgraded to latest version of HACS, but now Home Assistant will no longer start.
See error log below

## Debug log

2020-01-19 17:59:05 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-01-19 17:59:05 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 410, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.hacs. Platform hacs does not generate unique IDs

```text

Add your logs here.
2020-01-19 17:59:05 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-01-19 17:59:05 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 410, in _async_add_entity
    raise HomeAssistantError(msg)
homeassistant.exceptions.HomeAssistantError: Entity id already exists: sensor.hacs. Platform hacs does not generate unique IDs

```

**Comment by ludeeus** [comment]
It does not need unique ID's, It has a single platform, and you should only add it once.
Adding it both with YAML and in the UI will cause this.

**Comment by T2evh** [comment]
it was working fine until I tried to upgrade. Should I remove the HACS section from the config (below)?

hacs:
  token: !secret hacs_github
  appdaemon: true
  pythos_scripts: true
  theme: true

**Comment by ludeeus** [comment]
If you set it up in the UI then yes.
