### ISSUE TITLE
HACS broken with Python3.7 on HASS 0.104.3

### ISSUE THREAD

**Issue by Gamerayers** [hacs/integration#942]
## Version of HACS
0.20.8

## Describe the bug
I am using Rasbperry Pi 4b with the 32-bit install of Home Assistant.  When upgrading from version 0.103.x to 0.104.3.  Home Assistant would crash during start up.  In an attempt to fix it, reset entire configuration and started over.
After starting over, couldn't get HACS to work.  1st attempt was using Integrations -> HACS.  After clicking HACS, it goes back to the Integration list.  Does not allow for any inputs.  Tried with configuration.yaml, and Home Assistant will fail to start similar to the original.
Log is from including the custom_component alone and clicking integrations -> HACS.  Currently, no log available from using with yaml.

## Debug log
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 127, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 59, in post
    handler, context={"source": config_entries.SOURCE_USER}
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 100, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 500, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 290, in async_process_deps_reqs
    hass, integration.domain
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 55, in async_get_integration_with_requirements
    hass, integration.domain, integration.requirements
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 99, in async_process_requirements
    if pkg_util.is_installed(req):
  File "/usr/src/homeassistant/homeassistant/util/package.py", line 44, in is_installed
    return version(req.project_name) in req
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3138, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/specifiers.py", line 703, in contains
    item = parse(item)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 31, in parse
    return Version(version)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

**Comment by ludeeus** [comment]
This issue happens _before_ HACS is started, HACS requires a few pypi libs to function, without those HA will not try to load HACS.

If you have a `deps` dir in your config, delete that.
If not, try restarting a few times.

**Comment by Gamerayers** [comment]
I'm a little unsure how to fix this as I have continue to restart and continue to get this error.  I also have an empty deps folder and no reference to it in my config.  I tried again, and have an additional log if that helps.

The log has no issues until I click on the integration -> HACS, then it has the error.

[home-assistant.log](https://github.com/hacs/integration/files/4113686/home-assistant.log)

**Comment by ludeeus** [comment]
> If you have a deps dir in your config, delete that.

**Comment by Gamerayers** [comment]
No change.  Same exact error info.

**Comment by ludeeus** [comment]
🤷‍♂  This happens _before_ HACS is loaded, so not really much I can do.

**Comment by Gamerayers** [comment]
I guess thanks for the help... Unfortunately, since it is exclusive to HACS, and there is no fix, while it is not a HACS issue, I guess HACS is broken.  Seemed there was another guy who had similar issue who posted without logs when updating to Home Assistant 0.104.3.  Wonder if anybody on 0.104.3 is able to use it.

**Comment by ludeeus** [comment]
It is **NOT** a HACS issue, you have an issue with installing the requirements for it, HACS itself does **not** install those, at that point HACS is not fully loaded.

And yes, multiple folks on 0.104.3 and even 0.105.x are using it (my self included)

**Comment by gittersam** [comment]
Hi,
I have the same issue. What additional requirements do I need to check for?

**Comment by Sebcul** [comment]
I also have the same issue. Running hassio 0.102.2 and hassos 3.8 on a rasp pi 3b.

**Comment by gdude2002** [comment]
Hiya, I was on Discord when @Sebcul asked for help with this issue.

@ludeeus I agree that this issue probably isn't specific to HACS (and I myself have a working install of HACS on an environment that almost exactly matches @Sebcul's), do you have any information on how the problem might be debugged?

**Comment by ludeeus** [comment]
Nope, I have seen similar with permission issues and with network (mostly DNS) issues, but not sure what can be done further 🤷‍♂, even if you were able to "force" HACS to run, every (most of them) integrations you find will have the same issue.

**Comment by Sebcul** [comment]
Updated to 0.104.3 and now it’s working..

**Comment by krzysztofwolski** [comment]
Had same issue, same error in logs. (Fresh hassio + fresh hacs). Add integration modal window could not load, so I've alt tabbed for answers. Later restarted server and it seems to be working. (Was restarting ealier like guide suggested but it did not help).

**Comment by fthmko** [comment]
@krzysztofwolski 
Same issue, with fresh hassio and install HACS as the first component.
But in my case, I found the system date is wrong(it's 2018) and resolved by change it.

My steps:
1. login to Raspberry Pi (not ssh to ha)
2. replace the NTP server in `/etc/systemd/timesyncd.conf` with another
3. run `systemctl restart systemd-timesyncd`
4. run `timedatectl status`  and check if the date is correct now
5. `reboot`  then try to install HACS again
