### ISSUE TITLE
HACS > 0.21.1 fails during repo setup

### ISSUE THREAD

**Issue by dewet22** [hacs/integration#972]
## Version of HACS

Tested clean install of 0.21.5. Rolled back to 0.21.1 where the regression disappears. The implicated commit might be https://github.com/hacs/integration/commit/13340477fe60ce7ec2886250ca6a1bdcfd7518a7 (prescient commit message).

## Describe the bug
After upgrading HACS via its own UI, it is unable to start when restarting hass:

```
2020-02-15 21:06:58 INFO (SyncWorker_11) [homeassistant.util.package] Attempting install of aiogithubapi==0.5.0
2020-02-15 21:07:06 INFO (SyncWorker_29) [homeassistant.util.package] Attempting install of hacs_frontend==20200212060803
2020-02-15 21:10:02 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.139957977055632] Connection closed by client
2020-02-15 21:10:25 INFO (MainThread) [homeassistant.setup] Setting up hacs
2020-02-15 21:10:25 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 0.0 seconds.
2020-02-15 21:10:25 INFO (MainThread) [hacs]
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 0.21.5
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/hacs/integration/issues
-------------------------------------------------------------------

2020-02-15 21:10:26 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for hacs
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 215, in async_setup
    hass, self
  File "/config/custom_components/hacs/__init__.py", line 67, in async_setup_entry
    startup_result = await hacs_startup(Hacs)
  File "/config/custom_components/hacs/__init__.py", line 131, in hacs_startup
    if not await load_hacs_repository(hacs):
  File "/config/custom_components/hacs/setup.py", line 17, in load_hacs_repository
    await hacs().register_repository("hacs/integration", "integration")
  File "/config/custom_components/hacs/hacsbase/__init__.py", line 157, in register_repository
    await repository.registration()
  File "/config/custom_components/hacs/repositories/integration.py", line 83, in registration
    if not await self.validate_repository():
  File "/config/custom_components/hacs/repositories/integration.py", line 31, in validate_repository
    await self.common_validate()
  File "/config/custom_components/hacs/repositories/repository.py", line 282, in common_validate
    self.tree = await self.repository_object.get_tree(self.ref)
AttributeError: 'AIOGithubRepository' object has no attribute 'get_tree'
2020-02-15 21:10:26 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2020-02-15 21:10:26 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.hacs entity: sensor.hacs
```

**Comment by dewet22** [comment]
Actually, 0.21.1 might be broken in the same way; from my clean install when trying to install anything, I get the same error in hass logs:

```
2020-02-15 21:31:01 ERROR (MainThread) [hacs.repository.integration.custom-components.breaking_changes] Download was not complete ['AIOGithubRepository' object has no attribute 'get_tree']
2020-02-15 21:31:12 ERROR (MainThread) [hacs.repository.integration.claytonjn.hass-circadian_lighting] Download was not complete ['AIOGithubRepository' object has no attribute 'get_tree']
2020-02-15 21:31:27 ERROR (MainThread) [hacs.repository.integration.danobot.entity-controller] Download was not complete ['AIOGithubRepository' object has no attribute 'get_tree']
2020-02-15 21:31:40 ERROR (MainThread) [hacs.repository.integration.thomasloven.hass-fontawesome] Download was not complete ['AIOGithubRepository' object has no attribute 'get_tree']
2020-02-15 21:32:08 ERROR (MainThread) [hacs.repository.integration.amelchio.logbook_cache] Download was not complete ['AIOGithubRepository' object has no attribute 'get_tree']
```

**Comment by ludeeus** [comment]
It is not broken.
You are running and old version of aiogithubapi.

**Comment by dewet22** [comment]
HACS itself claims to install as dep:

```
2020-02-15 21:06:58 INFO (SyncWorker_11) [homeassistant.util.package] Attempting install of aiogithubapi==0.5.0
2020-02-15 21:07:06 INFO (SyncWorker_29) [homeassistant.util.package] Attempting install of hacs_frontend==20200212060803
```

What version do I need? I'm running hass in a docker container and don't fiddle with any deps otherwise.

**Comment by ludeeus** [comment]
HA handle the requirement installation.
0.5.0 is the needed version, but from the logs, the installation attempt is not complete.
If you added a user/group to the container, you might get issues with requirements.

**Comment by dewet22** [comment]
I know hass manages requirements, that's why I posted the log line. This is a clean container, I make no modifications to it. I don't see from the logs how the downloading of aiogithubapi failed, and this is despite multiple restarts.

What fixed it was blowing away the `/config/deps` directory so everything can be re-downloaded.
